Cython/Includes/libcpp/optional.pxd, tests/run/cpp_stl_optional.pyx
Issue: https://github.com/cython/cython/issues/3293
- Added the std::optional declarations (pxd) as `from libcpp.optional cimport optional`
- Added tests, which run with -std=c++17
_Side note: This is a great alternative for having to use pointers for classes that do not have a default constructur available, and avoids using the heap or memory management, but still offers lifetime control through emplace() and reset()._
I've used "distutils" tag in the testing framework to force c++17 support which seemed to work fine since this is a c++17 only feature. I am unsure of whether there are any other places where a c++ version check is required and if so how, please advise.
Also, please note that although this may break Cython builds on non c++17 builds, such builds should never try to include …
=> Add std::optional for c++17 (GH-3293)

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Utility/ModuleSetupCode.c, tests/run/nogil.pyx
Fixes #4137
Also adds a check whether we have the GIL before doing so. This
is important because Py_UNBLOCK_THREADS is documented as unsafe
if we don't hold the GIL. This bit of it is possibly a candidate to be
backported (since the pattern was allowed in Cython 0.29 but
can cause a segfault).
=> Allow releasing gil in nogil functions

.github/workflows/wheel-manylinux.yml, Tools/ci-run.sh
Try to unbreak CI?
It seems around the time CI stopped passing, setuptools changed from 59.7.0 to 60.0.0, see [this comment](https://github.com/cython/cython/pull/4509#issuecomment-998767635) for more info
=> pin setuptools<60

Cython/Compiler/TypeSlots.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c
The release of Cython 0.29.26 exposed a problem with the way PyPy3.8 defined PyTypeObject: PyPy is missing the `tp_vectorcall` slot. See [PyPy issue 3618](https://foss.heptapod.net/pypy/pypy/-/issues/3618). The reason this only came up after the release of Cython 0.29.26 is that release 0.29.26 backported the code from commit b0d8de7928019372ebd5fb81e027529e79aa922e to the 0.29 release branch. Before that commit, the last few fields of the PyTypeObject in Cython were
- For Python3.8:
- Cython<0.29.26 initializes a struct with the last fields `tp_finalize`, `tp_vectorcall`, `tp_print`
- Cython>=0.29.26 initializes a struct with the last fields `tp_finalize`, `tp_vectorcall`, `tp_print`, `tp_pypy_flags`
- For Python3.9:
- Cython<0.29.26 initializes a struct with the last fields …
=> qualify use of tp_pypy_flags and tp_vectorcall on PyPy

Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.py, tests/run/annotation_typing.pyx
Fixes #4514
It looks like annotations attached to namenodes weren't correctly
processed with "InterpretCompilerDirectivesTransform"
=> Fix class pointer annotations

Cython/Compiler/TypeSlots.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, tests/build/module_api.srctree, tests/run/posonly.py, tests/run/test_genericclass.py, tests/run/test_genericclass_exttype.pyx
After testing #4509 on PyPy3.8, it became clear that I messed up the condition: `PY_VERSION_HEX > 0x03080000` should have been `PY_VERSION_HEX >= 0x03090000` since the intention was to match a future PyPy3.9 build and not match any PyPy3.8 build (which of course has `PY_VERSION_HEX == 0x03081200`.
Along the way, the next release of PyPy will change a non-compatible `AttributeError` into a `TypeError`.
Also PyPy 3.8 cleans up a singular/plural error message.
```
def f(a, b, /):
pass
```
When calling `f(3, b=4)` CPython emits
> TypeError: f() got some positional-only arguments passed as keyword arguments: 'b'
while PyPy emits
> TypeError: f() got a positional-only argument passed as keyword argument: 'b'
For `f(a=3, b=4)`, both implementations emit
> TypeError: f() got some positional-only …
=> Redo pypy tp flags

Cython/Compiler/ExprNodes.py, tests/run/cyfunction_defaults.pyx
An attempt at fixing #4313.
Essentially, what I tried to achieve is to pass the default values as a decoration to the `__default__` instead of casting it into the type associated with the argument.
For example, let us take the following example
```cython
class Foo:
def my_method(self, int[:] foo = None):
pass
```
My understanding is that Cython tries to cast None into a memory view, which it then fails to cast back into a Python object to populate the `__default__` of `my_method`. One solution is to *not* cast default values and use them as is.
However, since I am not at all an expert into the inner workings of Cython, I am a bit worried I have missed something here and that this PR may cause inconsistencies between the actual default argument (as understood by Cython) and the one found …
=> Allow default value for memory view

Cython/Includes/libcpp/vector.pxd
This PR implements #2171 using C variadics. This is already done in a similar way in [optional.pxd](https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/optional.pxd):
```
T& emplace(...)
```
This definition could be improved when variadic templates are supported at some point, but since the types are not really relevant for Cython it should be fine to use C variadics here (especially since I do not expect that variadic templates will be supported anytime soon). Adding `emplace_back` is useful, since it is not only potentially faster, but allows for simpler implementations as well:
```
vec.push_back(move(MyClass(var)))
```
vs
```
vec.emplace_back(var)
```
=> add emplace_back to vector

docs/src/reference/directives.rst
Avoid pointing users to a link that just says "this section was
moved to...". Just take them to the correct page first time.
This annoys me surprisingly often when looking things up. As
far as I can tell it's just the one link that does this.
=> Avoid double redirect in old documentation

Cython/Includes/libcpp/deque.pxd, Cython/Includes/libcpp/vector.pxd
This adds a missing template specifier to some template definition and updates the template typenames to match the names on cppreference.com.
=> fix incorrect template definition

Cython/Build/Cythonize.py, Cython/Build/Dependencies.py, tests/build/depfile.srctree, tests/build/depfile_numpy.srctree, tests/build/depfile_package.srctree
Here's an initial WIP attempt at addressing https://github.com/cython/cython/pull/4510#issuecomment-999361757,  gh-1214 and gh-1459; see also https://github.com/mesonbuild/meson/issues/9049
This PR is deliberately simplistic : given a `foo.pyx` which cimport `bar.pxd` and includes `baz.pxi`, 
```
$ cythonize -M foo.pyx
```
produces `foo.c.dep` file in with foo.pyx dependencies along with `foo.c`.
An immediate question to mainainers: is this a reasonable place to plug it? Is this simple interface OK?  
I'd also appreciate a pointer to how to best add tests for this. I can of course write out several tempfiles, or is there a better way?
Also, @eli-schwartz what would meson need --- in the example above, does it need a list of dependencies for the `foo.c` file (thus `foo.c: foo.pyx bar.pxd …
=> add a depfile support to cythonize

Cython/Utility/Coroutine.c, Cython/Utility/Exceptions.c
"->exc_type" and… "->exc_traceback" are gone and now get inferred from "->exc_value".
Closes https://github.com/cython/cython/issues/4500
=> Adapt to "exc_info" changes in CPython 3.11a4

docs/_templates/layout.html, docs/conf.py
This PR adds a new banner for latest version of documentation to indicate that this is development version.
Rationale:
* Current default documentation shows by default all commited changes not released. This can be confusing for users.
* User can see the version of documentation but it can be easilly overlooked.
* there are multiple bugs complaining about current default: #4577, #4010
* django framework uses simmilar approach: See warning banner here: https://docs.djangoproject.com/en/dev/
Current solution simulates django approach - we will show a warning.
To see this PR in action see: https://matusvalo-cython.readthedocs.io/en/latest/index.html
Closes #4577. Maybe also #4010.
=> Add warning banner for latest version of documentation

Cython/Parser/ConcreteSyntaxTree.pyx, pyximport/pyximport.py, pyximport/test/test_pyximport.py, pyximport/test/test_reload.py, runtests.py, tests/build/common_include_dir.srctree, tests/run/cpdef_pickle.srctree
When testing windows + PyPy over at [pypy/binary-testing](https://github.com/pypy/binary-testing/runs/5065921724?check_suite_focus=true#step:6), I came across a number of places where Cython was not using a context manager when opening files. I found these by grepping for `open(` without a `with`: 
```
git grep "open(" | grep -v with
```
=> ENH: use context manager when opening files

docs/conf.py
fixes look of the "tabs", `html_context` was redefined in #4583, so here's a little fix 😀
(GH-4634)
This pr can be just merged as it contains only one commit
I checked, banner remains, so we're ready to go
=> Fix redefinition of the `html_context` in the docs/conf.py

Cython/Compiler/Nodes.py, tests/run/tryfinally.pyx
Fixes https://github.com/cython/cython/issues/4651.
This creates two copies of the function, one for the exception
cause and one for the non-exception case. It's probably inefficient
but the simplest solution
=> Fix function definions in finally clauses

Cython/Compiler/Symtab.py, tests/errors/redeclaration_of_var_by_cfunc_T600.pyx
Fixes #600
To reproduce:
```cython
cdef class Bar:
cdef list _operands
cdef int _operands(self):
return -1
```
This is how the error looks right now:
```text
File "c:\Python\projects\cython\venv\cyth.py", line 15, in <module>
ext_modules=cythonize(
File "c:\python\projects\cython\Cython\Build\Dependencies.py", line 1143, in cythonize
cythonize_one(*args)
File "c:\python\projects\cython\Cython\Build\Dependencies.py", line 1289, in cythonize_one
result = compile_single(pyx_file, options, full_module_name=full_module_name)
File "c:\python\projects\cython\Cython\Compiler\Main.py", line 576, in compile_single
return run_pipeline(source, options, full_module_name)
File "c:\python\projects\cython\Cython\Compiler\Main.py", line 504, in run_pipeline
err, enddata …
```
=> Catch redeclaration of var by cfunc

Cython/Compiler/UtilNodes.py, tests/memoryview/memslice.pyx
Fixes https://github.com/cython/cython/issues/4662
Memoryview temps weren't being properly incremented (at the start
of the loop) or decremented (at the end of the loop). They were
decremented in the exception handling case.
Long-term I think we really should unify reference counting for
memoryviews further. It's *slightly* different from PyObjects
(mainly that it happens in wrapper functions rather than the
main function) and that leads to a large chance that it just
gets missed.
=> Fix reference counting in memoryview loops

Cython/Utility/Coroutine.c, Cython/Utility/Exceptions.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Profile.c
In 18b5dd68c6b616257ae243c0b6bb965ffc885a23 /
https://github.com/python/cpython/pull/31530 /
https://bugs.python.org/issue46836
The `_frame` struct was moved to an internal header, however the public API is
primarily read-only, and cython needs to build _frame objects so still import
the internal headers.
The version bounding is wrong (the problem commit won't be out until a6, but this condition will compile against the current CPYthon main branch.
I'm not at all sure that this is the right fix, but it compiled!
=> FIX: import internal cpython headers to fix for py311

Cython/Compiler/PyrexTypes.py, tests/run/fused_types.pyx
Fixes https://github.com/cython/cython/issues/4644
For fused functions it makes sense that the return type is ignored
(a function can't be specialized based on return type alone) but
for function pointers the return type should be included (since
such a pointer might be an argument to a fused function)
=> Allow fused function pointer return type

Cython/Utility/ModuleSetupCode.c
We unconditionally add `/D_USE_MATH_DEFINES` via cmdline and doing this triggers `-Wmacro-redefined` in cython-generated code.
=> Do not redefine _USE_MATH_DEFINES in generated code

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Utility/ModuleSetupCode.c
This backports 7d99b0f085bb254e9a9b4a9fe50aefe133837a81 to 0.29.x which fixes #4637 
Acquire the GIL in nogil functions only when strictly needed on function exit, e.g. for cleaning up temp variables from with-gil blocks or adding tracebacks.
Closes GH-3554.
=> Avoid acquiring the GIL at the end of nogil functions (GH-3556)

docs/src/userguide/external_C_code.rst
Since cimporting directly from cpython has long been deprecated.
e.g. https://github.com/cython/cython/issues/4707
=> Warning to use submodules instead of "cimport cpython"

Cython/Includes/libcpp/stack.pxd
This adds a simple exception handling to `stack::pop`.
Tests are to be added, if needed.
=> Add exception handling for `libcpp::stack::push`

Cython/Utility/Exceptions.c
Fixes: #4722 by saving the exception for the duration of `py_code` creation.
Compared to the proposed fix in the issue I used `__Pyx_ErrFetchInState()` and `__Pyx_ErrRestoreInState()` as that's what other functions around use and improved it in the way @scoder told me to.
=> Fix possible exception reset in the exception handling code

Cython/Compiler/Dataclass.py, tests/run/cdef_class_dataclass.pyx
Fixes #4704
PyrexTypes.declaration_code is kind of inconsistent about whether
it returns an encoded string or not. Therefore this is probably
a lazy fix (of applying EncodedString anyway rather than making
the interface consistent).
=> Force EncodedString on dataclass types

Cython/Utility/ExtensionTypes.c
Python 3.11 adds `object.__getstate__`. Therefore the presence of
this function should not prevent Cython from making a class
pickleable.
Fixes #4730
@tacaswell I've tested this to the extent that it lets Cython self-compile twice (the second time is then running the compiled modules). But I haven't compiled Numpy with it.
=> Test for object.__getstate__ in pickling

Cython/Utility/ModuleSetupCode.c, tests/run/call_trace_gh4609.srctree
It causes issues while profiling or debugging where global
variables can end up inadvertently changed.
Test largely copied from @seberg's reproducer
Fixes https://github.com/cython/cython/issues/4609
=>  Disable CYTHON_FAST_PYCALL on Py3.10 (0.29.x) 

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Utility/ModuleSetupCode.c
PR 4703 was an incomplete backport of the changes needed for #3554 and generates incorrect C code.
See https://github.com/cython/cython/issues/3554
Reverts https://github.com/cython/cython/pull/4703
=> Revert "Avoid acquiring the GIL at the end of nogil functions (GH-3556)"

Cython/Utility/ExtensionTypes.c
Fixes bug introduced by https://github.com/cython/cython/commit/ae4ade8daeae206db68583f2f4b9c1cbce9cba75 for PyPy (hopefully)
Fixes #4738
=> Avoid error if type doesn't have __getstate__

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/ModuleSetupCode.c, tests/run/unicodemethods.pyx
This is used by some optimisations for builtins that call C-API functions directly but need to convert None arguments to NULL or special integer values in order to mimic the original Python interface.
Also add and backport the CPython macros for None checks (and True/False, while we're at it):
https://docs.python.org/3/c-api/structures.html#c.Py_Is
See https://github.com/cython/cython/issues/4706
Closes https://github.com/cython/cython/issues/4737
=> Allow None to coerce to C types separately from other object values.

Cython/Utility/ObjectHandling.c
Some code I have uses lxml. When I compile and run lxml with LLVM-12's undefined behaviour sanitizer, I see this:
```
lxml/4.6.3/cython_parts=etree.c/etree.c:191228:65: runtime error: applying zero offset to null pointer
#0 0x7faedc799e7c in __Pyx_PyList_GetSlice lxml/4.6.3/cython_parts=etree.c/etree.c:191228
#1 0x7faedc6b3723 in __pyx_f_4lxml_5etree_9_ErrorLog_copy lxml/4.6.3/cython_parts=etree.c/etree.c:38092
#2 0x7faedc77636e in __pyx_f_4lxml_5etree___copyGlobalErrorLog lxml/4.6.3/cython_parts=etree.c/etree.c:40203
#3 0x7faedc775a5c in __pyx_pf_4lxml_5etree_9LxmlError___init__ lxml/4.6.3/cython_parts=etree.c/etree.c:21080
#4 0x7faedc774dff in __pyx_pw_4lxml_5etree_9LxmlError_1__init__ lxml/4.6.3/cython_parts=etree.c/etree.c:21019
```
which implies that Cython's generating undefined …
=> Avoid nullptr math undefined behaviour in ObjectHandling.c

Cython/Includes/libcpp/random.pxd, tests/run/cpp_stl_random.pyx
This PR adds the [`mt19937`](https://www.cplusplus.com/reference/random/mt19937/) random number generator to `libcpp`.
=> Add mt19937 random number generator to libcpp.

Cython/Includes/cpython/object.pxd
Includes [`tp_methods`]( https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_methods ) in the `PyTypeObject` `extern` definition. Should allow Cython code to access this field and inspect its contents.
=> Add `tp_methods` to `PyTypeObject`

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Utility/ModuleSetupCode.c, tests/run/trace_nogil.pyx
Closes #4637.
This change set was obtained using 
```
git checkout 0.29.x
git cherry-pick 7d99b0f085bb254e9a9b4a9fe50aefe133837a81 01085d2ad588bf41e2d17cff6aa96d0507087ce3 
```
and conflicts in `Cython/Compiler/Nodes.py` manually resolved, as well as removed `tests/run/with_gil_automatic.pyx` as it was failing.
#4703 only contained the first commit there. 
I checked that scikit-image could be built with this change-set. Local test has 1 error: `ERROR: test_embed (__main__.EmbedTest)`, but this time (unlike #4744) it is likely due to missing env. variables.
=> Fix 3564 in 0.29

tests/run/cpp_stl_list.pyx, tests/run/cpp_stl_list_cpp11.pyx, tests/run/cpp_stl_vector.pyx, tests/run/cpp_stl_vector_cpp11.pyx
@scoder #4530 mistakenly added some C++11 specific tests into the general test files. This moves those tests into separate files.
=> move c++11 specific tests into separate files

.github/workflows/ci.yml
For Py3.7
See if it fixes breaking CI. I'm not sure why it's only failing for one Python version though
=> Change MACOSX_DEPLOYMENT_TARGET

runtests.py
I think we've now got rid of all legacy uses of "tags". Therefore
make it an error instead of a warning to avoid new uses sneaking
in.
=> Make 'tags' an error in runtests.py

.github/workflows/wheel-manylinux.yml
A bit of maintenance on the manylinux CI:
- Update actions/checkout to v3, actions/setup-python to v3 and actions/upload-artifact to v3. Those version are currently maintained and use NodeJS 16.
- Use Python 3.10 for sdist and wheel building jobs
=> manylinux CI: Update used actions, use Python 3.10

.github/workflows/ci.yml
A bit of maintenance on the regular CI.
- Updates the used actions to their latest versions (v3)
_(note that for actions/checkout, the `fetch-depth` is now 1 by default)_
- Allow triggering a run manually from the GitHub UI by adding `workflow_dispatch` (see [GitHub docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch))
- Run pycoverage job with Ubuntu 20.04 and Python 3.10
=> CI: Updated used actions, allow workflow_dispatch

.github/workflows/ci.yml
It looks like Python 3.8 now needs MACOSX_DEPLOYMENT_TARGET=10.15
=> Update MACOSX_DEPLOYMENT_TARGET for fix test failure

Cython/Compiler/TypeSlots.py
`raise NotImplemented()` gives `TypeError` instead of `NotImplementedError` since `NotImplemented`'s type is `NotImplementedType`
=> Replace `NotImplemented`

tests/run/cpp_classes.pyx, tests/run/cpp_classes_def.pyx, tests/run/shapes.h
These are the companion tests for PR [#3183](https://github.com/cython/cython/pull/3183).
=> Tests for cppclass docstrings.

Cython/Compiler/Nodes.py, Cython/Utility/NumpyImportArray.c
The label it was using was unrelated to the place where the utility
code was actually appearing, and it was essentially luck that it
seemed to work (largly because it was always going to __pyx_L1_error
label).
It's guarded anyway because of
`writer.putln(writer.error_goto_if_PyErr(output.module_pos))`
which is added after every block of utility code in the init
section.
The only thing we lose is a position that links it back to the
"cimport numpy" line.
=> Removed goto error from numpy cimport guard

Cython/Compiler/Builtin.py, tests/run/builtin_subtype_methods_T653.pyx
Since they prevent explicitly calling base-class `__contains__`.
https://github.com/cython/cython/issues/4785
Draft for now to see what breaks - I suspect some test will, but I'm not sure if anything significant like `x in container` will
=> Remove __contains__->PySequence_Contains slots

Cython/Compiler/ModuleNode.py, Cython/Utility/ImportExport.c, tests/pypy2_bugs.txt
Closes #4763. When `!CYTHON_PEP489_MULTI_PHASE_INIT`, the module setup code sets `__path__` and `__file__` via calls to `importlib.find_loader`. That was deprecated in favor of `find_spec` in python 3.4. The deprecation warning is causing problems when running with `-Werror`. This PR
- uses the eqivalent of `package_path = [importlib.util.find_spec(module_name, package).origin.rsplit(os.sep, 1)[0]]`
- if `package` exists (`module_name` is a sub-package), prefix `'.'` to module_name
I tested this with `pypy3.8 runtests.py --no-cpp -vv`
It would be nice to backport this to the next 0.29 release if possible.
=> move from deprecated find_loader to find_spec

Cython/Compiler/Dataclass.py, tests/run/cdef_class_dataclass.pyx
Enables possibility to use kw_only option like in `dataclasesses.dataclass` requested in https://github.com/cython/cython/issues/4303
=> dataclasses: enable kw_only dataclasses

Cython/Utility/CythonFunction.c, tests/run/function_self.py
It's a bit simpler, and it lets `hasattr` work correctly where-as
the getset didn't (hasattr returned true, but it still raised an
error).
=> Replace fused __self__ getset with slot memberdef

Cython/Includes/libcpp/random.pxd, tests/run/cpp_stl_random.pyx
As `mt19937` already included in #4746, it is better to include `mt19937_64` as well for int64 random variables.
=> Add mt19937_64 random number generator to libcpp

docs/src/userguide/extension_types.rst
This PR fixes the link to init methods in extension types user guide
=> DOC Fixes link to init methods in extension types user guide

Cython/Utility/MemoryView_C.c
https://github.com/python/cpython/pull/93215 chance CPython to always use the
2-input version of va_start and dropped defining HAVE_STDARG_PROTOTYPES.  This
resulted in the 1-argument version being used when compiling cython source
which fails
This makes cython also always use the 2-argument version.
=> MNT: always require va_start to have two arguments

Cython/Compiler/Nodes.py
Solves #4825.
I am not sure about the standard (if any) for indenting code blocks in the generated C source code, so I wrote the 4-space indentation the naive way.
=> Update preprocessing warning to be compatible with MSVC

Cython/Utility/Exceptions.c
When compiling `cython` generated code with `ubsan` enabled, it warns that in `__Pyx_WriteUnraisable()`, `state` can be used without initialization. It seems we need to extend the workaround beyond MSVC here.
Using Cent OS 7 (manylinux_2014 image), with gcc 10 and libubsan.
=> Always initialize `state` to avoid `ubsan` error

docs/src/quickstart/install.rst
Let's assume nobody who reads the quickstart documentation actually wants
python2-dev.
=> [docs] Mention python3-dev requirement on Ubuntu/Debian

docs/src/userguide/sharing_declarations.rst
Patch is against 0.29.x branch (to fix both versions of the
documentation).
Fixes https://github.com/cython/cython/issues/4862
=> Docs: don't say cdef functions exist in module dict

tests/run/line_trace.pyx
Thus fixing linetracing tests of Python 3.11.
The issue we were seeing looked to be something to do with functions
defined within doctest docstrings. It was fixed by moving the
"defined-in-Python" functions into an exec call instead.
I'm not sure I quite understand the issue but it doesn't look
like a Cython issue.
=> Move linetracing functions into an "exec"

Cython/Compiler/ExprNodes.py, tests/buffers/bufaccess.pyx
While NumPy tends to not actively create object buffers initialized
only with NULL (rather than filled with None), at least older versions
of NumPy did do that.  And NumPy guards against this.
This guards against embedded NULLs in object buffers interpreting
a NULL as None (and anticipating a NULL value also when setting
the buffer for reference count purposes).
Closes gh-4858
=> BUG: Fortify object buffers against included NULLs

Cython/Includes/cpython/object.pxd
object means the argument is always non-NULL valid Python object, while
PyObject* argument can be generally NULL. If the argument is indeed
passed as NULL, and we declare it as object, generated code will crash
while trying to incref it.
Quoting https://github.com/cython/cython/issues/4822:
object.pxd currently declares `newfunc` as follows:
```pyx
ctypedef object (*newfunc)(cpython.type.type, object, object)  # (type, args, kwargs)
```
which implies that `args` and `kwargs` are always live objects and cannot be NULL.
However Python can, and does, call tp_new with either args=NULL, or kwargs=NULL or both. And in such cases this leads to segfault in automatically-generated __Pyx_INCREF for args or kw.
The fix is to change `object` to `PyObject*` for both args and kwargs.
Please see below …
=> includes/cpython: Fix newfunc to use PyObject* for args/kwargs instead of object

Cython/Utility/FunctionArguments.c
Simpler follow up to https://github.com/cython/cython/pull/4726.
I don't think we need to be worried null args and non-zero nargs,
but null args and 0 nargs is quite common and valid I think.
This PR just avoids a dereference in that case (which i think is
probably dubious)
=> avoid null dereference in __Pyx_KwValues_FASTCALL

docs/src/tutorial/embedding.rst, docs/src/userguide/external_C_code.rst
Try to make it clear that using cython --embed doesn't embed
any external dependencies.
=> Notes about embedding and portable applications

Cython/Compiler/Nodes.py, tests/memoryview/memslice.pyx
Error on memoryview argument capture on 0.29.x
I don't believe it's easy to fix 
https://github.com/cython/cython/issues/4798 for def functions on 0.29.x Therefore,
generate an error message that explains two possible workarounds.
This at least makes sure that people don't end up with mysterious
crashes.
It is possible to fix for cdef functions though, so I've done that.
Best attempt at backporting https://github.com/cython/cython/pull/4848 for 0.29.x
=> Error on memoryview argument capture on 0.29.x

tests/run/tuple_constants.pyx
CPython no longer stores the varnames tuple. Instead it stores it
as part of a larger list of names and calculates it dynamically
on request.
=> Disable co_varnames identity check on Python 3.11

Cython/Compiler/Nodes.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/ExtensionTypes.c, Cython/Utility/ImportExport.c, runtests.py, tests/errors/builtin_type_inheritance.pyx, tests/pypy_bugs.txt, tests/run/builtin_type_inheritance_T608.pyx, tests/run/builtin_type_inheritance_T608_py2only.pyx, tests/run/extern_varobject_extensions.srctree
Fixes https://github.com/cython/cython/issues/4827 at least
partially.
Some of patch copied from https://src.fedoraproject.org/rpms/Cython/pull-request/35#request_diff
Allows the size of a type to be between basicsize and basicsize+itemsize
since anything is this range is a reasonable size for a class to be.
Adds a test when an extern extension type is inherited from to
make sure that it isn't a PyVarObject.
=> Handle extern PyVarObjects

Cython/Utility/MemoryView.pyx, tests/compile/fused_redeclare_T3111.pyx, tests/memoryview/cythonarray.pyx, tests/memoryview/memoryview.pyx
The main reason to do this is so that they'll work in sequence
patterns in structural pattern matching in Python 3.10+.
Since the builtin "memoryview"
type and "array.array" are sequences, I think this is reasonable.
=> Make memoryviewslice and cython.array be collections.abc.Sequence

Cython/Compiler/Nodes.py, Cython/Compiler/Parsing.py, tests/run/test_grammar.py
As described in https://docs.python.org/3/whatsnew/3.10.html#parenthesized-context-managers
The approach to parsing is largely copied from the CPython parser
(with comments to support it) - closer to the PEG approach of
"try the bracketed case first, and let it fail silently then
try the unbracketed case".
Fixes one of the items listed in https://github.com/cython/cython/issues/4595
=> Enable parenthesized context managers

Cython/Compiler/ModuleNode.py, Cython/Utility/ImportExport.c
I think this is the right thing to do for https://github.com/cython/cython/issues/4827#issuecomment-1186178009. It adds a bit of extra leeway to the size check to account for any padding that the compiler might have added. It gives a better answer on more recent compilers (where `alignof` exists).
Obviously extra leeway does make the check a little weaker (but only for variable sized objects)
=> Account for possible struct padding when calculating itemsize

.github/workflows/ci.yml
[Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html) is now [in beta](https://www.python.org/downloads/release/python-3110b1/) and considered feature frozen. That means we can start helping making Python 3.11 more stable by fixing internal bugs and reporting upstream bugs.
This commit removes `allowed_failure: true` element of the CI configuration. It might happen that the CI will not always pass, but that only makes us aware of any existing and appearing bugs, and does not always have to be a strict blocker for PRs, especially in early beta.
Cython is one of the lowest level dependencies for many project, so early adoption of Python 3.11 can accelerate adoption across the whole ecosystem, especially as numpy and pandas are enabled to start to support Python 3.11.
=> CI: Remove allow_failures for Python 3.11

pyximport/_pyximport2.py, pyximport/_pyximport3.py
makes pyximport tests work on windows, part of #4324.
The idea is to cd into the common directory while compiling. Would it be better to do this in `pyx_to_dll` just before creating the `ext`?
=> pyximport: cd into common dir to prevent too-long filenames for windows

Cython/Compiler/CmdLine.py, Cython/Compiler/Main.py, Cython/Compiler/Options.py, Cython/Compiler/Tests/TestCmdLine.py, tests/compile/module_name_arg.srctree
I'd like to ask for feedback for this implementation of a
`--module-name` command line argument to the `cython` utility.
It can be useful to specify the module name for the output file
directly, rather than working it out from the enclosing file tree -
particularly for out of tree build systems, like Meson.
See: https://github.com/rgommers/scipy/issues/31#issuecomment-1002662816
for background.
However, the implementation here is a little ugly, because the cython
command line utility always executes through the `compile_multiple` code
path in `Main.py`.  This in turn is because the passed `sources`
argument is a list, and not a string, and therefore, the check around
line 629 always fails, meaning that I have to recover the passed
`module_name` from `options` in `compile_multiple`, rather …
=> MRG: add --module-name argument to cython command

tests/run/special_methods_T561.pyx
https://github.com/cython/cython/issues/4163
```
if old_type.is_pyobject:
if arg.default:  # 4325 ↛ 4326
code.putln("if (%s) {" % arg.hdr_cname)
else:
code.putln("assert(%s); {" % arg.hdr_cname)
self.generate_arg_conversion_from_pyobject(arg, code)
code.putln("}")
elif new_type.is_pyobject:  # 4331 ↛ 4334
self.generate_arg_conversion_to_pyobject(arg, code)
else:
if new_type.assignable_from(old_type):
code.putln("%s = %s;" % (arg.entry.cname, arg.hdr_cname))
else:
error(arg.pos, "Cannot convert 1 argument from '%s' to '%s'" % (old_type, new_type))
```
It doesn't cover the arg.default case (since I don't think any
of these methods accept a default argument), or the failed conversion
case. But does cover the pyobject->C, C->pyobject and C->C cases
=> Improve test coverage of special methods with type conversions

Cython/Includes/cpython/unicode.pxd
Most other functions in this CPython API files come with the Python documentation (e.g. the C++ API does not come with docs). They tend to get easily out of sync with the official CPython documentation and can get quite long. However if you prefer to have the documentation added I can copy them over from the Cpython docs.
=> add missing unicode APIs

Cython/Compiler/Parsing.pxd, Cython/Compiler/Parsing.py
Originally was part of https://github.com/cython/cython/pull/4896, but that's still a WIP so it's not clear if it'll be useful.
This function is unused so can be removed.
=> Remove unused function "looking_at_call" from parser

Cython/Utility/MemoryView.pyx, Cython/Utility/MemoryView_C.c, tests/compile/fused_redeclare_T3111.pyx
This fixes a few issues in MemoryView_C.c to allow atomic reference
counting to be used in more cases.
- Enable GNU atomics for `__GNUC__` >= 5. Previously, GCC 5.0, 6.0, X.0
versions previously used lock-based reference counting due to the
preprocessor check.
- Typo in `__GNUC_PATCHLEVEL__` macro (missing underscores)
- Enable atomics in MSVC and fix returned values. InterlockedExchangeAdd
returns the *initial* value (like __sync_fetch_and_add).
InterlockedIncrement returned the *resulting* value (post increment),
which would have been incorrect if MSVC atomics had been enabled.
Also avoids allocating a lock in MemoryView when atomics are available,
which additionally fixes a thread-safety issue in "nogil" Python.
=> [0.29] Use atomic reference counting in MemoryView in more cases (gh-4912)

Cython/Compiler/Parsing.py, docs/src/userguide/language_basics.rst, tests/compile/excvaldecl.pyx
As a no-op but it parses fine.
Also add some basic compile tests, and some brief documentation.
Related to https://github.com/cython/cython/issues/4280
Co-authored-by: Ashwin Srinath <3190405+shwina@users.noreply.github.com>
=> Backport noexcept to Cython 0.29.x

Cython/Compiler/Nodes.py, tests/memoryview/memslice.pyx
It was actually OK in def functions. It looks very dodgy:
```
__Pyx_XDEC_MEMVIEW(closure->arg)
```
gets called twice and `INC` gets called once. However this is
actually OK since XDEC really means "clear" (this is why I
renamed it in master...)
Fixes https://github.com/cython/cython/issues/4798 (completely
I think).
Sorry for the mess with this!
=> Reallow capture of memoryview arguments

Cython/Compiler/Nodes.py, tests/memoryview/memslice.pyx
+ fixed crash with a captured memoryview argument
(https://github.com/cython/cython/issues/4798)
Moves reference counting of memoryview arguments entirely into
the def function wrapper. New behaviour is:
```
def wrapper(x, ...):
xview = memoryview(x)
if error_in_rest_of_args:
cleanup(xview)
ret_value = func(xview, ...)
cleanup(xview)
return ret_value
```
while old behaviour was
```
def wrapper(x, ...)
xview = memoryview(x)
if error_in_rest_of_args:
cleanup(xview)
return func(xview, ...)
def func(xview, ...):
cleanup(xview)
return ...
```
This treats memoryviews in the same way as PyObjects.
The next step (not done here) is to unify put_var_incref_memoryviewslice
with put_var_incref of other types.
One observable consequence is that a memoryview argument is released
later in functions that …
=> Further unified memoryview reference counting

Cython/Compiler/ExprNodes.py, Cython/Utility/ModuleSetupCode.c, tests/run/test_coroutines_pep492.pyx
After the CPython change in https://github.com/python/cpython/pull/94050, it seems reasonable to try it.
Closes https://github.com/cython/cython/issues/2273
=> Make Cython async functions set CO_COROUTINE and CO_ASYNC_GENERATOR code flags

Cython/Compiler/Dataclass.py, tests/run/pure_cdef_class_dataclass.py
init=False (in a field name) means that it isn't an argument to
`__init__`. It does not mean that the field isn't initialized if
a default method of initialization is provided.
=> Fix initialization of init=False dataclass fields

Cython/Utility/MemoryView_C.c
Use them in preference to the existing compiler-specific
atomic types.
In both cases this requires the 2011 edition of the standard.
Closes https://github.com/cython/cython/issues/4923
=> Use standard C or C++ atomics for memoryviews

docs/examples/tutorial/clibraries/queue.py, docs/src/tutorial/clibraries.rst
#4293 seems to be fixed so we can use annotation and remove note.
=> [Docs] Use annotation since #4293 is fixed

Cython/Build/Dependencies.py, Cython/Compiler/CmdLine.py, Cython/Compiler/Main.py, Cython/Utils.py, tests/build/depfile_package_cython.srctree, tests/build/depfile_package_cythonize.srctree
Backports #4916
I'm not sure I understand what's up with the second commit here.
=> [0.29] implement the depfile command-line option for the "cython" tool

Cython/Compiler/PyrexTypes.py, tests/run/fused_cpp.pyx
=> Let C++ references work in fused types

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.py, tests/memoryview/memoryview.pyx, tests/memoryview/memslice.pyx
as a result of f946fe22fff32077dc58beeb64ec1ebc85d37632
And fix at least one pre-existing reference counting leak
for memoryview references in things like
`any(i > 0 for i in memview)`
=> Fix memoryviews in generator expressions

Cython/Compiler/Builtin.py
Fixes a small omission in https://github.com/cython/cython/pull/4603
I'm not 100% sure what code this actually fixes (so there isn't a test...). It's cherry-picked from https://github.com/cython/cython/pull/4463 (where it fixes an actual problem) but it seems like a valid change whatever happens with annotations.
=> Set is_variable on "special" entries

.github/workflows/ci.yml
This cancels the ci for previous commits on the same branch and previous commits in a PR, which should save CI time since the CI builds do no longer stack up when pushing multiple times while the CI is still running.
=> cancel unfinished CI run to save CI time

Cython/Utility/ModuleSetupCode.c
This led to warnings when building with clang and the `-pedantic` warnings when building for C++ versions below C++17
=> only use [[fallthrough]] starting C++17

.github/workflows/ci.yml
This should skip workflows only in pull requests, since the commit sha should be unique. In case the ci is run for the same commit sha (e.g. when creating new branches), I think it is fine to cancel the CI.
@da-woods this should help with https://github.com/cython/cython/pull/5006#issuecomment-1236300023
=> only cancel successive runs for pull requests

Cython/Compiler/ExprNodes.py, Cython/Utility/AsyncGen.c, Cython/Utility/CommonStructures.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, Cython/Utility/Exceptions.c, Cython/Utility/ExtensionTypes.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/Optimize.c
This is a subset of https://github.com/cython/cython/pull/4693 without all of the more complex changes. In addition it uses the `[[maybe_unused]]` attribute when possible, which should prevent most warning on msvc starting with C++17.
=> prevent more unused variable warnings

Cython/Compiler/ExprNodes.py, tests/run/cfunc_convert.pyx
Fixes https://github.com/cython/cython/issues/4890 (although likely
doesn't generate the optimized code they were really after).
This is an initial pass at the problem that just uses functools.
It's likely that Cython could generate more efficient code in
future.
=> Allow bound cfuncs to be coerced to object

Cython/Compiler/ModuleNode.py, Cython/Compiler/Nodes.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, Cython/Compiler/TypeSlots.py, runtests.py, tests/run/pep442_tp_finalize.pyx, tests/run/pep442_tp_finalize_cimport.srctree
including final types that inherit `__del__` from elsewhere (either
known or unknown).
Fixes #4995
=> Make sure we call __del__ for final types

Tools/make_dataclass_tests.py, tests/run/test_dataclasses.pyx
We accidently made cdef classes mutable in Python 3.10. @maxbachmann has shown that it's trivially easy to crash them (e.g. by trying to change the name). Therefore we should make them immutable.
I included this test from the CPython test-suite because it seemed to work. However, it relies on a feature that's unsafe and unintended.
=> Remove dataclass tests that used mutability

.github/workflows/wheels.yml
=> Mark new GitHub releases as pre-releases depending on the tag name

Cython/Compiler/Symtab.py, tests/compile/pxd_mangling_names.srctree, tests/pypy2_bugs.txt
Fixes #2940 
This PR fixes a typo that caused `cdef public` functions from .pxd files to be erroneously mangled.
The unmangled name is chosen when the definition from the .py file is processed, but on the condition that the cname determined while processing the declaration from the .pxd file was the mangled one (instead of a user-defined one).
It also adds a test for the ticket.
=> [Ticket 2940] fix mangling for .pxd cdef public functions

Cython/Utility/Complex.c, tests/run/complex_numbers_T305.pyx
A shortcut was incorrectly applied that returned NaN instead of an imaginary number
Fixes https://github.com/cython/cython/issues/5013
PR is against 0.29.x
Not completely sure how to make the tests reliable for this - I think we'd need to try `CYTHON_CCOMPLEX` both on and off.
=> Fix bug with complex powers of negative numbers

.github/workflows/ci.yml, .github/workflows/wheels.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

Cython/Compiler/Code.py, Cython/Compiler/FusedNode.py
It was written before `with` was universally available. Update the interface to make it harder to get wrong.
=> Update pyxcodewriter.indenter to use `with`

Cython/Utility/TypeConversion.c
The Intel compilers define `__GNUC__` but do not implement the warning pragma's used by Cython in `TypeConversion.c`. That results in a large amount of warnings like:
```
scipy/special/_ufuncs_cxx.cpython-310-x86_64-linux-gnu.so.p/_ufuncs_cxx.cpp(4940): warning #2282: unrecognized GCC pragma
#pragma GCC diagnostic push
^
scipy/special/_ufuncs_cxx.cpython-310-x86_64-linux-gnu.so.p/_ufuncs_cxx.cpp(4941): warning #2282: unrecognized GCC pragma
#pragma GCC diagnostic ignored "-Wconversion"
^
scipy/special/_ufuncs_cxx.cpython-310-x86_64-linux-gnu.so.p/_ufuncs_cxx.cpp(4945): warning #2282: unrecognized GCC pragma
#pragma GCC diagnostic pop
```
Hence disable the use of these pragma's when we see an Intel compiler is used.
=> Don't use unsupported GCC pragma's with Intel compilers

Cython/Compiler/Dataclass.py, Tools/make_dataclass_tests.py, tests/run/test_dataclasses.pyx
The dataclass module specifically guards repr from being invoked recursively. I use a slightly different method here to do the same thing.
Part of https://github.com/cython/cython/issues/4956
=> Fix recursive repr on cdef dataclasses

Cython/Compiler/ExprNodes.py, tests/run/cpp_iterators.pyx
This pull request aims to
1. support C++ classes with rbegin/rend implemented for reversed iteration, and
2. solve the compilation error when the type of temporary variable used to store the result of iterator has 'constness'.
One example of 2. is when iterating std::map, Cython uses std::map<Key, Value>::value_type as the type of temporary variable to store the value of an iterator. However, std::map<Key, Value>::value_type will deduce to std::pair<const Key, Value>, which cannot be reused within a loop as its first component is const.
Related to #2225
=> Implement reversed C++ iteration

setup.py
Add [`project_urls`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls) dictionary to setup.py with URLs to the Cython documentation, funding, source code and bug tracker. This will add those URLs under the "Project links" section on https://pypi.org/project/cython, making it easy to find these resources directly from PyPI.
=> setup.py: Add project_urls for PyPI

docs/examples/userguide/buffer/matrix_with_buffer.pyx
Fixes following error:
```
$ cython -3 matrix_with_buffer.pyx
...
self.v.resize(self.v.size() + self.ncols)
def __getbuffer__(self, Py_buffer *buffer, int flags):
cdef Py_ssize_t itemsize = sizeof(self.v[0])
self.shape[0] = self.v.size() / self.ncols
^
matrix_with_buffer.pyx:22:38: Cannot assign type 'double' to 'Py_ssize_t'
```
=> Docs: Fix example in buffer user guide

Cython/Compiler/TypeSlots.py, tests/run/binop_reverse_methods_GH2056.pyx
`__matmul__`, `__truediv__`, `__floordiv__` all forgot to set the type of `self`.
Fixes #5067
=> Fixed missed binop self types

Cython/Compiler/Parsing.py
See https://github.com/cython/cython/pull/4904
=> [0.29] deprecation warning for "from x cimport class A" syntax

docs/src/two-syntax-variants-used
I know this is officially in the "Cython 3" documentation, but I think most users end up with this documentation. It'd be good to link the annotation typing mainly to Cython 3.
=> Recommend Cython 3 for pure-Python syntax

Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, docs/src/userguide/migrating_to_cy30.rst, tests/run/annotation_typing.pyx
a44bbd363029aa9ba16fefcb485c68162f8ab663 changed an `int` annotation so that it was interpreted as a Python `int` instead of a Python object, which potentially breaks large integers on Python 2.
I think this was unintentional so I've added the special-cases for this in. (I'm happy with this PR being rejected though if it was intentional since I don't *really* care that much about Python 2).
Fixes #4944
=> Restore 'int'->'object' for now

Cython/Includes/libcpp/map.pxd, Cython/Includes/libcpp/numeric.pxd, Cython/Includes/libcpp/set.pxd, Cython/Includes/libcpp/string.pxd, Cython/Includes/libcpp/unordered_map.pxd, Cython/Includes/libcpp/unordered_set.pxd, tests/run/cpp_stl_associated_containers_contains_cpp20.pyx, tests/run/cpp_stl_numeric_ops_cpp17.pyx, tests/run/cpp_stl_numeric_ops_cpp20.pyx, tests/run/cpp_stl_string_cpp20.pyx
Adds
- C++17 numeric's new [`gcd()`](https://en.cppreference.com/w/cpp/numeric/gcd) and [`lcm()`](https://en.cppreference.com/w/cpp/numeric/gcd) functions
- C++20 numeric's new [`midpoint()`](https://en.cppreference.com/w/cpp/numeric/midpoint) function
- C++20's new [`.contains()`](https://en.cppreference.com/w/cpp/container/map/contains) method for all associated STL containers (map, multimap, set, multiset, ...)
- C++20's new [`std::string::starts_with()`](https://en.cppreference.com/w/cpp/string/basic_string/starts_with) and [`std::string::ends_with()`](https://en.cppreference.com/w/cpp/string/basic_string/ends_with) methods
=> Add missing C++17/20 STL functions and methods

Cython/Build/Dependencies.py, Cython/Build/Inline.py
which were mistakenly passing options instead of compiler directives.
=> Fix faulty calls to Context

docs/src/tutorial/cython_tutorial.rst
On windows cmd the code doesn't run with single quotes as explained [here](https://stackoverflow.com/questions/23987208/python-timeit-command-line-error-syntaxerror-eol-while-scanning-string-litera), it gives "SyntaxError: EOL while scanning string literal".  In contrast, this way runs both for Unix and Windows shells.
=> Use double quotes for arguments in timeit

.github/workflows/wheels.yml
Updates cibuildwheel from [v.2.8.1](https://github.com/pypa/cibuildwheel/releases/tag/v2.8.1) to v2.11.2. The v2.8.1 release still used a Python 3.11 beta to build wheels (which aren't ABI stable (!)), [v2.11.2](https://github.com/pypa/cibuildwheel/releases/tag/v2.11.2) uses the stable Python 3.11.0 release.
Since [v2.11.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.11.0) cibuildwheel also allows building Windows Arm64 wheels (`-windows_arm64`). This could be interesting to look at (in another PR).
=> Wheel CI: Update cibuildwheel to v2.11.2

Cython/Compiler/ModuleNode.py, docs/examples/tutorial/embedding/embedded.pyx, tests/compile/excvalcheck.h, tests/compile/nogil.h, tests/run/cpp_extern.srctree
Fixes #1839 
`cdef public` functions should be declared with the appropriate linkage:
- in C mode, either `extern` or `extern "C"`, depending on whether the header file is included in (resp. object code is linked against) a C or a C++ compilation unit. Choice is made at compile-time through `#ifdef __cplusplus` macros. NB: This is the current behavior.
- in C++ mode, `extern "C++"` is the only option, as C code cannot call C++ code. Note that `extern "C++"` should be preferred over `extern` to allow users to `#include` the C++ header inside a `extern "C"` block (which is legal, although barely used).
Note that the current behavior is OK for C mode, but is incorrect for the C++ mode. As described in #1839, this incorrect behavior is diagnosed by compilers emitting warnings when `cdef …
=> Fix linkage for `cdef public` functions in C++ mode

.github/workflows/ci.yml, Cython/Utility/ModuleSetupCode.c
It doesn't look like we're testing with a compiler using up-to-date language standards, and this meant we missed at least one bug recently:
https://github.com/cython/cython/pull/5029.
It seems like the GCC11 tests may as well double as "GCC11 with up-to-date language standards"
=> Run GCC 11 tests with the most recent language standard

Cython/Utility/CppSupport.cpp, tests/run/cpp_locals_directive.pyx
Fixes #4558 by making the assignment operation of a cpp_locals
variable actually use "emplace".
I've done this by creating a class that implements __Pyx_Optional_Type
rather than justing using std::optional directly (and rewriting
operator= for that). This seemed less intrusive that changing the
code generation to call "emplace" directly, but possibly less
efficient in some cases.
=> Remove "assignable" requirement from cpp_locals

test-requirements-cpython.txt
Ideally we'd work out why it isn't working, but for now it seems easiest to try to pin the version.
=> Pin line_profiler version to <4

Cython/Tempita/_tempita.py
HTML templates (and the associated functions/classes `sub_html`, `html`, `attr`, and `html_quote`) were not used by Cython itself, but were left over from the original, general-purpose, Tempita tool. The HTML templating relied on the cgi package, which is deprecated as of Python 3.11 and will be removed with Python 3.13 (meaning that merely importing the tempita package currently raises a DeprecationWarning). More specifically, it relied on the function `cgi.escape`, which was already removed with Python 3.8. This clearly suggests that the code has not been used by anyone, since no-one seems to have complained about this breakage.
Fixes #3309
I did not include a test case, but the main test is that nothing breaks in the existing test cases :grimacing: If you prefer, I could add a test …
=> Remove HTML template support from Tempita

Cython/Compiler/ModuleNode.py
With clang 14+ and `-Werror,-Wbitwise-instead-of-logical` build failed with:
```
$(BUILD_ROOT)/library/python/cyson/cyson/_cyson.pyx.cpp:29973:39: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
if (CYTHON_COMPILING_IN_CPYTHON && ((__pyx_freecount_5cyson_6_cyson_InputStream < 16) & (Py_TYPE(o)->tp_basicsize == sizeof(struct __pyx_obj_5cyson_6_cyson_InputStream)) & ((Py_TYPE(o)->tp_flags & (Py_TPFLAGS_IS_ABSTRACT | Py_TPFLAGS_HEAPTYPE)) == 0))) {
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&&
$(BUILD_ROOT)/library/python/cyson/cyson/_cyson.pyx.cpp:29973:39: note: cast one or both …
```
=> Fix use of bitwise '&' with boolean operands

Cython/Utility/ObjectHandling.c, Tools/ci-run.sh
Fixes #4804 (but not hugely satisfactorally)
=> Avoid triggering type-check assert for cyfuncs [0.29.x]

.github/workflows/ci.yml, tests/run/py_classbody.py
PyPy will add a suggestion to AttributeError, so the error message becomes
```
AttributeError: type object 'TestCdefAttr' has no attribute 'cdefvar'. Did you mean: cdefval1?
```
instead of the CPython
```
AttributeError: type object 'TestCdefAttr' has no attribute 'cdefvar'
```
Adding an ellipsis suffix is enought to fix the error.
=> allow suggestions on AttributeError for PyPy in doctests

Tools/ci-run.sh, runtests.py, test-requirements-312.txt, tests/pypy_implementation_detail_bugs.txt, tests/python_312.txt
See issue #5149. This skips the test that cannot run on 3.12+ and is problematic on PyPy. I think there should still be a warning somewhere if the APIs are used.
This also unpins setuptools for 3.12 so the tests can start.
=> Use setuptools>60 for cpython3.12, skip unicode test on PyPy and 3.12+

Cython/Includes/libcpp/unordered_map.pxd
See `unordered_map` above in the same file. Also https://en.cppreference.com/w/cpp/container/unordered_multimap/load_factor
=> missing load_factor method on unordered_multimap

Cython/Compiler/ModuleNode.py
At Meta, we have some large .pyx files generated by https://github.com/facebook/fbthrift . I found through profiling that `ModuleNode.sort_types_by_inheritance` was taking about 10% of the time for Cython to process our largest file, and through inspection that it took quadratic time. This PR changes `sort_types_by_inheritance` to use`sorted` to avoid quadratic time, with the result that `sort_type_by_inheritance` take a small fraction of a percent on the same large workload after this change.
This function seems to be covered by the `cdef_class_order` and `ooo_base_classes` tests; they failed during development and now pass.
=> Fix quadratic-time ModuleNode.sort_types_by_inheritance

docs/examples/userguide/fusedtypes/char_or_float.py, docs/examples/userguide/fusedtypes/conditional_gil.pyx, docs/examples/userguide/fusedtypes/indexing.py, docs/examples/userguide/fusedtypes/indexing.pyx, docs/examples/userguide/fusedtypes/pointer.py, docs/examples/userguide/fusedtypes/pointer.pyx, docs/examples/userguide/fusedtypes/type_checking.py, docs/examples/userguide/fusedtypes/type_checking.pyx, docs/src/tutorial/pure.rst, docs/src/userguide/fusedtypes.rst, docs/src/userguide/source_files_and_compilation.rst
This PR migrates fused types user guide to pure python. Moreover, this PR:
* moves examples to files in order to check them during CI build
* introduces some minor text improvements - formatting some paragraphs as a note, etc
* some code examples were improved for better readability
* in cython mode types are now used more consistently - avoid mixing (`TYPE` and `cython.TYPE`)
#4187
=> Docs: Migrate fused types userguide to pure python

Cython/Compiler/ExprNodes.py, tests/errors/nogil.pyx, tests/run/nogil.pyx
=> Relax `nogil_check()` of `SliceIndexNode` to support array initialisation

CHANGES.rst, Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/ModuleSetupCode.c, docs/src/userguide/migrating_to_cy30.rst, docs/src/userguide/source_files_and_compilation.rst, tests/run/cython3.pyx, tests/run/cython3_no_unicode_literals.pyx
Disregard 'x: int' type annotations only when language_level=2, and otherwise make sure that we accept both int and long in Py2.
Closes https://github.com/cython/cython/issues/4944
=> Accept both 'int' and 'long' for 'x: int'  annotations in Py2

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/Complex.c
The existing check didn't really work (but I've left it...). I think it's based on the quote:
> POSIX recommends checking if the macro _Imaginary_I is defined to
> identify imaginary number support.
My reading is that this is a way to determine if a special imaginary type exists, but only after including the header. Until you've included complex.h the macro won't be defined anyway.
From C11 there's a feature macro to determine if complex.h exists so I've used that as the main way of detecting it.
In principle this could be backported to 0.29.x, but I don't think it should be.
I've also fixed a couple of existing bugs that this exposed:
* integer complex types can't be handled by C (or C++ in principle) so must use the Cython implementation
* extern typedef complex types can't be handled …
=> Improve detection of C complex.h

Cython/Includes/cpython/unicode.pxd
Co-authored-by: William Ayd <william.ayd@icloud.com>
This is backport of #5163 to 0.29.x branch.
=> [0.29.x] Added PyUnicode_AsUTF8AndSize to cpython imports

Cython/Utility/CpdefEnums.pyx
Since python 3.7, builtin dict is guaranteed to keep insertion order, so use dict on python 3.7 or later instead.
Stdlib enum.Enum supports an iterable of `(name, value)` even since python 3.4, so a list of `(name, value)` pairs is good enough.
=> Remove unnecessary OrderedDict usage for CpdefEnums

.github/workflows/ci.yml, Tools/ci-run.sh, tests/run/cpp_extern.srctree, tests/run/test_named_expressions.py
Fixes named expression tests on Windows (I forgot that Windows filenames could contain ":")
Turns off allowed_failures on as many of the windows builds as possible
Fixes #5172
=> Fix named expression tests windows

Cython/Utility/ExtensionTypes.c, tests/run/cclass_assign_attr_GH3100.pyx
Since https://github.com/python/cpython/pull/25520 types are automatically marked as immutable if they are static.
While we still have the `Py_TPFLAGS_HEAPTYPE` hack in place we need to manually mark our types as immutable.
=> mark extension types as immutable

tests/run/asyncio_generators.srctree, tests/run/py35_asyncio_async_def.srctree
The behaviour of creating a new event loop if one doesn't already exist was removed in Python 3.12 alpha and was allegedly deprecated before then.
Fixes #5183
Wants to be in 0.29.x and master
=> [0.29.x] Avoid using asyncio.get_event_loop

Cython/Compiler/PyrexTypes.py, tests/errors/fused_types.pyx, tests/memoryview/numpy_memoryview_readonly.pyx, tests/run/fused_types.pyx
Cherry-pick candidate for 0.29.x - the actual change outside the tests is really pretty tiny. Would fix #3783
=> [0.29.x] Add support of const fused type memory views (GH-3118)

.github/workflows/wheels.yml
`cibuildwheel` puts the wheels into `wheelhouse`, not `dist`. There also doesn't seem to be any reason to list a bunch of separate per-platform wildcards, so replace them with `*.whl`.
=> Fix the step for uploading platform-specific wheels to GitHub

Cython/Compiler/ExprNodes.py, tests/run/struct_conversion.pyx
Related to #5178
Using `memcpy`, copy the content of an array into the array field of a `struct`.
=> Initialize array fields of struct with memcpy

Cython/Shadow.py
Fixes https://github.com/cython/cython/issues/5204
As specified by PEP 440: https://peps.python.org/pep-0440/#public-version-identifiers
=> Use Development release segment in public version identifiers

Cython/Utils.py
I [though](https://github.com/cython/cython/pull/5208#issuecomment-1377285773) that at last I could bring some value here, but @scoder it too fast 069794816423948a3dd7cc3365cf969d44fc9326 ^-^
Well, I don't want to throw the refactoring out, so here it is
=> Enhance `build_hex_version`

Cython/Utility/Embed.c
`Py_SetProgramName` and `PySys_SetArgv` has been deprecated in Python 3.11
Fix #5134 (part) and #4895
=> Replace deprecated functions

Cython/Utility/Embed.c
After #5210 parsing command line arguments turned on.
https://docs.python.org/3/c-api/init_config.html#c.PyConfig.parse_argv
=> Disable parsing command line arguments

runtests.py
`threading.Thread` supports enabling daemon mode through property `.daemon` begin from Python 2.6
Fix #5134 (part)
=> Switch from deprecated `.setDaemon()`

Cython/Compiler/ModuleNode.py
Was generating warnings like
```
templates.cpp:1639:52: warning: missing initializer for member ‘__pyx_mstate::__pyx_n_s_name’ [-Wmissing-field-initializers]
```
This PR should hopefully fix them
=> Avoid C++ warnings when initializing module state

setup.py
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
It's already tested, let's add the Trove classifier.
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
=> Declare support for Python 3.11

Cython/Compiler/TypeInference.py, tests/run/pep526_variable_annotations.py, tests/run/type_inference.pyx
~It currently infers to object, and double seems better than object.~
~I've picked "double" on the basis that this will always give the same precision answer as Python so it seems to match the semantics of "safe" mode better.~
Now does the simpler thing and just keeps it as a C float
Closes #5202
=> Infer float in "safe" mode

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
Supercedes https://github.com/cython/cython/pull/3702 (but fixes
the same error).
PyInit_* needs to return a new reference to the module object
so effectively we have to transfer ownership of a reference
to __pyx_m.
Also pay a bit more attention to cleaning up on the error path.
Co-authored-by: Matthias Braun <matze@braunis.de>
=> Fix an initialization reference counting error in the limited API

Cython/Compiler/Nodes.py, tests/run/locals.pyx
If you had a function
```
def f(**kwds):
return locals()
```
then 'kwds' would not appear in locals. Found while investigating
one of the coverage gaps listed in
https://github.com/cython/cython/issues/4163.
```
allow_null = all(ref.node.allow_null for ref in self.starstar_arg.entry.cf_references)  # 3772 ↛ exit
if allow_null:    # 3773 ↛ 3774
code.putln("%s = NULL;" % (self.starstar_arg.entry.cname,))
```
This uncovered code was wrong and has been removed. The only way
I can see to have an `allow_null` reference to the ** argument
would be to use `locals()`, and in this case an empty dict
should be generated.
=> Fix bug with unused keyword arguments and locals

Cython/Utility/Optimize.c
`__Pyx_PyUnicode_READ` for the limited API just uses `data` as the unicode object. Bring the initialization for unicode iteration in line with that definition.
Cherry-picked from https://github.com/cython/cython/pull/5261
=> Fix limited API unicode iteration

Cython/Utils.py
Since its first implementation in commit 9db1fc39b31b7b3b2ed574a79f5f9fd980ee3be7, depfiles try to calculate relative paths for files relative to the project base dir. This usually worked, but fails when the output directory is being used from another Windows drive letter. This can happen for build systems that encourage out of source build directories. When that happens, the logical thing to do is to use an absolute path anyway. That's what those build systems do as well, so the resulting depfiles still align with the build system manifest.
=> fix depfile generation on Windows, across different drives

Cython/Utils.py
Since its first implementation in commit 9db1fc39b31b7b3b2ed574a79f5f9fd980ee3be7, depfiles try to calculate relative paths for files relative to the project base dir. This usually worked, but fails when the output directory is being used from another Windows drive letter. This can happen for build systems that encourage out of source build directories. When that happens, the logical thing to do is to use an absolute path anyway. That's what those build systems do as well, so the resulting depfiles still align with the build system manifest.
(cherry picked from commit 038f94e9fd9e3b7ff279b3bd2627e974b94cb946)
=> [0.29] fix depfile generation on Windows, across different drives

Cython/Compiler/ModuleNode.py, Cython/Compiler/Pipeline.py, tests/run/cpdef_enums.pyx
Force utility code to come before pxd code which comes before module code. This specifically fixes #5269, (where the "ToPy" functions for cpdef enums weren't available when cyfunctions were created). But I think it's a good idea anyway.
=> Order merged_in utility code

Cython/Compiler/PyrexTypes.py, tests/run/pep526_variable_annotations.py
Allow it to use a Py-tuple instead of a ctuple
Fixes https://github.com/cython/cython/issues/5263
=> Fix annotation typing of Optional[tuple]

.github/workflows/ci.yml
=> Allow 3.12-dev in limited-api to fail

Cython/Utility/ModuleSetupCode.c
Apparently default function template parameters aren't allowed (and they don't seem to be needed here anyway)
Hopefully fixes #5316
=> Try to fix FakeReference on c++03

Cython/Includes/libcpp/any.pxd, tests/run/cpp_stl_any.pyx
closes #2633
Not much to say in fact...
Added an `any.pxd` to `Cython/Includes/libcpp/` and a test inspired by other STL tests.
=> Add support for C++ std::any

Cython/Compiler/FusedNode.py, Cython/Compiler/ModuleNode.py, tests/run/cimport_from_pyx.srctree
Related to #5072.
This pull request attempts to fix the compilation errors that happen when the Cython compiler fails to generate the declarations of unused exported functions from `pyx` files with the `cimport_from_pyx` option on.
=> Fix missing exported C function declarations with cimport_from_pyx enabled

Cython/Utility/MemoryView.pyx, tests/compile/fused_redeclare_T3111.pyx, tests/errors/pure_warnings.py, tests/memoryview/memoryview_no_withgil_check.pyx
The new exception-handling semantics meant that the utility code always had to check for exceptions on some void nogil functions (requiring us to re-acquire the GIL). This made performance noticably worse under some circumstances.
Fix this by making the exception specifications noexcept for quite a few cdef functions in the memoryview utility code.
Fixes https://github.com/cython/cython/issues/5324
=> Fix exception handling in memoryview utilitycode

Cython/Compiler/Buffer.py, Cython/Utility/Buffer.c, Cython/Utility/Overflow.c
this adds support for constant types in the `IS_UNSIGNED` macro to fix #5301 without reducing const correctness.
This uses the same implementation used for the C++11 type_trait `std::is_unsigned`: https://en.cppreference.com/w/cpp/types/is_unsigned
=> allow IS_UNSIGNED to handle const types

Cython/Utility/Exceptions.c
…se().
This is a backport of 1dba3d3b44 from Cython's master branch.
=> [0.29.x] Use a more correct and specific CPython internals guard in __Pyx_Raise()

Cython/Compiler/UFuncs.py, Cython/Utility/UFuncs.pyx, tests/run/ufunc.pyx
It looks like Numpy releases the GIL for us (unless it's PyObject arguments), so we should assume that we don't have the GIL, and write code to regain it if needed, rather than assuming we need to release the GIL.
Fixes #5328
=> Fix ufunc GIL handling

Cython/Compiler/FusedNode.py, tests/run/fused_types.pyx
Partial fix for #5297 - ideally I think we should do something cleverer, but this'd complicated memoryview dispatch significantly. This PR just restores the 0.29.x behaviour where None matches the first type.
=> Restore 0.29.x handling of None fused memoryviews

tests/run/relative_cimport.srctree
This test mirrors the structure of SciPy's `linalg.cython_blas`, `linalg.cython_lapack` and `special.cython_special` modules.
xref https://github.com/scipy/scipy/issues/17234#issuecomment-1471600772 for the relevant discussion on SciPy, and gh-4552 for the fix that made this work in `master`. Things are broken in 0.29.x for this `python runtests.py relative_cimport` (even before this addition, the gh-4552 fix wasn't backported):
<details>
```
$ python runtests.py relative_cimport
/home/rgommers/code/tmp/cython/runtests.py:2240: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
thread.setDaemon(True)  # Py2.6 ...
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
Running tests against Cython 0.29.33 …
```
=> Add a test for relative cimport within a submodule

docs/src/quickstart/cythonize.rst, docs/src/tutorial/pure.rst, docs/src/userguide/index.rst, docs/src/userguide/nogil.rst
This was originally step 1 in trying to copy some of my own https://cython-guidelines.readthedocs.io content into the official docs. However, I noticed that we're actually missing quite a bit of information about the GIL and thought it'd be good to bring it together in one place. So most of this PR is new content rather than moved content.
=> Added documentation about the GIL

Cython/Compiler/Main.py
This would be pretty useless as it cannot be used -- the output file does not exist either. But as it happens, on error, the output file is reset to None, so instead we triggered a python traceback while trying to write a depfile for `os.path.relpath(None, cwd)` that was written to `None+'.dep'`
Discovered when trying to help debug https://github.com/pandas-dev/pandas/pull/49115#issuecomment-1452775557
=> Do not attempt to write out a depfile on failure

Cython/Compiler/ParseTreeTransforms.py, tests/run/annotation_typing.pyx
Related to #5235
I discovered that the following code did not work with nodes having no child nodes, such as `NameNode`.
https://github.com/cython/cython/blob/0ffa7e91816a00a1694d1466aa91613b6708b244/Cython/Compiler/ParseTreeTransforms.py#L1106-L1111
```python
from cython cimport int as cy_i
cimport cython
def f(a: cython.int, b: cy_i):
print(cython.typeof(a), cython.typeof(b))
```
(Code from #5235)
It caused the `NameNode` of `cy_i` to be ignored by `InterpretCompilerDirectives` when it was referenced by `node.expr`.
=> Allow InterpretCompilerDirectives.visit_AnnotationNode to process nodes having no children

Cython/Utility/ModuleSetupCode.c
CPython 3.12a6 made PyThreadState an opaque structure thus the fast thread state optimization cannot be employed anymore.
Fixes #5286.
=> Fix compilation with CPython 3.12a6

Cython/Build/Dependencies.py
In the context of https://github.com/cython/cython/issues/5089, it seems like
the general opinion is that it's not a good idea to ship generated sources in
Python package release tarballs. 
Right now there are tons of Python package releases that *do* include generated
C sources, and they may be generated from Cython versions that were not forward
compatible or had bugs. It would make sense to re-cythonize those packages with
the same minor version of cython (typically 0.29.x), without having to patch
`force=True` into each and every setup.py script, especially since `setup.py clean`
is not generally defined as a command. Notice that in [some cases](https://github.com/gevent/gevent/issues/1936#issuecomment-1464038807) certain packages
simply won't update their tarballs and release bugfix …
=> Backport CYTHON_FORCE_REGEN=1 feature to 0.29

Cython/Compiler/Builtin.py, Cython/Compiler/Nodes.py, Cython/Utility/Exceptions.c, Cython/Utility/ModuleSetupCode.c
Work around the deprecation of Py_OptimizeFlag in Py3.12 by reading the value from the interpreter's current PyConfig.
This is probably less efficient than was originally intended and makes assertions a little more costly.
See https://github.com/python/cpython/issues/99872
=> Avoid deprecated Py_OptimizeFlag in Py3.12

Cython/CodeWriter.py, tests/run/embedsignatures.pyx
I hit this issue while adding argument annotations like `tuple[()]`. The annotation writer would emit `tuple[]`, which is invalid syntax. Despite the context being related to annotations, I believe the fix goes to the base `ExpressionWriter` class, so I did.
=> Fix AnnotationWriter for IndexNode with empty TupleNode

Cython/Compiler/Dataclass.py, Cython/Utility/Dataclasses.c, Cython/Utility/Dataclasses.py
Fixes #5346.
I've written a potentially slightly inefficient helper function to inspect the signature of dataclasses.field and
dataclasses._DataclassParams and drop any arguments that are unsupported (i.e. ones that we're passing because they apply to later Python versions).
=> Handle additions to signatures in Py3.12 dataclasses

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, tests/run/cascmp.pyx
If a cascaded comparison is partially optimized (i.e. only some of the comparisons are optimized) then the result types must end up consistent all the way through. At the moment we select PyObject which probably isn't the most efficient option, but is the easiest to implement.
Fixes #5354
=> Fix issues with partially optimized cascaded comparisons

Cython/Compiler/ModuleNode.py, Cython/Compiler/Naming.py, Cython/Utility/ImportExport.c
Fixes issue with changed signature for these functions between Cython releases (https://github.com/cython/cython/pull/5289#issuecomment-1509371606)
=> Distinguish api import functions from cython versions

Cython/Compiler/PyrexTypes.py, tests/memoryview/memoryview.pyx
Tentative fix for https://github.com/cython/cython/issues/5373
=> Make memoryviews with aliased types comformable

Cython/Compiler/ModuleNode.py, Cython/Compiler/Naming.py, Cython/Utility/ImportExport.c
Fixes issue with changed signature for these functions between Cython releases
Issue was reported here: https://github.com/cython/cython/pull/5289#issuecomment-1509371606
-----------------------------
Cut-down cherry-pick of https://github.com/cython/cython/commit/2a2608081dab528b2e28a3c729c049436e7ce8e6
I've dropped the cleanup of IdentifierString. I believe it probably is unused, but it doesn't seem necessary for 0.29.x
=> Distinguish 'api' import functions from different Cython versions

Cython/Compiler/ModuleNode.py, tests/run/cdef_class_order.pyx
Minor regression introduced in commit 1acc5b1634d34c2f26b4921068ac68372a9226d7 by @swolchok.
With this fix, cdef classes in mpi4py are emitted in the same order as Cython 0.29.x, classes are already ordered by inheritance int the source code, and IMHO that order should be preserved.
I've extended one of the tests to ensure that cdef classes are emitted in the order they appear in the Cython sources.
WITHOUT this fix, the added test would fail the following way:
```
Failed example:
test()
Expected:
A
B
C
X
Y
Z
Got:
C
X
Y
A
Z
B
```
=> Fix regression in code generation order for cdef classes

docs/src/userguide/wrapping_CPlusPlus.rst
This PR adds documentation of how a user could define a custom C++ exception handler that maps arbitrary C++ exceptions to arbitrary Python exception types. It includes an example of creating a new Python exception type via the Python C API, mapping it to a C++ exception via an exception handler function, and showing how to make the exception available in Python so that it may be caught if desired.
Closes #4613
=> Add an example of a custom exception handler.

Cython/Compiler/TypeSlots.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c
In the upcoming PyPy support for python3.10 we removed the `tp_pypy_flags` slot from `PyTypeObject`. I checked this worked with NumPy + MSVC (that is picky about matching structs when compiling) + PyPy 3.10 nightly build
If accepted, the change should be backported to the 0.29 branch. I expect to start the PyPy release cycle in May, so if this could be incorporated into a new release it would be helpful.
=> prepare cython for PyPy3.10

Cython/Compiler/CmdLine.py, Cython/Compiler/Tests/TestCmdLine.py
Checking for the existence of source files must account for the user-specified working directory. 
If the source filename is not absolute,  prepend the working directory if specified, then perform the check.
=> CmdLine: Fix regression when using the `--working` option.

Cython/Utility/ModuleSetupCode.c
Change #if to #ifdef so we don't get undefined macro warnings on non microsoft compilers.
Fix typo in macro.
=> Fix usage of _MSC_VER macro

tests/pypy_bugs.txt
These tests are enabled on master, and passed for me locally. 
I am trying to track down pandas-dev/pandas#50817 where using a PyDateTimeDelta crashes, it [seems](https://github.com/pandas-dev/pandas/issues/50817#issuecomment-1400786923)
> `(struct __pyx_vtabstruct_6pandas_5_libs_6tslibs_10timedeltas__Timedelta *)__pyx_v_self->__pyx_vtab` is `NULL`, which results in a segfault, any hints of how to write a test for this are welcome.
=> enable passing datetime tests on PyPy

Cython/Compiler/ModuleNode.py, tests/run/exttype_gc.pyx
This shows warnings in CPython (3.12) debug builds and can lead to crashes when GC triggers on an object while deallocating it. This is also an issue in 0.29.x, thus, needs to be backported.
=> Prevent calling the dealloc slot of a non-GC base class with GC tracking enabled

Cython/Utility/CppConvert.pyx
When compiling cythonized code which uses `std::vector` we get the following compiler warning on GCC 8 and Python 3.9 (which is turned into an error in our case):
```
my_file.cpp: In function ‘PyObject* __pyx_convert_vector_to_py_int(const std::vector<int>&)’:
my_file.cpp:4716:33: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
for (__pyx_t_5 = 0; __pyx_t_5 < __pyx_t_4; __pyx_t_5+=1) {
~~~~~~~~~~^~~~~~~~~~~
```
The generated code in question is as follows:
```cpp
/* "vector.to_py":75
*     cdef object item
*
*     for i in range(v.size()):             # <<<<<<<<<<<<<<
*         item = v[i]
*         Py_INCREF(item)
*/
__pyx_t_3 = __pyx_v_v.size();
__pyx_t_4 = __pyx_t_3;
for (__pyx_t_5 …
```
=> Fix a signedness compiler warning in vector.to_py

Cython/Compiler/TypeSlots.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c
Fixes #5436. PyPy < 3.10 still has a `tp_print` field, where CPython removed it for 3.9
=> PyPy < 3.10 needs tp_print

Cython/Utility/Complex.c, Cython/Utility/ImportExport.c, Cython/Utility/ModuleSetupCode.c
Clang gets upset when an undefined macro is used
=> Fix usage of __STDC_VERSION__ macro

Cython/Compiler/ExprNodes.py, Cython/Debugger/libpython.py, Cython/Utility/Coroutine.c, Cython/Utility/Exceptions.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c
… which replaces the (type, value, tb) exception triplet with a single tstate->current_exception value.
This allows to re-enable `CYTHON_FAST_THREAD_STATE` in Python 3.12.
=> Adapt the exception handling to Py3.12a6

Cython/Compiler/AutoDocTransforms.py, Cython/Compiler/FusedNode.py, Cython/Compiler/Options.py, Cython/Compiler/PyrexTypes.py, Cython/Shadow.py, docs/src/userguide/source_files_and_compilation.rst, tests/run/embedsignatures.pyx, tests/run/embedsignatures_clinic.pyx, tests/run/embedsignatures_python.pyx, tests/run/fused_types.pyx
Add `embedsignature.pure` compiler directive to generate pure-Python type annotations compatible with type hinting syntax. This mostly amounts to:
* Not emitting C type declarations in signatures.
* Preferring explicit argument type annotations over C types.
* Mapping C type names to the closest Python type name.
See https://github.com/cython/cython/issues/3150
=> Enhancements to autodoc/embedsignature

Cython/Shadow.py, tests/run/test_shadow_error.py
Fixes #5411, needed for using pickle with cython3 on NumPy
The basic premise is that a failure in `__getattr__` should raise an `AttributeError`
=> raise AttributeError inside __getattr__

.github/workflows/ci.yml
PR #5429 changed CI to use pypy3.9 nightly in order to get a pypy-specific `_PyEval_GetAsyncGenFinalizer` and `_PyEval_GetAsyncGenFirstiter`. Using a nightly is unstable, since sometimes they are broken. It is better to use the latest v7.3.12rc2 which includes the needed changes for #5429. This PR is temporary, I expect the final release within a week or two.
=> use pypy-3.9-v7.3.12rc2 instead of a nightly

.github/workflows/wheels.yml
This commit updates cibuildwheel to v2.13.0 in the GitHub Actions wheel.yml CI workflow. cibuildwheel v2.13 adds CPython 3.12 support, under the prerelease flag CIBW_PRERELEASE_PYTHONS, among other this.
A small first step in solving https://github.com/cython/cython/issues/5467.
> ### [v2.13.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.13.0)
> ✨ Adds CPython 3.12 support, under the prerelease flag [CIBW_PRERELEASE_PYTHONS](https://cibuildwheel.readthedocs.io/en/stable/options/#prerelease-pythons). This version of cibuildwheel uses 3.12.0b1.
> 
> While CPython is in beta, the ABI can change, so your wheels might not be compatible with the final release. For this reason, we don't recommend distributing wheels until RC1, at which point 3.12 will be available in cibuildwheel …
=> wheel CI: Update cibuildwheel to v2.13.0

docs/examples/tutorial/numpy/convolve2.pyx, docs/src/tutorial/numpy.rst, docs/src/userguide/memoryviews.rst
Fixes https://github.com/cython/cython/issues/5457
=> Update numpy tutorial not to use deprecated/removed np.int

docs/src/userguide/faq.rst, docs/src/userguide/pypy.rst
Fixes #5473. 
I checked with a `-b linkcheck` target, specifically
`sphinx-build -b linkcheck -d build/doctrees -D latex_paper_size=a4  . build/html | grep broken`
There is still this one that I don't know where it should go, but that can be done in a future PR if it requires larger refactoring
```
(src/userguide/external_C_code: line  660) broken    \
https://docs.python.org/dev/c-api/init.html#c.PyEval_InitThreads \
- Anchor 'c.PyEval_InitThreads' not found
```
=> DOC: fix broken links

docs/src/userguide/numpy_pythran.rst
Using the exemple in the documentation, I kept on getting the following error :
```
lib/lib_cython_serial.c:798:10: fatal error: pythonic/core.hpp: No such file or directory
798 | #include "pythonic/core.hpp"
```
The setup process could not find the header files.
This pull request fixes this small flaw in the docs.
=> added include_dirs to numpy pythran docs

.github/workflows/ci.yml
PyPy released a new version, so CI does not need to use a nightly.
=> Update pypy in CI to released version

CHANGES.rst, Cython/Includes/numpy/__init__.pxd, tests/run/numpy_test.pyx
Numpy removed the confusing aliases for `np.long_t` and `np.ulong_t` in https://github.com/numpy/numpy/pull/22637. This was incorporated into yesterday's v1.25.0 release. This broke tests and CI here.
=> sync with NumPy 1.25

docs/src/userguide/faq.rst
Reformatted links missed during the migration from the wiki to reST
=> Correct links in faq

Cython/Compiler/Nodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, tests/run/cpdef_enums.pyx
1. Where possible, track the equivalent integer value for an enum type as they're defined.
2. Use this to determine if the switch optimization can be used (if present)
3. If not present, disable the switch optimization for enum to py-enum conversion, since it's duplicates are pretty likely in this case.
Fixes #5400
=> Fix to-py conversion with duplicate enum values

docs/src/tutorial/embedding.rst, docs/src/userguide/troubleshooting.rst
This addition letter "s" cause error on displaying format.
Here is what it originally looks like:
This is what you really mean:
=> Fix display error on Cython3.0 document on troubleshooting

Cython/Compiler/PyrexTypes.py, tests/run/cpp_stl_conversion.pyx
The previously clashed with "int" containers.
Fixes #5516
=> Fix conversion of C++ bint containers

.github/workflows/ci.yml, Cython/Build/Inline.py, Cython/Build/Tests/TestInline.py, Cython/Compiler/Nodes.py, Cython/Compiler/Options.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Shadow.py, docs/examples/userguide/fusedtypes/conditional_gil.py, docs/src/userguide/fusedtypes.rst, tests/errors/pure_nogil_conditional.py, tests/run/pure_nogil_conditional.pyx
Fixes #5113.
This is secondary attempt. Supersedes #5200. It tries to:
1. Raise an error when directive contains expression in all cases except `with gil()` or `with nogil()`. This maintains compatibility with current status quo
2. `try_to_parse_directive()` returns `optname, value` for all non-error cases, which ensures that it does not break code using this function.
=> Recognize `gil()`/`nogil()` arguments in pure python mode

tests/run/complex_numbers_c99_T398.h
Follow up to d8bb216c261d1911a0725ea9364cb837e692416b just to ensure the behaviour is tested.
=> Test including complex in MSVC

tests/pypy_bugs.txt
The test added in #5510 does not pass on PyPy. Without adding a `gc.collect, the `release` is never called. But even when adding `gc.collect() between the deletions, the output is different. With this change:
```diff
from cython.parallel cimport prange
cimport cython
+import gc
from random import randint, random
include "../buffers/mockbuffers.pxi"
@@ -43,8 +44,11 @@ def refcounting_stress_test(int N):
del aview
+    gc.collect()
del bview
+    gc.collect()
del cview
+    gc.collect()
return total
```
I get as output (`release c` comes before `release b`)
```
acquired a
acquired b
acquired c
released a
released c
released b
```
I don't think there is a way to get doctest to have alternatives based on implementation, so I suggest skipping the test.
=> on pypy, skip test that depends on gc behaviour

CHANGES.rst
With Cython 3.0 in development for a long time, the release notes -- which are split over 15 different sections (11 alphas, 3 betas, at least 1rc, plus GA) and many years -- are IMO very hard to absorb for an average (or even advanced) user. Add on top that various different fixes were backported to 0.29 (or sometimes, just the compatibility, without the functionality), and it becomes pretty much impenetrable to know what's _actually_ in 3.0.
Even though it's probably a bunch of work, I think Cython 3.0 deserves some kind of unified release notes that are an easy reference of what's new, what's already in 0.29, what changed, etc.
I had a moment today to try my hand at this, but quickly realized that I'm a bit in over my head with coming up with categories, writing a prose summary, and …
=> WIP: Unified release notes

Cython/Utility/ImportExport.c
If enabling CYTHON_LIMITED_API, relative imports are failing the following way:
```
$ python3 -c 'from mpi4py import MPI'
File "<string>", line 1, in <module>
File "src/mpi4py/MPI/MPI.pyx", line 12, in init mpi4py.MPI
bootstrap()
File "src/mpi4py/MPI/atimport.pxi", line 291, in mpi4py.MPI.bootstrap
getOptions(&options)
File "src/mpi4py/MPI/atimport.pxi", line 139, in mpi4py.MPI.getOptions
from . import rc
KeyError: "'__name__' not in globals"
```
After looking elsewhere in utility codes, looks like using `$moddict_cname` with `CYTHON_COMPILING_IN_LIMITED_API` enabled should work by now after all the changes to support per-module state.
=> CYTHON_LIMITED_API: Fix import utility code

Cython/Compiler/ModuleNode.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c
Mostly that we store the PyCFunctionObject as an attribute of it rather than "inheriting" from PyCFunctionObject.
(Actually testing the compilation with `Py_LIMITED_API` defined needs to it be put on top of https://github.com/cython/cython/pull/5550, but I think this PR can stand alone generally)
=> Change CyFunction to compile with Py_LIMITED_API

Cython/Utility/CppConvert.pyx, tests/compile/vector_include.pyx, tests/run/bytesmethods.pyx, tests/run/charptr_decode.pyx, tests/run/unicode_slicing.pyx
Follow the lead of `Cython/Includes/cpython/pyport.pxd` to declare
`PY_SSIZE_T_MIN` and `PY_SSIZE_T_MAX` as `const`. This prevents Cython
from trying to override or assign to this "variable" when doing wildcard
imports.
Add a test that shows this behavior in one example.
Fixes https://github.com/cython/cython/issues/5562
---
Note: This PR morphed from just the test case to a patch that includes a modified version of the test as well.
=> Declare PY_SSIZE_T_MAX/PY_SSIZE_T_MIN as const 

Cython/Compiler/Main.py
At least one project tries to detect the Cython version by redirecting stderr to stdout and capturing it. This is done in pure POSIX shell, so it probably seemed like the simple and obvious solution for a less capable programming language given that no output at all was expected on stdout.
But the result is that the version number appears twice, and then gets misparsed and ends up triggering bad assumptions in the code running cython.
It turns out that it's pretty easy to just print once, though. Detect when stdout and stderr are redirected to the same location, and only print once.
See #5504
Fixes https://bugs.gentoo.org/911333
=> Only write the version to stderr, if it's a separate file descriptor from stdout

Cython/Utility/CythonFunction.c
PR #5556 changed the code to use `__Pyx_PySequence_ITEM`, but changed a bit too much on this line. This was causing PyPy to fail the `fused_def` test, after the fix the test passes.
[This](https://github.com/cython/cython/commit/9c3268163c#diff-de808597bd4a1085b999963541b05187126914c467a95f52290f810b36660affR311) is the change in the context of the PR
=> fix changed code

Cython/Compiler/ExprNodes.py, tests/run/cyfunction_defaults.pyx, tests/run/cyfunction_defaults_cpp.pyx
Related to #5553
The `analyse_types` function does not mark SimpleCallNode as analysed after successfully analysing the node as a type constructor. In #5553, this results in `vector[double]()` being analysed twice, as a constructor and as an initialisation function, and therefore the type is misinterpreted as void eventually.
=> Ensure analyse_types marks SimpleCallNode as analysed

Cython/Includes/libcpp/memory.pxd, Cython/Utility/CppSupport.cpp, Cython/Utility/ModuleSetupCode.c, tests/run/cpp_smart_ptr.pyx, tests/run/cpp_smart_ptr_helper.h
Also tweak the selection for move-if-supported. This now lets the user enable it by a define even if the compiler support isn't detected. This is useful because the new signature for make_unique kind of relies on move-if-supported to work.
Fixes #5560
=> Update signature of make_unique

.github/workflows/ci.yml
Three tweaks:
- The pypy3 CI run was using CPython since the condition to set up python was wrong
- Remove the pypy2 CI run, it is not popular enough to justify the resources
- Update the CI caching action to a newer version ~code and add a check if it is used~. The older action was [emitting warnings](https://github.com/cython/cython/actions/runs/5708344400) (scroll down a bit in the central window)~, revert to using the official action instead of a fork of a fork. I added a check if the cache is used, which should help debugging caching issues.~
=> Run CI with PyPy3, update caching

Cython/Utility/Exceptions.c
Closes https://github.com/cython/cython/issues/5605
=> Avoid using Py_OptimizeFlag in the Limited API.

Cython/Compiler/ExprNodes.py, tests/run/fused_def.pyx
Python object fused function arguments weren't being correctly coerced, which meant that sometimes an int was being cast directly to a PyObject*, causing a crash if you actually tried to use it.
=> Fix fused function default argument coercion

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Utils.py, runtests.py, tests/run/constant_folding.py, tests/run/int_literals.pyx, tests/run/large_integer_T5290.py, tests/run/pure_py.py
This avoids running into Python's limits about the maximum number of digits to use in string conversion.
Fixes #5596
I suspect this isn't *everywhere* that could generate long number strings but it's sufficient to solve the reported bug.
=> Use hex to store large integers

.codespellrc, .github/workflows/codespell.yml, CHANGES.rst, Cython/Compiler/PyrexTypes.py, Cython/Tempita/_tempita.py, Tools/cython-numpy-mode-kate.xml, Tools/gen_tests_for_posix_pxds.py, Tools/kate.diff, runtests.py, tests/run/cpp_classes_def.pyx, tests/run/pep448_test_extcall.pyx
Config does exclude quite a bit of ideosyncratic constructs and even a typo (`delimeters`) which is now part of the API, so I decided to leave it alone for this round.
=> codespell: add config, workflow (so no new typos sneak in) and get some typos fixed

Cython/Compiler/Main.py
Looks like this was inadvertently introduced in https://github.com/cython/cython/commit/2a625fbd8793a83e16c524b7804710591dfe363e.
Fixes `cython --version`, which is used by `FindCython.cmake`
=> Fix minor regression related to print_version()

.github/workflows/ci.yml, Demos/setup.py, Tools/ci-run.sh, runtests.py, test-requirements-312.txt, test-requirements-36.txt
Fixes #5607 by refactoring places that import `numpy.distutils`, which is deprecated. `numpy.get_include` has existed forever (well, since 2006), there is no fear it is missing from an older NumPy.
=> refactor out use of numpy.distutils

Cython/Compiler/PyrexTypes.py, tests/run/c_int_types_T255.pyx
Introduced in dec61cdd222ded6d5f96a635d9c4b0dddcbc4e78 (where `IS_ENUM` was introduced, which meant the implementation diverged but the name stayed the same)
Fixes #5623
=> Avoid conflict between int-to-py and anonymous-enum-to-py

Cython/Compiler/Nodes.py, tests/memoryview/memoryview.pyx
Fixes #5571.
I believe this is to any function with a special signature (essentially most dunder methods of cdef classes). The specific report was about properties though.
It largely just aligns the reference counting of memoryviews and PyObjects for these functions.
=> Fix reference counting of memoryview arguments to special functions

Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.pxd, Cython/Compiler/ParseTreeTransforms.py, tests/run/parallel.pyx, tests/run/sequential_parallel.pyx
Essentially the problem is that a `nogil` function just promises that the function *can* be called without the GIL, not that it actually doesn't have the GIL.
If you call `prange`/`parallel` inside that function while still holding the GIL, if any thread has finished the GIL will be held (... I think it's probably more of a mess than this, but mostly you get away with it...). If a thread is still running and tries to acquire the GIL then it'll deadlock permenantly.
I've solved this by adding an implicit `with nogil` around any `prange`/`parallel` that's in a `nogil` block but isn't certain that it has the GIL.
Fixes #5573 and #5564.
=> Fix issues with parallel/exception checked functions

Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, tests/run/pep526_variable_annotations.py
The attributes were accidently being converted to NameNode instead. The tests weren't picking this up because the names were available so were being looked up successfully.
Fixes #5536
=> Fix attribute lookup of standard library names

Cython/Utility/Buffer.c
Since we're returning a borrowed reference to None just for the sake of returning a success flag, and that's needlessly confusing.
See #5598
=> Switch __pyx_buffmt_parse_array to return an int

Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Compiler/Optimize.py, Cython/Utility/CythonFunction.c, Cython/Utility/ExtensionTypes.c, Cython/Utility/FunctionArguments.c, Cython/Utility/ModuleSetupCode.c, tests/run/isolated_limited_api_tests.srctree
(A good chunk of these changes are actually to do with the auto-generated pickling functions for an empty class)
=> Get some minimal cdef classes working with `Py_LIMITED_API`

Cython/Compiler/FusedNode.py, tests/run/fused_types.pyx, tests/run/fused_types_complex.pyx
Fix invalid C code with -DCYTHON_CCOMPLEX=0 when assigning a simple (integer) default value to a fused type generated complex argument (which ends up as a struct).
Closes https://github.com/cython/cython/issues/5644
=> Fix invalid C code when assigning int->fused complex with CYTHON_CCOMPLEX=0

Cython/Compiler/ExprNodes.py, tests/run/default_optional_gh5643.py
For Python int (which we turn into a plain Python object type internally to avoid Py2 int/long issues), we previously generated a type check which made the None default argument much more complex than it was.
Closes https://github.com/cython/cython/issues/5643
=> Avoid useless runtime type checks when coercing a None default argument to a Python type argument.

Cython/Compiler/Nodes.py
https://github.com/cython/cython/commit/584078a371ef412554a2cd0b96fcc20fb3b9c476 looks like it introduced a minor typo.
=> Fix loop var declaration

Cython/Utility/CppSupport.cpp, tests/compile/cppenum.pyx
When a scoped enumeration appears in the declaration of a method of a cdef class, the C++ declaration of the method currently appears before the necessary macro is defined. This PR moves that declaration to a different section that is always before type declarations.
Resolves #5637
=> Add enum class decl to before types block

runtests.py, tests/run/isolated_limited_api_tests.srctree
Add handling for a new `limited-api` tag that skips such tests when run under a non-cpython interpreter
Closes #5659 
Tested locally with `pypy runtests.py isolated_limited_api_tests` and `python3.9 runtests.py isolated_limited_api_tests`
=> skip tests with limited-api tag on non-cpython

Cython/Utility/ImportExport.c
Closes gh-5663
The older workaround was added in commit 12bbe5f3d2. Since `strchr` may return `NULL`, I don't see a reason here not to check for that the regular way. This fixes the warnings I'm seeing in the SciPy build.
=> Fix a null comparison compiler warning visible with gcc 12

Cython/Compiler/Nodes.py, Cython/Compiler/PyrexTypes.py
This PR Generate following code:
Comparing to master generated code:
Note: Code example is taken from bug report.
Closes #5670
=> Skip acquiring  GIL for __PYX_XCLEAR_MEMVIEW

Cython/Compiler/Nodes.py, tests/run/always_allow_keywords_T295.pyx, tests/run/callargs.pyx
Returning immediately instead of going through the error label (and creating a traceback) avoids a potentially unused label (due to preprocessor guards).
Closes https://github.com/cython/cython/issues/5681
=> Simplify the handling of immediate (and highly unlikely) failures when entering a Python function wrapper

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c, tests/run/compare_binary_pyversions.pyx
The compile time Python version is allowed to be older when using the Limited API / stable ABI.
Closes https://github.com/cython/cython/pull/5689
=> Implement a better check for the import time Python version

docs/src/userguide/parallelism.rst
If one is using MSVC on Windows and inserting "/openmp" in the extra_link_args option, then one will receive an unnecessary warning. It's only necessary to include "-fopenmp" when using gcc.
=> Update description of how to set flags for OpenMP with MSVC

Cython/Utility/ObjectHandling.c
Fixes #5665
I'm slightly surprised this hasn't caused more bugs. We're passing a dict where we should be passing a tuple of names.
Replacement should hopefully be right, but I don't know how optimized or otherwise it is.
=> Fix invalid fastcall dict when keywords are passed

Cython/Debugger/DebugWriter.py
This change attempts to exclude arguments with invalid tag names from being inserted into the `TreeBuilder` as per comment from gh-5552.
It does resolve the exception reported  in gh-5552 and in gh-5686, but I am not sure whether this is the best way to implement the idea to skip nodes with invalid names. 
Please feel free to suggest improvements.
=> Skip building trees for nodes with invalid tag name

Cython/Build/Dependencies.py
I completely overlooked this in https://github.com/cython/cython/pull/5307,
that backport was useless because the signature of `cythonize` is
```python
def cythonize(..., force=False, ...)
```
in 0.29.x instead of
```python
def cytonize(..., force=None, ...)
```
like it is on `3.x`, meaning that setting `CYTHON_FORCE_REGEN=1` had no effect.
=> cythonize 0.29.x: use force=None as default instead of force=False

Cython/Utility/ObjectHandling.c
In ` __Pyx_PyObject_CallNoArg`, the call to `__Pyx_PyObject_FastCall` should pass `(&arg)` instead of `(&arg) + 1`.
Closes gh-5716
=> Fix Out of bounds access Coverity reported issue

Cython/Utility/Exceptions.c
=> Release references to traceback objects in Python 3.12+

Cython/Utility/MemoryView_C.c
This fixes a warning (C4005). When using MSVC the macro `__pyx_nonatomic_int_type` is already defined above
=> Fix macro redefintion warning

Cython/Compiler/Nodes.py
It didn't need to acquire the GIL here unless lenv.nogil is set (since while it needs the GIL, it already has it).
=> Fix mistake acquiring GIL while generating closure functions

Cython/Build/Cythonize.py
Currently `cython` command contains `-+` command for producing .cpp files. The `cythonize` command does not have alternative, so the only hidden way how to compile file using C++ via `cythonize` is to use `# distutils: language = c++` flag.
=> Add `--cplus` argument to cythonize command

Cython/Compiler/Nodes.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c
This avoids crashes in debug mode where CPython's access functions assert a type check (which fails for CyFunction).
Avoid excluding CyFunction from the fast-call fast-paths for 0/1 args in Python debug mode.
Also include the 1-arg (METH_O) case in the optimisation - I cannot see a reason why only 0-args should be special-cased for CyFunction.
Fix a bug in __Pyx_TryUnpackUnboundCMethod() where we checked for "defined(CYTHON_COMPILING_IN_PYPY)" (which is always true) instead of the defined 0/1 value.
=> Clean up special handling of PyCFunction and CyFunction

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
```
src/petsc4py/PETSc.c:22:5: warning: 'CYTHON_LIMITED_API' is not defined, evaluates to 0 [-Wundef]
#if CYTHON_LIMITED_API
^
src/petsc4py/PETSc.c:5283:47: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
static unsigned long __Pyx_get_runtime_version();
^
void
src/petsc4py/PETSc.c:561483:49: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
static unsigned long __Pyx_get_runtime_version() {
^
void
3 warnings generated.
```
=> Fix -Wundef -Wstrict-prototypes

Cython/Compiler/Errors.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/Options.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, docs/src/userguide/source_files_and_compilation.rst, tests/run/nogil.pyx
Note I've removed the former option because I doubt it's been around long enough for people to use it. However, I could do both if needed.
Fixes https://github.com/cython/cython/issues/5757 (Note I haven't skipped them on explicit `except *` as I suggested there, just because that's a harder change so I'll look at it separately when I have more time)
Supersedes https://github.com/cython/cython/pull/5759/
=> Make performance hints a directive rather than an Option

Cython/Utility/ModuleSetupCode.c
```
src/petsc4py/PETSc.c:563230:49: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
static unsigned long __Pyx_get_runtime_version() {
^
void
1 warning generated.
```
=> Follow-up of MR #5756

Cython/Utility/Optimize.c, tests/run/isolated_limited_api_tests.srctree
This PR fixes `float(obj)` when running with the limited api enabled.
=> Fix limited api float

Cython/Utility/ObjectHandling.c, tests/pypy_bugs.txt, tests/run/index.pyx
since this behaves differently to the PyObject functions.
Fixes #5776 and some indexing bugs on PyPy and the Limited API
=> Stop fallback indexing code using PySequence_*Item first

Cython/Utility/ExtensionTypes.c
Rather than just declaring it impossible.
Fixes #5696
(Note that this isn't sufficient to declare multiply-inherited cdef classes in the limited api - the calling code generates a few `PyTuple_GET_ITEM`s. However, I have tested the dictoffset code itself)
=> Do no-type-slots dictoffset check as python lookup

Cython/Utility/FunctionArguments.c
This is only relevant on Python 3.13+
Fixes https://github.com/cython/cython/issues/5790
Still testing this.
=> Fix C++17 error: standard attributes in middle of decl-specifiers (CYTHON_UNUSED)

docs/src/tutorial/embedding.rst
I've seen a couple of questions on this lately so I think it's worth making clear that it's a limitation (so at least people don't waste too much time when they hit problems).
I've outlined a possible solution but it's a hint - it's not something I have had time to test unfortunately.
=> Add warning about embedding + multiprocessing

Cython/Shadow.py
Backport of part of 042451402cbbedbb3f6fc1b6324de880831367ff (but only the changes to Shadow.py rather than the tests, or changes to the scope of any directives)
=> Add missing directives to Shadow.py

Cython/Compiler/ExprNodes.py
This avoids a "Compiler crash in AnalyseExpressionsTransform", although still produces a compile error as intended.
The reason for the issue is that `i` comes from the length of `args`, where there is an additional object first in the list. The `self.args` is therefore offset by 1.
Bonus question: Why is this error here? I found this, as I was monkeypatching this error out. Seemingly, there's no issue passing `PyObject*` as a vararg parameter.
=> Fix indexing of self.args when passing Python object as varargs parameter

.github/workflows/ci.yml, runtests.py
and disable profiling tests there, since it doesn't look like we'll be able to fix them.
Knowing about other regressions is probably more important than testing profiling...
=> Remove allowed_failure from Python 3.12

docs/src/quickstart/install.rst, setup.py
Removed line using deprecated ``pip --install-options`` (https://github.com/pypa/pip/pull/11858). The second option (setting NO_CYTHON_COMPILE=true) still works. 
closes #5694
=> update no-compile install from source (closes #5694)

Cython/Build/Tests/TestCyCache.py
See #5825 for a description of the failure.
=> Disable failing Windows CyCache test

Cython/Compiler/ExprNodes.py, Cython/Includes/cpython/unicode.pxd, tests/errors/charptr_from_temp.pyx
1. Add missing C API functions for unicode to wchar_t (since these are what should be used to replace Py_UNICODE*).
2. Add an explicit warning for users converting to Py_UNICODE*.
=> Add missing unicode C API functions and Py_UNICODE warning

tests/run/trashcan.pyx
The test is requiring a derministic order of destruction which PyPy doesn't give reliably and thus we're getting occasional CI failures. Therefore just treat is as compile and don't crash test.
=> Partially disable trashcan test in PyPy

Cython/Utility/Optimize.c, tests/run/isolated_limited_api_tests.srctree
These macros stopped doing anything in Python 3.7 (and may have been broken before): https://github.com/python/cpython/issues/73323.
This has the side-effect of fixing basic arthmetic in the limited API.
=> Drop PyFPE macros

Cython/Compiler/Dataclass.py, Tools/make_dataclass_tests.py, tests/run/test_dataclasses.pyx
Part of #4303
This was originally supposed to go on top of https://github.com/cython/cython/pull/4989, but that's a pretty complicated PR while this is very simple and can be isolated so it may as well come first
=> Support match_args in cdef dataclasses

Cython/Compiler/Dataclass.py, Tools/make_dataclass_tests.py, tests/run/test_dataclasses.pyx
They hadn't been following proper tuple comparison semantics so had been giving the wrong result.
=> Fix dataclass comparison operators and enable tests

Cython/Compiler/ExprNodes.py, Cython/Utility/StringTools.c
Avoids a tuple for joining the unicode string parts.
=> Speed up fstrings

docs/src/userguide/external_C_code.rst, docs/src/userguide/source_files_and_compilation.rst
I've shown the 4 that are most user-relevant clearly, and hidden most of the rest by default (but documented them if people really want to read them).
=> Document user-selectable C macros

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, Cython/Utility/Builtins.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, Cython/Utility/ExtensionTypes.c, Cython/Utility/FunctionArguments.c, Cython/Utility/ImportExport.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c, docs/src/userguide/source_files_and_compilation.rst
Add a separate macro guard "CYTHON_ASSUME_SAFE_SIZE" for calling Py*_GET_SIZE() without expecting failures.
=> Add separate macro guard "CYTHON_ASSUME_SAFE_SIZE"

Cython/Compiler/Dataclass.py, Tools/make_dataclass_tests.py, tests/run/pure_cdef_class_dataclass.py
This should allow a field without a default argument a non-init argument with a default value (because the no-init doesn't appear as an argument in `__init__`).
Also add a few notes on non-working tests from CPython.
=> Fix dataclasses default field and with no-init

Cython/Utility/Builtins.c, Cython/Utility/ModuleSetupCode.c
By just calling builtin function.
Makes tempita build in limited API (possibly when combined with other limited api fixes)
=> Fix exec in limited API

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c, docs/src/userguide/extension_types.rst, docs/src/userguide/source_files_and_compilation.rst, docs/src/userguide/special_methods.rst
Avoids a few unused variable warnings. (It's unused anyway so this just gets rid of the definitions and a bit of pointless cleanup)
=> Disable all freelist code outside cpython

Cython/Includes/cpython/unicode.pxd
And add a missing function.
Possibly worth backporting to 3.0.x (at least partly)
=> Fix some exceptions in the unicode library

docs/src/userguide/language_basics.rst, docs/src/userguide/numpy_tutorial.rst, docs/src/userguide/source_files_and_compilation.rst
This PR:
* Fixes wrong documentation of `include_path` which does not control search path of C/C++ headers - fixes #1480
* Improves documentation of `Extention` parameters used in example to have it self contained and reader does not need to visit setuptools documentation for details.
* Adds *Compilation using setuptools* chapter to *Cython for NumPy users* and include numpy related documentation from *Source files and compilation*.
=> [Docs] Reorganize and improve documenation of `include_dirs` and `include_path`

Cython/Compiler/Symtab.py
I don't think it was ever used.
(No need to review... just checking I haven't missed anything. I'll merge it if it passes)
=> Remove unused Entry.pep563_annotation

Cython/Compiler/Optimize.py, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c, tests/run/dict_pop.pyx
Use the new `PyDict_Pop()` function in Py3.13 and special-case the common "discard and ignore" use case.
=> Improve optimisation of "dict.pop()"

Cython/Compiler/ParseTreeTransforms.pxd, Cython/Compiler/ParseTreeTransforms.py, tests/run/async_def.pyx
Do this by ignoring the generator expression iterator when searching for yield/await nodes - the iterator is evaluated in the outer scope instead.
Fixes #5851
=> Fix await/yield/yield from in genexpression iteration

Cython/Compiler/Nodes.py
Address sanitizers consistently gives an error on running the "parallel" test, saying that it ends up getting freed after releasing and reacquiring the gil, and thus we can't keep using the same threadstate.
I'm not sure I understand threadstate well enough to know if this is expected behaviour, and I suspect it pessimizes some of the exception handling a little.
=> Fixes an address-sanitizer issue in parallel

Cython/Compiler/Nodes.py, Cython/Utility/FunctionArguments.c, docs/src/userguide/migrating_to_cy30.rst, tests/run/annotation_typing.pyx
For most builtin types, Cython interprets an annotation to mean that an exact type is required. This is stricter than PEP-484 and occassionally causes confusion.
1. Adds a bit more detail to the exception message in these cases (or to `__notes__` in Python 3.12+) to explain.
2. Add a note in the migration guide.
I've only applied this to function arguments. Applying it to general assignments would be possible but looks significantly more complicated so I thought it better to cover the main case.
Related issue: https://github.com/cython/cython/issues/5908
=> Add extra info on annotation inexact type

Cython/Debugger/libcython.py
In most cases, gdb calls the [completion method twice](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/python/py-cmd.c;h=7143c1c5f7fdce9316a8c41fc2246bc6a07630d4;hb=HEAD#l140), meaning that it's possible for [`word`](https://github.com/kentslaney/cython/blob/6ea8ca4e9701a2ced71b9abdf201563c6a9bc507/Cython/Debugger/libcython.py#L828) to be [`None`](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/python/py-cmd.c;h=7143c1c5f7fdce9316a8c41fc2246bc6a07630d4;hb=HEAD#l195) (in this case, [`text` is also empty](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/completer.c;h=d69ddcceca9ce5940e5fce136f10529228d7917d;hb=HEAD#l1269)). This means that, in some cases, `CyBreak.complete` will throw
```
File …
```
=> Cygdb completion bug fix: handle_brkchars support

tests/run/cpdef_extern_func.pyx
I don't think the test is really interested in the exact type of strchr, so instead wrap a function with a known function type.
Fixes #5939
=> Fix types in cpdef_extern_func

Cython/Build/Tests/TestCyCache.py
instead of relying on the destructor to do it.
I'm not sure if this'll fix it, but it's maybe worth a try. If it works, fixes https://github.com/cython/cython/issues/5825
=> Force closing gzip file in TestCyCache

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, tests/errors/cfuncptr.pyx, tests/errors/e_excvalfunctype.pyx
I think the existing message is a little confusing. This hopefully makes it clearer where to add `noexcept`.
Backport of 0b6cab31738870e60b4ae552dd1c4335529c71a0 and 15675a5e2ff2685b9aa1af7695fe306548361a92 (I'm including 1567a5 in this because I think it ends up too much of a mess if I backport 1 and not the other).
=> Improve message when exception values don't match (3.0.x backport)

docs/src/userguide/source_files_and_compilation.rst
The example raised the following error while cythonising.
`error: unknown file type '.c,'`
It looks like the correct syntax is either without the comma or with brackets around.
The function that parses this is here
https://github.com/cython/cython/blob/master/Cython/Build/Dependencies.py#L139
=> Fix distutils sources syntax

pyximport/pyximport.py
#4630 started to use relative paths in pyximport, when the path got long, to avoid issues on Windows.
This has two issues:
1. A bug, the path calculation assumed that the common path would be the same as the CWD.
2. It loses information, on platforms that don't have this filesystem limitation. In particular, it breaks pretty traceback formatting in `stack_data`, if the source file isn't available at the same relative path.
Discoverd these while investigating [Debian bug #1056872](https://bugs.debian.org/1056872)
=> pyximport: Use relative paths less, and correctly

tests/run/test_unicode.pyx
Fixes #5927.
I don't think this test is useful for reasons documented in the comments, thus I propose to get rid of it rather than spend time debugging it.
Note - targetted at 3.0.x
=> Disable unicode test_raiseMemError

Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py
`is_extern` doesn't look to be something we use, but it's been mistyped a few places when we meant `is_external`.
=> "is_extern" -> "is_external"

Cython/Compiler/PyrexTypes.py, tests/run/cpdef_enums_import.srctree
It's possible to declare an extern enum multiple times, in a way that makes the declaration name the same. Therefore, also prefix declaration names with the module qualified name where possible.
=> Fix some more duplicate enum to_py utility code names

Cython/Utility/CpdefEnums.pyx
This is just to make the warning a little less noisy. I think it's worth printing it, but probably not on every conversion.
Also make the function a little more lightweight by not repeating the import multiple times.
=> "failed to import" warning once per cpdef enum

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
In this case we actually have to initialize rather than just do nothing. Fixes #5278.
Supercedes #5296 (I think this is better since it limits the amount of work Cython itself has to do)
=> Modified "pretend_to_initialize" for c++

Cython/Compiler/PyrexTypes.py, tests/run/builtin_memory_view.pyx
Fix the compilation error:
```
error: call to undeclared function 'PyMemoryView_CheckExact'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
if (!(likely(PyMemoryView_CheckExact(__pyx_v_rv))||((__pyx_v_rv) == Py_None) || __Pyx_RaiseUnexpectedTypeError("memoryview", __pyx_v_rv))) __PYX_ERR(0, 172, __pyx_L1_error)
```
=> Fix memoryview type checking issue

.github/workflows/ci.yml, .github/workflows/wheels.yml, tests/errors/nogil_buffer_acquisition.pyx
Fixes #5979
Before (without numpy installed):
```
$ python runtests.py nogil_buffer_acquisition -vv
Python 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
Running tests against Cython 3.1.0a0 55c24376c6173f255f8b063625b466e1c7c169e8
Using Cython language level 2.
Test dependency not found: 'numpy'
...
Backends: c,cpp
runTest (__main__.CythonCompileTestCase.runTest)
[-1] compiling (c/cy2) nogil_buffer_acquisition ... 
=== Expected: ===
5:15: Buffer may not be acquired without the GIL. Consider using memoryview slices instead.
=== Got: ===
3:8: 'numpy.pxd' not found
5:15: 'ndarray' is not a type identifier
FAIL
```
After (without numpy installed)
```
$ python runtests.py nogil_buffer_acquisition -vv
Python 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
Running tests against Cython …
```
=> add tag for numpy in error test, update actions versions

tests/run/builtin_memory_view.pyx
There's differences in what it prints that are pretty unrelated to the point of the test, so just skip the test.
=> Skip builtin memoryview test on Python 2 (3.0.x)

Cython/Build/Tests/TestCyCache.py
Backport of 2f1a9bafec62a63cabf1268e82cdca7b86395a32 and 2f314fb1b1fd0a93eca08d842a7616e5c804105d
(For testing only, no need to review)
=> Force closing gzip file in TestCyCache (#5945)

.github/workflows/ci.yml, .github/workflows/wheels.yml, tests/errors/nogil_buffer_acquisition.pyx
* add tag for numpy in error test
* fix the test for the extra line
* upgrade github actions to versions using node20
* update ccache action, add python version to wheel upload name
Barkport of #5985 to 3.0.x - just confirming that it runs correctly there
=> add tag for numpy in error test, update actions versions (#5985)

Cython/Build/Dependencies.py, Cython/Build/Tests/TestDependencies.py, Cython/Build/Tests/TestStripLiterals.py
… to handle unclosed string literals and recursive f-strings.
Closes https://github.com/cython/cython/issues/5977
=> Reimplement "Dependencies.strip_string_literals()"

Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c
Python 3.13a4 adds a public PyCFunctionFastWithKeywords type and removes the private _PyCFunctionFastWithKeywords type:
* https://github.com/python/cpython/commit/9e3729bbd77fb9dcaea6a06ac760160136d80b79
* https://github.com/python/cpython/pull/114627
* https://github.com/capi-workgroup/decisions/issues/11
=> Use Python 3.13a4 PyCFunctionFastWithKeywords

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c
It's deprecated in 3.13, so the existence of a function is now generating C warnings. Therefore move it to its own section to be included on demand.
Remove a limited API implementation for it - it isn't in the limited API so just shouldn't be usable there.
Fixes #5982
=> Move Py_UNICODE out of universal utility code

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c
It's deprecated in 3.13, so the existence of a function is now generated C warnings. Therefore move it to its own section to be included on demand.
Remove a limited API implementation for it - it isn't in the limited API so just shouldn't be usable there.
Fixes #5982
=> Move Py_UNICODE out of universal utility code (#6006) (3.0.x backport)

Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, Cython/Utility/StringTools.c
This seems to take about 1.5% off the size of
compiled "ParseTreeTransforms".
Essentially the original version is "an array of pointers to unmodifiable strings". The new version is
"an unmodifiable array pointers to unmodifiable strings". Presumably the advantage is that the compiler can know the result at compile-time in a lot of cases.
=> Tighten the constness on some string arrays

Cython/Compiler/ExprNodes.py, Cython/Utility/ObjectHandling.c
Analagous to "PyTuple_Pack" designed to be used in "slow" (i.e. module-level) code. The main thing this catches are lists used in "from something import name".
Also use `PyTuple_Pack` more thoroughly in module-level code. The slow attribute of SequenceNode was never being set. This probably affects tuples used in class construction like the bases tuple, which isn't a literal.
(Part of "looking at small marginal module-size gains" https://github.com/cython/cython/issues/4425)
=> Add __Pyx_PyList_pack function

Cython/Includes/libcpp/string.pxd, tests/run/cpp_stl_string.pyx
Hi, I noticed the other day that the `string.replace(...)` functions were missing in libcpp.string. Assuming there was no reason they are missing, I've added them to the pxd file.
=> Added missing `replace` functions to C++ `std::string` definition

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py
As opposed to declaring them individually.
Unlikely to make a huge different in compiled size (except to module-state builds, where it simplifies the cleanup). However, does mean that things like tuples can be indexed, which may help with optimizing codeobjecttab
=> Declare tuple/slice/other constants in arrays

Cython/Compiler/ExprNodes.py, Cython/Utility/ExtensionTypes.c, Cython/Utility/ModuleSetupCode.c
The main change being that PyType_Modified is considered part of the operation so is moved into utility code instead of being something that we have to remember to call.
=> Cleanup of SetItemInTypeDict

Cython/Compiler/ExprNodes.py
See https://github.com/cython/cython/issues/2747
=> Disable GCC warnings/errors about wrong self casts in final function calls

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
Stop using a table with init data and use one function call per code object creation again, but reduce the number of arguments passed into that function.
See comment in https://github.com/cython/cython/pull/6053#issuecomment-1975229048
See https://github.com/cython/cython/issues/4425
Supersedes https://github.com/cython/cython/pull/6044
=> Reduce the overhead of creating the function code objects at module init time

Cython/Compiler/ModuleNode.py, Cython/Compiler/Options.py, Cython/Distutils/build_ext.py, Cython/Utility/Exceptions.c, docs/src/userguide/source_files_and_compilation.rst, runtests.py, tests/run/cline_in_traceback.srctree
* If the user has specified the c_line_in_traceback=False option
to the Cython compiler, then set CYTHON_CLINE_IN_TRACEBACK=0 to
avoid generating all the code to print clines out.
* If the user has defined the C flag CYTHON_CLINE_IN_TRACEBACK=0 then
skip recording the C line on an exception (since we know this
is expensive in terms of code size, and we'll never actually
use what we've recorded)
PR also includes commits from #6035 so merge that first.
This should probably be 3.1 only.
=> Rationalize the different cline traceback options

tests/memoryview/contig_check.pyx, tests/memoryview/memoryview_annotation_typing.py, tests/memoryview/numpy_memoryview.pyx, tests/memoryview/numpy_memoryview_readonly.pyx, tests/memoryview/relaxed_strides.pyx, tests/run/numpy_parallel.pyx, tests/run/numpy_test.pyx, tests/run/ufunc.pyx
Fixes #6072 
Should this also add a numpy2.0b1 test run to CI via the wheels at https://pypi.anaconda.org/scientific-python-nightly-wheels/numpy (i.e. install numpy via this index)?
```
pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
```
Edit: make it a question
=> make tests run on numpy1.x and numpy2.x

Cython/Compiler/Nodes.py, Cython/Compiler/Parsing.py, Cython/Includes/cpython/array.pxd, Cython/Includes/cpython/complex.pxd, Cython/Includes/cpython/datetime.pxd, Cython/Includes/cpython/time.pxd, tests/run/legacy_implicit_noexcept.pyx
Follow up to: https://github.com/cython/cython/pull/5999#issuecomment-1987520482
Currently, the warning `Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.` gives false positives for functions returning python objects. This is misleading and results in naively adding incorrect `noexcept` clauses (as in https://github.com/sagemath/sage/pull/36507 which added about 40k incorrect ones!).
With #5999, the incorrect `noexcept` clauses are warned, which is good. But it also means that it's not possible to "fix" warnings for some functions (when running in legacy implicit noexcept mode).
For instance in
```
$ cat test_noexcept.pyx 
cdef test_good():
return 0
cdef test_bad() noexcept:
return 0
$ cython -3 -X legacy_implicit_noexcept=True …
```
=> Fix warnings for "implicit noexcept" when using `legacy_implicit_noexcept=True`

tests/run/legacy_implicit_noexcept.pyx
By keeping the "print_stderr" changes, but not using contextlib.
Supercedes #6103
No real need for review - just checking the CI before merging
=> 3.0.x fix legacy_implicit_noexcept tests

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
Closes #6099
Partial cherry-pick of https://github.com/cython/cython/pull/5885 (I've omitted the docs changes)
No need for review I think - I'm just checking it runs before merging
=> [3.0.x] Disable all freelist code outside CPython and add a new guard

tests/run/numpy_pythran.pyx, tests/run/numpy_pythran_unit.pyx, tests/run/numpy_test.pyx
Continuation of #6076 to make tests pass on NumPy2 and still support NumPy1.
The complex changes incorporate the fix for numpy/numpy#26029. Unfortunately on C++, NumPy no longer supports `a[1].real += 1`. It still works in C, but not in C++. This is documented in the [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#complex-types-underlying-type-changes) (last paragraph in that section).
=> more fixes for NumPy2

Cython/Utility/CppConvert.pyx, tests/run/cpp_stl_conversion.pyx
Calling push_back in a loop to grow the vector caused it to perform repeated unnecessary memory allocations.
In this change, the necessary memory is reserved once ahead of the loop. This has a significant performance improvement for large data sets.
For objects which do not have a length, the original behaviour is preserved.
=> Reserve vector memory upfront

docs/src/userguide/source_files_and_compilation.rst
Currently, the rendering of the link to PEP 518 is broken (see https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#basic-setup-py). This PR should fix this.
=> Fix broken rendering of PEP link

test-requirements-312.txt, test-requirements.txt
Backport a799b1b to 3.0.x, see [this thread](https://github.com/cython/cython/pull/6100#issuecomment-2016711585) in cython/cython#6100.
Once NumPy releases 2.0.0rc1, these pins should be reverted.
=> CI: Pin Numpy<2 in test dependencies.

tests/run/complex_numbers_cpp.pyx
I think the issue was partly that the function was defined twice with slightly different tests and that this was behaving differently on Py2.7, but not completely sure.
Either way, it's testing the standard library rather than our code, so we probably don't have to make it too detailed beyond that it compiles.
=> [3.0.x] Fix c++ complex double_proj test

Cython/Compiler/PyrexTypes.py, Cython/Compiler/Tests/TestTypes.py
Because max_prefix was much less than max_len, it was actually just making the names longer.
Probably fixes #6052 (unfortunately, I can't actually reproduce the issue from the information in the issue so it's hard to know)
=> Fix cap length

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, tests/compile/nogil_perf_hints.pyx, tests/compile/nogil_perf_hints_pxd.pxd, tests/run/nogil.pxd, tests/run/nogil.pyx
In order to be called efficiently, these functions must have the exception specification set in the pxd file since Cython is unable to assume an implicit exception specification.
This improves the quality of the messages to draw attention to this detail.
Closes #6001
=> Improve performance hints for nogil + pxd

Cython/Compiler/Code.py, Cython/Compiler/UtilityCode.py, Cython/Utility/CppConvert.pyx, Cython/Utility/ObjectHandling.c
Follow up to https://github.com/cython/cython/pull/6077.
I've had to make a change to allow Cython utility code to require C utility code - I think that's worthwhile but there's other ways rounds the problem if we don't want to do that (e.g. just putting __Pyx_PyObject_LengthHint in the universal module setup code).
I've picked the easy route and not implemented a limited API version of length hint. It'd be perfectly possible to do this, but it doesn't really seem like a priority.
=> Make C++ conversion lengthhint limited-api friendly

tests/run/analyse_expressions.srctree
Including a .srctree file with modules A and B to validate the overriding behaviour of `analyse_expressions` method.
Fix to #4163 
```python
4644    def analyse_expressions(self, env): 
4645        self.args = env.arg_entries 
4646        if self.py_func.is_module_scope:  # 4646 ↛ 4647
4647            first_arg = 0 
```
=> Add tests to cover Node analyse expressions

Cython/Compiler/Parsing.py
The unused `@cfunc` was creating a compiler warning
=> Remove unused function from Parsing.py

Cython/Compiler/Symtab.py
Fix a typo introduced in https://github.com/cython/cython/pull/4673.
Shouldn't make a difference but avoids accidently generating __dict__ and __weakref__ getters
=> Fix typo in defaults-as-class

Cython/Compiler/Code.py, Cython/Compiler/TypeSlots.py, tests/run/binop_reverse_methods_GH2056.pyx
This means that the user-provided version can be looked up by e.g. `self.__add__` skipping the Cython-generated dispatch wrapper and matching python semantics.
Fixes #5863
=> Always add binops to methoddef

docs/examples/tutorial/parallelization/manual_work.pyx
Fixes the following error:
```
cython -3 docs/examples/tutorial/parallelization/manual_work.pyx
performance hint: docs/examples/tutorial/parallelization/manual_work.pyx:9:5: Exception check on 'long_running_task1' will always require the GIL to be acquired.
Possible solutions:
1. Declare 'long_running_task1' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
2. Use an 'int' return type on 'long_running_task1' to allow an error code to be returned.
performance hint: docs/examples/tutorial/parallelization/manual_work.pyx:14:5: Exception check on 'long_running_task2' will always require the GIL to be acquired.
Possible solutions:
1. Declare 'long_running_task2' as 'noexcept' if you control the definition and you're sure you don't want …
```
=> Docs: Fix example manual work in parallelization

docs/examples/tutorial/string/cpp_string.pyx, docs/examples/tutorial/string/for_bytes.pyx, docs/examples/tutorial/string/for_char.pyx
Fixes the following examples: 
```
cython -3 -+ docs/examples/tutorial/string/*.pyx
...
def get_bytes():
py_bytes_object = b'hello world'
cdef string s = py_bytes_object
s.append('abc')
^
docs/examples/tutorial/string/cpp_string.pyx:9:12: no suitable method found
...
cdef bytes bytes_string = b"hello to A bytes' world"
cdef char c
for c in bytes_string:
if c == 'A':
^
docs/examples/tutorial/string/for_bytes.pyx:5:12: Unicode literals do not support coercion to C types other than …
```
=> Docs: Fix string examples

Cython/Utility/ModuleSetupCode.c
This works locally (numpy.random test suite passes, no new test failures in the cython tests) and should be substantially faster. It was disabled for the python 3.9 nogil fork but @colesbury tells me the version in Python 3.13 supports vectorcall.
=> Enable vectorcall on nogil build

Cython/Compiler/Nodes.py, tests/run/legacy_implicit_noexcept_build.srctree
When .pxd file is defined there are two runs CFuncDeclaratorNode.analyse:
1. run is executed for .pxd file and is triggered by the parser
2. run is executed for .py file and is triggered by ParseTreeTransform.AlignFunctionDefinitions.visit_DefNode
The problem is causing 2nd run because it does uses information from entry which misses correct value of has_explicit_exc_clause (default value False is used).
PR solves it by not overriding exception_check when CFuncDeclaratorNode is already declared by .pxd file since it already contains correct value of exception_check from 1st run. 
Fixes #6122
=> Do not set exception_check if already set during analyzing pxd file

Cython/Includes/cpython/ref.pxd, docs/examples/userguide/language_basics/parameter_refcount.py, docs/examples/userguide/language_basics/parameter_refcount.pyx, tests/buffers/bufaccess.pyx, tests/memoryview/memoryview.pyx, tests/memoryview/memslice.pyx, tests/run/exceptionrefcount.pyx, tests/run/refcount_in_meth.pyx, tests/run/test_coroutines_pep492.pyx
In the nogil build, the `PyObject` struct doesn't have an `ob_refcnt` field. This adds bindings for `Py_REFCNT` to the `cpython.ref` namespace and replaces all usages of `ob_refcnt` in the tests and docs with the new bindings for the macro.
Note there are still `ob_refcnt` usages in the cython implementation:
https://github.com/cython/cython/blob/023d4af351042a3b6241dbe06cbb003b3ce1fb58/Cython/Utility/Coroutine.c#L1283
However it's guarded by a `#if !CYTHON_USE_TP_FINALIZE` so in practice the nogil build doesn't hit it. It also wasn't clear to me what to do about a usage that mutates the refcount but explicitly can't use the refcounting macros.
=> Add bindings for Py_REFCNT and use it in tests and docs

Cython/Includes/libcpp/deque.pxd, tests/run/cpp_stl_cpp11.pyx
I've updated cython/Cython/Includes/libcpp/deque.pxd to include two functions to move a single T object to the front or back:
emplace_front()
emplace_back()
I also added test code to cython/tests/run/cpp_stl_cpp11.pyx to test the two new functions, under the test function:
test_deque_functionality()
Please let me know if something is wrong with both the pull request or code as this is my first time attempting to contribute to an open-source project.
=> Updated deque.pxd to include two functions from C++11

Cython/Compiler/Code.py, Cython/Compiler/ParseTreeTransforms.py, docs/src/userguide/special_methods.rst
Instead of complaining about conversion of arguments.
Update the docs.
Fixes #6174
=> Warn on use of the old Py2 buffer protocol

Cython/Utility/TypeConversion.c
Untested since it's not released yet.
See https://github.com/python/cpython/issues/111140
=> Use the new large PyLong conversion functions in Py3.13.

Cython/Utility/ExtensionTypes.c, docs/src/userguide/special_methods.rst, tests/run/module_init_error.srctree, tests/run/special_methods_T561.pyx
Based on https://docs.python.org/3/reference/datamodel.html#object.__set_name__
Fixes #5523
=> Call `__set_name__` during setting type attribute.

runtests.py
According to the Python 3.12 documentation findTestCase is deprecated and removed in 3.13 in favor of loadTestsFromModule.
=> Test runner: Python 3.13 removes unittest.findTestCase

Cython/Includes/libcpp/optional.pxd, tests/run/cpp_stl_optional.pyx
`std::optional::value()` raises a `std::bad_optional_access` if it does not contain a value. See [std::optional::value()](https://en.cppreference.com/w/cpp/utility/optional/value).
=> Mark `libcpp.optional.optional.value()` as `except +`

Cython/Utility/ObjectHandling.c
This block is in `#if PY_VERSION_HEX >= 0x030b00a6`, but Python 3.11.0a6 doesn't have f_localsplus.
https://github.com/python/cpython/blob/v3.11.0a6/Include/internal/pycore_frame.h
f_localsplus was removed 3.11.0a1.
https://github.com/python/cpython/commit/b11a951f16f0603d98de24fee5c023df83ea552c
On the other hand, CYTHON_VECTORCALL is enabled for CPython 3.8+.
So this section is not used and doesn't work.
=> remove unused include pycore_frame

docs/src/tutorial/numpy.rst
Partial fix for #4641
Partial fix for #6160
=> Documentation of old buffer syntax options

docs/examples/userguide/language_basics/parameter_refcount.py, docs/examples/userguide/language_basics/parameter_refcount.pyx, docs/src/userguide/language_basics.rst
I think this makes some of the different behaviour clearer. The initial example was somewhat complicated by things like "is sys.getrefcount creating an extra reference?", and reading global variables inside the functions which isn't
hugely relevant to much.
This tries to show the effect of creating new references inside a function, which is more direct and probably shows what we actually want.
=> Update documentation refcounting example

Cython/Includes/cpython/time.pxd, tests/run/time_pxd.pyx
Raw time functions that do not require the GIL were added to the C-API in Py3.13.
See https://github.com/python/cpython/pull/115215
See https://github.com/python/cpython/issues/110850
=> Py3.13 support in cpython/time.pxd

Cython/Utility/CythonFunction.c, tests/run/isolated_limited_api_tests.srctree
Except for the case where binding=False, which I don't think we can easily do. I don't care that much given that binding=True works correctly.
Fixes #5797
=> Make classmethod work in limited-api

runtests.py, tests/limited_api_bugs.txt, tests/memoryview_tests.txt
These are a big chunk of tests that need to be run/not run in Limited API mode depending on the Python version.
This categorization isn't hugely useful right now, but should become more useful as we're able to test more with the limited API.
=> Categorise memoryview tests

docs/src/userguide/source_files_and_compilation.rst
This is a tentative fix for #5089, following [@scoder's reply](https://github.com/cython/cython/issues/5089#issuecomment-1408714455)
I feel that the section as it exists now still has value as an historical document, and the modern recommendation is simple enough that it can maybe live alongside it instead of replacing it, but I'm happy to change my approach if desired.
=> DOC: recommend not distributing generated code

Cython/Utility/Exceptions.c, tests/run/dealloc_raise.srctree
I'm not 100% sure what causes the error, but I think it's that _PyErr_PrintEx stashes away some illicit references to invalid objects on sys.last_exc.
There's no reason to do this, so just do the print without the stash.
Fixes #6022
=> Fix write unraisable followed by interpretter shutdown

Cython/Compiler/Code.py, Cython/Compiler/Naming.py, Cython/Compiler/Nodes.py, Cython/Runtime/refnanny.pyx, Cython/Utility/ModuleSetupCode.c
Add locking to refnanny.
Add mutex to guard the three exception state variables in a parallel block.
Untested.
"Fixes" https://github.com/cython/cython/issues/6198
=> Try to improve parallel in free-threading

Cython/Compiler/PyrexTypes.py, tests/errors/fused_types.pyx
=> [3.0.X] Fix crash when function contains fused extension type

Cython/Utility/MemoryView.pyx, tests/memoryview/memoryview.pyx, tests/memoryview/memslice.pyx
As outlined in #6227 — we have experienced an issue in production where attempting to write a folly:IOBuf with zero-length backing buffers is triggering a SIGSEGV.
The specific issue actual has to do with how `memoryview` attempts to use scalar assignment instead of slice assignment in the case where the source buffer (in this case, an empty slice) has `len == 0`. By fixing the fork to properly use slice assignment, we avoid the SIGSEGV when we string format the view format (which is NULL).
This PR also adds two additional tests for writing either a single byte or an empty slice to a `memoryview`.
Tested via: `python runtests.py memslice -vv` (which includes the two new tests)
fixes #6227
=> Fix segfault on zero-length slice assignment on memoryview

Cython/Compiler/AutoDocTransforms.py, tests/run/embedsignatures.pyx
PEP257 documents rules for stripping inline docstrings such that they may be formatted at the REPL using help.
Broadly, this is "strip whitespace from the first line, and dedent all subsequent lines by the minimum common whitespace prefix".
This allows writing a docstring as:
```python
def function(*args) -> result:
"""This is the first line.
Here is a long description.
"""
```
and having it rendered as:
```
This is the first line.
Here is a long description.
```
Similarly to if the docstring were:
```python
def function(*args) -> result:
"""
This is the first line.
Here is a long description.
"""
```
When compiling Cython files with embedsignature=True, the insertion of the function signature breaks the normal cleaning rules, since the raw docstring becomes:
```python
def function(*args) …
```
=> Pre-clean docstrings when running EmbedSignature transform

.github/workflows/ci.yml, runtests.py
They were almost all failing because `import imp` no longer works. To fix this I've backported 48325b43e2f3107e07723ef209ed1ce1528aa956
I'll also tried removing "allow_failure" on Python 3.12 to see what happens. I suspect this'll need to be reverted.
=> [0.29.x] Fix Python 3.12 tests

runtests.py
runtests.py catches distutils.errors.CompileError and prints the output to help in diagnosis of errors. Change this to catch CCompilerError (which is also the base class for LinkError, and a few other less likely options like PreProcessError and LibError).
I'm tempted to backport this to 3.0.x but don't feel strongly if there's any objections.
@hroncok - w.r.t. your mailing list post https://mail.python.org/pipermail/cython-devel/2024-June/005464.html.
=> Improve reporting distutils LinkErrors

Cython/Utility/ImportExport.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/TypeConversion.c
Fixes #6236. It was defined in the main ModuleSetupCode which meant it wasn't available in headers. Now it's no longer required to be defined.
Also noted that __Pyx_capsule_to_c_func_ptr ends up in _api.h files. Therefore gave it a version tag and an include guard so that it's not required to be perpetually compatible.
I'm a little worried that the _api.h headers aren't tested well enough and that we probably only use them from other Cython modules rather than from an isolated C program.
=> Fix use of __Pyx_TEST_large_func_pointers

Cython/Utility/ModuleSetupCode.c
It doesn't actually make a huge performance difference, but it already works with and without it, so no reason to stop users configuring it.
=> Make modulestate optional in limited API

Cython/Build/Inline.py
The difference is that locals is now a proxy object rather than a dict, and it has stricter rules for equality than dict does.
Fix for some of #6251
=> Fix cython_inline and locals on Python 3.13

Cython/Utility/Builtins.c
Revert one of the changes in fd9644342c0a7af885e103677e407173428162b9. This leads to the behaviour of hasattr being inconsistent between Python 3.13 and earlier versions since in 3.13 it propagates exceptions.
Part of #6251
=> [3.0.x] Revert changes to hasattr for Py3.13

Cython/Utility/ImportExport.c
`malloc` was generating warnings in some limited API builds because it wasn't included (so we'd need to have included in directly). Use `PyMem_Malloc` instead.
=> malloc -> PyMem_Malloc in MergeVTables

Tools/dataclass_test_data/test_dataclasses.py, tests/run/test_dataclasses.pyx
An exception changed.
Part of #6251
=> Fix test_dataclasses for Python 3.13

Cython/Utility/FunctionArguments.c
Fixes manually setting AVOID_BORROWED_REFS macro while using fastcall. Tested locally to the extent that Cython can build a working version of itself with these settings.
Mainly prepared for nogil Python, where avoiding borrowed references may generally be a good idea.
=> Fix CPython and AVOID_BORROWED_REFS

Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c, Cython/Utility/StringTools.c
Moves boilerplate code out of sight for users, more towards the end of the C file.
Refactors some of the code generation to use more f-strings and avoid repetition.
=> Move more generated init code after user code

Cython/Compiler/ExprNodes.py, tests/run/type_inference.pyx
This was broken due to changes to type inference. It infers the type as a double, but "py_operations" for binops need to have a Python result. Therefore I've separated into a two step:
* calculate Python result
* coerce to known C type.
In principle Optimize.c could take this back to 1 step. But at the moment it doesn't.
Fixes #6183
Fixes #6004
=> Fix PyInteger / float division

Cython/Compiler/Code.py
Previously, we called Py_VISIT() and Py_CLEAR() on them, which is wrong.
Probably needs backporting to 3.0.x.
=> Fix module cleanup for global memoryview slices.

Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, docs/src/userguide/source_files_and_compilation.rst
Based off https://github.com/cython/cython/pull/6276 since it needs the same fix.
=> Avoid traversing constants with Py_VISIT()

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Compiler/Nodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/MemoryView_C.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c
and separate the meaning of `__Pyx_PyNumber_Int/Long()`.
`__Pyx_PyNumber_Int()` is now the equivalent of `int()`.
`__Pyx_PyNumber_Long()` does not attempt conversion e.g. from strings but calls `.__int__()`. This used to be called `__Pyx_PyNumber_IntOrLong()`
This distinction might not be immediately obvious to everyone. Basically, the only use case of `__Pyx_PyNumber_Int()` is as a replacement for `int()`, whereas all "normal" coercions should use `__Pyx_PyNumber_Long()` to get a plain `PyLong` value from an arbitrary Python number.
=> Rename PyInt_* usages to PyLong_*

Cython/Utility/Builtins.c, tests/run/hasattr.py
For Cython 3.1. Change test to pure-py to demonstrate Python 3 behaviour.
=> Change hasattr to Python 3 behaviour

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c, tests/run/abitests.srctree
What I'm mainly worried building things that look like free-threaded modules with the wrong macros on Windows (since it's actually quite difficult to get it right at the moment).
I think a basic check here will safe us a lot of support questions later.
=> Add sanity check on import for ABI details

Cython/Compiler/Optimize.py, tests/run/cython3.pyx, tests/run/unicodemethods.pyx
If the type of a call to `str` has already been deduced as unicode (because of language_level=3), then keep that type.
This was causing optimizations to fail, where the optimization was made on the basis that the type was unicode and then that was reversed by the replacement of `str`.
Fixes #6166.
Most of this doesn't need to go into 3.1.
=> [3.0.x] Fix type of str call

Cython/Compiler/Options.py, Cython/Compiler/Parsing.py, docs/src/userguide/source_files_and_compilation.rst
Over in https://github.com/h5py/h5py/pull/2444 the GitHub actions logs get clogged with hundreds/thousands of:
```
warning: h5py/api_types_hdf5.pxd:710:2: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
```
The proper solution is to fix these. But in the meantime, it would be nice if I could:
1. Open a GitHub issue about it for `h5py` to keep track of it with milestones etc., and
2. Silence the warnings in the meantime so the build logs are more readable
This PR moves toward (2). Consider it a proposal-as-PR so feel free to close if it's not the way to go -- I wanted to see if it was doable *at all* and it turned out not to be too bad to get something …
=> Add option to silence IF deprecation warning

Cython/Compiler/ModuleNode.py, Cython/Compiler/Options.py, docs/src/userguide/source_files_and_compilation.rst, tests/run/freethreading_compatible.srctree
Closes #6239.
The reason this is still a draft is that the test should only run under the free-threaded build. Is that something we can do easily? I saw the mechanism that includes limited api tests, but that seems more complex.
=> Add freethreading_compatible directive to set Py_mod_gil slot

Cython/Utility/ModuleSetupCode.c, docs/src/userguide/source_files_and_compilation.rst, setup.py, tests/run/isolated_limited_api_tests.srctree
Essentially:
* Py_LIMITED_API is sufficient to enable Limited API mode on Cython too since
1. It isn't going to build without it.
2. Most build systems are geared to defining this, so let's make it easy for them!
* CYTHON_LIMITED_API exists are an undocumented intermediate mode which turns on Limited API code generation in Cython, but doesn't affect the Python headers.
=> Simply macros to enable Limited API mode

Cython/Utility/ExtensionTypes.c, Cython/Utility/ImportExport.c
We already had a workaround for old PyPy so just use that here too
=> Work around missing PyImport_GetModule in graalpython

Cython/Compiler/TypeSlots.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/ModuleSetupCode.c, docs/src/userguide/source_files_and_compilation.rst
It's a backport for versions that we no longer care about.
We're always able to define the async methods on classes. It should also be possible to look them up in the limited API (which was the only case where it wasn't defined).
=> Remove CYTHON_USE_ASYNC_SLOTS

docs/src/userguide/index.rst, docs/src/userguide/limited_api.rst, docs/src/userguide/source_files_and_compilation.rst
A more complete set of documentation for Limited API support. This hopefully covers the core benefits, limitations and how to use it.
=> Document Limited API support

Cython/Utility/Complex.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/StringTools.c
GraalPython maintains a patch against Cython at
https://github.com/oracle/graalpython/blob/f207af3b41b2beaa29e5698b045bd2b9c5146f20/graalpython/lib-graalpython/patches/Cython/Cython-3.0.10.patch
I've taken some of the easy fixes out of it (but not everything) and applied them here. They all look reasonable, but I've taken it on trust that these fixes are the right thing to do.
=> GraalPython fixes taken from their patch

Cython/Compiler/ExprNodes.py
This propery was a measurable issue on GraalPython (profiling says ~17% of the total runtime, although replacing it only gets 9% speedup). PyPy also looks slightly faster with the more straightforward Python code.
As far as I can tell, in CPython this operator.attrgetter ends up in an optimized C code path so is probably worthwhile. In most other implementations it ends up in a slightly slow Python code-path that also loops over a list of attributes.
Since this property is looked up in TreeVisitor._visitchildren it ends up quite significant to the performance.
=> Optimize child_attrs property on non-CPython

runtests.py, tests/run/freethreading_compatible.srctree
This adds a mechanism to be able to unset environment variables in end-to-end tests and unsets `PYTHON_GIL` in `freethreading_compatible`. Not sure if it's the best solution.
=> Unset PYTHON_GIL env variable in freethreading_compatible tests

.github/workflows/wheels.yml
This commit updates [cibuildwheel](https://github.com/pypa/cibuildwheel) to the latest version ([v2.20.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.20.0)) in the GitHub Actions `wheel.yml` CI workflow.
cibuildwheel 2.20.0 uses the ABI stable Python 3.13.0rc1 and build Python 3.13 wheels by default.
I think it would be really beneficial to automate these updates in some fashion, since they need to happen quite often and can be easily forgotten.
=> wheel CI: Update cibuildwheel to v2.20.0

Cython/Utility/ExtensionTypes.c
Instead of relying of PyObject_GenericSetAttr (which looks to have been updated in Python 3.14 to ban this usage) we instead work out where the type dict is from `__dictoffset__` and manipulate that.
Fixes #6323
=> More robust Limited API SetItemOnTypeDict

Cython/Utility/Optimize.c
I'm not sure we should use `CYTHON_COMPILING_IN_CPYTHON`, or just `!defined(Py_LIMITED_API)`
=> PyDict_Pop() is not part of the Python 3.13 limited API

Cython/Compiler/Code.py, Cython/Compiler/Scanning.py, Cython/Compiler/StringEncoding.py, Cython/Coverage.py, Cython/Utils.py
I don't think there's a reason to produce plain ASCII in comments, as long as the actual C code (including string literals) that we generate is ASCII.
=> Change C code encoding from Latin-1 to UTF-8

Cython/Build/Cache.py, Cython/Build/Inline.py, Cython/Build/IpythonMagic.py, Cython/Compiler/Code.py
SHA-1 is excluded by some Python installations due to being non-secure. SHA-256 is used as a replacement, which should be fine for years to come (for our strictly non-cryptographic needs).
I think all of these changes should be ok for Cython 3.1. Given the large changes in the C code in this release, no hash value would remain the same or at least relevant.
=> Remove usages of SHA-1

Cython/Compiler/Builtin.py, Cython/Compiler/Nodes.py, tests/run/cdef_subclass_builtin.pyx
1. Support subclasses of `complex`
```cython
cdef class Complex(complex): pass
```
2. Fix code generation for subclasses of `int` (generated C code used `PyIntObject` instead of `PyLongObject`)
```cython
cdef class Int(int): pass
```
=> Fixes for cdef subclasses of int/complex builtin types

Cython/Compiler/Code.py, tests/build/common_include_dir.srctree, tests/windows_bugs.txt
This assures identical code generation on Windows and Posix. C/C++ compilers should be ok with it also on Windows.
=> Use forward slashes in include file paths to the common include directory

Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, runtests.py, tests/build/run_cython_not_in_cwd.srctree
When cython is run on a file that is not in the current working directory it outputs filepaths that are either absolute or are basenames. It is not good to output absolute paths in the generated C code and outputing only basenames messes up coverage measurement.
Partial fix for gh-6186. In combination with https://github.com/flintlib/python-flint/pull/188 this makes it possible to measure coverage of Cython for for python-flint which uses meson as its build system.
The two places changed here were inconsistent. In ModuleNodes.py the code detects an absolute path and then outputs `basename(path)` instead. The path in question will usually not be absolute but it will be absolute if the source file being compiled is not in CWD and so in that case it is the basename that is emitted to the …
=> Output import-relative paths in generated C code.

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/Dataclass.py, Cython/Compiler/Tests/TestCode.py, Cython/Utility/TypeConversion.c
The `PyxCodeWriter` knows about code indentation, so we don't need to take care of the indentation in the code strings.
The first two changes in this PR are taken from https://github.com/cython/cython/pull/6358
=> Use PyxCodeWriter features in dataclasses

Cython/Utility/ObjectHandling.c
The first commit is the important one (including a fix for limited API), while the second are related optimizations.
=> Fix access to builtins dictionary with Py_LIMITED_API

Cython/Compiler/Nodes.py, tests/run/cdef_subclass_userdef.pyx
* Lookup complex type in current scope.
* Remove special handling for `c_long_type` as `long` is Python 2.
@scoder's objections https://github.com/cython/cython/commit/a2120861a9c3f87b246c9ade4bed68b84ce95dba#r145771848 to my changes in #6346 proved very accurate. Indeed, I trusted type analysis too much. As per Stefan's request, I'm PRing the fix.
The following type-analysis code doesn't not do the right thing. If the scope is a C context (which it is in a cdef class?), I believe it goes too quickly to check whether the name can be parsed as int/float/complex basic C type, rather than looking first in the scope to see if name is already user defined.
```python
class NameNode(AtomicExprNode):
...
def analyse_as_type(self, env):
type = None
if self.cython_attribute:
type = …
```
=> Fixes for cdef subclass of int/float/complex user defined types

runtests.py
One of the problems in #6370. cpp_locals specify a standard of c++17. This is applied first, and thus breaks c++20 tests because the C++ standard is never applied.
=> Allow update_cpp_extension to specifiy a higher standard

docs/src/userguide/source_files_and_compilation.rst
Closes https://github.com/cython/cython/issues/6340
This PR makes it easier to see the default values at a glance:
=> Adds default to Compiler directives docs

Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/Tests/TestBuiltin.py, tests/run/constant_folding.py, tests/run/fstring.pyx
I actually started off optimising constant builtin method calls here and ended up doing a lot of additional optimisations for f-strings. Especially the expression deduplication seems a very neat improvement, although there's a tiny risk of diverting from strict Python semantics. It's difficult to run into for users, though.
=> Optimise constant f-strings and constant builtin method calls

Cython/Compiler/FlowControl.py, tests/run/extra_walrus.py
Some expressions are partly conditionally evaluated, and so bits of them may be skipped. This has implications if they contain an assignment expression since the variable may not actually be assigned.
The tests for various comprehensions aren't actually needed since they already worked, but are added for completeness.
Fixes #6094
=> Fix missing flow control for assignment expression

Cython/Compiler/Nodes.py, tests/run/legacy_implicit_noexcept_build.srctree
The change in #6124 introduces a regression with functions that are
implicit noexcept in a pxd file.
Here we implement a different fix for #6122 that doesn't cause the regression.
See the discussion in https://github.com/cython/cython/pull/6124#issuecomment-2282955499
Fixes: #6335
=> Better fix for #6122 to avoid #6535

Cython/Compiler/ParseTreeTransforms.py
One of the issues from #6370.
Fixes erroneous generation of "(void)((*None));"
=> Fix cpp_locals code generation with unused expressions

Cython/Compiler/ExprNodes.py, tests/run/cpp_operators.pyx
It looks very difficult to handle correctly, so I'm not sure it's worth the complication. A clean error message is better than a compiler crash.
One part of #6370
=> Disallow cpp_locals and boolean binary operators

Cython/Compiler/ParseTreeTransforms.py, tests/compile/inplace_lhs_nested.pyx
Fixing what I determine must be a bug. When using "inplace assignment", Cython would emit code to acquire the GIL, although it shouldn't be necessary.
Given two extension types:
```Cython
cdef class A:
cdef int b
cdef class C:
cdef A _a
```
We can successfully bitwise-or onto the attribute `b` without GIL:
```Cython
cdef void set_a(A a) noexcept nogil:
a.b |= 1
```
But if we nest the structure, we now hit a problem, as this will take `c` as a PyObject and emit code to reference count (requiring GIL).
```Cython
cdef void set_b(C c) noexcept:
c._a.b |= 1
```
Although if we split up the bitwise-or and assignment, we can now perform the same operation without acquiring the GIL:
```Cython
cdef void set_c(C c) noexcept nogil:
c._a.b = c._a.b | 1
```
This PR attempts to fix this issue, and emit …
=> Fix inplace assignment on nested attributes without GIL

.github/workflows/nightly-wheels.yml
* [`scientific-python/upload-nightly-action` `0.6.x`](https://github.com/scientific-python/upload-nightly-action/releases/tag/0.6.1) adopts [`pixi`](https://pixi.sh/) as the environment and lock file management tool, which both makes maintenance easier and allows for the `scientific-python/upload-nightly-action` to support both Linux and macOS runners.
There is no change to the `scientific-python/upload-nightly-action` GitHub action API.
* This PR is being opened to keep all projects (known to be) using the action on the same minor version series.
=> CI: Bump scientific-python/upload-nightly-action from 0.5.0 to 0.6.1

Cython/Compiler/Code.py, tests/compile/profile_exttypereturn.pyx
The first argument of `__Pyx_TraceReturnValue` needs to be cast to `PyObject *` if the function returns an extension type.
=> Cast non-PyObject return values in __Pyx_TraceReturnValue invocations

Cython/Compiler/Code.py, Cython/Utility/ModuleSetupCode.c
The PyMutex functions were previously in a private pycore_lock.h header. Since Python 3.13.0b3, `PyMutex_Lock` and `PyMutex_Unlock` are now available when including `Python.h`.
Fixes #6391
=> Don't include pycore_lock.h

runtests.py
in runtests.py.
_default_directives are used for things like utility code, where they genuinely are expected to be fixed.  This isn't really the correct way of overriding compiler directives so we shouldn't do it in the tests.
Part of fixing #6370
=> Don't override Options._default_directives

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Utility/AsyncGen.c, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Printing.c
A lot of the things we currently store as static globals really belong in module state (at least if they are to work in multiple interpreters in future). Here this includes freelists, async types, and various cached objects.
Do this partly by adding a new utility code section that can be used to inject declarations into the module state.
Additionally make async freelists obey CYTHON_USE_FREELISTS (since they're not thread safe in freethreading).
(Probably isn't completely comprehensive yet)
=> Move some static globals to module state

BUILD.bazel
- Prefer rules from `rules_python` as the native Bazel rules are going to be removed soon (Bazel 8?)
- Rename a target as it caused problems on OSX but add an alias such that existing references (e.g. in `deps` attributes) continue to work
=> Improve Bazel support

Cython/Compiler/Nodes.py
This affects PyPy ~and Limited API~ I think.
References to the function default arguments were being incremented but never decremeneted in the case where the argument was actually provided. I suspect this mostly didn't matter, since arguments are usually just globals with an extended lifetime, but it's worth getting right.
For the more common case where we aren't avoiding borrowed refs, the ref counting becomes a no-op so it doesn't matter.
Needs backporting to 3.0.x (so I'd rather use `%` formatting than update to fstrings)
=> Fix refcounting of default arguments with CYTHON_AVOID_BORROWED_REFS

Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.py
So that they don't get lost based on being part of a larger change that may not be our proposed behaviour.
A couple of `is_target` set on the lhs of generated assignments that are generated too late to pick it up in analysis.
Skip `self.arg.generate_result_code` because it already gets called indirectly via `ExprNode.generate_evaluation_code` -> `ExprNode.generate_subexpr_evaluation_code`.
=> Pick a few small fixes out of #6226

Cython/Compiler/Nodes.py, tests/errors/w_noexcept.pxd, tests/errors/w_noexcept.pyx, tests/errors/w_noexcept_pure.pxd, tests/errors/w_noexcept_pure.py, tests/run/legacy_implicit_noexcept_build.srctree
This re-adds #6343, removes one line which seems to be the source of the spurious warnings, and add a bunch of tests to make sure we don't get the spurious warnings.
Goes into 3.0.x
Fixes https://github.com/cython/cython/issues/6428
=> Avoid spurious noexcept warnings

Cython/Utility/Optimize.c, tests/run/pyintop.pyx
int.from_bytes on Python 3.10 does not use the small int optimzation and produces a `size = 0` object that has no `digits` array allocated.
This can lead to Cython's and implementation dereferencing unallocated memory.  Fix this by moving this special case below the check for zero.
Fixes GH-6480.
=> Fix & on 0 produced by int.from_bytes on Python 3.10

Cython/Utility/Optimize.c, tests/run/pyintop.pyx
`int.from_bytes()` on Python 3.10 does not use the small int optimzation and produces a `size == 0` object that has no `digits` array allocated.
This can lead to Cython's "&" implementation dereferencing unallocated memory.  Fix this by moving this special case below the check for zero.
Fixes https://github.com/cython/cython/issues/6480
=> [3.0.x] Fix & on 0 produced by int.from_bytes on Python 3.10 (GH-6481)

Cython/Utility/ModuleSetupCode.c, tests/run/isolated_limited_api_tests.srctree
Turn off module state for the Limited API. My view is that we probably need to restrict some features quite heavily in future (e.g. cdef globals, "with gil"). I don't think these restrictions need apply to the limited API by default so I'd rather turn it off now.
However, it should still be a supported configuration, so make sure it's tested to an extent.
Additionally, enable multi-phase initialization in the Limited API and make sure that's tested too. (No change to the defaults yet).
=> Turn off module state for Limited API

Cython/Compiler/ModuleNode.py, Cython/Utility/MemoryView_C.c, Cython/Utility/ModuleSetupCode.c, Tools/ci-run.sh, docs/src/userguide/source_files_and_compilation.rst, test-requirements-313.txt, tests/run/subinterpreters.srctree, tests/run/subinterpreters_threading_stress_test.srctree
Essentially I've reimplemented the PyState_GetModule function to provide a base-line fallback which will work (at least while the GIL is held). Long-term I think we want to use the proper mechanisms for isolating modules to get the state from the class or the functions. However this achieves a base level of functionality.
I've used binary-search in a list of thread ids. This is probably needlessly inefficient (since practically the thread ids are low sequential integers). However it should at least be fairly general.
=> Get module-state working on multi-phase init

Cython/Utility/ImportExport.c
1. Put the ndarray object onto the module state rather than a static global. This would be necessary in a multi-interpreter environment.
2. On freethreading builds, access this via atomics (for read) and a lock (for write). This can be fairly simple because it's only written once.
Part of #6506 (but I don't think this is the major problem).
=> Make access fused access to ndarray thread safe

Cython/Compiler/FusedNode.py, tests/run/fused_def.pyx
The main issue was that it was possible for other threads to see _fused_sigindex in a partially initialized state.
Hopefully fixes #6506
I've added a stress-test. This fails (intermittently) without the fix and doesn't seem to fail with the fix. But I obviously doesn't prove all is good
=> Fix an issue with fused dispatch on freethreading

Cython/Compiler/ModuleNode.py
This was causing single-phase freethreading builds not to work correctly.
=> Move PyUnstable_Module_SetGIL out of "if MODULE_STATE"

BUILD.bazel, Tools/rules.bzl
- Format `rules.bzl`
- Use `cc_binary` instead of `cytonize.py` to compile generated CC code
- Use rules libraries instead of deprecated native ones
=> Improve Bazel `pyx_library()`

Cython/Compiler/Naming.py, Cython/Compiler/Nodes.py, Cython/Compiler/Options.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/PyrexTypes.py, Cython/Shadow.py, Cython/Utility/ModuleSetupCode.c, docs/src/userguide/freethreading.rst, docs/src/userguide/source_files_and_compilation.rst, tests/errors/critical_sections.pyx, tests/run/critical_sections.pyx
This just provides a nice interface for the freethreading Python's critical section feature, so that users can attempt to do their own locking.
Implementation is heavily based on `with gil`/`with nogil` blocks however I haven't attempted to directly share it via inheritance.
=> Implement cython.critical_section

tests/run/sequential_parallel.pyx
Note that these tests are disabled because the current behaviour doesn't work where more than one thread can be running with the GIL.
i.e. to fix them would require a change in our intended behaviour for parallel code rather than just a Cython code-generation fix.
(The intention here is to be able to turn off "allowed_failure" on the freethreading branches)
=> Disable some parallel tests in freethreading Python

Cython/Includes/cpython/weakref.pxd
Adding this since `PyWeakref_GetObject` has been deprecated since 3.13, `PyWeakref_GetRef` is the recommended replacement and we're already hitting thread safety issues (looks like [this one](https://github.com/pandas-dev/pandas/issues/59057#issuecomment-2474643730) is related to this) with using `PyWeakref_GetObject`, so it needs a replacement.
=> Add PyWeakref_GetRef to cpython.weakref

Cython/Compiler/Code.py, Cython/Utility/Profile.c, tests/run/sys_monitoring.py
The value might not be valid.
Also avoid the coercion for char* since the value might not be 0-terminated.
Closes https://github.com/cython/cython/issues/6503
=> When tracing C return values, allow the Python coercion to fail

tests/run/double_dealloc_T796.pyx
I think the issue is that freethreading garbage collection is often deferred, so `_ = gc.collect()` isn't sufficient to ensure that the next `gc.collect()` doesn't collect anything.
But it is possible I've misunderstood the test.
=> Change calculation of "unreachable" for double dealloc

.github/workflows/ci.yml
We expect (and intend) freethreading to keep working.
Similarly Limited API on Python 3.12 and 3.13 should be stable.
=> Remove unnecessary allow_failures

docs/conf.py, docs/src/userguide/source_files_and_compilation.rst
Built-in Sphinx RST roles: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-program
Explicit external refs: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#role-external
`pycon` code highlighting is for REPL sessions.
`console` is for terminal sessions (it differentiates lines starting with a prompt like `$` from the output)
Demo/preview: https://cython--6550.org.readthedocs.build/en/6550/src/userguide/source_files_and_compilation.html
=> Correct RST markup @  `source_files_and_compilation` doc

Cython/Utility/ObjectHandling.c, tests/limited_api_bugs.txt, tests/memoryview_tests.txt, tests/run/exectest.pyx
Enables a bunch more limited API run tests, silence one unused variable warning, fix one test.
=> Enable Limited API run tests (e-o)

Cython/Utility/CythonFunction.c, Cython/Utility/ObjectHandling.c, tests/limited_api_bugs.txt, tests/memoryview_tests.txt
Again, fixing very little - just disabling tests.
~One notable fix is `__module__` for cyfunction - this messes up pickling so seems fairly useful to get right.~ (Removed - it breaks other things)
=> Enable remaining Limited API run tests

Cython/Compiler/ModuleNode.py, Cython/Compiler/TypeSlots.py, Cython/Utility/ModuleSetupCode.c, tests/limited_api_bugs.txt
Also delete special-casing for sq_ass_slice since it just isn't used any more (since Python3 at least)
=> Make calling inherited slots work in the limited API

Cython/Debugger/libcython.py
I encountered this bug when [trying to debug Kivy](https://gist.github.com/clayote/6ba9692240e0471859aa212baf94d643). I'm not sure exactly why that line of C code didn't get indexed; that could be another bug. But in any case, the debugger should keep working.
=> Fix `IndexError` when stepping the debugger through unindexed C code

Cython/Runtime/refnanny.pyx
...since it's now publically available. This should be a lower-cost locking mechanism, and doesn't require initialization (beyond setting to 0 which happens anyway).
=> Switch refnanny to PyMutex on freethreading

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py
Hello wonderful people!
This PR resolves #6578.
This change allows CppIteratorNode to insert it's own 'for' statement that uses standard C for loop capabilities.
```
from libcpp.vector cimport vector
cpdef test():
cdef vector[int] v
for i in v:
print(i)
```
Before:
```
__pyx_t_1 = __pyx_v_v.begin();
/*              <- CppIteratorNode.generate_result_code (6, 13) */
for (;;) {
/*              -> NextNode.generate_result_code (6, 13) */
if (!(__pyx_t_1 != __pyx_v_v.end())) break;
__pyx_t_2 = *__pyx_t_1;
++__pyx_t_1;
/*              <- NextNode.generate_result_code (6, 13) */
__pyx_v_i = __pyx_t_2;
```
After:
```
__pyx_t_1 = __pyx_v_v.begin();
/*              <- CppIteratorNode.generate_result_code (6, 13) */
for (                    /*          -> CppIteratorNode.generate_for_loop_header …
```
=> Fix iteration over cpp input ranges

test-requirements-cpython.txt
(Dependencies of) Jupyter is failing to install on Windows Python 3.8. I don't think we need the full install anyway, so try this instead.
=> Test requirements jupyter->ipython

Cython/Utility/MemoryView.pyx, Cython/Utility/MemoryView_C.c, tests/compile/fused_redeclare_T3111.pyx
It's very difficult to make them thread-safe. Although practically almost everyone will be using the atomic path anyway.
=> Avoid globally allocated mview locks in freethreading

Cython/Utility/Coroutine.c, tests/run/generator_thread_safety.pyx
Mostly for free-threading build but somewhere applicable anyway.
Improve thread safety of generators. The main mechanism to enforce that was `is_running` so ensure that this is read and set pseudo-atomically. This mostly means moving it a little further out in the implementation (which is probably a good thing anyway).
Add some tests to try to stress-test the implementation at bit. They definitely fail without the changes.
=> Make generators thread safe

Cython/Utility/Exceptions.c
Normalizing the exception is the only thing that can fail, so if we don't need to normalize it then we don't need the error-handling code
=> Remove unused label

tests/run/subinterpreters.srctree, tests/run/subinterpreters_threading_stress_test.srctree
I was using the wrong test for freethreading Python, and so it was being skipped on all Py3.13+ versions (which wasn't the intent because it's also skipped on anything under Py3.13).
=> Re-enable subinterpreters tests

Cython/Utility/Optimize.c
By adding a critical section. Also replace a PyList_GET_ITEM.
All the other uses of PyDict_Next look to be handling function arguments (when they should have their own copy of the dict) and thus don't need changing.
=> Add thread safety around PyDict_Next

Cython/Utility/Builtins.c, Cython/Utility/CythonFunction.c, Cython/Utility/Exceptions.c, Cython/Utility/ImportExport.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c
A bunch of small thread-safety changes related to PyDict_GetItem and similar avoiding borrowed references.
=> Dict_GetItem thread safety

Cython/Includes/libcpp/vector.pxd, tests/run/cpp_stl_vector.pyx, tests/run/cpp_stl_vector_cpp11.pyx
In particular, add C++11 declarations, more const-correctness.
I have added a new file for testing C++11 methods, I think this can be later used to add more tests for container methods and algorithms, which have been added with C++11 and were not tested before, because otherwise these tests will fail on compilers where the default mode is still not C++11.
=> ENH: Restructure libcpp.vector and cover API with tests

Cython/Compiler/ExprNodes.py, Cython/Compiler/Options.py, Cython/Compiler/ParseTreeTransforms.py, docs/src/userguide/freethreading.rst, tests/errors/critical_sections.pyx, tests/run/critical_sections.pyx
Allows critical_section to be applied as a function decorator, to put the entire function body in a with critical_section block (using the first argument as the lock).
This is just a useful bit of syntax (I hope) - it doesn't do anything that you can't already do with the with statement.
It's inspired by a somewhat similar feature in Python's argument clinic (see e.g. https://github.com/python/cpython/blob/3f6a618e49b1c8c12a7bc0c26e846735e108dc97/Modules/_queuemodule.c#L284) which seems like a useful tool there so I thought I'd copy it.
=> Add critical_section decorator

tests/run/isolated_limited_api_tests.srctree, tests/run/sequential_parallel.pyx
The existing one excluded any Py3.13+ build while this is the one that's documented.
=> Update freethreading check in tests

Cython/Includes/libcpp/vector.pxd, tests/run/cpp_stl_cpp11.pyx, tests/run/cpp_stl_vector.pyx, tests/run/cpp_stl_vector_cpp11.pyx
This is a follow-up to #489:
This time, I split it in two commits - one that does purely reordering and labeling, and the second one with follow-up changes.
To check the first commit, I have sorted master-version of `vector.pxd` and my version of `vector.pxd`, while removing the comments and indentation. The following diff comes out:
```diff
libcpp % diff -Naur vector-orig.pxd vector-new.pxd
--- vector-orig.pxd     2025-01-24 17:12:28.927578349 +0100
+++ vector-new.pxd      2025-01-24 17:15:15.482622670 +0100
@@ -102,7 +102,7 @@
difference_type operator-(iterator)
difference_type operator-(iterator)
iterator begin()
-iterator emplace(const_iterator, ...) except +
+iterator emplace(const_iterator, ...) except + # C++11
iterator end()
iterator erase(iterator) except +
iterator …
```
=> Libcpp vector reordering

Cython/Utility/arrayarray.h
Change the helper union for arrayarray so that users who don't use as_pyunicodes don't get a deprecation warning. However, add our own deprecation warning for anyone that does use it.
Fixes #6607
=> Avoid Py_UNICODE deprecation warning for arrayarray

Cython/Includes/libcpp/string.pxd, tests/run/cpp_stl_string.pyx
I did my best to fully sync `libcpp.string` with the standard and cover all overloads with meaningful tests. The only missing bits are the search functions. The highlight of this version is the introduction of iterators and corresponding overloads (note some of the hack comments I left). If anything, this is an excellent stress test for Cython overload resolution engine :-)
=> ENH: Rewrite & cover with tests libcpp.string declarations

Cython/Utility/Builtins.c, Cython/Utility/Dataclasses.c, Cython/Utility/Exceptions.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c, Cython/Utility/StringTools.c
* Replace use of alfa/beta+level markers with 00
* Consistently use uppercase hexadecimal digits
Fixes #6629
=> Fix LIMITED_VERSION version checks

Cython/Includes/libcpp/string.pxd, tests/run/cpp_stl_string.pyx
This is a follow-up to #488.
The first commit is the reordering according to the C++20 standard draft. When comments are removed and lines are sorted, these are semantic changes:
```diff
libcpp % diff -Naur string-orig.pxd string-new.pxd
--- string-orig.pxd	2025-01-25 14:18:57.670755478 +0100
+++ string-new.pxd	2025-01-25 14:26:23.365514610 +0100
@@ -135,11 +135,12 @@
int stoi(const string& s, size_t* idx, int base) except +
iterator begin()
iterator end()
-iterator erase(const_iterator first, const_iterator last)
-iterator erase(const_iterator p)
-iterator erase(iterator first, iterator last)
-iterator erase(iterator p)
+iterator erase(const_iterator first, const_iterator last) except +
+iterator erase(const_iterator p) except +
+iterator erase(iterator first, iterator last) except + …
```
=> Libcpp string reordering

tests/run/defnode_err_val.pyx
Similar to #6592. The error message on PyPy3.11 does not include the module name, which I don't think is an error but an implementation detail.
=> loosen errmsg regex for PyPy

Cython/Compiler/FlowControl.py, tests/run/sequential_parallel.pyx
So that it behaves like a regular for-loop does (rather than always being inferred to object). Just because the absence of this feature is a bit of a pain for prange.
=> Add type-inference to prange target

Cython/Compiler/Nodes.py
Since PyCriticalSection_End with never generate exceptions we can save the effort of getting and restoring the exception state while we call it.
=> Improve code-gen for critical_section error path

tests/limited_api_bugs.txt, tests/limited_api_bugs_38.txt, tests/run/importfrom.pyx
Mainly just version-specific ones that fail on Python 3.8.
=> Enable a few more Limited API tests

runtests.py, tests/limited_api_bugs.txt, tests/memoryview_tests.txt, tests/run/abitests.srctree, tests/run/freethreading_compatible.srctree, tests/run/isolated_limited_api_tests.srctree, tests/run/reimport_from_subinterpreter.srctree, tests/run/subinterpreters.srctree, tests/run/subinterpreters_threading_stress_test.srctree
by passing the cflags into the environment.
I'm expecting to have to turn this off for some tests (e.g. the isolated limited api ones, where it's being explicitly controlled in the test) and to have to disable some other tests where it'll fail.
=> Enable Limited API in srctree tests

setup.py
Provide a mechanism where users can force it to if they want, but turn it off by default.
---------------------------
As discussed in the comments of #6653, I think this is something that shouldn't be enabled for most people. I don't want to stop anyone who wants to, but making it off by default will stop pip doing it by mistake.
=> Stop Cython compiling itself in freethreaded builds

tests/build/common_include_dir.srctree
For anything but fork, multiprocessing need the main script to be wrapped in `if __name__ == "__main__":`
Supercedes #6668 (assuming to works universally)
=> Better fix for common_include_dir

tests/run/subinterpreters.srctree
The low-level _interpreters module has a slightly different interface - it doesn't have the nice "Interpreter" object but just returns an integer ID
=> Fix subinterpreters test in 3.14

docs/src/quickstart/build.rst
Currently, the user lands at a redirection page:
I replaced the URL with the tutorial shown on the right (which is a subdomain of the general guide shown on the left)
=> Fix outdated URL for packaging tutorial

Cython/Compiler/Buffer.py, Cython/Utility/Buffer.c, Cython/Utility/MemoryView.pyx, Cython/Utility/MemoryView_C.c
They aren't modified, so const will hopefully help the compiler out a little (and prevent them from being modified in future)
=> Define buffer typeinfo structs as const

Cython/Compiler/Symtab.py, tests/run/static_method_inheritance.pyx
#3235 subtly changed the behavior of `declare` to return a reference to an already declared `Entry` in the case of overriding a parent method. 
This caused `cfunc_entries` to have two entries pointing to the same `Entry` object, whereas `cfunc_entries` is expected to have two different `Entry` objects, one for the parent method that is being inherited, and one of the new override from the child class.
This PR fixes this bug by copying `Entry` instead of returning a reference. 
Closes https://github.com/cython/cython/issues/6704
=> Fix incorrect code generation for method override

Cython/Utility/MemoryView.pyx
It's generating a compiler warning and an unnecessary cast in Cython code.
=> Add a missing "const" in memoryview code

Cython/Compiler/Nodes.py, Cython/Utility/Profile.c
The Python implementation doesn't look like it attempts any thread safety. The Cython implementation doesn't currently. This feels like a corner-case where it isn't worth the complication to make it work right, but is worth disabling so that people doing try to use it.
=> Disable monitoring in parallel/prange

Cython/Utility/ObjectHandling.c
=> Avoid clang uninitialized member warn in unbound methods

Cython/Utility/ModuleSetupCode.c
In principle this is an existing bug and might be worth backporting to 3.0.x. In practice freethreading is the only place it's likely to really happen.
=> Fix reference counting issue in code object cache

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c
Originally reported here: https://gitlab.com/petsc/petsc/-/merge_requests/8104
I was able to get rid of almost all of these warnings, however there are two that I have not yet figured out:
```console
src/mpi4py/MPI.c:283486:19: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
283486 |   {Py_mod_create, (void*)__pyx_pymod_create},
|                   ^
src/mpi4py/MPI.c:283487:17: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
283487 |   {Py_mod_exec, (void*)__pyx_pymod_exec_MPI},
```
=> Silence GCC -Wpedantic in C function pointer casts

Cython/Utility/Coroutine.c
Turns out that CPython<3.14 doesn't benefit from `__Pyx_PyObject_CallOneArg()` for exceptions because `BaseException` does not implement vectorcall yet.
See https://github.com/cython/cython/issues/6710
=> Avoid a performance panelty in CPython 3.12/13 when creating a StopIteration

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, tests/errors/tree_assert.pyx, tests/run/all.pyx, tests/run/any.pyx, tests/run/builtin_sorted.pyx, tests/run/isinstance.pyx
Recent CPython versions added vectorcall support for `type` and builtin types, allowing faster object creation and calls to `__init__` etc.
See https://github.com/cython/cython/issues/6710
=> Use vectorcall when calling known builtin/ext types

Cython/Includes/numpy/math.pxd
Closes https://github.com/cython/cython/issues/6449
Supersedes and closes https://github.com/cython/cython/pull/5967
=> Deprecate "numpy.math"

Cython/Compiler/Symtab.py, tests/run/cclass_attr.pyx
"visibility" in this case means "visibility to Python". It's where the class comes from that matters to whether we mangle the name.
It's slightly debatable what we should be doing for api or public classes, but it's probably reasonable to treat them as the user's responsibility to get them right.
Fixes #6678
=> Fix logic for c_safe_identifier to extension types

Cython/Shadow.py
to let it be used as either a decorator or context manager.
I don't think the existing generic version works because the usages are:
```
@critical_section
def method(self, ...)
```
or
```
with critical_section(o1, [o2]):
...
```
which isn't the normal combination of arguments.
=> Update definition of critical_section in Shadow

Cython/Utility/CommonStructures.c
If two Cython modules are being imported simultaneously there's a possible race. This ensures that the type that's set up first is always used.
=> Fix a possible race when setting up the common types

Cython/Utility/TypeConversion.c
We're using it like a function (i.e. casting to void to mark it unused) so it has to be a function.
Fixes #6781
=> Fix __Pyx_Owned_Py_None

Cython/Compiler/Code.py
The issue is that if a requirement has `{{py: ...}}` tempita code, it can modify the context meaning different substitutions are made.
This was an issue in https://github.com/cython/cython/pull/6774 (but I think it's worth taking independently of that since it was awkward to debug)
=> Fix utility code passing context to requirements

Cython/Compiler/ExprNodes.py
I think the intent of the guard was mainly disable to optimization on things like PyPy which aren't natively refcounted. I don't see why it'd be unreliable on the Limited API.
=> Enable no-copy optimization on Limited API

Cython/Build/IpythonMagic.py
closes #6502.
technically the expression isn't valid Python, but it should be understandable enough.
=> Fix documentation to mention get_ipython_cache_dir() instead of IPYTHONDIR for %%cython cell cache location

Cython/Compiler/Code.py
Fixes #6800
It was generating the C code
```c
__Pyx_RaiseUnboundLocalError("进程对象");
```
Essentially you don't see the error any more in 3.1 because of 3eb16fd8229ddf89396405e2b571435fb2e2ddec. However I think it's a bit compiler-dependent whether that's actually acceptable in a source file. So it's probably better to encode the string if we can.
=> Fix UnboundLocalError with non-ascii names

Cython/Utility/ExtensionTypes.c
The reason I'm worried about this is that I don't think it's possible to turn the GC on and off in a thread-safe manner. This PR doesn't fix that problem, however if does avoid having to interact with the GC in most cases so it makes it less likely that we'll hit any issues.
(I have what may be a better fix in progress, but I thought I'd pick the simple part of this out since it can stand alone, while the better fix may need more thought)
=> Simplify __Pyx_PyType_Ready for single inheritance case

Cython/Utility/Coroutine.c
1. Potential race initializing it.
2. We can't usefully return a globals dictionary because the coroutine module is shared, and thus we don't actually know which module it comes from.
(picked out of a larger change in the interests of keeping that simple(r))
=> Fix a couple of issues with __Pyx_Coroutine_get_frame

docs/src/userguide/freethreading.rst
I'm glad to see the 3.1 release shaping up.
=> fix typo in free-threading guide

.readthedocs.yaml
=> docs: Use pip for readthedocs build to fix setuptools failure.

Cython/Compiler/PyrexTypes.py, tests/run/unicode_identifiers.pxd, tests/run/unicode_identifiers.pyx
Unicode characters got into the function argument name, but inside the function the variable was properly escaped.
=> Fix issue with unicode cpdef args

Cython/Compiler/Code.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/CppSupport.cpp, Cython/Utility/ModuleSetupCode.c, tests/run/cpp_classes.pyx
This way uses templates to work out what constructor to call so we don't need to care about the name.
Fixes #6821
=> Fix placement new of c++ class typedefs

.github/workflows/ci.yml
There's definitely differences in what headers they include (for example) so I think we should be checking this too.
=> Add freethreaded dev version of Python to the CI

Cython/Compiler/PyrexTypes.py
It's assigned to in what should be a read-only predicate. But fortunately it's never read so no real harm done.
=> Remove unused original_sig attribute

Cython/Compiler/Builtin.py, Cython/Compiler/PyrexTypes.py, tests/run/builtin_exceptions.py
Exceptions are special because a) a declaration like "exc: Exception" usually means that a subtype rather than a bare "Exception" instance will be assigned, and b) there is not much we can do to optimise their access, and what we could do (attribute access) would also work for subtypes. Thus, allowing subtypes seems safe.
Closes https://github.com/cython/cython/issues/6828
=> Let variables declared with builtin exception types accept any subtype

Cython/Includes/libc/threads.pxd, Cython/Includes/libcpp/barrier.pxd, Cython/Includes/libcpp/latch.pxd, Cython/Includes/libcpp/mutex.pxd, Cython/Includes/libcpp/semaphore.pxd, Cython/Includes/libcpp/shared_mutex.pxd, tests/run/cpp_mutex.pyx, tests/run/libc_threads.pyx
The called functions really should be "nogil" so enforce that before people start using it.
(Cherry-picked bug fixes from https://github.com/cython/cython/pull/6829)
=> Some small bugfixes to call_once

docs/src/userguide/limited_api.rst, docs/src/userguide/source_files_and_compilation.rst
I believe it should work reasonably well in Cython 3.1 and most of it is even tested, so let's not discourage people unnecessarily.
=> [Docs] Stop describing Limited API as experimental

Cython/Compiler/ExprNodes.py
This looks wrong to me - `PyList_Append` doesn't steal a reference. I haven't yet tested it against the complete test suite though so maybe I've missed something
=> Refcounting error in class cells

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Utility/ObjectHandling.c, tests/run/cpp_locals_directive.pyx
We need to reacquire the GIL in this case (which we mostly didn't do before because it was just dealing with Python objects which always had the GIL)
Fixes #6834
Should probably wait until after 3.1 - it's a fairly niche issue (and not a regression)
=> Fix handling of cpp_locals exception in nogil

Cython/Build/Dependencies.py, Cython/Build/SharedModule.py, docs/src/userguide/source_files_and_compilation.rst, tests/memoryview/memoryview_shared_utility.srctree
This avoids a two-step build where users have to generate the shared module C file before running `setup.py` or `pip wheel`, which might actually not be feasible in practice.
=> Automate the shared utility module generation from a setuptools build

Tools/ci-run.sh
It requires cryptography which isn't yet available.
=> Skip twine check on freethreading Python.

Cython/Compiler/ExprNodes.py, tests/errors/e_typing_errors.pyx
We used to analyse the item type as C type instead of requiring a Python type here.
Fixes https://github.com/cython/cython/issues/6856
=> Allow "list[int | None]()" etc.

Cython/Utility/ImportExport.c
`PyErr_WarnFormat` uses `PyUnicode_FromFormat()` to format the warning message, which is more portable than `PyOS_snprintf`, since the latter depends on compiler support for format specifiers. Specifically, MinGW-w64 emits the following warnings when using `%zd` on Windows:
```
warning: unknown conversion type character 'z' in format [-Wformat=]
|             "Expected %zd from C header, got %zd from PyObject",
|                        ^
warning: unknown conversion type character 'z' in format [-Wformat=]
|             "Expected %zd from C header, got %zd from PyObject",
|                                               ^
warning: too many arguments for format [-Wformat-extra-args]
|             "%s.%s size changed, may indicate binary incompatibility. "
| …
```
=> Use PyErr_WarnFormat to avoid %zd format warning

Cython/Compiler/ExprNodes.py, tests/run/cpp_stl_vector.pyx
They are always passed by value and need to be assignable.
Closes https://github.com/cython/cython/issues/6864
=> Prevent ctuples from being 'const'

Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, tests/errors/charptr_from_temp.pyx, tests/run/if_else_expr.pyx
The spanning type is not necessarily the correct result type when mixing numeric types in conditional expressions. This specifically shows when one is a Python object type that could coerce to the C numeric type of the other side (but shouldn't).
While fixing this, I noticed that we accidentally set `bint` as an `equivalent_type` on `object` that was intended for `bool`. `bool` really shouldn't be that special…
Fixes https://github.com/cython/cython/issues/6854
=> Fix result type analysis when mixing numeric C and Python types in conditional expressions

Cython/Compiler/FusedNode.py, tests/run/fused_def.pyx
Fixes #6855
Just restores the old behaviour whether they have a code object based on their first overload.
=> Restore signatures of fused functions

Cython/Utility/ObjectHandling.c, Tools/ci-run.sh
- Downgrade the cryptography (twine) dependency to 41.x which still has binary wheels for it.
- Downgrade nh3 to 0.2.18 which uses PyO3  0.22 (0.23.0 dropped PyPy3.8 support).
=> CI: Fix PyPy3.8 build

Cython/Compiler/ModuleNode.py
Very minor race but probably still worth fixing.
In principle I wonder if we should just use `PyObject_GenericGetDict` though. Or maybe `Py_TPFLAGS_MANAGED_DICT` where possible (although that's a larger change probably)
=> Fix race in dict getter

Cython/Utility/ObjectHandling.c, tests/run/builtin_callable.pyx
=> Use PyCallable_Check() instead of type slots for callable() in PyPy

Cython/Utility/ModuleSetupCode.c
This header was only added in C++11, and not all compilers make it available when compiling for older C++ standard versions.
The call to `std::is_trivially_default_constructible` is appropriately guarded below, but the include was not.
=> Only `#include <type_traits>` for C++11

tests/run/ufunc.pyx
np.intc is designed to exactly match up with a C int so this seems like the easiest way to define the tests with a known C type and have it work.
Arrays do print with a `dtype=` at the end though, so ignore that in the doctest output.
=> Fix ufunc tests on Numpy2 on Windows

runtests.py
instead of multiprocessing.Pool.
The main advantage of this is that it can apparently detect segmentation faults (https://stackoverflow.com/questions/24370930/multiprocessing-pool-hangs-if-child-causes-a-segmentation-fault) so it won't hang forever if one of the processes crash.
It should be available on all Python versions we care about.
=> runtests use concurrent.futures.ProcessPoolExecutor

Cython/Compiler/ExprNodes.py
Previously, we always used a managed temp even on constants (like builtins), which is useless overhead.
=> When not unpacking methods on call, avoid putting 'self' into a temp if it's already immutable

Cython/Compiler/AutoDocTransforms.py, tests/run/embedsignatures.pyx, tests/run/embedsignatures_python.pyx
Fixes https://github.com/cython/cython/issues/6904
=> Always add two blank lines after embedded signatures

test-requirements-312.txt, test-requirements.txt
This was added in a799b1b8c6d584f1a8df1853abdad047b69d3aca but per that commit:
> Once NumPy releases 2.0.0rc1, these pins should be reverted.
numpy 2.0.0 was released nearly a year ago, so drop it.
=> CI: drop numpy<2 pin

Cython/Compiler/Builtin.py, tests/run/annotation_typing.pyx, tests/run/cpp_bool.pyx
For all other Python builtin types the cname evaluates to a PyTypeObject*
Fixes #6902
It's still a little inconsistent in when it evaluates bool as a type-checked argument. But at least it compiles.
=> Fix C type of PyBool_Type

runtests.py
I don't propose using this on the CI (there's just too many combinations to test) but I think it's a useful thing to be able to do locally.
=> Add an option to runtests to run with a specific Limited API version

runtests.py
Only makes sense for Limited API (it can be enabled on other modes but wouldn't be expected to pass).
I'm just adding it as an option and not enabling it on the CI because there's a few false positives that I know of.
=> Add optional abi3audit checks to runtests

Cython/Utility/Overflow.c
It isn't available in the Limited API without an extra include (just because the Limited API includes slightly different headers than the full API).
Using `Py_FatalError` seems the most descriptive way of fixing it.
=> Remove use of C abort function

Cython/Compiler/ExprNodes.py
It's possible that we might want to generalize this rule, rather than leave it as a very specific special-case. However: `range` is going to be a very common function to be looping over and we know the result isn't a tuple or list. So let's not tell that compiler that it is.
=> Avoid pessimizing sequence checks on 'range'

Cython/Compiler/ExprNodes.py, tests/run/isinstance.pyx, tests/run/type_inference.pyx
`type | type` does not give `type` (it gives a subclass of `type`). This was giving an over-optimization, and causing `instance` to fail.
Fixes https://github.com/cython/cython/issues/6420
=> Fix type inference of type bitwise or

Cython/Compiler/Builtin.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/FlowControl.py, Cython/Compiler/Scanning.py, Cython/Compiler/Symtab.py, Cython/Compiler/TypeInference.py, tests/run/builtin_functions.pyx, tests/run/builtin_ord.pyx, tests/run/builtin_range.pyx, tests/run/for_in_range_T372.pyx, tests/run/type_inference.pyx
Add functions: `ascii`, `bin`, `format`, `hex`, `oct`
Add type: `range`
Looks like PyPy doesn't currently define `PyFilter_Type` and `PyZip_Type`, unlike CPython, but it defines `PyRange_Type`.
=> Update list of builtin functions and types

Cython/Utility/CythonFunction.c, tests/run/cyfunction.pyx, tests/run/numpy_test.pyx
Fixes #6897
Cherry-picked out of #6882 because I probably should have treated it as a separate issue.
I'd quite like to get this fix merged sooner rather than later because it's invisibly disabling most of the tests fused functions and I don't want to have to fix too many regressions there.
=> [3.1.x] Fix fused module attribute

Cython/Runtime/refnanny.pyx
We have actually made the effort to make this work right, so let's say so.
This is mostly so that any users who are using refnanny to audit their own code aren't thrown back to single-threaded mode just on account of refnanny.
=> Explicitly mark refnanny as freethreading_compatible

Cython/Compiler/ModuleNode.py, Cython/Utility/CommonStructures.c
Initialization was happening after cyfunction (and the other shared types) were already initialized.
=> Fixup shared metaclass in 3.1.x

Cython/Compiler/ExprNodes.py, Cython/Utility/StringTools.c
This adds a critical section around `wraparound` or `boundcheck` bytearray indexing on freethreaded builds. This ensures the boundscheck is accurate and that the size doesn't change between the check and the indexing. A critical section is what Python does internally.
It's slightly debatable whether the lock should be applied with wraparound alone. Python itself calculates the wrapped index without a critical section, but then always does the boundscheck making it safe. I've chosen to lock but could see the argument either way.
Another question is what to do when we don't have the GIL. I've chosen to reacquire it (which should be relatively cheap on freethreaded builds because it's uncontended) but I think skipping the lock would also be defensible here. If I was starting from scratch I …
=> Thread-safe bytearray indexing

Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c
(where possible).
I'm working on the basis that the MANAGED versions will be the mildly optimized path in future (although I suspect it doesn't make a whole lot of difference right now).
(I'm marking this as draft for the moment; the PR should be "done" but should probably wait until we branch off for 3.2)
=> Use MANAGED dict and weakref in utility code types

Cython/CodeWriter.py, Cython/Compiler/AutoDocTransforms.py, tests/run/embedsignatures.pyx, tests/run/embedsignatures_clinic.pyx, tests/run/embedsignatures_python.pyx
Fixes https://github.com/cython/cython/issues/6880
My view is that it's fine if there's unserializable stuff in a signature and we should ignore it rather than fail with an assertion.
=> "Fix" lambdas in embedsignatures

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Utility/ModuleSetupCode.c
It is now much more efficient to store them together with the other compressed Python bytes object contents, than to store them as plain const C strings and constructing the bytes objects at import time anyway.
=> Compress the function line tables as Python bytes objects

Cython/Compiler/Builtin.py
This was already tested in `tests/run/bytesmethods.pyx`, but there were apparently (non-trivial?) cases where the return type wasn't correctly inferred.
=> Fix return type of bytes.join()

Cython/Utility/Builtins.c
Use PYIDENT (since it's in the stringtab we may as well use it).
Fix Limited API version check.
Use simpler calling protocol.
This was in but didn't make it into https://github.com/cython/cython/commit/1d72e6ca1b6c3ab915d80d408b65c90bfea2341f. A microbenchmarks suggests it's about 3 times faster.
=> Further optimize Limited API setdefault slightly

Cython/Utility/CommonStructures.c
In this case, most of the shared types use the contents of the module state and so the lifetime is potentially important.
=> Keep defining module alive with CYTHON_USE_MODULE_STATE

Cython/Compiler/FlowControl.py, Cython/Compiler/Nodes.py, tests/run/sequential_parallel.pyx
Fix type inference on prange target when the type of the arguments to prange needs infering themselves.
Fixes #6974
=> Fix two-step prange type inference

Cython/Utility/ObjectHandling.c, Cython/Utility/StringTools.c
=> Mark "unsafe_shared" as maybe unused

tests/run/api_includes.srctree
Since they seems to be basically untested
---------------------------------------------
Picked out of #7001 since it doesn't require it. It's a very basic test, but as far as I can tell this feature isn't tested at all right now.
=> Add some tests for api headers

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, Cython/Compiler/Optimize.py
We often need simple constants like 0 or 1, but creating an `IntNode` literal for them in a uniform and correct way is not trivial.
=> Simplify constant "IntNode" creation with class method factories

Cython/Compiler/StringEncoding.py
Fixes #6982
I can find conflicting sources on whether it's printable or not, but it doesn't look great in my editor and it doesn't appear in the C language standard of what's allowed to appear in a character constant (https://en.cppreference.com/w/c/language/charset.html).
I don't think it's causing problems with real compilers but equally I don't think it hurts to escape it instead.
=> Don't put the DEL character in character strings

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Utility/StringTools.c, tests/run/bytes_indexing.pyx
This used to be special because bytes indexing returned a bytes string (not an int) in Python 2.x, but that's long gone now.
Closes https://github.com/cython/cython/issues/6997
=> Integrate bytes indexing into the existing infrastructure

Tools/ci-run.sh, runtests.py, test-requirements-312.txt, test-requirements-cpython.txt, test-requirements.txt
The main point is to update line-profiler to allow the new version which should support Cython again.
Also tried to rationalize the requirements a little. test-requirements-312 seemed the same as test-requirements so I wasn't sure why we were diverging there for example.
=> Try to simplify requirements, update line_profiler

Tools/ci-run.sh, runtests.py, test-requirements-312.txt, test-requirements-cpython.txt, test-requirements.txt
The main point is to update line-profiler to allow the new version which should support Cython again.
Also tried to rationalize the requirements a little. test-requirements-312 seemed the same as test-requirements so I wasn't sure why we were diverging there for example.
=> [3.1.x] Try to simplify requirements, update line_profiler (#7036)

Cython/Plex/Regexps.py
It no longer exists in Python 3 so it fails. You only see the failure of course if you manage to misuse plex, so it isn't a "real" bug
=> Remove Py2 InstanceType from Plex

Cython/Utility/Optimize.c
... since I think that's what it really means.  It should hopefully make things better for Graal too for example.
=> Change a COMPILING_IN_PYPY to AVOID_BORROWED_REFS

Cython/Compiler/ExprNodes.py, tests/run/extra_walrus.py
Fixes 2 issues:
1. `int` literals being coerced to Python objects got the integer passed instead of a Python pointer.
2. It failed to use cached Python integer constants (because coercion nodes got in the way).
=> Fix code-generation with walrus+literals

Cython/Compiler/FusedNode.py, Cython/Utility/FusedFunction.pyx
- Reduces the module size when many fused functions are used.
- Makes the utility functions candidates for the shared module.
- Simplifies optimisations like specialised matchers for 1 or 2 argument functions.
=> Extract common code from the fused functions dispatch into utility functions

Cython/Compiler/Annotate.py
This change makes it slightly more readable to see which lines have been expanded.
=> HTML annotation UI: toggle +/- symbols for expand/collapse state

tests/run/test_fstring.pyx
Previously it had been running in Python so wasn't confirming that Cython raised an error
=> Enable one more fstring error test

Cython/Utility/Profile.c, tests/run/sys_monitoring.py
Fixes #7050
Happens with a function with monitoring/tracing is used within a sys.monitoring handler.  In this case, the reference counting of `__code__` is inconsistent.
=> Fix a crash in sys.monitoring

Cython/Compiler/ExprNodes.py, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/StringTools.c, tests/run/freethreaded_list_indexing.pyx
1. Function arguments are different - they're owned by someone else and we (mostly) can't trust what they're doing with it.
2. `Py_REFCNT == 1` apparently isn't thread-safe
3. `PyUnstable_Object_IsUniquelyReferenced` has an implicit assumption that you own a strong reference to the object and that's what our different modes evaluate.
=> Improve "unique reference" checking

Cython/Compiler/ExprNodes.py, Cython/Compiler/Parsing.py, Cython/Utility/ImportExport.c, tests/errors/nogil.pyx
Avoid creating a Python list in cases where it isn't needed for the "from_list" part of the import code.
Follow up to #7035
=> Replace list with array in import code

Cython/Utility/CommonStructures.c
The bases tuple wasn't being decrefed. But actually, we don't need the bases tuple and it can just be set statically.
=> Fix refcounting error on metaclass base tuple

Cython/Shadow.pyi
- Add ufunc to the decorator assignment in Shadow.pyi
- Fixes mypy error: Module has no attribute 'ufunc'
- Resolves issue where @cython.ufunc was not recognized by type checkers https://github.com/cython/cython/issues/7109
=> Add missing ufunc decorator to type annotations

Cython/Utility/ModuleSetupCode.c
... because it's no longer true and refers to the previous implementation.
=> Update comment in __Pyx__PyCode_New

docs/src/userguide/limited_api.rst
For the examples, I've change them to 3.10 just as a consistent illustrative example that we probably won't have to update too soon.
Closes #7147
=> Correct the Limited API documentation supported versions

docs/conf.py
Readding missed YEAR statement from regenerating conf.py for Sphinx.
ref: https://github.com/cython/cython/pull/7137
=> docs: Automatically adapt year in copyright line

Cython/Utility/Optimize.c, Cython/Utility/TypeConversion.c
Previously, we assumed that a compact PyLong value always fits into a C `long`, which is usually true (<= 30 bits) but doesn't need to stay that way, given the `Py_ssize_t` return value when converting it.
Fixes https://github.com/cython/cython/issues/7134
=> Use a fast and safe conversion from PyLong to C long.

Cython/Compiler/ExprNodes.py, Cython/Compiler/PyrexTypes.py, tests/run/fstring.pyx
External typedefs are a little more tricky because their Cython declaration may not be accurate and they need their own conversion function. For typedefs in Cython code, we can reuse the function of the underlying base type.
=> Optimise integer formatting for typedefs.

Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, tests/errors/w_pxd_assign.pxd, tests/errors/w_pxd_assign.pyx
It looks like lots of executable statements end up silently getting dropped in pxd files. However this kind of "initialization/assignment" seems like a particularly easy mistake to make so I think it's worth a specific warning.
Fixes #7173
=> Add a warning on assignments in pxd files
