- Cython/Compiler/Optimize.py
- tests/errors/reversed_literal_pyobjs.pyx
- tests/run/reversed_iteration.pyx
One potential problem is that is does not generate warnings on the division, however we know that `step_value != 0`. I have a much larger test file on my computer, if there are doubts of the basic functionality. Hopefully it fits into the structure properly this time, if not comments are welcome.
Completing ticket #765.
> Optimize reversed(range(...)), with non-constant values.

- Cython/Includes/numpy/__init__.pxd
There were several fields missing from the defintion of the Numpy dtype.
Contribution based on suggestions on the Numpy-Mailinglist:
http://mail.scipy.org/pipermail/numpy-discussion/2014-December/071952.html
> Enhance cython defintion of the Numpy dtype

- runtests.py
I had spent more than half an hour figuring out why I couldn't run a test file unless I renamed it, chasing around `runtests.py` to see where my tests where being excluded.
> have runtests.py explain when it's excluding based on bugs.txt

- Cython/Compiler/PyrexTypes.py
These two example functions, meant to be called with arguments that are lists of numpy arrays, each result in C++ compiler errors using the current Cython master (db4001f):
```Cython
from libcpp.vector cimport vector
def test_memviews_same(a,b):
cdef vector[double[:]] aa = a
cdef vector[double[:]] bb = b
def test_memviews_diff(a,b):
cdef vector[double[:]] aa = a
cdef vector[int[:]] bb = b
```
Compiling that file using db4001f would result in an error like
```
blah.cpp: In function 'std::vector<__Pyx_memviewslice> __pyx_convert_vector_from_py___Pyx_memviewslice(PyObject*)':
blah.cpp:12109:40: error: redefinition of 'std::vector<__Pyx_memviewslice> __pyx_convert_vector_from_py___Pyx_memviewslice(PyObject*)'
static std::vector<__Pyx_memviewslice> …
```
> fix utility code generation for C++ vectors of typed memoryviews

- docs/src/reference/compilation.rst
Document the `initializedcheck` compiler directive. With the default value of `True` the following is inserted into the generated .c files whenever memoryviews are accessed:
```
if (unlikely(!__pyx_v_lightfm->model_biases.memview)) 
{PyErr_SetString(PyExc_AttributeError,"Memoryview is not initialized");
{__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}}
```
As far as I can tell this is not documented anywhere at the moment. There is some discussion here: https://mail.python.org/pipermail//cython-devel/2012-April/002289.html
Can anybody comment on the performance impact of changing this?
> Document `initializedcheck` compiler directive.

- Cython/Utility/MemoryView.pyx
In CPython 2.7, the memoryview.tobytes() method (implemented in
function memoryview_tobytes() in cpython/Objects/memoryobject.c) calls
PyBuffer_ToContiguous() to copy the bytes in the buffer object to the
newly allocated string memory.  PyBuffer_ToContiguous() in turn calls
PyBuffer_IsContiguous(), which always returns false when the
suboffsets member of the Py_buffer struct is non-NULL (even if all
entries in that array are negative!).  When PyBuffer_IsContiguous()
returns false, PyBuffer_ToContiguous() runs an alternative memory copy
scheme which apparently has an off-by-one bug that the normal memory
copy scheme doesn't have.
This change sets the Py_buffer suboffsets member to NULL if all
entries are negative, avoiding the off-by-one bug.
To reproduce the bug:
cpdef foo():
cdef …
> work around memoryview.tobytes() off-by-one bug with suboffsets

- docs/src/userguide/buffer.rst
- docs/src/userguide/index.rst
- docs/src/userguide/special_methods.rst
I noticed there was hardly any documentation for implementing the buffer protocol (PEP 3118) from Cython, even though there is special support for it in the compiler. Since I had to implement the protocol today, I thought I'd write up what I did in a sort of tutorial.
> Docs: how to implement PEP 3118, the buffer protocol

- docs/src/userguide/source_files_and_compilation.rst
All 4 user guides are quite old. I have seen a lot of minor mistakes here and there.
> Fix document error "*.pyx" -> ["*.pyx"]

- Cython/Build/Dependencies.py
When looking for .pxd files for a relative cimport, use `is_package_dir()` instead of only supporting `__init__.py` files. This fixes in particular an issue inside `Cython/Includes/cpython`:
```
missing cimport in module '.object': /usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython-0.23.dev0-py2.7-linux-x86_64.egg/Cython/Includes/cpython/module.pxd
```
> Fix relative cimport for Cython package dirs

- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_compiler.cmd
Use the appveyor continuous integration service to build wheels for
windows. This procedure was adapted from this guide:
https://packaging.python.org/en/latest/appveyor.html
This is the same as #388 but against the 0.22.x branch instead of master.
> Use appveyor to build windows wheels

- Cython/Build/Dependencies.py
Implement a simple progress indicator for `cythonize()`:
```
[  1/411] Cythonizing sage/algebras/letterplace/free_algebra_element_letterplace.pyx
[  3/411] Cythonizing sage/algebras/letterplace/letterplace_ideal.pyx
[  4/411] Cythonizing sage/algebras/quatalg/quaternion_algebra_cython.pyx
[  2/411] Cythonizing sage/algebras/letterplace/free_algebra_letterplace.pyx
[  6/411] Cythonizing sage/calculus/interpolators.pyx
[  7/411] Cythonizing sage/calculus/riemann.pyx
[  8/411] Cythonizing sage/calculus/var.pyx
[  5/411] Cythonizing sage/algebras/quatalg/quaternion_algebra_element.pyx
[  9/411] Cythonizing sage/categories/action.pyx
[ 10/411] Cythonizing sage/categories/category_cy_helper.pyx
warning: sage/misc/classcall_metaclass.pxd:9:4: type already a builtin Cython type
warning: …
```
> Progress indicator for cythonize()

- tox.ini
Was trying to run tox tests but failing with
~~~
error: invalid integral value '0 -ggdb' in '-O0 -ggdb'
error: invalid integral value '0 -ggdb' in '-O0 -ggdb'
error: command 'clang' failed with exit status 1
~~~
(Full log can be found [here](http://d.pr/f/1fkBi+).)
I removed the quotes around the CFLAGS env value, and the tox tests seem to work now.
> Fix CFLAGS environ in tox config

- Cython/Compiler/Parsing.py
- tests/run/cpp_assignment_overload.srctree
As near as I can tell, the only thing needed to enable the assignment operator was to add it to the supported operators list. Tests pending.
> Enable overloading the assignment operator.

- Cython/Utility/ModuleSetupCode.c
> fix binary search in code object cache

- Cython/Utility/TypeConversion.c
Comparing `sizeof(Py_ssize_t)` to different sizes at compile time results in warnings or errors when the C++ compiler tries to find a function matching `abs(value)` (Per the standard library spec, no functions match if `ssize_t` is a typedef of `long long`). Luckily, `pyport.h` provides some SIZEOF macros we can use at preprocess time. __Pyx_sst_abs is now conditionally defined to a much shorter expression.
64-bit MSVC is one case where `ssize_t` is a `long long`. Instead of falling back to `((value<0) ? -value : value))`, I added a check for 64-bit MSVC that calls the MS-specific function `_abs64(long long)`
This change also includes the change given by PR #402, improved with a check against the available C++ version as `std::abs` is only available on C++11.
Have only tested this with …
> Rewrite __Pyx_sst_abs using only preprocessor macros, and add a case for 64-bit MSVC

- Cython/Utility/TypeConversion.c
This crept into a recent commit to fix a different MSVC error. I came across it when compiling a module with MinGW-w64.
> Fixed mismatched parenthesis.

- Cython/Build/Dependencies.py
This patch sorts the dependencies in the metadata of Cython extensions. This is mostly useful when looking at the JSON dump of the metadata in the generated C file: the dependencies are no longer in arbitrary order (making diffs less useful).
> Sort dependencies in metadata

- Cython/Build/Dependencies.py
- tests/compile/distutils_libraries_T845.srctree
Cython does not correctly handle the dependencies in case of a statement like
```
cimport foo, bar
```
(only `foo` is considered)
> Correctly parse dependencies of "cimport foo,bar"

- Cython/Utility/TypeConversion.c
Some compilers appear to require you to explicitly `#include <cstdlib>` before
providing `std::abs`.
Fix for #403
> Fixed __Pyx_sst_abs with C++11

- Cython/Utility/Embed.c
Found by clang's static analyzer.
None of those are significant, but we might as well fix them.
> Fixed some memory leaks in Utility/Embed.c

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- tests/run/cpp_assignment_overload.srctree
Somehow I missed this in https://github.com/cython/cython/pull/399. This allows assignment from a different type if the corresponding operator= is available.
> Further Assignment Operator Fixes

- tests/run/cpp_call_stack_allocated.srctree
This tests that overloading the signature for the C++ call operator works properly.
> More tests for calling stack allocated objects

- tests/errors/cpp_no_auto_conversion.pyx
check that cython does not automatically convert from native type to an object when calling cpp functions. added in file tests/errors/cpp_no_auto_conversion.pyx
> Added tests for cpp auto conversion of function parametes

- Cython/Compiler/Nodes.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
Many C API calls, both from CPython and externally, expect
PyTypeObject* for the type argument.  A misdeclaration is
a warning in C, but an error in C++.
The C type of other builtins, such as lists, are not typically
required in function signatures, so they are left as PyObject*.
> Use PyTypeObject* for the builtin type type.

- Cython/Tests/TestJediTyper.py
- Tools/jedi-typer.py
- runtests.py
Allow jedi-typer to support both jedi 0.8.x and jedi 0.9.0.
It compiled and passed all 4 tests. However, in order to further improve the jedi-typer, some more tests are needed. But add more features and tests might break the original jedi-typer and it is difficult to maintain the code that supports both 0.8.x and 0.9.0 API. 
So this patch only aims for getting jedi-typer works with current jedi 0.9.0 while having similar functionality of current jedi-typer.
> Experimental support for jedi 0.9.0

- docs/src/tutorial/array.rst
This adds documentation of the Cython functions available for cpython.array objects, which were previously only documented in the source code. Let me know if it's better to move or split this to the user guide section.
> document array module

- tests/run/cpp_smart_ptr.pyx
https://github.com/cython/cython/commit/e801a4abb8d3ffba63a1d2a3681a4de41a8546b1 didn't fix the recurring Travis build failure since the default gcc still doesn't support the flag `-std=c++11`. This fixes it by using `-std=c++0x` instead.
> Use c++0x rather than c++11 for unique_ptr tests

- Cython/Compiler/Code.py
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/Optimize.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/StringEncoding.py
- Cython/Compiler/TypeSlots.py
- Cython/Utility/ModuleSetupCode.c
- tests/run/charptr_decode.pyx
- tests/run/charptr_len.pyx
- tests/run/posix_test.pyx
This also prevents non-const ``char*`` string literals from being interned in the first place.
> make C char* string literals "const" unless specified otherwise

- Cython/Utility/ModuleSetupCode.c
Python's `longintrepr.h` defines macros `SHIFT`, `BASE` and `MASK`. These short names can easily lead to conflicts if other headers use them. Now that the `longintrepr.h` include has moved up in the Cython-generated files, we really don't want these macros. This fix is in particular needed for http://bugseng.com/products/ppl/
> undef unwanted defines from longintrepr.h

- Cython/Includes/libc/float.pxd
See discussion on cython-users.
> Constants in float.pxd are not integers.

- Cython/Utility/StringTools.c
Fixes http://trac.cython.org/ticket/864.
> __Pyx_decode_c_string: check for overflow when calling strlen.

- Cython/Compiler/Main.py
This PR should make this behaviour allowed:
```
$ pwd
/some/path/
$ cython -o . /other/path/somefile.pyx
$ ls
somefile.c
```
Useful when cythonizing files from read-only media and you want the filenames to be deduced.
> Allow output file to be a dir. E.g. 'cython -o . /path/somefile.pyx'

- Cython/Includes/libcpp/algorithm.pxd
Expose C++'s copy in <algorithm>
With pull request #454, this can be used in Cython code to copy stuff amongst c++ containers.
> Cpp copy added to libcpp/algorithm.pxd

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Shadow.py
- docs/src/tutorial/pure.rst
Currently `cython.cast('list', l)` will fail because of missing `typecheck` attr. Similarly, `cython.cast('MyType', o)` will fail because of missing `base_type` attr. The cause is that `ParseTreeTransforms` creates the `TypecastNode` directly from the type. Also, it forgets to set the `typecheck` attr (maybe I could add an optional kwattr to the cast function, say `cython.cast('list', l, typecheck=True)`).
> Allow cast(...) to python types.

- Cython/Build/Dependencies.py
Avoid checking the dependencies of the same file multiple times if that file is found with different filenames.
> Normalize filenames when calling parse_dependencies()

- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/Pipeline.py
- tests/run/cdef_class_property_decorator_T264.pyx
- tests/run/pure_cdef_class_property_decorator_T264.pxd
- tests/run/pure_cdef_class_property_decorator_T264.py
This makes properties work properly in cdef classes, and gives them the
exact same AST as the “property something:” blocks, whose syntax should
probably be deprecated now.
Fixes T264.
Note: this is the v2 version of this patch, the first one was sent to the cython-devel ML and is now obsolete. The differences are a simpler and more efficient code that doesn’t leak, and another test for pure mode.
> Add a pass transforming Python-style properties in cdef class into Cython-style properties

- Cython/Compiler/ParseTreeTransforms.py
As a follow-up on #462, this deprecates the old-style pyx-only syntax for properties.
I couldn’t find out how to check if the “property” name has been redefined before in this pass, it seems this analysis is done later in the pipeline, so I didn’t implement the other suggested fix.
> Deprecate the 'property …:' syntax, as suggested in #462

- Cython/Includes/libcpp/limits.pxd
- tests/run/libcpp_all.pyx
I'm working on wrapping a C++ library where numeric_limits is needed.  This .pxd works for my purposes.
One caveat is that Cython doesn't appear to support static member variables, so I've declared them non-static.  I've documented that a user must then create an object of that type in order to access those values.   I'm guessing such access are edge cases, but that having the static function is useful.
> Cpp limits

- Cython/Utility/ImportExport.c
Changes the error message to include the sizes of the two
structures. This aids in debugging the it allows us to check the sizes
to see which version we were built against versus the version we have at
runtime.
Would a test be needed for the contents of the error message?
> update error message in __Pyx_ImportType when basicsize doesn't match

- Cython/Compiler/Scanning.py
This avoids inadvertently using the backslash path separator in the generated `#line` directives on Windows. Using a backslash in a source file directive can cause compilation errors from using incorrect escape sequences and doesn't have the desired effect regardless of whether or not the compiler accepts the input.
> Fix generated `#line` directives on Windows

- .travis.yml
Enable tests on python 3.5-dev to catch problems with upcoming python releases early.
This test fails because Cython:master currently fails with with Python 3.5.1 and later.  See the [Cython-devel mailing list discussion](https://mail.python.org/pipermail/cython-devel/2016-January/004639.html) for more information.
> Enable tests on python 3.5-dev

- Cython/Compiler/Code.py
- Cython/Compiler/ModuleNode.py
I'm always using Cython for seeing how this or that piece of code in Python will be represented using Python C API, so my changes are devoted to improving (in a way) readability of the resulting C code. The idea is the following. The resulting code is full of the constructions like this
```c
{__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
```
They are always catching your eye and distract attention from other pieces of automatically generated code. I suggest we hide each constructions like that in the macro like this
```c
__PYX_ERR(0, 4, __pyx_L1_error)
```
The `__PYX_ERR` macro looks in the following way
```c
#define __PYX_ERR(f_index, lineno, Ln_error) \\
{ \\
%s = %s[f_index]; %s = lineno; %sgoto Ln_error; \\
}
```
> Hide some parts of stack trace in __PYX_ERR macro

- Cython/Compiler/ParseTreeTransforms.py
- tests/errors/pure_cclass_without_body.pxd
- tests/errors/pure_cclass_without_body.py
> Don’t crash when a C class isn’t defined in the pxd

- Cython/Includes/libcpp/iterator.pxd
This change exposes's C++'s <iterator> to Cython.   Having this allows some other functions in <algorithm> currently missing from Cython to be added.
There are issues, though.  C++11 and C++98 define some of these functions differently.  Perhaps there should be a libcpp11 directory that contains functions differing b/c C++98 and C++11?
> Cpp iterator

- Cython/Compiler/PyrexTypes.py
Use [documented variables](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html) to check GCC version (`GCC_VERSION` doesn't actually work).
> Use correct macros to check GCC version

- Cython/Distutils/build_ext.py
This change allows to pass generator (e.g. `itertools.chain`) as `include_dirs` if for some reason evaluation of include directories needs to be delayed e.g. due to simultaneous dependency on *cython* and *numpy*.
Since version 18.0 of *setuptools* it's possible to seamlessly install cython extensions and depend on *Cython* via `setup_requires`. However, due to the way it's implemented (via delayed import of `Cython.Distutils.build_ext`), it's hard to modify how the extensions are compiled without recreating the whole `build_ext` from scratch. One of the canonical examples where custom builder is required is passing `numpy.get_include()` to `include_dirs`.
With this change and following pseudo-code:
```
def delayed_numpy_inc():
import numpy
yield numpy.get_include()
import itertools
for …
```
> Ensure that extension's include_dirs is a list

- Cython/Build/Dependencies.py
- Cython/Utils.py
When applying this branch, running SageMath's `setup.py` goes 25% faster when all sources are up to date.
> Optimize dependency checking

- Cython/Build/Dependencies.py
This seems to be necessary since distutils.Extension is an old-style class, which is not comparable that way. If setuptools Extensions are being passed into the function, I got the TypeError being raised at the else block, because the check ```isinstance(pattern, distutils.Extension)``` is False in that case.
I only experience this bug, if installing several dependent setuptools based projects (A depends B and during setup of B, which also uses Cython, this happened).
This PR adds an additional check for Setuptools derived Extensions, which then succeeds.
As a test to reproduce it, the following real-world example (sorry has a lot of dependencies like scipy and matplotlib): 
pip install git+https://github.com/markovmodel/pyemma@dev_release_1.3
installs pyemma, depended on msmtools and …
> [Build/Dependencies] added a comparision for setuptools.Extension class

- Cython/Utility/Optimize.c
- Cython/Utility/TypeConversion.c
The current cast isn't doing anything, because the unary minus implicitly
upcasts to int again, resulting in warnings about potentially value altering
conversions on 32 bit systems.
Fixes issue #877.
> FROM_PY_FUNCTION: Cast to sdigit after unary minus, not before

- Cython/Utility/Optimize.c
The current order results in compiler warnings on 32 bit machines, e.g.
src/llfuse.c: In function '__Pyx_PyInt_TrueDivideObjC':
src/llfuse.c:43980:17: warning: left shift count >= width of type
if (8 * sizeof(long) <= 53 || (__Pyx_sst_abs(size) <= 52 / PyLong_SHIFT) || likely(labs(a) <= (1L << 53))) {
Switching the order so that the left shift is closer to the sizeof test
avoids the warning, presumably because it makes it easier for the
compiler to see that the left shift is only executed on 64 bit.
Thanks to Christian Neukirchen for doing most of the work!
> __Pyx_PyInt_TrueDivideObjC: switch comparison order

- Cython/Utility/TypeConversion.c
This showed up on MSVC after https://github.com/cython/cython/pull/493. Moving the cast made it so that we were applying a unary minus to an unsigned integer. The code should be correct now.
An alternative would be to define a general size preserving unary minus macro that checks sizeof and branches on that and then lets the optimizer get rid of dead branches. Either one requires the optimizer to do something intelligent though.
> Silence a warning about applying unary minus to an unsigned integer

- Cython/Compiler/ExprNodes.py
- tests/errors/cpp_no_auto_conversion.pyx
- tests/run/non_const_as_const_arg.pyx
When function arguments are marked as const, this means that the function should not modify them, not that non-const arguments are not allowed.
> Don't error out when non-const value is passed as const function parameter

- Cython/Includes/libcpp/memory.pxd
This makes it possible to use a new idiom to wrap C++ classes if the target compiler can be assumed to support C++14:
```
from libcpp.memory cimport unique_ptr, make_unique
from cython.operator cimport dereference as deref
cdef extern from *:
cdef cppclass Rectangle:
void draw()
cdef class PyRectangle:
cdef unique_ptr[Rectangle] thisptr
def __cinit__(self):
self.thisptr = make_unique[Rectangle]()
def draw(self):
deref(self.thisptr).draw()
```
No more worries about forgotten `__dealloc__` functions, very clean and expressive code.
I was thinking of adding a test, but this requires `-std=c++14` support from the compiler, which is probably too much for now. At the same time, I couldn't figure out how one could add a test that is only cythonized, not compiled.
Also, maybe this example is …
> Add declarations for C++11/14 smart pointer factories (make_shared & make_unique)

- Cython/Compiler/Nodes.py
- docs/src/tutorial/pure.rst
This allows to declare `readonly` and `public` attrs for extension types in pure python.
Please see the documentation diff for an example.
> Add visibility kwarg to cython.declare.

- setup.py
Otherwise, `pip show cython` says `License: UNKNOWN`.
It may be preferable to include the Apache license version number, though none of `numpy`, `scipy`, or `matplotlib` do. They simply write `BSD`. Both here and there, omitting the version number leaves ambiguity, because compatibility with GPL depends on the license version. Nonetheless, it is simpler to just note the license name. After all, this is metadata that people read quickly, and should thus remain uncluttered.
Admittedly, this duplicates information contained in the trove classifiers.
> REL: pass license argument to setuptools.setup

- Cython/Build/Dependencies.py
The message "missing cimport in module" is very confusing. This patch fixes it.
> Improve "missing cimport" message

- Cython/Compiler/PyrexTypes.py
- tests/run/locals.pyx
For example, the following code
```
def f():
cdef int a = 1
cdef np.ndarray[double, ndim=1] b = np.zeros(3)
c = tuple()
return locals()
```
would only return `a` and `c` in locals.
I fix this by making BufferType coercable to pyobject (I think this is a reasonable thing to do, and it doesn't seem to break anything else, but I could be missing a good reason why it wasn't)
Also adds a testcase
> numpy arrays are no longer omitted from locals()

- Cython/Compiler/Options.py
- Cython/Compiler/Symtab.py
- Cython/Shadow.py
- docs/src/userguide/extension_types.rst
- tests/run/no_gc.pyx
Useful when one can guarantee the class cannot participate in
cycles, but the compiler cannot prove it on its own
> Add no_gc directive to fully disable GC

- Cython/Build/Dependencies.py
- tests/run/define_macro.pyx
- tests/run/define_macro_helper.h
This makes it so that define macros without a specified value can be passed using commented distutils directives in Cython source files. There's no way to do that with the current syntax. This makes it so that macros listed without a value are defined without a value. See the test case for an example.
> Allow passing define macros without specified values as commented directives

- Cython/Compiler/ExprNodes.py
- tests/run/cpp_classes_def.pyx
This little tweak to the (currently undocumented) C++ class feature lets you call a base class' method from the body of a derived class' method, even if you overrode it.
A relevant test has also been added.
> Allow C++ class methods to use base class' methods

- Cython/Includes/libc/math.pxd
- Cython/Includes/numpy/math.pxd
I found that some of the definitions in `Includes` were missing some arguments. Which made it impossible for example to use for example:
```
from libc.math cimport fma
def do_stuff(double x, double y, double z):
cdef double res
res = fma(x, y, z)
return res
```
I didn't find any wiki or help page for contributors. So I hope it's okay to just open a PR.
> completed some signatures in Includes - libc.math and numpy.math

- Cython/Debugger/libpython.py
Recent versions of `gdb` do not convert every `gdb.Value` to `int`. To check for NULL pointers, use `not value` instead of `int(value) == 0`.
> Replace "int(val) == 0" by "not val" for gdb.Value instances

- docs/src/userguide/wrapping_CPlusPlus.rst
http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html
There is only `int getArea();` in the `Rectangle` class.
> fix docs example: getArea instead of undefined getLength

- setup.py
In general it's best for actions performed in `setup.py` to be deferred until the command to which they are relevant is actually run.  For example most of what `compile_cython_modules` does should be deferred until finalizing the `build_ext` command.  But as a simpler workaround, just ensure that anything it prints is to stderr.
Otherwise this breaks certain assumptions, such as that `./setup.py --name` will print (on stdout) the distribution name (and nothing else), and likewise for `./setup.py --version`.
> setup.py shouldn't write arbitrarily to stdout (especially when passed display options)

- Cython/Compiler/CythonScope.py
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/Symtab.py
- Cython/Includes/libcpp/typeindex.pxd
- Cython/Includes/libcpp/typeinfo.pxd
- Cython/Parser/Grammar
- Cython/Utility/CppSupport.cpp
- docs/src/userguide/wrapping_CPlusPlus.rst
- tests/run/cpp_operators.pyx
- tests/run/cpp_operators_helper.h
This pull request adds the C++ `typeid(...)` operator to Cython, available by cimporting:
```cython
from cython.operator cimport typeid
cimport libcpp.typeinfo
```
(the operator requires the `libcpp.typeinfo.type_info` type and you cannot use it without the `<typeinfo>` header included)
`std::bad_typeid` exceptions thrown by `typeid()` are caught.
Relevant documentation and a test has also been added.
> Add support for the typeid operator

- Cython/Build/Dependencies.py
- tests/compile/conditional_dependencies.srctree
We should support finding dependencies in conditional compilation like
```
IF some_condition:
cimport foo
```
Note that the dependencies will always be dependencies unconditionally (independent of the condition), since the dependency-checking code doesn't actually parse the files.
CC @anntzer
> Support dependencies in conditional compilation

- Cython/Compiler/Main.py
Get rid of the warning
```
UserWarning: got unknown compilation option, please remove: cache
```
when calling `cythonize(..., cache=something)`.
> Do not warn for "cache" option

- tests/run/builtin_type_inheritance_T608.pyx
Test is failing on Python 3 because output is:
builtin_type_inheritance_T608.MyException: 3
on py3, but
MyException: 3
on py2
IGNORE_EXCEPTION_DETAIL ignores the module prefix on py3.
> set IGNORE_EXCEPTION_DETAIL on MyException test

- Cython/Distutils/build_ext.py
- Cython/Distutils/old_build_ext.py
When setuptools imports from Cython (Python 3.5), setuptools.command.build_ext is defined, but setuptools.command.build_ext has no attribute .build_ext yet, causing the `_build_ext.build_ext` to fail with an AttributeError.
By attempting to import the object, rather than its containing module, the check is more thorough.
This appears to be necessary to build any extensions with setuptools on Python 3.5 with Cython 0.25a0.
> check for build_ext object in import check

- tests/run/numpy_math.pyx
This reverts commit 24cf7c9671b45e891a6c35b4f576fff3dff5c00e.
According to the numpy documentation npy_isinf merely provides an
equivalent of C99 isinf, which in turn is only required to return a
non-zero value for a given infinite argument.
The original commit breaks the test when compiled with clang & libc++.
cc @larsmans
> Revert "test: assert that isinf returns -1 for negative infinity"

- Cython/Includes/cpython/longintrepr.pxd
- tests/run/longintrepr.pyx
`longintrepr.h` is not part of Python's official API, but it is still useful to implement conversion between Python integers and other multi-precision integer types. This is used by SageMath for example to implement conversion to/from GMP integers.
Note that the `ctypedef class __builtin__.long [object PyLongObject]` trick doesn't work because Cython uses `long` for the C type `long`, not the Python type. So, I had to resort to an uglier solution.
> Add declarations for longintrepr.h

- Cython/Includes/numpy/__init__.pxd
The numpy macros `import_array` (and similarly `import_umath`) have a `return` statement in them, making them not really useful for Cython. The underscored functions `_import_array` and `_import_umath` are more useful. This PR implements `import_array` and `import_umath` as `cdef` functions in Cython instead of using the numpy macros.
> Implement numpy's import_array and friends in Cython

- Cython/Utility/ModuleSetupCode.c
Currently, the macro `CYTHON_UNUSED` appears below the `#include` lines coming from `cdef extern from "..."` files. By moving it higher in the preamble, those included files can use `CYTHON_UNUSED`.
> Move CYTHON_UNUSED macro up such that included files can use it

- tests/run/annotate_html.pyx
Otherwise tests are failing on my box with a UnicodeDecodeError.
```
======================================================================
FAIL: annotate_html ()
Doctest: annotate_html
----------------------------------------------------------------------
File "/home/engshare/third-party2/python/3.5.0/gcc-4.9-glibc-2.20/cb5a762/lib/python3.5/doctest.py", line 2190, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for annotate_html
File "/home/engshare/third-party2/Cython/master/src/build-gcc-4.9-glibc-2.20/build/TEST_TMP/0/run/c/annotate_html/annotate_html.cpython-35m-x86_64-linux-gnu.so", line 1, in annotate_html
----------------------------------------------------------------------
File …
```
> Allow UTF8 in tests/run/annotate_html.pyx

- Cython/Includes/libc/errno.pxd
So allow for that value in this enumeration.
Added immediately after ENODATA
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>
> errno.h on FreeBSD contains ENOATTR instead of ENODATA

- Cython/Build/Dependencies.py
The hash digest cannot be computed under Python 3 because of a few missing string `encode` calls (to get  hashable bytes). Here is a example when trying to enable the cythonize cache to build scikit-learn:
```
File "setup.py", line 268, in <module>
setup_package()
File "setup.py", line 264, in setup_package
setup(**metadata)
File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
config = configuration()
File "setup.py", line 135, in configuration
config.add_subpackage('sklearn')
File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage
caller_level = 2)
File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/numpy/distutils …
```
> Fix cythonize(source_filename, cache=True) under Python 3

- Cython/Includes/libcpp/algorithm.pxd
- Cython/Includes/libcpp/vector.pxd
A straightforward addition of std::unique(), std::lower_bound(), std::upper_bound() and std::vector::iterator::operator-(iterator).
Tested with this code: http://pastebin.com/fzySXX2A (output: http://pastebin.com/9yEFVkuC ), both with and without c++11 (setup.py: http://pastebin.com/87MH0VtR and http://pastebin.com/RSeKSaEW )
> A few more wrappers in libcpp.algorithm and libcpp.vector

- Cython/Compiler/Options.py
Reported-by: Paulo Andrade <paulo.cesar.pereira.de.andrade@gmail.com>
References: https://bugzilla.redhat.com/show_bug.cgi?id=1406533
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> fix typo in Compiler/Options.py

- Cython/Utility/StringTools.c
Avoid doing the bulk compare if string hashes are initialized and unequal.
Let comparisons against literals take advantage of this optimization by initializing their hashes at import time.
The following benchmark yields a 10% speedup on the best case, and a 2% slowdown on the very worst case (albeit a somewhat contrived worst case). On average, I'd expect it to be an overall improvement in-between those numbers:
``` python
import timeit
import cython
@cython.ccall
@cython.locals(x=bytes)
def f(x):
return x in (b'1234', b'4321', b'2321')
def main():
print timeit.timeit(lambda:f(b'4242'), number=100000000)
```
While subtle, it could make a significant difference in string-heavy code.
> Optimize string comparisons

- setup.py
On Windows the comparison `directory == 'Cython/Includes/Deprecated'` fails because `os.path.sep` is `'\\'`, not `'/'`.
> Fix Includes/Deprecated not included in Windows wheels

- Cython/Build/IpythonMagic.py
Hi,
I added a --src (-S) flag to add to the list of source files to compile with the IPython notebook's cell-generated pyx file when using cythonmagic. I found it useful when I was testing any integration of new c/c++ code with Cython. And when I cimport any modules that require source code if I cdef extern from an external header file, the --src flag allows successful compilation.
e.g.:
%%cython --cplus --src=/path/to/src1.cc --src=/path/to/src2.cc --include=/path/to/include.h
Let me know what you think about this addition. Thanks!
> Add --src flag to add c/c++ src files (cythonmagic)

- Cython/Includes/libcpp/vector.pxd
- tests/run/cpp_stl_vector.pyx
Adds test case for #1596
While I was there, I noticed that there was no `size_type` or `difference_type`.
This test fails (with `size_type` switched to `size_t`) before my commit with the same crash I was seeing.
> Vector cleanups

- pyximport/pyximport.py
- pyximport/test/test_pyximport.py
Python allows to import and run modules from ZIP archives. I thought it would be useful if pyximport handled this case!
Here's a quick demo:
``` bash
$ cat _speedups.pyx
def main():
print("Hello, world!")
$ cat __main__.py
import pyximport
pyximport.install()
import _speedups
_speedups.main()
$ zip demo.zip _speedups.pyx __main__.py
adding: _speedups.pyx (stored 0%)
adding: __main__.py (deflated 29%)
$ PYTHONPATH=. python3 demo.zip
...
8 warnings generated.
Hello, world!
```
> Allowed importing pyx files from ZIP archives

- Cython/Debugger/Cygdb.py
- Cython/Debugger/libcython.py
```
/usr/local/lib/python3.5/dist-packages/Cython-0.25.2-py3.5-linux-x86_64.egg/Cython/Debugger/Cygdb.py:141: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp7zs49q09' mode='r' encoding='UTF-8'>
logger.debug('Command file (%s) contains: """\n%s"""', tempfilename, open(tempfilename).read())
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see: …
```
> Fix Python 2 and 3 have diffrent default encoding

- Cython/Compiler/Code.py
- Cython/Debugger/Tests/TestLibCython.py
- Cython/Debugger/Tests/cfuncs.h
- Cython/Debugger/Tests/codefile
- runtests.py
- tests/compile/callingconvention.srctree
- tests/compile/declarations.srctree
- tests/cygwin_bugs.txt
- tests/run/complex_numbers_T305.pyx
- tests/run/complex_numbers_T305_long_double.pyx
- tests/run/complex_numbers_c89_T398_long_double.pyx
- tests/run/cpdef_extern_func.pyx
- tests/run/int_float_builtins_as_casts_T400.pyx
- tests/run/int_float_builtins_as_casts_T400_long_double.pyx
See individual commit messages for more details.  I only skipped a tiny handful of tests.  In other cases test files were split up so that I could skip _only_ those cases that depend on `long double` functions on Cygwin (pending any better resolution to that issue).
In other cases a few tests were slightly rewritten to work correctly, and a few fixes to the test runner itself were needed.
I don't think there is any continuous integration being done for Cython on Windows, or Cygwin in particular.  If there's any interest I would be willing to work on setting that up and maintaining it.
> Several fixes to get test suite passing on Cygwin

- Cython/Compiler/ExprNodes.py
This makes the build reproducible irregardless of the build path. Fixes: #1565
> Encode relative path to working tree in code paths when possible.

- docs/src/userguide/early_binding_for_speed.rst
There is no `:meth:`_rect`` method in the example. Context makes clear it should be `:meth:`_area``
> Correct mistake in doc `early_binding_for_speed.rst`

- docs/src/userguide/language_basics.rst
The example
```cython
cdef:
struct Spam:
int tons
int i
float f
Spam *p
void f(Spam *s):
print(s.tons, "Tons of spam")
```
produces the error
```
...
int i
float f
Spam *p
void f(Spam *s):
^
/home/fabian/.cache/ipython/cython/_cython_magic_1754f7a2d1965e143dc9fe6d26b00c19.pyx:10:4: Function signature does not match previous declaration
```
because of `float f`and `void f`. This is solved by e.g. renaming `float f` to `float a`.
> Update language_basics.rst: corrected an example

- Cython/Compiler/ExprNodes.py
In the functions `__Pyx_Py3MetaclassPrepare` and `__Pyx_Py3ClassCreate`, the `metaclass` argument is of type `PyObject*` but it is sometimes passed as `PyTypeObject*`. This gives compiler warnings of the form
```
build/cythonized/sage/misc/classcall_metaclass.c:3077:36: warning: passing argument 1 of ‘__Pyx_Py3ClassCreate’ from incompatible pointer type
__pyx_t_4 = __Pyx_Py3ClassCreate(__pyx_ptype_4sage_4misc_19classcall_metaclass_ClasscallMetaclass, __pyx_n_s_C3, __pyx_t_1, __pyx_t_3, __pyx_t_2, 1, 0); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 524, __pyx_L1_error)                                                                                                                         
^ …
```
> Pass metaclass as PyObject* (and not PyTypeObject*)

- Cython/Compiler/ModuleNode.py
Similar to #1621, this avoids some compiler warnings like
```
build/cythonized/sage/categories/category_singleton.c:3133:14: warning: passing argument 1 of ‘v’ from incompatible pointer type
e = (*v)(p->_parent_class_of_category, a); if (e) return e;
^
build/cythonized/sage/categories/category_singleton.c:3133:14: note: expected ‘struct PyObject *’ but argument is of type ‘struct PyTypeObject *’
```
> Pass first arg of visitproc as PyObject*

- Cython/Build/IpythonMagic.py
Make the IPython cell magic only import things in `"__all__"` when `"__all__"` exits in the cython cell.
I feel that this makes the cython cells not to pollute the space names unintentionally.
BTW, not clear why the import only skip the variables starts with `__`. In Python, from module import star will also skip the single underscores `_`.
> Let IPython magic only import things in `"__all__"`

- Cython/Utility/Optimize.c
The .iterkeys(), .itervalues() and .iteritems() methods are accepted in Cython
even when targetting Python 3.x.  However, this is implemented by a shortcut
inside Optimize.c that is explicitly disabled on PyPy.  This fixes the
situation.
> PyPy3: make special dict methods work

- Cython/Compiler/TypeSlots.py
Context: we (the pypy devs) are working on pypy3 compatibility with Python 3.5, including C-API support, with a first 3.5-compatible release expected in a few weeks. 
The previous releases of pypy3 (implementing 3.2 and 3.3) hadn't updated their nb_* slots definitions to Python 3, but this has been fixed in the pypy3 nightlies, so the pypy3-specific workaround is no longer necessary.
> Un-disable Python3-specific slots on pypy3.5

- Cython/Includes/cpython/tuple.pxd
Otherwise this will raise `SystemError: <built-in function ...> returned a result with an error set` when failing. 
For example:
```
%load_ext cython
%%cython
from cpython.tuple cimport PyTuple_SetItem
cpdef test():
cdef Py_ssize_t b = 5
PyTuple_SetItem((1,2,3), b, 2)
return 10
test()
```
> Include except clause for PyTuple_SetItem in CPython-Includes

- Cython/Build/Dependencies.py
- Cython/Compiler/Main.py
- docs/src/reference/compilation.rst
- tests/compile/create_extension.srctree
As alternative to #412, add support for a hook function `create_extension()` allowing complete customization of creating the `Extension` object after Cython has processed the list of sources and `# distutils` declarations.
> Add create_extension() hook

- Cython/Includes/cpython/long.pxd
This includes some "new" functions from [Integer Objects](https://docs.python.org/3/c-api/long.html). Functions that are not supported by all versions that cython supports are commented but also included.
> Add declarations for several PyLong_Type functions

- Cython/Compiler/Parsing.py
- tests/run/inlinepxd.pyx
- tests/run/inlinepxd_support.pxd
A `cdef inline` implemented in a `.pxd` with default values does not work as expected:
```cython
cdef inline int my_add(int a, int b=1, int c=0):
return a + b + c
```
gives `default values cannot be specified in pxd files, use ? or *`
This pull request fixes that.
> Allow "cdef inline" with default values in .pxd

- tests/run/extstarargs.pyx
`tests/run/extstarargs.pyx` read:
```python
__doc__ = re.sub(u"(ELLIPSIS[^>]*Error: )[^\n]*\n", u"\\1...\n", __doc__, re.M)
```
But the 4th argument of re.sub() is supposed to be maximum number of substitutions, not flags.
Moreover, `re.M` affects only semantics of `^` and `$`, so it wouldn't have any effect on this regexp.
> Fix incorrect use of flags in re.sub()

- pyximport/test/test_reload.py
The indentation was inadvertently broken when expanding tabs in e908c0b9262008014d0698732acb5de48dbbf950.
Fixes:
$ python pyximport/test/test_reload.py
File "pyximport/test/test_reload.py", line 23
assert hello.x == 1
^
IndentationError: unexpected indent
NB, this change is not enough to make the test run successfully; but I'll let somebody more competent fix the remaining problems. :)
> Fix bad indentation in a pyximport test

- Cython/Build/Dependencies.py
If `cythonize()` is called with `force=True`, do not print
```
Compiling foo.pyx because it changed.
```
> Print no message if force=True

- Cython/Compiler/Builtin.py
- tests/run/builtin_abs.pyx
This patch avoids `abs(a_complex_number)` casting the complex number back to a Python object and instead uses the `__pyx_c_abs*` functions that are already defined. It also modifies the specialization for `abs` on int and long to not require the GIL.
Also added a test case to confirm it's working
Notes:
* I don't think the correct utility code is loaded for complex abs
(but it should be loaded by the complex data types hopefully)
This might be worth someone double checking
* Would probably be worth making double and float abs not require GIL
(but this is a minor improvement to existing code)
> Now uses specialised functions for complex abs

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- tests/run/pstats_profile_test.pyx
Fixes #1668. The profile hook is now called with 'call' and 'return'
each time the generator resumes/yields.
> Fix profiling for generators and generator expressions

- pyximport/pyximport.py
The file is syntactically correct only in Python ≥ 2.6, so the version check would never be run.
> pyximport: remove obsolete version check

- Cython/Includes/cpython/array.pxd
- Cython/Utility/arrayarray.h
- docs/src/tutorial/array.rst
Add support for `array.array`s of int64s or uint64s (type codes `q`/`Q`).
> Allow pointer access to 64-bit arrays

- Cython/Compiler/ExprNodes.py
Before this patch, the compiler would crash on this simple program:
<double[:4]>NULL
or on any other cast to a memoryview without first explicitly declaring a memoryview variable.
The error message was this:
```
cython_memviews.pyx:1:0: Compiler crash in AnalyseExpressionsTransform
File 'Nodes.py', line 430, in analyse_expressions: StatListNode(cython_memviews.pyx:1:0)
File 'Nodes.py', line 4746, in analyse_expressions: ExprStatNode(cython_memviews.pyx:1:0)
File 'ExprNodes.py', line 519, in analyse_expressions: CythonArrayNode(cython_memviews.pyx:1:0,
is_temp = True,
mode = 'c',
use_managed_ref = True)
File 'ExprNodes.py', line 10108, in analyse_types: CythonArrayNode(cython_memviews.pyx:1:0,
is_temp = True,
mode = 'c',
use_managed_ref = True)
File 'ExprNodes.py', line 10123, in …
```
> Fix a compiler crash when casting to a memoryview

- Cython/Build/Dependencies.py
- tests/run/cimport_from_sys_path.srctree
Consider the following situation: some package Foo has installed files `foo.pxd` and `header.h` in `.../python/site-packages/foo`. The `foo.pxd` file contains `cdef extern from "header.h"` where `header.h` is installed in `.../python/site-packages/foo/header.h`
When another package Bar wants to `cimport foo.foo`, the `cdef extern from "header.h"` will become `#include "header.h"` in the C file. The problem is now that the C compiler will not be able to find this file.
The solution is obvious: whenever we look for a `cdef extern from` file, we add its directory to the `include_dirs` of the extension.
> Automatically add include_dirs for externs

- docs/src/userguide/external_C_code.rst
closes #1747 
This adds the calls to `Py_Initialize` and `Py_Finalize` that were missing in the `cdef api` code example, together with a small note. I'm not a Cython expert, so it would be great to get some confirmation that I'm not overlooking anything and that these calls are needed!
> DOC: Add calls to Py_Initialize/Py_Finalize in code sample.

- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- tests/run/cyfunction.pyx
When calling `chain_decorators(node, ...)`, set `node.decorators = None` to avoid calling the decorators twice.
This fixes https://github.com/cython/cython/issues/1679
> Do not apply decorators twice

- docs/src/userguide/external_C_code.rst
I think the documentation about `cdef public` is unclear, especially about the "linking" part. In particular, it seems to imply that you can link code against the extension module (i.e. using the `.so` file as a dynamic library). That works on Linux, but isn't portable (it does not work on OS X for example).
> Clarify documentation regarding "cdef public"

- Cython/Includes/posix/types.pxd
In order to avoid having Cython generate `__Pyx_PyInt_From_sigset_t()`, we declare `sigset_t` as `struct` instead of `long`.
> sigset_t is not an integral type

- Cython/Utility/ObjectHandling.c
- tests/run/cyfunction_METH_O_GH1728.pyx
This code
```C
static CYTHON_INLINE PyObject* __Pyx_PyObject_CallOneArg(PyObject *func, PyObject *arg) {
#if CYTHON_FAST_PYCALL
if (PyFunction_Check(func)) {
return __Pyx_PyFunction_FastCall(func, &arg, 1);
}
#endif
#ifdef __Pyx_CyFunction_USED
if (likely(PyCFunction_Check(func) || PyObject_TypeCheck(func, __pyx_CyFunctionType))) {
#else
if (likely(PyCFunction_Check(func))) {
#endif
if (likely(PyCFunction_GET_FLAGS(func) & METH_O)) {
// fast and simple case that we are optimising for
return __Pyx_PyObject_CallMethO(func, arg);
#if CYTHON_FAST_PYCCALL
} else if (PyCFunction_GET_FLAGS(func) & METH_FASTCALL) {
return __Pyx_PyCFunction_FastCall(func, &arg, 1);
#endif
}
}
return __Pyx__PyObject_CallOneArg(func, arg);
}
```
is confusing *bound* and *unbound* methods. In particular, it can …
> Don't use __Pyx_PyObject_CallMethO on cyfunctions

- Cython/Compiler/ModuleNode.py
- tests/cygwin_bugs.txt
This is meant to fix the `module_api` Cython test on Cygwin and help with various bugs in SageMath, such as https://trac.sagemath.org/ticket/21459
@embray Please test on Cygwin.
> Do not use special dll linkage for "cdef public" functions

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Parsing.py
- tests/run/complex_numbers_T305.pyx
Complex values are not currently evaluated at compile time at all because they are stored as strings but used like floats.
Based on #1777 (first three commits).
> Repair compile time complex expressions

- Cython/Compiler/ParseTreeTransforms.py
- tests/run/reduce_pickle.pyx
Fixes #1786.
This is a quick-and-dirty way to do it and would still conflict with a class named `__pyx_result`, so there may be a better way (I honestly didn't look that hard). 
I also didn't add a change note.
> Don't conflict with a class named 'result' in auto-pickle

- Cython/Compiler/Parsing.py
- tests/run/ct_IF.pyx
Fixes #1796 
Since this is a backwards incompatible fix that might introduce hard to detect bugs on user side, I nominate it for the next major release instead of a bug-fix release.
> Do not evaluate DEF statements inside of IF blocks with false condiions

- Cython/Includes/posix/stat.pxd
This is available on OS X, FreeBSD and NetBSD. On Linux, the definition
itself will not result in any errors. However, code that does attempt to
st_birthtime under Linux will now fail at C compile time rather than
Cython compile time.
> Add st_birthtime to struct stat

- Cython/Includes/cpython/set.pxd
Both were added in Python 2.6 so should be available for all supported Python versions.
> Include PySet_Check and PyFrozenSet_Check to CPython includes file

- Cython/Utility/Profile.c
The code right now creates a frame containing a reference to f_globals in f_locals. This is because of
https://github.com/python/cpython/blob/2.7/Objects/frameobject.c#L732
If a profiler accesses `frame.f_locals` (from python) it will trigger 
`frame_getlocals` https://github.com/python/cpython/blob/02e03672e6766b1da847b1635982a70346780744/Objects/frameobject.c#L56
`PyFrame_FastToLocals` https://github.com/python/cpython/blob/02e03672e6766b1da847b1635982a70346780744/Objects/frameobject.c#L867
which will call `map_to_dict` with (pseudocode)
`map_to_dict(f.co_code.co_varnames, len(f.co_code.co_varnames), f.f_locals, f.f_localsplus, 0)`
which will remove everything from f_locals which is also in `f.co_code.co_varnames`.
As f_locals == f_globals in the current setup that modifies the global …
> Pass am empty dict instead of a f_globals reference to profilers.

- Cython/Includes/numpy.pxd
- tests/run/numpy_subarray.pyx
Changes include:
- Added the PyDataType_HASSUBARRAY macro
- Added the new NPY_DATETIME and NPY_TIMEDELTA entries to NPY_TYPES
- Added the "kind" and "subarray" fields to the dtype class
Additional work could be done to expose the datatime metadata, but
non-performance users can already get at that data using the pure
python numpy.datetime_data function.
Author: Gerald Dalley
> allow inspection of the data used by PyArray_EquivTypes

- Cython/Compiler/Nodes.py
- Cython/Compiler/Options.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Shadow.py
- tests/run/annotation_typing.pyx
- tests/run/extern_impl_excvalue.srctree
Inside of a module, it is safe to convert a function declared
```
cdef int func() except *:
...
```
into
```
cdef int func() except? -1:
...
```
because a) we need an exception return value anyway and b) there will always be an explicit exception check afterwards. Thus, changing the function implementation itself is safe.
Changing the function declaration and its calls is only safe if we can be sure that we changed the function signature, though. This requires control of the function implementation. We must exclude functions that are only declared but not implemented since we do not control their signature and it is not safe to assume a specific exception return value if it is not declared.
The implementation also excludes methods, as they might have to match a parent method (if …
> Attempt to use a faster exception value for return type annotations that check for exceptions

- Tools/rules.bzl
Ensure additional arguments, like visibility, can still be applied to pyx_libraries.
> Pass pyx_library kwargs to py_library

- Cython/Utility/Coroutine.c
- Cython/Utility/TypeConversion.c
- tests/pypy_bugs.txt
- tests/run/test_coroutines_pep492.pyx
Here are some more fixes to improve pypy{,3} support.
Note that the `gc.collect(); exec('')` trick in getrefcount() could probably be generalised to any test that tries to check refcounts.
> More pypy3 fixes

- Cython/Compiler/ModuleNode.py
- Cython/Utility/ModuleSetupCode.c
- runtests.py
- tests/bugs.txt
This is a hack to re-enable PEP-489 support while enforcing single module execution. It the module exec function is run more than once, it would otherwise overwrite and recreate the entire module state, lose lots of references and probably just crash.
> Enforce single module initialisation despite PEP 489 allowing to re-execute a module

- Cython/Utility/CythonFunction.c
__Pyx_Method_ClassMethod() used a hack on PyPy that relied on bugs in cpyext. The bugs have been fixed for the upcoming 5.9 release, which broke classmethod creation. This patch, together with the addition of `PyMethodDescr_Check` to pypy's C-API, fixes it.
Can you please include it in 0.27.1?
> Fix classmethod creation for (upcoming) PyPy{,3} 5.9

- .travis.yml
- Cython/Utility/ModuleSetupCode.c
- Demos/embed/Makefile
- runtests.py
- tests/travis_macos_cpp_bugs.txt
Summary:
* Fixed minor issues in the testsuite and runtest script.
* Update `CYTHON_FALLTHROUGH` to works with old Apple Clang.
* Extend Travis-CI build matrix to macOS using Anaconda Python (Miniconda).
Details:
* The macOS build matrix uses Python 2 for now and test dependencies are not installed for the runs to finish as quickly as possible (the macOS build infrastructure is slower than the Linux one). It should be trivial to add Python 3 and/or test dependencies.
* I'm using the oldest macOS image available in Travis-CI, which is the same image currently used by conda-forge builds. Newer images (maybe newest?) could be added to the build matrix, however this would delay even further the builds to finish (Travis-CI macOS workers are always under pressure).
* It took me quite a while to …
> Travis-CI: Setup macOS builds

- Cython/Utility/ModuleSetupCode.c
@scoder I think you forgot this bit. Is this fix OK with you?
PS: Also, add the the `(void)something;` trick to your pocket.
> PyPy3: Register module cleanup with atexit

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Pythran.py
- Cython/Compiler/TypeInference.py
In the moment, the pythran objects get converted into "normal" python objects in the last assignment in each line and copied back into pythran when used in the next line.
This PR fixes this by:
* adding pythran objects to the safe objects
* adding support for pythran in cmp and index during type interference
* added proper support for pythran in assignments
This was done during a sprint together with @scoder.
On a small benchmark on one of the numpy_pythran tests, a speed improvement of ~15% could be achieved (but this was just a small test).
> Type inference for Pythran expressions

- Cython/Utility/Exceptions.c
Closes #1955 
CPython change how the exception information is stored internally in
3.7a3.
This simply adds fences based on python version around how to access
the objects.
Xref:
https://github.com/python/cpython/commit/ae3087c6382011c47db82fea4d05f8bbf514265d
https://bugs.python.org/issue25612
https://github.com/python/cpython/pull/1773
> FIX: account for change in how exception information is stored

- tests/run/annotation_typing.pyx
`ctypes_def` test in ``annotation_typing`` did check againt `pytypes_def` instead of `ctypes_def` @scoder
> Fix annotation_typing test case

- Cython/Includes/cpython/pythread.pxd
- Cython/Utility/ModuleSetupCode.c
- tests/run/tss.pyx
For https://github.com/cython/cython/issues/1932
> [WIP] Add TSS (Thread Specific Storage) API in CPython 3.7+

- Cython/Compiler/Nodes.py
- Cython/Includes/numpy/__init__.pxd
- tests/buffers/userbuffer.pyx
* Rework check for `view==NULL` required for legacy Python 3 releases.
* Handle redefined `struct Py_buffer` in user code (e.g. mpi4py).
> Update implementation of PEP 3118 getbuffer special method

- docs/src/reference/language_basics.rst
1. Clearly mention that type checks for builtin types (`cdef str`) require the exact class, not a subclass.
2. Move the section about optional and keyword-only arguments to the "Functions and Methods" section where it belongs.
3. Many small fixes.
This doc is still far from perfect, but I hope that this PR is a strict improvement.
@embray
> Improve typing doc

- Cython/Compiler/ExprNodes.py
- Cython/Includes/libc/limits.pxd
- tests/run/fstring.pyx
```
from libc.limits cimport LONG_MAX
print(f"{LONG_MAX}")
```
currently gives `-1` on a 64-bit system because Cython thinks that `LONG_MAX` is of type `int`.
This requires #2020.
> Fix types of values in libc.limits

- Cython/Compiler/ExprNodes.py
This should be allowed:
```
cdef extern from *:
const long N
cdef int arr[N]
```
This is required to fix a testcase in #2016.
> Treat entries with constant type as constant

- docs/src/reference/extension_types.rst
- docs/src/userguide/special_methods.rst
In the docs, mention `__eq__` and friends and `__richcmp__` as two alternatives without preferring any of the two ways.
> Undeprecate __richcmp__

- Cython/Compiler/Nodes.py
- Cython/Utility/ExtensionTypes.c
- tests/run/cdef_multiple_inheritance_errors.srctree
- tests/run/cdef_multiple_inheritance_nodict.pyx
If none of the base classes has a `__dict__` slot (i.e. `tp_dictoffset` is 0), then it is safe to inherit from those with a `cdef class` without a `__dict__`. Unfortunately, we cannot check this condition at compile-time so it must be done at run-time.
Since we are adding run-time checks anyway, we also verify that the base types are actually heap types.
> Allow multiple inheritance without __dict__

- Cython/Compiler/Nodes.py
- tests/run/staticmethod.pyx
This fixes some `-Wstrict-prototypes` warnings
> C functions without args should be declared as f(void)

- docs/src/tutorial/strings.rst
The memory management has nothing to do with which character encoding was used. Furthermore, this paragraph was very confusing for someone like me who just wanted to tell Cython that all strings are in UTF-8.
> Rewrite documentation paragraph on automatic string encoding for clarity

- Tools/cython-mode.el
Emacs lisp packages are often distributed by themselves, so it
is important to specify the license in the Elisp library itself.
> Specify license in cython-mode.el's header

- Cython/Utility/ModuleSetupCode.c
- tests/run/cyfunction.pyx
- tests/run/pure_py.py
In plain Python 3, there is no "unbound method" type, an unbound method is just the function in the class `__dict__`:
```python
In [1]: class P:
...:     def meth(self): pass
In [2]: P.meth
Out[2]: <function __main__.P.meth>
In [3]: P.meth is P.__dict__["meth"]
Out[3]: True
```
In Cython, unbound methods instead become instancemethod objects:
```cython
In [3]: %%cython
...: cimport cython
...: cdef class X:
...:     @cython.binding(True)
...:     def meth(self): pass
...: class Y:
...:     def meth(self): pass
In [4]: X.meth
Out[4]: <instancemethod meth at 0x3fff79e0a7c8>
In [5]: Y.meth
Out[5]: <instancemethod meth at 0x3fff7a7bbd38>
```
This uses [PyInstanceMethod_New](https://docs.python.org/3.6/c-api/method.html). That seems wrong because the docs say that this is meant for a …
> In Python 3, an unbound method is just a function

- docs/src/userguide/debugging.rst
At least on Ubuntu, if you don't have `python-numpy-dbg` then you get an import error for `multiarray_d.so`, which is only in numpy debugging. thanks!
> DOC: BUG: suggest install numpy debugging

- docs/src/userguide/extension_types.rst
Hi,
I tried to compile the `OwnedPointer` at http://docs.cython.org/en/latest/src/userguide/extension_types.html#c-methods
It failed to compile telling me that special methods must be declared with 'def', not 'cdef'.
Thanks
> documentation __dealloc__ should be def not cdef

- docs/src/tutorial/numpy.rst
When using google to search for how to use numpy and cython, users find themselve on the `Working with NumPy` page, with the old interface to the numpy arrays. 
Nothing to tell them that there is a more recent interface (Typed Memoryviews). 
I added a note at the top of the page to mention the existence of Memoryviews.
> Mention Typed Memoryviews in the Working with NumPy doc.

- docs/src/quickstart/build.rst
- docs/src/quickstart/install.rst
Hi! I tried to add some clarifications to the build page in the quickstart. Also, I added mention of setuptools. Do you want to keep it?
Also for futures PR on the docs, should I try to replaces the examples using distutils by setuptools?
I see on on the distutils docs:
>Most Python users will not want to use this module directly, but instead use the cross-version tools maintained by the Python Packaging Authority. In particular, setuptools is an enhanced alternative to distutils that provides...
>It is currently recommended as a more regularly updated alternative to distutils that offers consistent support for more recent packaging standards across a wide range of Python versions.
I have no preferences. It's just to know if I should mention setuptools/replace distutils in the examples/ …
> Improvements of the docs.

- docs/src/quickstart/install.rst
I think it's not a big change, but it makes more sense to put the prefered way of installation first.
> Put the pip installation first.

- docs/src/userguide/language_basics.rst
changes the text "may or be not be" to "may or may not be"
> Fix one word typo

- Cython/Compiler/ModuleNode.py
PyPy had a bug that the ``tp_basicsize`` of ``PyType_Type`` was wrong. From the next release, this will be fixed. The pull request pins the work-around to previous versions of PyPy
> COMPAT: From the next release PyPy fixed tp_basicsize of PyType_Type

- Cython/Compiler/ExprNodes.py
- tests/run/fused_types.pyx
Currently, when `NULL` and a fused type are passed to [ExprNodes.coerce_to](https://github.com/cython/cython/blob/master/Cython/Compiler/ExprNodes.py#L807), the compiler throws the following error:
```
...
char
wchar_t
ctypedef c_char* c_string
cdef c_string check_ptr(c_string ptr) except NULL:
^
test.pyx:9:43: Cannot coerce to a type that is not specialized
```
However, this error is a false positive; `NULL` is assignable to any pointer type, and `c_string` is a pointer type. This PR avoids the false positive by explicitly allowing `NULL` to be coerced to a pointer to a fused type.
The only example I know of in which this error is thrown …
> Allow `NULL` to be coerced to a pointer to a fused type

- Cython/Includes/libcpp/string.pxd
- tests/run/cpp_stl_string_cpp11.pyx
Adds the C++11 functions `front()` and `back()` to `std::string`, as well as unittests for functionality.
> Patch to add front() and back(), as per issue #2123.

- docs/src/quickstart/build.rst
- docs/src/reference/compilation.rst
Credit goes to @ibell for his PR #2119 .
Lines are long because of the table. It's because restructuredtext had a hard time recognizing things like `-+` as a valid argument. I could have made a full table with all the separators, but it would have made the `.rst` file very verbose.
> Added %%cython options.

- docs/src/quickstart/build.rst
- docs/src/reference/compilation.rst
- docs/src/userguide/sharing_declarations.rst
This adds a recommendation of including zip_safe=False to the
userguide/sharing_declarations.rst documentation.
Because cimport will not load pxd definitions from a zipped egg file and
the default format when installing from a source package using
"python setup.py install" is to create a zipped egg, including this
option will guard against this error when people install this way.
> Add zip_safe=False to userguide setup.py

- Cython/Includes/libcpp/unordered_map.pxd
Hi.
This PR improve the API provided by `libcpp unordered_map`.
I only add `reserve` and `bucket_count` to the  API cause it was needed on my side. But there is other missing functions. Let me know if you prefer a patch with the exhaustive API.
> Improve libcpp.unordered_map API

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Symtab.py
- docs/src/userguide/wrapping_CPlusPlus.rst
- tests/run/cpp_operators.pyx
- tests/run/cpp_operators_helper.h
- tests/run/libcpp_all.pyx
This allows non-member operators to be specified with cppclasses, and ensures they're looked up correctly when used.
```
cdef extern from "somefile.hpp":
cdef cppclass C:
C operator+(int, const C&) # this line now creates something usable
C operator*(int const C&)
```
The reason this is useful is because, although non-member operators could be defined outside the class (as shown for operator*, above) they aren't easily accessible when cimporting for .pxd files (which is probably a separate bug).
Looking at the C++ standard library wrappings, people seem to have assumed that this method of wrapping non-member operators already works and written operators in this form.
I've also defined appropriate tests, and updated the documentation.
> Allow C++ operator declarations outside of classes

- Cython/Build/Dependencies.py
- Cython/Build/Tests/TestCyCache.py
- Cython/Compiler/Main.py
I made the section that drops options quite verbose because it took me a while to
figure out whether an option should be included or not. I hope I got everything
right.
Closes #1397.
> Relevant options/directives must go into the cache fingerprint

- Cython/Includes/libcpp/list.pxd
- tests/run/cpp_stl_list.pyx
Add `size_type` and `difference_type` to `std::list` and add initial unittests specific for `std::list`.
> Bug fixes for STL lists.

- docs/src/userguide/language_basics.rst
Added a mention of C99's variable lenght arrays in Cython.
fixes #2069
> Clarified cython's capabilities about C99's VLA.

- docs/src/reference/language_basics.rst
- docs/src/tutorial/pxd_files.rst
- docs/src/userguide/language_basics.rst
Migration of **Cython file types** into the useguide. 
I kept the section **the include statement** which was already there and renamed it **The include statement and include files**. 
The part **cimport** wasn't transferred because there is already a nice section on it in `sharing_declarations.rst`. I make reference to it two times.
> Transfered the Cython file types in the userguide.

- docs/src/userguide/language_basics.rst
It was mostly copy pasting of what was in the reference guide. 
I corrected some syntax error with the `:` missing in the examples.
> Transfered overriding in extension types.

- docs/src/userguide/language_basics.rst
Copy pasting and also extended the examples.
> Transfered keyword only arguments.

- Cython/Compiler/Optimize.py
- Cython/Utility/Optimize.c
- Cython/Utility/TypeConversion.c
- tests/compile/buildenv.pyx
- tests/run/pyintop.pyx
By accident, the existing special int object handling code was not used when the result of a comparison was already known to be of type bint (instead of a Python object), nor for the "!=" operator.
It now has a dedicated implementation for (in-)equality.
> Further optimise int/float comparison

- docs/src/reference/language_basics.rst
- docs/src/userguide/language_basics.rst
I replaced all the text in the language basics of the reference guide by links to the corresponding places in the user guide. No information has been lost except for those two lines:
```
Function Pointers
=================
Functions declared in a ``struct`` are automatically converted to function pointers.	
see **using exceptions with function pointers**	
```
Since **using exceptions with function pointers** doesn't exist yet, I suppose we don't loose much.
> Replace text with links

- docs/src/userguide/special_methods.rst
The note comes from `reference/extension_types.rst` section **Initialization: __cinit__() and __init__()**
At the same time, I noticed that a note that was already there wasn't rendered because of a bad formatting. I fixed it.
> Transfered a note from the reference guide extension types to the userguide.

- docs/src/tutorial/array.rst
- docs/src/tutorial/pure.rst
- docs/src/userguide/extension_types.rst
- docs/src/userguide/external_C_code.rst
- docs/src/userguide/fusedtypes.rst
- docs/src/userguide/language_basics.rst
- docs/src/userguide/limitations.rst
- docs/src/userguide/sharing_declarations.rst
- docs/src/userguide/wrapping_CPlusPlus.rst
I just changed the print function here and there so that people using python 2 and 3 can both copy-past the example to try them without having to change anything.
> Made code examples in the docs compatible with python 2 and 3.

- docs/src/userguide/extension_types.rst
- docs/src/userguide/special_methods.rst
A common use case for extension types is to instantiate them from existing C/C++ pointers without copying. The documentation is not very clear on how to do this - there is a mention of 'factory function' in [extension type reference documentation](http://cython.readthedocs.io/en/latest/src/reference/extension_types.html?highlight=factory) but no example.
This is one of the most frequently asked questions on Q/A forums and websites like stack overflow with many new users struggling to get this right the first time, or why it doesn't work for extension types from pointers but does for extension types from native types. I also struggled with this when first starting to use Cython.
This example should help with this common question. The example code works as-is and can be compiled directly …
> [Docs][Ready for Review] Added documentation on extension class instanciation from existing pointer

- runtests.py
`--root-dir` had the same description as `--work-dir` in the command line options for running the tests. I corrected it.
> Corrected the description of a test option.

- docs/examples/memoryviews/C_func_file.c
- docs/examples/memoryviews/C_func_file.h
- docs/examples/memoryviews/memview_to_c.pyx
- docs/src/userguide/memoryviews.rst
- runtests.py
I added tests for the examples directory. For the moment it only covers the memoryview tests. 
I would like some feedback on the approach and if it's good, I'll enable more tests for files in the examples directory.
I added a else close when checking the value of `mode` because I think it'll more clear for people who are getting into the `runtests.py` (I know I wanted a compile test, so I looked for the string 'compile' and it took me a while to figure out where the mode was tested).
> Added tests for the convolve with the memoryviews in the docs.

- pyximport/pyximport.py
- runtests.py
- tests/pyximport/pyximport_namespace.srctree
Python 3.3 added in support for namespace packages which are essentially directories with no `__init__.py` file. This pull request adds in support for these into pyximport.
On python2 trying to import a pyx module in a namespace package is still an error (which matches normal python behavior). 
Note that the regtest only works on python3. Not sure how to adjust it for python2 but happy to update this pr if somebody can point me in the right direction...
-- PG
> Fix importing of namespace packages. Add in a regtest for the same.

- CHANGES.rst
- Cython/Compiler/ExprNodes.py
- tests/compile/builtinbuffer.py
This fixes issue #2046 
The underlying issue was that _analyse_name_as_type was not considering either the builtin scope, or other types than extension types. Py_buffer happened to be a builtin type that was a C struct.
> Fix purepython builtin type strings

- runtests.py
The variable is declared again in the `runtest` function, I think this is where the error came from.
> Removed the unused variable "WORKDIR" from runtests.py.

- runtests.py
The variable `source` is declare afterwards, in the `if` and the `else`.
> Removed an unused variable.

- runtests.py
In https://www.python.org/dev/peps/pep-0008/#other-recommendations it says that it's recommended to unpack (expand?), anyway, write on 4 lines the try...except instead of using two lines.
> Formatted runtests.py to make it respect the pep8 conventions of try...except.

- docs/src/reference/compilation.rst
A note in the `userguide/source_files_and_compilation.rst` states:
```
.. note:: See :ref:`compilation-reference` reference section for more details
```
and links to the reference guide.
But  `userguide/source_files_and_compilation.rst` was the file with the most information on pyximport. I fixed it.
Maybe replacing `userguide/source_files_and_compilation.rst` by `reference/compilation.rst`  would make sense  since `reference/compilation.rst` is the only file in the reference guide which is not empty? This way the reference guide would be entirely empty with just links to the userguide.
> Added more info on pyximport in compilation.rst

- docs/examples/userguide/buffer/matrix.pyx
- docs/src/userguide/buffer.rst
As extend doesn't exist for vectors, replaced it by a resize. This is where automatic testing shines.
> Added tests to "Implementing the buffer protocol" part 1

- docs/examples/tutorial/pure/exceptval.py
- docs/src/tutorial/pure.rst
It allowed me to find a small syntax error: there was a colon after the decorator.
> Adding tests for "pure python mode" part 10

- docs/examples/tutorial/string/cpp_string.pyx
- docs/src/tutorial/strings.rst
There was a bug in the example. The string is stack allocated, so there was no need to call `del` on it. The C++ compiler was complaining, so I removed it.
> Adding tests for "Unicode and passing strings" part 10

- tests/run/posix_time.pyx
On x32, tv_sec and tv_usec are in fact long long rather than the standard long,
and so in Python 2.x are automatically converted to Python longs, causing the
test to fail with:
Failed example:
test_itimer(10, 2)
Expected:
(10, 2)
Got:
(10L, 2L)
To fix this, we should explicitly call the int constructor.
> Fix test_itimer on x32

- runtests.py
- tests/run/simpcall.pyx
I think it was just a small mistake because the mode `test` was only used in one file and in `runtests.py` is treated like the mode `compile`. 
Since this file has docstrings, I think mode: `run` is more appropriate.
> Removed the mode "test" for the tests because it's not a real test mode.

- docs/conf.py
It's nothing major, it was just an annoying warning when building the docs.
> Avoid being redirected every time the doc is being built.

- Cython/Build/Dependencies.py
- Cython/Compiler/Main.py
- Cython/Utils.py
- tests/build/cythonize_cython.srctree
1) unifies handling of "cython cython.pyx" and "cythonize cython.pyx" - both raise an error now.
2) makes the check robuster, also "cythonize xxx/cython.pyx" fails now.
Fixes #2422
> fixes #2422

- docs/src/tutorial/strings.rst
Mentioned in the docs that converting a python bytes string to char* gives a null terminated string.
Fix #2421
> Small mention in the docs about bytes strings conversion.

- docs/src/tutorial/clibraries.rst
- docs/src/tutorial/cython_tutorial.rst
- docs/src/tutorial/external.rst
- docs/src/tutorial/pure.rst
- docs/src/tutorial/strings.rst
- docs/src/userguide/extension_types.rst
- docs/src/userguide/pypy.rst
- docs/src/userguide/wrapping_CPlusPlus.rst
The doc has many sentences starting by 
> Since Cython 0.xxxxx
or 
> Since version 0.xxxxx
I think the ones that are too old are not useful for the readers. I would like too remove all mentions of Cython versions below 0.xxx but I don't know what this xxx should be. 
Any idea?
> Removed mention of a version so old that nobody should be concerned.

- docs/src/reference/compilation.rst
- docs/src/userguide/source_files_and_compilation.rst
The text in the userguide and the reference guide are really close for `pyximport`. Since @scoder reviewed recently the description of pyximport in the reference guide, I think it is worth removing duplication and redirect to it. 
It also keeps the section "Source file and compilation" short and makes it easy to have an overview of the possible means of compilation. And I think it's the spirit of this section compared to the "Compilation" section in the reference guide which is more "fat" and has a lot more details about everything.
> Removed some text duplication and redicted for pyximport.

- docs/src/reference/compilation.rst
I think that it wasn't clear enough in which case the user needed to compile with numpy header files.
> Added a note on the compilation with numpy to avoid confusion.

- Cython/Includes/libcpp/forward_list.pxd
- tests/run/cpp_stl_forward_list.pyx
Added preliminary support for `<forward_list>` which is a lightweight, singly-linked list, a C++11 feature.
> Added support for C++11's <forward_list>.

- Cython/Build/Dependencies.py
- docs/src/reference/compilation.rst
This PR uses autodoc to pull the docstring of cythonize in the documentation, thus removing duplicates.
This PR requires #2180 to be fixed before being merged.
> Moved the cythonize description from the docs to the docstring.

- docs/src/userguide/parallelism.rst
I added the autodocs style formatting to the `prange` function. 
I think it makes it easier for users to jump to the information they are looking for.
The were only a few lines of text added to describe start, stop and step. The rest was just moving the text around.
If you want a preview of the result:
> Changed the organisation of prange.

- docs/examples/userguide/fusedtypes/char_or_float.pyx
Maybe there is something obvious that I'm missing, but I don't see why it is necessary to declare those types like `cython.char`.
> Simplified the first example of fused types.

- docs/src/reference/index.rst
Those pages still exist, so we shouldn't have any dead link issues with this PR.
> Removing oudated pages from the table of content in the documenation main page.

- Cython/Compiler/Options.py
- docs/src/reference/compilation.rst
Not all the options are there, I only put the main ones. The ones not included are `old_style_globals` and `pre_import`. 
Maybe in a perfect world, those options would be arguments of a function (`set_options(docstrings=True,...)` or something like that) and then we would use autodoc? It's just an idea.
> Added the docs for the compiler options.

- tests/windows_bugs.txt
Following up on #2327 
I'm not a big user of windows, so everything I'm saying is guesses and stuff I found online.
The bug message was the following:
```
[00:09:23]    Creating library C:\projects\cython\TEST_TMP\6\clibraries\c\queue2\queue2.cp36-win32.lib and object C:\projects\cython\TEST_TMP\6\clibraries\c\queue2\queue2.cp36-win32.exp
[00:09:23] queue2.obj : error LNK2001: unresolved external symbol _queue_new
[00:09:23] C:\projects\cython\TEST_TMP\6\clibraries\c\queue2\queue2.cp36-win32.pyd : fatal error LNK1120: 1 unresolved externals
```
At first glance, I though the mistake was 
https://github.com/cython/cython/blob/09e9b502f63ecc966635fedadb84f3a40fe18925/docs/examples/tutorial/clibraries/cqueue.pxd#L3
Because it didn't use backward slashes like on windows paths. After some …
> docs: Fixed tests under windows.

- CHANGES.rst
- Cython/Includes/numpy/__init__.pxd
In the discussion of issue #2498, it seems cython uses direct access of ndarray structure base attribute in `set_array_base` and `get_array_base`. This bypasses much of the NumPy error checks, and can lead to violating assumptions NumPy makes as to the correctness of the base attribute.
This PR refactors the functions to use NumPy APIs. I am not sure it is correct, I could find no tests for the functionality, and truthfully struggle to see when these functions could be properly used. I would prefer to deprecate them.
NumPy uses the base attribute internally when 
- creating a view by sharing the data attribute of both self and base, or 
- in creating temporary buffer data in ufuncs via writeback semantics. 
The simple code in these functions does none of the data attribute manipulations …
> WIP: MAINT: avoid numpy internals in {sg}et_array_base

- Cython/Includes/cpython/mem.pxd
- Cython/Utility/ModuleSetupCode.c
In Python 3.4+, Raw memory helper functions were added to wrap, track, and check `malloc` and `free` calls for C memory outside of the GIL. These have the same API as the existing `PyMem_*` calls except they use Raw and never require the GIL. For Python 2/3 compatibility, export the existing `PyMem_` functions on Python 2 as `PyMem_Raw` where they act basically equivalently. These are especially important as Python 3.6 changed the existing `PyMem_` functions to allocate from pymalloc instead of the C allocator meaning the GIL must now be held with them. So these are Python 2/3 alternatives that can be relied on to not require the GIL.
> Add Python Raw memory helper functions

- Cython/Includes/numpy/__init__.pxd
Allows users to get the underlying `typeobj` (e.g. `numpy.float64`) from the `dtype`.
ref: https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.types-and-structures.html#c.PyArray_Descr
ref: https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.types-and-structures.html#c.PyArray_Descr.typeobj
> Add `typeobj` to `dtype`

- docs/README
- docs/make.bat
Added how to build the docs in the readme and added a make.bat for building the docs on Windows.
I took the make.bat from another github repository.
I tested the make.bat with the option `html` and `linkcheck`. Both worked fine. I suppose that it should work too with other options.
> Added a make.bat to be able to build the docs on Windows too.

- docs/src/userguide/source_files_and_compilation.rst
Copy-pasting from `reference/compilation.rst`.
> Moving the compiler options into the source files and compilation.

- docs/src/userguide/source_files_and_compilation.rst
Except for the small overview of ``cython`` and ``cythonize``, it was just copy-pasting.
> Moved the Cythonize section in the userguide.

- .travis.yml
- Cython/Build/Dependencies.py
- Cython/Compiler/ModuleNode.py
- Demos/overflow_perf_run.py
- runtests.py
- test-requirements.txt
- tox.ini
Maybe this should be discussed on the Cython dev mailing list. Even so, I'll open the PR so that we have some code, as a basis to discuss.
As someone who is knowledgeable in Cython but not a Cython developer, I'm in a good position to say that formatting could help reading this codebase for newcomers, especially when files are commonly made of thousands of lines.
I believe that it should be possible to contribute to Cython without having a brain that is the size of a planet, or without spending dozens of hours understanding the control flow with a debugger, because the project have already a very good structure.
Maybe this can start by a bit of formatting (I also would like to make a "For Cython dev" section in the documentation, with quite more info than in the Wiki, but that will be for …
> Gradually enabling PEP8 checks on Travis ci.

- docs/examples/tutorial/pure/cclass.py
- docs/src/tutorial/pure.rst
It seems that this one is failing.
From the output, it seems that Cython generate incorrect code when using a initial value for an attribute with `cython.declare`.
What should we do?
> Adding tests for "pure python mode" part 13

- Cython/Compiler/ModuleNode.py
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
Second pull request for #2534.
Compute the offset of the PyFrameObject member "f_localsplus" at runtime,
because the layout of PyFrameObject differs between regular C-python and
Stackless Python.
> make __Pyx_PyFunction_FastCallNoKw compatible with Stackless Python

- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
This is the first pull request related to #2534.
Add METH_STACKLESS to the bit mask used to test the call signature. If METH_STACKLESS is not defined in the Python headers, this patch is a NOOP.
I'm currently not sure, how to write a test case. Obviously it would require Stackless Python (METH_STACKLESS is always unset in regular C-Python). Without this patch tests for a fast-call method be false negative. As far as I understand the generated C-code, this affects performance only.
> make the fast-call signature test compatible with Stackless Python

- Cython/Shadow.py
This lambda is assigned to multiple names, so the fold attribute would be copied to all those names.
> Fix overflow.fold being available on most directives in pure python mode

- docs/src/userguide/language_basics.rst
Ctuples have been present for a while but not documented. 
Hopefully this helps to address issue #2574.
> Added basic ctuple documentation.

- Cython/Compiler/ExprNodes.py
- tests/run/slice2.pyx
- tests/run/typed_slice.pyx
Patch and associated unittests for issue #2508.
Apologies for the overly long wait for this PR - I spent entirely too much time attempting to reverse engineer and brute-force the Cython compilation internals instead of taking the time to understand the various hooks. Feedback appreciated.
> Support two-element slicing with literal None

- Cython/Build/Inline.py
- Cython/Build/Tests/TestInline.py
- tests/run/test_fstring.pyx
Support for user-supplied compiler directives to `cython_inline()` via a new `cython_compiler_directives` argument.
> cython_inline compiler directives support

- docs/src/userguide/wrapping_CPlusPlus.rst
Explicitly call out the different name used for the wrapper `.pyx` file vs. the other C++ sources
As a new user, I was following along and just called the `.pyx` file `Rectangle.pyx` like everything else which was kinda confusing then when in the `wrapping_CPlusPlus/setup.py` there's a `setup(ext_modules=cythonize("rect.pyx"))` and I was thinking that maybe that file was magically created somehow and was miffed.
Hoisted the blurb on why the file name needs to be different without some additional work and worded it in there.
> Call out the different name used for the wrapper

- tests/run/check_size.srctree
Beginning of a PR to work on #2221.
The first step is to add tests for the "binary incompatibilty" check. ~How do I get the test to pass? I need to build a module around the header file added in commit 2eb0fe2 before starting the test, so I can play with the `tp_basicsize` field. Any hints? If I add a C file with the module init code, how will it get compiled for the test?~
Edit: using `check_size.srctree` to build the module and tests
Edit2: make sure this does not close #2221
> TEST: add test for 'binary incompatibility' warning

- runtests.py
srctree tests may invoke multiple commands. If one fails, print out all the commands, stdout, and stderr. This is helpful when debugging. Print statements can be used to reveal state during the successful first steps that cause later steps to fail.
> MAINT: if subtree test fails, print out all stdout, stderr not just last

- docs/src/userguide/extension_types.rst
- docs/src/userguide/external_C_code.rst
- tests/run/ext_attr_getter.srctree
Before approaching the changes needed to enable getter aliasing for external extension types (issue #2498 and the proposed [solution](https://github.com/cython/cython/issues/2498#issuecomment-414543549), I propose documenting the existing attribute aliasing.
I couldn't find the feature documented elsewhere. Is this the right place/way to do it?
It also seems that `extension_types.rst` is getting long, should it be split into shorter pieces?
> DOC, TST: test and document external extension type attribute aliasing

- CHANGES.rst
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/Parsing.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
- Cython/Utility/ImportExport.c
- docs/src/userguide/extension_types.rst
- runtests.py
- tests/run/check_size.srctree
Address #2221 by adding a new `check_size` clause to `ctypedef class` definitions. This will allow suppressing the warning.
The srctree test actually comprises a few tests, but they are reported as one pass/fail. I am not sure how to break them into separate tests.
I think 'min', True, and False were the proposed values, but maybe I misunderstood.
>  ENH: add check_size option to ctypedef class for external classes 

- CHANGES.rst
- Cython/Compiler/Main.py
- Cython/Compiler/Options.py
- Cython/Compiler/Parsing.py
- tests/run/cython3_no_unicode_literals.pyx
Remove the new 'str_is_str' directive again and replace it by a new "language_level=3str" that resembles "language_level=3" but keeps unprefixed string literals and the 'str' builtin type unchanged.
See #2565.
> Add new "language_level=3str"

- Cython/Build/Dependencies.py
The message
```
Please put "# distutils: language=%s" in your .pyx or .pxd file(s)
```
is not so clear: it doesn't make it clear that it's just a warning and it doesn't mention what precisely is being deprecated. Without the Cython sources, I wouldn't have guessed. (I saw this message while compiling some other project)
> Improve message for deprecated "language=..." option

- Cython/Compiler/CmdLine.py
Looks like CmdLine.py needed the new '3str' language_level mode as a parameter?
> Add --3str command line option to 'cython' program

- Cython/Compiler/Parsing.py
- tests/run/cython3_no_unicode_literals.pyx
Allow non-ASCII string literals like `"μ"` when language_level=3str.
> Only error out for non-ASCII literals on actual bytes literals

- Cython/Compiler/Nodes.py
- tests/run/line_trace.pyx
Previously, this jumped to the error label of the try-statement, whereas it must target the outer error label instead.
Closes #2274.
> Correct the handling of line tracing errors on try-statements.

- Cython/Utility/MemoryView_C.c
- tests/memoryview/gh2588.pyx
Closes #2588 
Issues working on at PyConDE sprint.
Stop generate codes that will be skipped by the compiler (for example `if (0 && …`)
> Fix stop generating code that compiler skips

- .gitignore
- Cython/Utility/Buffer.c
- tests/run/numpy_test.pyx
Fixes #2675.
Currently, the `cast=True` argument is needed when writing functions with `ndarray` parameters of type `npy_bool`, like so:
```
def foo(np.ndarray[np.npy_bool, ndim=1, cast=True] npdata):
return npdata
```
Without `cast`, any such function will always raise a `ValueError`:
ValueError: Does not understand character buffer dtype format string ('?')
The code in this PR removes the need for the `cast` keyword.
This fix puts support for `ndarray` parameters of type `npy_bool` at the same level as support for parameters of the other `npy_` types (eg `npy_long`, `npy_float`, etc). The fix was accomplished by adding a `'?'` case to a few case/swtich statements in `Buffer.c` from which it was missing.
> Fix support for functions with ndarray parameters of type npy_bool

- CHANGES.rst
- runtests.py
When running srctree tests, they run under a separate process. It is sometimes convenient to add a `import pdb;pdb.set_trace()` breakpoint inside one of these tests to debug what is going on, but the test runner captures stdout and stderr so the interactive prompt is swallowed. Add a `no-capture` option to `runtests` to allow the subtree tests to run without capturing stdout, stderr.
If capturing is off, also increase the `time_stamper_thread` interval to prevent printing logging messages while debugging.
> ENH: add no-capture option to runtests to allow debugging srctree tests

- Cython/Compiler/Builtin.py
- Cython/Compiler/TypeSlots.py
- tests/run/builtin_abs.pyx
I'm not entirely sure how to get the single test file to run, so I'm not sure if they're written correctlyy, but at least it compiles.
Fixes #2746.
> Mark optimized abs as being nogil-safe.

- docs/src/userguide/numpy_tutorial.rst
"convolve_cy.so" -> "compute_cy.so" to match imports used in this tutorial.
> DOC: Fixed name of .so file in userguide's numpy_tutorial.

- Cython/Utility/Builtins.c
- Cython/Utility/Coroutine.c
- Cython/Utility/Exceptions.c
- Cython/Utility/ExtensionTypes.c
- Cython/Utility/ObjectHandling.c
Add a new utility function `__Pyx_PyObject_GetAttrStrNoError()` that does not raise AttributeError if the lookup fails, and use `_PyObject_GenericGetAttrWithDict()` for it in Py3.7+ to avoid instantiating the exception completely.
> Speed up attribute lookups that do not care about the AttributeError

- Cython/Utility/ObjectHandling.c
- runtests.py
- tests/run/decorators_T593.pyx
- tests/run/locals_T732.pyx
- tests/run/metaclass.pyx
Fix #2772
Needs a bit of work in the testsuite to fix test failures on Python 2.
> Only generate __qualname__ in Python versions supporting it

- Cython/Utility/TypeConversion.c
This fixes the following compiler warning:
warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
> TypeConversion: Fix pointer qualifier compiler warning [-Wcast-qual]

- Cython/Utility/ModuleSetupCode.c
With C++ comments, we obtain the following errors if the generated code is compiled with -std=c89
error: C++ style comments are not allowed in ISO C90
> fix the comments to have a  c89 compliant generated code

- Cython/Compiler/Code.py
Hi,
I'm trying to get reproducible builds for my project and found a source of indeterminism in cython.
The __PYX_XDEC_MEMVIEW statements generated for try/finally statements varied per build if there were multiple types of variables to be cleaned up.
This patch sorts the list of free variables before returning it, making this bit of the codegen deterministic.
> Fix source of non-deterministic cython output for try/finally statements

- tests/run/lvalue_refs.pyx
Accessing the first element of a `std::vector` that is empty results in a crash.
In C++11, one could use [`std::vector.data()`](https://en.cppreference.com/w/cpp/container/vector/data) for the pointer, but I think this test is not C++11.
> Fix crash in lvalue_refs test.

- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/TypeConversion.c
This avoids the compiler warning
warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
by casting the pointer to uintptr_t before removing the const-ness.
The warning was introduced in 6cd70f0914d327f21feb8535810414c12e021737
Also merge the two places that define stdint types.
> Avoid const-ness compiler warning in __Pyx_PyObject_AsWritableString

- Cython/Compiler/ModuleNode.py
It seems that CPython searches for them there.
> Export "PyInit___init__" and "init__init__" as additional module init functions on Windows

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/Pipeline.py
- Cython/Compiler/Symtab.py
- runtests.py
- tests/run/ext_attr_getter.srctree
Following up the discussion on the mailing list. I got to the point where I can use the new syntax:
- ~fix the entry in `PropertyNode.analyse_declarations` and somehow make sure it is used instead of the old entry~
- ~change the code in `CFuncDefNode.analyse_declarations` and remove the `DecoratorTransform.visit_CFuncDefNode` function~
Any hints would be welcome.
Edit: added a new pass, ~still not working~
> ENH: allow @property decorator on external ctypedef classes

- Cython/Utility/StringTools.c
It fixes error 
```
src\lxml\etree.c(241210) : error C2275: 'PyObject' : illegal use of this type as an expression
```
when installing lxml 4.3.0 to pypy2 v6.0.0 on Windows.
> Fix incompatibility with C89

- Cython/Coverage.py
- tests/run/coverage_installed_pkg.srctree
When solving #2776 which reported ``Plugin 'Cython.Coverage.Plugin' did not provide a file reporter for '/Users/wenjun.swj/miniconda3/lib/python3.7/site-packages/gevent/_hub_local.py'`` when executing ``coverage report``, I find the cause is that some tracers built in Cython.Coverage do not have corresponding reporters.
In Cython.Coverage, when ``Plugin._parse_lines(c_file, filename)`` returns (None, None), ``Plugin.file_tracer(filename)`` returns a tracer, while ``Plugin.file_reporter(filename)`` returns None, and then coverage.py reports the error. This happens when shared packages have both *.py and *.c sharing the same base name. For instance, in the wheel package of gevent, both _hub_local.c and _hub_local.py exist, which mislead Cython.Coverage to produce a tracer as it does not …
> Fix inconsistency between traced files and reported files

- CHANGES.rst
- Cython/Utility/Coroutine.c
- tests/run/coroutines.py
- tests/run/generators.pyx
Make them return an inspectable (although otherwise dead) frame object.
Closes #2306.
> Implement "gen.gi_frame" and "coro.cr_frame" attributes on generators and coroutines

- Cython/Utility/TypeConversion.c
The current code fails to compile with:
```
<source>:3:54: error: invalid operands to binary expression ('enum E' and 'enum E')
const enum E neg_one_class_29 = (enum E) ((enum E) 0 - (enum E) 1);
~~~~~~~~~~ ^ ~~~~~~~~~~
```
This change reverts to the code that was before #2186 but silences erroneous GCC warning enabled by `-Wconversion` (which is not a part of `-Wall`).
Fixes #2749
---
Alternatively Cython can revert to the state before #2186 without adding GCC pragmas because the warning is a GCC bug with `-Wconversion`, which is not enabled even by `-Wall`.
> Fix support for C++ enum classes

- Cython/Plex/Actions.py
- Cython/Plex/DFA.py
- Cython/Plex/Errors.py
- Cython/Plex/Lexicons.py
- Cython/Plex/Machines.py
- Cython/Plex/Regexps.py
- Cython/Plex/Scanners.py
- Cython/Plex/Timing.py
- Cython/Plex/Traditional.py
- Cython/Plex/Transitions.py
- Cython/Plex/__init__.py
- setup.cfg
Implement setup.cfg to hold config for flake8.  Kept that config pretty minimal for the time being.  (If cython wants to put linting in the CI, it might be worth looking at statsmodels's lint.sh since statsmodels is in a similar situation vis-a-vis linting)
Side-note about setup.cfg: it can subsume .coveragerc and tox.ini if desired.  I'm not sure about pylintrc, but wouldn't be surprised.
Cleaned up the Plex directory.  Mostly (but not completely) ignored flake8 complaints about line length and module formatting.  Ignored 2 complaints about methods being too complex and 2 complaints about comparisons in Plex/Regexps.py comparing type(x) = ... instead of isinstance(x, ...) since I don't know if these are intentional.
> CLN: implement setup.cfg, lint cleanup of Plex directory

- Cython/Compiler/ExprNodes.py
- docs/src/tutorial/readings.rst
- docs/src/userguide/extension_types.rst
Found via `codespell -q 3 -L uint,sinc,nd,byteorder,delimeter,delimeters,te,iff,splitted,highlightning,tripple,varius,includee,ist,ue,ba,defin,amin,ith,creat,minimise,crasher`
> Misc. typo fixes

- Cython/Utils.py
- setup.cfg
xref #2825 
I threw in a non-flake8 edit to change the variable `dir` to `dirname` to avoid overlap with builtin names.
The remaining flake8 complaints after this are:
```
$ flake8 Cython/Utils.py
Cython/Utils.py:103:53: E226 missing whitespace around arithmetic operator
Cython/Utils.py:138:1: C901 'search_include_directories' is too complex (13)
Cython/Utils.py:228:53: E226 missing whitespace around arithmetic operator
Cython/Utils.py:326:42: E226 missing whitespace around arithmetic operator
```
The missing whitespace ones are because it wants `foo + 1` instead of `foo+1`.  I can either change these or edit the config to ignore this.
> CLN: flake8 fixups in Cython.Utils

- Cython/Build/Dependencies.py
- Cython/Build/Inline.py
- Cython/Compiler/CmdLine.py
- Cython/Compiler/Main.py
- Cython/Compiler/Options.py
- Cython/Compiler/Tests/TestParseTreeTransforms.py
- Cython/Tests/TestJediTyper.py
- runtests.py
update imports
remove Options.create_context in favor of Context.from_options
Discussed in #2831
> REF: Move CompilationOptions and default_options to Options

- Cython/Utility/TypeConversion.c
GCC diagnostic pragmas were introduced in GCC 4.6, so augment the GCC compiler check with a version check to avoid compilation errors with GCC < 4.6.
This should fix #2838.
> Avoid GCC diagnostic pragma if GCC < 4.6

- docs/examples/userguide/early_binding_for_speed/rectangle_cdef.pyx
- docs/examples/userguide/early_binding_for_speed/rectangle_cpdef.pyx
In the second and third examples of [early binding](https://cython.readthedocs.io/en/latest/src/userguide/early_binding_for_speed.html) the code doesn't match the description: namely, the function
```cython
def rectArea(x0, y0, x1, y1):
rect = Rectangle(x0, y0, x1, y1)
return rect.area()
```
doesn't `cdef`fine the local variable `rect`, so it doesn't gain access to the `cdef`/`cpdef` methods `area`/`_area`.
The correct code should be
```cython
def rectArea(x0, y0, x1, y1):
cdef Rectangle rect = Rectangle(x0, y0, x1, y1)
return rect._area()
```
for the second example and
```cython
def rectArea(x0, y0, x1, y1):
cdef Rectangle rect = Rectangle(x0, y0, x1, y1)
return rect.area()
```
for the third.
> Fix early binding example

- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Options.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
- Cython/Utility/ExtensionTypes.c
- tests/run/trashcan.pyx
Fix #1354 
This enables a `@cython.trashcan` directive which can enable using the Python trashcan for deallocations. This is optional, disabled by default (but one could argue about making it enabled by default).
Also see https://bugs.python.org/issue35983
> @cython.trashcan directive to enable the Python trashcan for deallocations

- CHANGES.rst
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Parsing.py
- Cython/Utility/ImportExport.c
- runtests.py
- tests/run/importas.pyx
- tests/run/reimport_from_package.srctree
- tests/run/relativeimport_T542.srctree
Closes #2854.
```
CPython:
$ python3.7 -m timeit 'import pyarrow.pandas_compat as pdcompat'
1 loop, best of 5: 592 nsec per loop
$ python3.6 -m timeit 'import pyarrow.pandas_compat as pdcompat'
10 loops, best of 3: 0.302 usec per loop
$ python3.5 -m timeit 'import pyarrow.pandas_compat as pdcompat'
10 loops, best of 3: 0.946 usec per loop
Cython before:
$ python3.7 -m timeit -s 'from importbench import _import_bench' '_import_bench()'
1 loop, best of 5: 1.37 usec per loop
After change, without initialisation check:
$ python3.7 -m timeit -n 100000 -r 50 -s 'from importbench import _import_bench' '_import_bench()'
100000 loops, best of 50: 51.5 nsec per loop
$ python3.6 -m timeit -n 100000 -r 50 -s 'from importbench import _import_bench' '_import_bench()'
100000 loops, best of 50: 0.0424 …
```
> Faster absolute reimports

- Cython/Compiler/Nodes.py
- Cython/Compiler/Optimize.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/Parsing.py
- docs/src/userguide/external_C_code.rst
- docs/src/userguide/fusedtypes.rst
- tests/errors/nogil_conditional.pyx
- tests/run/nogil_conditional.pyx
@scoder 
Implementation for [issue 2579](https://github.com/cython/cython/issues/2579).
Allowing statements such as:
```
with nogil(numeric is int):
<some code>
```
which will either run inside a nogil block if condition is True, or will run without a nogil block if the condition is False.
Original form still works the same (`with nogil: ...`).
**Still missing: errors tests.**
> Allow condition in GILStatNode

- CHANGES.rst
- Cython/Compiler/Nodes.py
- tests/run/coverage_nogil.srctree
> GH-1461: Include the signature line of cdef functions in the import-time line tracing and coverage report.

- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/TypeSlots.py
… by wrapping docstring literals in the `PyDoc_STR()` macro.
Closes GH-884.
> Support CPython builds with docstrings disabled

- Cython/Build/Cythonize.py
Add `-D, --no-docstrings` option for the cythonize script.
> cythonize --no-docstrings

- Cython/Includes/posix/mman.pxd
mlock2 is Linux-specific version of mlock that accepts flags. The only
flag available so far is MLOCK_ONFAULT which asks to lock pages only at
the time when they are faulted in, not in the beginning. MCL_ONFAULT is
Linux-specific flag to mlockall which requests similar behaviour.
http://man7.org/linux/man-pages/man2/mlock2.2.html
> include: posix.mman += mlock2, MLOCK_ONFAULT, MCL_ONFAULT

- Cython/Includes/posix/mman.pxd
mmap returns void* and indicates failure via MAP_FAILED that is defined
to be ((void *)-1). Every mmap call has to be checked for failure and
thus posix.mman with mmap, but without MAP_FAILED is not very useful.
We cannot declare MAP_FAILED as enum, because enum assumes int. However
Cython documentation says
4. If the header file uses macros to define constants, translate
them into a normal external variable declaration. ...
(https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#referencing-c-header-files)
So add proper declaration for MAP_FAILED to make posix.mman.mmap usable.
> include: posix.mman += MAP_FAILED

- CHANGES.rst
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/TypeSlots.py
- tests/run/exttype.pyx
- tests/run/tp_new.pyx
> Avoid generating a tp_new() function for extension types that do not need their own one.

- Tools/rules.bzl
there is no `py_deps` arg in the implementation, and the `data` argument causes errors because it is already used
> fix bazel rule pyx_library example

- CHANGES.rst
- Cython/Compiler/Main.py
- tests/compile/find_pxd.srctree
Fixes #2905 by raising the sys_path resolution into Context.search_include_directories
Also fix a bug in calling `os.path.join` with identical paths which merges them when they are absolute paths but concatenates them when they are relative paths, causing the test which adds a relative path to `sys.path` to fail. This would only occur when searching for `__init__.pxd`.
> BUG: prefer sys.path before Cython/Include when searching for pxd files

- docs/examples/userguide/wrapping_CPlusPlus/Rectangle.pxd
Well looking through the user guide noticed this very minor typo
> Minor typo of the word "declare" in user guide

- Cython/Compiler/Nodes.py
- tests/errors/nonconst_excval.pyx
Instead of two errors and a crash, just report it once and explicitly.
Closes #2934.
> GH-2934: improve error reporting for non-constant exception value expressions

- Cython/Build/Dependencies.py
- Cython/Compiler/Pythran.py
- runtests.py
Current checks breaks when setting 0.10.0 as a Pythran version :-/
> Make pythran version checks more resilient

- Cython/Compiler/Nodes.py
- tests/run/posonly.pyx
This addresses the suggestions from the comments in #2927.  There are two changes:
1. whenever a function has only positional-only arguments and no **arg, no keyword unpacking code is generated, and instead an error is raised,
2. if a function takes `n` positional-only args and `m` not-positional-only args, then the check that at least `n` positional args have been passed occurs in the very first switch statement.  The subsequent switch statements then exclude the cases `<n`,
As a concrete example of (1), here is the code generated for a signature like `test1(a, b, /)`:
```
PyObject* values[2] = {0,0};
if (unlikely(__pyx_kwds)) {
PyErr_Format(PyExc_TypeError, "test1() takes no keyword arguments");
__PYX_ERR(0, 2, __pyx_L3_error)
} else if (PyTuple_GET_SIZE(__pyx_args) != 2) {
goto …
```
> Positional-only code generation optimization

- Cython/Build/Cythonize.py
- Cython/Build/Tests/TestCythonizeArgsParser.py
Right now there are at least three different option/arguments parser:
1. parser for cython.py (uses no external libraries)
2. parser for cythonize.py (uses optparse)
3. parser for IPython-magic (based on argparse)
For adding/changing new options one has to understand all 3 way, there are also some discrepancies - for example `-3str` option is missed in IPython-magic's command line.
Since Cython no longer supports Python2.6 it is possible to use `argparse` and drop deprecated `optparse`.
The only behavior chance of this PR is a slightly different help message.
> Replace optparse by argparse

- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/Profile.c
This resolves compile errors with Python 3.8 on the 0.29.x branch.
> Fix compile error with 3.8

- Cython/Build/Cythonize.py
- Cython/Build/IpythonMagic.py
- Cython/Build/Tests/TestCythonizeArgsParser.py
- Cython/Build/Tests/TestIpythonMagic.py
- Cython/Compiler/Annotate.py
- Cython/Compiler/CmdLine.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Tests/TestCmdLine.py
- docs/src/userguide/source_files_and_compilation.rst
- tests/build/cythonize_with_annotate.srctree
- tests/build/cythonize_with_annotate_via_Options.srctree
- tests/run/annotate_html.pyx
Another alternative to close #2855  by adding the complete cythonized code to the annotated html. 
Question: Maybe there should  be an option, that the whole code is added only if asked (i.e. from IPython with `--show-cythonized-code`-option)?
> adding complete code to the annotated html-file

- tests/run/test_unicode.pyx
This patch enables disabled unicode tests with Py3.8 on the 0.29.x branch.
> [0.29.x] Unicode tests fix for Py3.8

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/MemoryView.py
- tests/memoryview/memslice.pyx
This addresses #2941.  The MemoryView scalar assignment code currently generates a stride 1 (ie. contiguous) loop whenever the destination of the slice is contiguous, regardless of the slice.  This isn't quite right, since slices of contiguous arrays of course aren't necessarily contiguous.  This patch just adds a check: if any of the indices of the slice is not simply `:`, then do not assume contiguity (these slices are referred to as "ToughSlices" elsewhere in the code).
One can do better than this, ie. if for a C-contiguous array the slice `a[1][:]` is contiguous, so the old generated code is correct and the new generated code is a little slower.  Not ideal, and maybe is worth adding logic to detect these cases, but this seems a reasonable first-pass fix.
> MemoryView slicing contiguity bugfix

- Cython/Compiler/ExprNodes.py
In https://github.com/python/cpython/pull/13726 CPython has change the semantics of argcount to reflect all positional arguments (including positional-only). This is to make it easier to consumers to obtain the number of positional arguments if they do not care about positional-only arguments.
More information in:
https://mail.python.org/pipermail/python-dev/2019-June/157812.html
https://bugs.python.org/issue37122
CC: @scoder @serhiy-storchaka
> Correct code object invocation after semantic change in argcount for 3.8

- CHANGES.rst
- Cython/Build/Cythonize.py
- Cython/Build/IpythonMagic.py
- Cython/Build/Tests/TestCythonizeArgsParser.py
- Cython/Build/Tests/TestIpythonMagic.py
- Cython/Compiler/CmdLine.py
- Cython/Compiler/Tests/TestCmdLine.py
- docs/src/userguide/source_files_and_compilation.rst
Unluckily my #2858 has introduced a regression for cythonize.py: in
cythonize -a foo.pyx
`foo.pyx` is interpreted as a value for option -a and not as source-file. The problem `nargs='?'` doesn't work well with positional arguments.
It would be possible to save the syntax `--annotate fullc` but at cost of adding more complexity, so I think it is easier to introduce new option `--annotate-fullc` instead, which corresponds to the old `--annotate=fullc`, as done in this PR.
> Fixing regression from #2858

- Cython/Build/Tests/TestCythonizeArgsParser.py
I noticed that most of the tests in TestCythonizeArgsParser were failing for me because options.parallel was hard coded to test against a default value of 3 when it is actually set to floor(CPU cores * 1.5). Fixed by importing the actual default and checking against that instead.
> Fix parallel option test in TestCythonizeArgsParser

- Cython/Compiler/Pythran.py
And make it more flexible in terms of API change.
> Simplify slice handling in Pythran

- Cython/Build/Cythonize.py
- Cython/Build/Tests/TestCythonizeArgsParser.py
This is fix for a regression in #2952: in optparse interspersed arguments are on per default, but not in argparse (I was not able to parse this information from https://docs.python.org/3.7/library/argparse.html#upgrading-optparse-code), thus the following
cythonize.py   file1 -a file2
works with optparse but not argparse.
As the native-argparse support for interspersed/intermixed arguments is only available since Python3.7 (https://bugs.python.org/issue14191) we need to emulate it.
> Fix interspersed positional arguments in cythonize.py

- Cython/Debugger/Tests/TestLibCython.py
The regex to match the gdb version is not intended to be interpreted as a regular string, it is designed to be used as-is as a regex.  This tells python about that minor detail.
> Mark regex as raw string to avoid syntax warnings

- Cython/Utility/CythonFunction.c
- Cython/Utility/ObjectHandling.c
Support `Py_TPFLAGS_METHOD_DESCRIPTOR` in `__Pyx_PyObject_GetMethod` and set that flag for the class `cython_function_or_method`.
I don't know whether `fused_cython_function` should also get that flag or not, so I didn't add it.
> Support Py_TPFLAGS_METHOD_DESCRIPTOR

- Cython/Includes/cpython/unicode.pxd
Fixes #2726 
Example use
```
:~/src/cython [v37] PyUnicode_FromStringAndSize(+4/-0)*± python
Python 3.7.3 (default, Apr  3 2019, 19:16:38)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyximport; pyximport.install()
(None, <pyximport.pyximport.PyxImporter object at 0x7f0732f02978>)
>>> import try_PyUnicode_FromStringAndSize
>>> hello(5)
File "<stdin>", line 1, in <module>
NameError: name 'hello' is not defined
>>> try_PyUnicode_FromStringAndSize.hello(5)
'Hello'
>>> try_PyUnicode_FromStringAndSize.hello(-1)
File "<stdin>", line 1, in <module>
File "try_PyUnicode_FromStringAndSize.pyx", line 5, in …
```
>  Declare PyUnicode_FromStringAndSize and PyUnicode_FromString

- Cython/Compiler/Symtab.py
It's just removing a useless code duplication.
> Scope.lookup_operator: use arg_types defined right above

- Cython/Includes/cpython/pystate.pxd
- tests/run/cpython_capi.pyx
PyGILState_STATE was added in commit 3fd6fdce66 (Gilnanny + pystate.pxd)
with struct type on-purpose different from what CPython actually uses
with the idea so that PyGILState_STATE cannot be coerced into int.
However as it is, it prevents PyGILState_STATE usage:
cdef PyGILState_STATE gstate = PyGILState_Ensure()
gives
Variable type 'PyGILState_STATE' is incomplete
Fix it by making PyGILState_STATE a defined structure.
> include: cpython.pystate: Fix PyGILState_STATE definition

- Cython/Utility/ModuleSetupCode.c
CPython bpo-37221 reverts the backwards incompatible
change to the PyCode_New API raised in #2938, replacing it with a new
PyCode_NewWithPosOnlyArgs function.
Checking for the new symbol definition allows Cython to
detect any version where bpo-37221 has been resolved,
even if the version number hasn't been updated for the
next beta release yet.
> Handle API compatibility for CPython bpo-37221

- Cython/Compiler/Naming.py
- Cython/Compiler/Nodes.py
Simplify args-parsing code by replacing all occurrences of `PyTuple_GET_SIZE(__pyx_args)` by `__pyx_nargs` and setting `__pyx_nargs = PyTuple_GET_SIZE(__pyx_args)` just once.
This will be needed also for `METH_FASTCALL`, where `nargs` is passed as a function parameter.
> Add nargs variable in args-parsing code

- CHANGES.rst
- Cython/Compiler/Main.py
- Cython/Utils.py
- tests/compile/find_pxd.srctree
Proposed backport of #2910 to allow NumPy to advance with https://github.com/numpy/numpy/pull/12284
> Backport of GH-2910 include path reordering

- Cython/Compiler/ExprNodes.py
- Cython/Utility/Coroutine.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
- tests/run/iterdict.pyx
- Replace the `_PyMethodDef_RawFastCallKeywords` calls by `_PyMethodDescr_FastCallKeywords` to fix #2996 and add a test for it.
- Replace the manually-written code to call functions with a known number of arguments by calls to a new function `__Pyx_PyObject_FastCall`. The compiler should be able to optimize this if the number of arguments is a compile-time constant. Some special code for 0 and 1 arguments is still kept.
- In `__Pyx_PyObject_FastCall`, use code optimized for each CPython version. This includes vectorcall on Python 3.8 (enabled by a new feature test macro `CYTHON_VECTORCALL`)
- Remove `__Pyx_PyCFunction_FastCall` and `__Pyx_PyFastCFunction_Check` which seems no longer needed.
- In `__Pyx_PyObject_CallMatrixMethod`, call `__Pyx_PyObject_Call2Args` instead of essentially …
> Simplify and optimize calls, using vectorcall on Python 3.8

- Cython/Includes/posix/mman.pxd
I was going to use posix_madvise(POSIX_MADV_DONTNEED) in my tests to
make sure a memory page should be evicted from kernel cache, but found
out that this operation is hardcoded to be NOOP on Glibc/Linux systems:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/posix_madvise.c;h=c89fa64f0749;hb=HEAD#l25
https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=8889e7aa461a
On the other hand, as also verified by strace, `madvise(MADV_DONTNEED)`
is not a NOOP as it actually goes to kernel by making syscall.
Since it is not possible to use posix_madvise for what should be
POSIX_MADV_DONTNEED behaviour, let's add all raw madvise behaviour flags
as documented on http://man7.org/linux/man-pages/man2/madvise.2.html
Presumably MADV_NORMAL and other behaviours that should …
> include: posix.mman += MADV_* (MADV_NORMAL, MADV_DONTNEED, etc ...)

- Cython/Utility/ObjectHandling.c
- Cython/Utility/Optimize.c
The new PyInt_FromSsize_t reference was not decref'ed in general.
---
I was hacking on numpy using `pytest-leaks` and ran into a reference issues within cython (numpy.random). This is the on that I managed to track down for now. There is another coming up (although most likely I will only open an issue).
I suppose these should get tests? Just ping me, and I will look into it.
> BUG: Fix reference count issues

- Cython/Utility/ObjectHandling.c
Sorry, my previous fix was cursed (not running the tests), now I
saw the compiler warning, and I suppose it would be good for the
tests to run error paths.
> BUG: Fix(up) incorrect return in SetItemFast

- Cython/Compiler/Code.py
- Cython/Compiler/ModuleNode.py
- tests/run/error_pos.srctree
Currently Cython generates code like this:
int __Pyx_InitCachedBuiltins(void) {
__pyx_builtin_NAME = __Pyx_GetBuiltinName(...);
if (!__pyx_builtin_NAME) __PYX_ERR(1, 44, __pyx_L1_error)
}
int __pyx_pymod_exec_MODULE(PyObject *__pyx_pyinit_module) {
if (__Pyx_InitCachedBuiltins() < 0) __PYX_ERR(1, 1, __pyx_L1_error)
}
When InitCachedBuiltins and InitCachedConstants call __PYX_ERR, they
pass the file and line where a builtin is used, but then pymod_exec
overwrites it with 1 and 1, and the error message looks like this:
File "FILE", line 1, in init MODULE.
import os
NameError: name 'NAME' is not defined
After this change Cython generates:
int __pyx_pymod_exec_MODULE(PyObject *__pyx_pyinit_module) {
if (__Pyx_InitCachedBuiltins() < 0) goto __pyx_L1_error;
}
and prints:
File "FILE", line 44, …
> Fix error positions of undefined builtins and constants

- Cython/Compiler/Pythran.py
Pythran assumes shapes are shapes of long, whatever the underlying
architecture.
> Fix 32-bit build compat for Pythran

- tests/errors/cimport_attributes.pyx
- tests/errors/cpp_object_template.pyx
2 error tests didn't have the `tag: cpp` although they use c++ features.
This was not noticed before because these error tests are not triggering a Node.cpp_check.
This cpp_check function is only called with memory statements `new` and `del`.
So, for example, cython is perfectly happy with compiling a .pyx which is declaring (even defining) a C++ class, as long as you only use stack allocation, **without the `--cplus` flag**.
I think this check may be generalized, just like what is done for gil checking.
If this sounds interesting, I can spare some time to do it.
> Add cpp tag to some cpp error tests

- runtests.py
Support compiler flag `-save-temps` when running the testsuite: files with extensions `.i`, `.ii` and `.s` are now treated the same as `.c` files when cleanup up. So cleanup can be skipped with `--no-cleanup`.
> runtests: keep also .i, .ii and .s files (generated by -save-temps)

- Cython/Includes/cpython/pystate.pxd
- Cython/Includes/posix/mman.pxd
- tests/run/cpython_capi.pyx
Backport from master to 0.29.x branch my fixes to mman and pystate includes. The following changes are backported:
- https://github.com/cython/cython/pull/2893
- https://github.com/cython/cython/pull/2894
- https://github.com/cython/cython/pull/2997
- https://github.com/cython/cython/pull/3012
Reason for backport is that not everyone is using unrelased Cython 3 while Cython 0.29.x usage is common.
> 0.29.x: posix.mman and cpython.pystate include backports

- Cython/Build/Cythonize.py
- Cython/Compiler/CmdLine.py
- Cython/Compiler/Tests/TestCmdLine.py
This is a continuation to  #2952: replacing a self-made command line parser for cython.py with argparse, which is already used by cythonize and (kind of) by IPython-magic.
Using only one library for argument parsing will make it easier to add new options to cython/cythonize/IPython-magic and/or syncronize/consolidate them all.
Apart of a slightly different help message there should be no behavioral changes.
> Argparse for cython

- tests/run/extstarargs.pyx
- tests/run/starargs.pyx
- Cleanup `tests/run/extstarargs.pyx`
- Add tests in `starargs.pyx` and `extstarargs.pyx` to check that the `*args` tuple is not copied if possible.
> Test that *args tuple is not copied if possible

- .travis.yml
Now that the CPython 3.8 release is getting nearer, we should make it mandatory on Travis CI, no longer allowing failures. We also test both C and C++ like the other Python versions.
> Travis CI: make CPython 3.8 tests mandatory

- runtests.py
- tests/run/tracebacks.pyx
- tests/run/unicode_identifiers.pyx
This compiles all tests with `-DCYTHON_CLINE_IN_TRACEBACK=1` which is useful for debugging test failures. As an exception, this is not done for `# tag: traceback` which specifically tests the `cline_in_traceback` feature.
> Always enable C line in traceback for tests

- Cython/Utility/ObjectHandling.c
- tests/run/cclass_assign_attr_GH3100.pyx
This fixes various bugs of the form
```
In [22]: %%cython
...: cdef class Foo:
...:     @classmethod
...:     def meth(cls): return cls
...:     meth2 = meth
In [23]: Foo.__dict__["meth"]
Out[23]: <method 'meth' of '_cython_magic_47326ec5db9a0810fa14f024478f1a5d.Foo' objects>
In [24]: Foo.__dict__["meth2"]
Out[24]: <built-in method meth of type object at 0x7fe8b9b61700>
```
One would expect `Foo.__dict__["meth"]` and `Foo.__dict__["meth2"]` to be the same. However, the logic that implements the line `meth2 = meth` uses `Foo.meth` (which calls `__get__` to bind the classmethod) instead of `Foo.__dict__["meth"]`.
> __Pyx_GetNameInClass() should get raw attribute from __dict__

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Includes/numpy/__init__.pxd
- tests/run/ext_attr_getter.srctree
Continuation of #2640. Add a failing test for `f.fieldF1 != 10` and a `pxd` file, and fix for the failures. This seems to now work quite nicely with numpy.
I still would like to refactor this, following the [comments](https://github.com/cython/cython/pull/2640#issuecomment-455460180) on the original PR, but in experiments on the NumPy code base this seems to do what is needed. Help in the high-level design of the refactoring would be welcome, I am not sure how to clean this all up.
> BUG: support wider use of @property decorator on CClassDef AttributeNodes

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/FusedNode.py
- Cython/Compiler/Naming.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/TypeSlots.py
- Cython/Utility/FunctionArguments.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
- tests/run/fastcall.pyx
- tests/run/str_subclass_kwargs.pyx
Support `METH_FASTCALL` for builtin functions (not yet CyFunctions) on CPython 3.7
> Use METH_FASTCALL on Python >= 3.7

- Cython/Compiler/ExprNodes.py
- Cython/Utility/ObjectHandling.c
- tests/run/set_new.py
Python special-cases the name `__new__` in a class: if it's a Python function, it's automatically wrapped in a staticmethod:
```
>>> class X:
...     def __new__(cls): return object.__new__(cls)
>>> X.__dict__["__new__"]
<staticmethod object at 0x7f0d52eafb38>
```
This PR implements this feature for Cython functions.
> Special-case setting __new__ in class

- Cython/Compiler/ExprNodes.py
- Cython/Utility/CythonFunction.c
- Cython/Utility/ObjectHandling.c
- tests/run/cyfunction.pyx
- tests/run/set_new.py
Currently, when defining a CyFunction with `@staticmethod`, this does *two* things:
1. It wraps the function inside a `staticmethod`.
2. It sets the flag `__Pyx_CYFUNCTION_STATICMETHOD` in the CyFunction, which prevents `__get__` from creating a bound method.
Only one of these is sufficient to have correct semantics for a static method. For consistency with Python, we should only do 1. and not 2. The same for class methods.
**Depends on #3102**
> Always bind Cython functions

- Cython/Utility/CythonFunction.c
There is some inconsistency in the naming of the fourth argument of `__Pyx_CyFunction_NewEx` and `__pyx_FusedFunction_NewEx`: in some places `self` is used and in other places `closure` is used. I think that `closure` is the right name since
1. This has nothing to do with the `self` of methods, nor with the `self` argument to the C function (in case the function is not defined in a cdef class).
2. The value is stored in the `func_closure` field of `__pyx_CyFunctionObject`.
This is a purely cosmetic fix in the source code, it doesn't affect any external behaviour.
> Consistently name "closure" argument for Cython functions

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ParseTreeTransforms.py
See #3104 for the rationale. This is fixing the Python side:
- remove `self_object` attribute, which was always set to `None`
- rename `self_result_code` -> `closure_result_code` and `needs_self_code` -> `needs_closure_code`
> Rename self_result_code -> closure_result_code

- Cython/Utility/CppConvert.pyx
When compiling to C++ code and using automatic conversion from Python
str to C++ string, Cython inserts this function template but generates
the warning:
```
warning: string.from_py:15:63: local variable 'length' might be
referenced before assignment
```
This commit fixes this.
> Utility/CppConvert: fix Cython warning

- Cython/Compiler/Lexicon.py
- Cython/Compiler/Scanning.py
- Cython/Utils.py
- runtests.py
- tests/errors/unicode_identifiers_e1.pyx
- tests/errors/unicode_identifiers_e2.pyx
- tests/errors/unicode_identifiers_e3.pyx
- tests/errors/unicode_identifiers_e4.pyx
- tests/run/unicode_identifiers.pyx
- tests/run/unicode_identifiers_normalization.srctree
Also add a test-case. (Also add a test case for passing keyword
arguments, which already worked, but is good to have as a test
case).
PEP3131 implies that normalization of identifiers should be done before tokenization (i.e. the moment any unicode character is found the surrounding area of code should be normalized then checked to see if it's an identifier). Practically, I don't think this is what Python does. Instead it finds a bit of string that might be an identifier and validates that it is (https://github.com/python/cpython/blob/69f37bcb28d7cd78255828029f895958b5baf6ff/Parser/tokenizer.c#L1062). Normalization is done when the AST is generated (https://github.com/python/cpython/blob/51aac15f6d525595e200e3580409c4b8656e8a96/Python/ast.c#L610).
I've followed (what I believe is) Python's …
> Handle normalization of unicode identifiers

- tests/memoryview/memslice.pyx
- tests/run/pstats_profile_test.pyx
Fix a couple of failing tests on the hg2564_enable_binding branch. From my analysis of the python3.6 no-cpp test log there are only a few failing tests, I could not replicate the get_refcount failures locally.
<details>
python runtests.py --no-cpp embedsignatures
fails with
```
analyse_types not implemented
Called from: CoerceToComplexNode.not_implemented 459
Called from: CoerceToComplexNode.analyse_types 664
Called from: AddNode.analyse_types 10987
```
python runtests.py --no-cpp memslice.assign_temporary_to_object
python runtests.py --no-cpp memslice.assign_to_object
python runtests.py --no-cpp memslice.printbuf_object
python runtests.py --no-cpp memoryview.assign_temporary_to_object
python runtests.py --no-cpp memoryview.assign_to_object
python runtests.py --no-cpp …
> TEST: Fix failing tests

- Cython/Includes/numpy/__init__.pxd
#3095 changed `Cython/Includes/numpy/__init.pxd` to use the new `@property` attributes. It seems that decorator is not quite finished yet, so I propose to back out the changed pxd file to unbreak downstream packages.
related to #3113
> BUG: revert numpy.pxd to 0.29.13

- Cython/Utility/Complex.c
I think this was a copy-paste error. There's no reason to compute the product, throw it away, and then compute it again.
> Remove duplicated line from __Pyx_c_pow

- Cython/Utility/CythonFunction.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
Minor cleanup regarding `__Pyx_PyMethod_New`:
1. Fix a `-Wunused` warning
2. Move it from `ModuleSetupCode.c` to `ObjectHandling.c`
3. Use it directly in the `tp_descr_get` slot instead of a writing a function just calling `__Pyx_PyMethod_New`
> Put __Pyx_PyMethod_New directly in the tp_descr_get slot

- Cython/Compiler/PyrexTypes.py
- tests/errors/fused_types.pyx
- tests/memoryview/numpy_memoryview_readonly.pyx
- tests/run/fused_types.pyx
This PR is related to #1772 and is an attempt at supporting `const` fused type memory views such as:
```
cimport cython
def sum(const cython.floating[:] array):
cdef cython.floating sum = 0
for v in array:
sum += v
return sum
```
Cython internals are new to me, so I don't know how far this is from a proper solution, but it's working fine from what I tested.
Let me know if it is worth spending more time on it and what can be improved.
One remark: In case of function signature like `def test(const cython.floating[:] a, cython.foating[:] b)` and mismatching input floating types, the exception is:
`TypeError: No matching signature found`
while without `const` it is: `ValueError: Buffer dtype mismatch, expected 'float' but got 'double'`
Closes #1772.
> Add support of const fused type memory views

- Cython/Build/Cythonize.py
- Cython/Build/Tests/TestCythonizeArgsParser.py
- Cython/Compiler/Tests/TestCmdLine.py
- Cython/Compiler/Tests/Utils.py
- runtests.py
- tests/build/cythonize_with_annotate_via_cli.srctree
cythonize.py doesn't take `--annotate-fullc` correctly into account  (https://github.com/cython/cython/commit/8e5f944607da002f918cd4c270ad0e4ad48bc4c8 - a test case showing the problem): when called via cli, there is no difference to calling with `--annotate`.
Also improved unit tests, so they also test changes in global Options.
Fixed [here](https://github.com/cython/cython/commit/841ec5e715f9575f2a5c7642f83fb35a40e6de85).
> Fixing the handling of --annotate-fullc in cythonize.py

- Cython/Compiler/TypeSlots.py
When compiling cython-generated extension modules in Python3.8rc1
this error is emitted by the compiler:
_ext.cpp:8104:1: error: missing initializer for member ‘_typeobject::tp_print’ [-Werror=missing-field-initializers]
The reason is that Python3.8 moved the tp_print slot (commit d917cfe4051) to
the end of the _typeobject struct and reused the original position for
tp_vectorcall_offset. The current generated code does not initialize the
deprecated tp_print slot that was moved to the end of the struct.
> Explicitly initialize tp_print in Python 3.8

- Cython/Compiler/TypeSlots.py
This is more follow up to https://bugs.python.org/issue37250
The action taken is:
- restore tp_print to not break all of the sdists on pypi for py38
- remove tp_print for real in py39
In https://github.com/cython/cython/pull/3171 tp_print was initialized
for PY_VERSION_HEX >= 0x030800b4 however, when trying to use cython
with cpython master (aka py39) there are compile time exceptions due
to too many initializers:
error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
This fixes that by putting an upper bound on the ifdef of including
pt_print at the end of the object.
The current test suite fails to on cpython master without this patch.
This should be back-ported to 0.29.x as well.
> FIX: do not include tp_print for py39

- Cython/Compiler/FusedNode.py
- tests/compile/fused_redeclare_T3111.pyx
Fixes #3111.
The test currently doesn't work because, while with the changes to `FusedNode`, the file itself no longer generates any warnings, for some reason it appears to be pulling in `Cython/Utility/TestCythonScope.pyx` which *does* produce warnings.  This doesn't happen when running `cython` from the command line.  I would appreciate some help figuring out how this test is supposed to work, since I wasn't sure where to look for examples of writing a test for "does not produce a warning".
> Make sure not to emit duplicate typedefs for fused nodes

- Cython/Distutils/old_build_ext.py
In Python 3.5, distutils added a `--parallel / -j` option to allow extensions to be compiled in parallel. setuptools leverages this by default unless Cython is present because it uses the build_ext provided by Cython instead. Cython overrides `build_extensions()` entirely assuming that it just calls `build_extension` (which it did before Python 3.5).
This change defers back to the original `build_extensions()` call in `build_ext` after mutating the sources so that --parallel works with Cython properly.
> Fix --parallel support in build_ext.build_extensions()

- Cython/Compiler/Parsing.py
This is a subset of [#2951](https://github.com/cython/cython/pull/2951), containing the (corrected) code for the introduction of cppclass docstrings (they are discarded as comments).
> Allow docstrings in c++ classes

- Cython/Includes/libcpp/algorithm.pxd
- Cython/Includes/libcpp/string.pxd
- tests/run/cpp_stl_algo_modifying_sequence_ops.pyx
- tests/run/cpp_stl_algo_nonmodifying_sequence_ops.pyx
- tests/run/libcpp_algo.pyx
> Add most modifying sequence operations to libcpp.algorithm

- Cython/Build/IpythonMagic.py
When using the IPython magic, if the compilation or build fails then the appropriate errors are printed followed by long tracebacks into Cython internals. These changes hide the tracebacks so only the actual errors are shown.
Before:
```
...
(void)expander{0, (void(out << ',' << std::forward<Args>(args)), 0)...};
}
"""
void doPrint[T1, T2](T1 a, T2 b)
def cprint(a, b)
^
/Users/matthew/.ipython/cython/_cython_magic_1976d2dff2a61ed3a6c96c26bc6f78aa75443df0.pyx:13:16: Expected ':', found 'NEWLINE'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call …
```
> Improve error presentation in IPython magic

- Cython/Utility/AsyncGen.c
- Cython/Utility/Coroutine.c
- Cython/Utility/CythonFunction.c
This should complete #3171 in silencing `-Wmissing-field-initializers`.
> Initialize tp_print in Python 3.8

- Cython/Compiler/Nodes.py
- tests/run/cdef_multiple_inheritance.pyx
Copying [comment](https://github.com/cython/cython/pull/2864#issuecomment-538297683) here:
The crash in `cdef_multiple_inheritance` has to do with a change in the method assignment. In the old version, the code 
```
cdef class Both(CBase, PyBase):
cdef dict __dict__
cdef c_method(self):
return "Both"
cpdef cp_method(self):
return "Both"
def call_c_method(self):
return self.c_method()
```
would assign `cp_method` and `call_c_method` to a `PyMethodDef` struct. In the new code only `call_c_method` is assigned in the `PyMethodDef` struct, but both are assigned to the `__pyx_ptype...Both->tp_dict` inside `__Pyx_Init_Globals` which happens while `__pyx_ptype...Both` is still NULL. The assignment `__pyx_ptype...Both = &__pyx_type...Both` happens in the next fragment, a few lines down.
This PR …
> BUG: emit init code before body code

- runtests.py
- tests/run/cpp_class_attrib.srctree
Add a test of attribute decorators from the [docs](http://docs.cython.org/en/latest/src/userguide/wrapping_CPlusPlus.html) to exercise the attribute getter/setter decorators
> TEST: add cpp attribute example from docs, add CYTHON_PROJECT_DIR for tests

- Cython/Compiler/ExprNodes.py
- tests/run/ext_attr_getter.srctree
The first new test is fixed
```
def check_binop(getter.Foo f):
return f.fieldF1 / 10
```
~but the others still fail~
and the others should pass now too
Edit: tests now pass
> ENH: add more tests and fixes for @property cdef decorator

- Cython/Compiler/Code.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Tests/TestUtilityLoad.py
Requires the source file to be named explicitly. It was almost always passed anyway, so having a non-trivial search algorithm in place for a rare case of unnecessary laziness is just code bloat.
> Simplify the utility code loading

- Cython/Build/IpythonMagic.py
- Cython/Build/Tests/TestIpythonMagic.py
The "py3compat" module changed incompatibly in IPython 7.11.
Closes #3296.
Closes #3291.
> Remove legacy imports from IPython integration

- docs/src/quickstart/install.rst
0.11.2 is over a decade old at this point so people aiming to install
earlier versions should probably just read the documentation for those
version. There aren't any footnotes in the documentation.
> Remove unnecessary sentence from documentation

- Cython/Compiler/Code.py
Add read_utitlities_hook to override how utilities files are accessed.
This change simplifies how Cython can be packaged into a single
file binary executable, where utility files are stored inside the
binary executable as package resource.
> Add a hook to change how `utilities` files are read.

- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Options.py
- docs/src/userguide/source_files_and_compilation.rst
See https://github.com/cython/cython/issues/2740
> #2740 emit_code_comments - removed from options, updated documentation

- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
- Cython/Utility/CppSupport.cpp
- tests/run/numpy_pythran.pyx
Through a conversion to array. I've tested that and it's ok performance wise,
the C++ compiler can deal with the abstraction (with a small overhead though).
This should fix https://github.com/serge-sans-paille/pythran/issues/1428
> Support Pythran shape

- Cython/Utility/ObjectHandling.c
This allows the compiler to reorganize the code to minimize jumps.
> Mark Py_EnterRecursiveCall as unlikely

- Cython/Compiler/ModuleNode.py
Title says it all. The generated code has a stray ';' that breaks with Wpedantic.
> Small tweak to generated limited API code to work with Wpedantic

- Cython/Compiler/ExprNodes.py
- tests/buffers/bufaccess.pyx
They were assigned to global scope, but buffers aren't allowed in
global scope. To fix, dropped the buffer type from the default value.
--------
Fixes the compile error. However a bunch of reference counting "errors" appear (i.e. numbers don't match existing numbers). Link to https://github.com/cython/cython/pull/2864
> Fixed default buffer arguments with binding [Fixes `bufaccess`]

- docs/src/tutorial/strings.rst
- docs/src/userguide/memoryviews.rst
Updated the docs for [Accepting strings from Python code](https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#accepting-strings-from-python-code) to mention that read-only buffers require a `const` type declaration (per the [Read-only views](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#read-only-views) section under Typed Memoryviews). Should hopefully close #1682.
> updated documentation to mention 'const' for read-only buffers

- CHANGES.rst
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- tests/run/pyclass_dynamic_bases.pyx
… by making the PyClassDefNode own it and other nodes only refer to it, rather than risking stale references in subnodes.
(Alternatively, ownership could be distributed across the subnodes, but it's a bit unclear how, and how to refer to the other subnodes then.)
Closes #3338.
> Use the correct post-analysed bases, mkw and metaclass in Python class creation

- Cython/Build/Inline.py
Fixes gh-3306
Using `imp` is deprecated. Add an alternative incantation from `importlib` which was [added in Python 3.3](https://docs.python.org/3/library/importlib.html?highlight=extensionfileloader#importlib.machinery.ExtensionFileLoader)
> Remove deprecated import of imp module

- tests/buffers/bufaccess.pyx
- tests/run/extstarargs.pyx
Updating some of the tests that are failing with binding enabled (and which aren't hiding real problems)
------------------------
Disabled binding on the get_refcount function. It looks like
binding generates slightly different refcounts to function arguments
on Python 3.8 (possibly to do with vectorcall?). It isn't relevant
to what's being tested so it's easier to turn it off.
Passing a star-arg tuple and getting the same tuple out doesn't
work with binding, so only tested that without
> bufaccess ref-counting tests and extstarargs test

- tests/memoryview/memoryview.pyx
- tests/memoryview/memslice.pyx
It looks like different Python versions will now
generate different reference counts during function
calls to CyFunction (due to vectorcall).
Disabled binding for the `get_refcount` function
(since it really doesn't need this complication)
and made one test relative instead of absolute.
Hopefully this fixes the remaining reference
counting mismatches on the enable_binding branch.
--------------------------------
I think this should just leave `w_undeclared` and possible profiling failing (unless there's something I've missed). Writing tests for version-dependent reference counts does look like a nightmare for the future though.
> More tweaks for reference counting with binding=True

- Cython/Compiler/ParseTreeTransforms.py
The pickle functions `__reduce__` and `__setstate_cython__` were being
visited in the module scope (where they were undeclared) rather
than the class scope where they were declared
> w_undeclared fix

- tests/run/always_allow_keywords_T295.pyx
https://bugs.python.org/issue37645 appears to change some error
messages slightly (including the qualname and not just the
function name). This change just allows doctest to cope with
both the new and old messages.
-----------------------------------
Fixes (part of) https://github.com/cython/cython/issues/3349. I'm
slightly surprised that the change to Python didn't break more
of the Cython tests.
> Changed always_allow_keywords_T295 for Py3.9

- Cython/Compiler/Nodes.py
- tests/run/sequential_parallel.pyx
Currently inner/nested pranges are not translated to an active OpenMP parallel for.
The private temporary variables identified for these inner loops were only declared in the 
```
#if 0
#pragma omp for private....
#endif
```
but not anywhere else. This apparently causes races.
The suggested code propagates the privatization to the outer construct so that it gets actually exposed.
> Fixing declaration of inner OpenMP privates

- Cython/Compiler/ExprNodes.py
- tests/run/cpp_operator_exc_handling.pyx
- tests/run/cpp_operator_exc_handling_helper.hpp
They'd generate two calls - one exception checked and one not
--------------------------------
```
return c1 < c1
```
currently translates to
```
try {
__pyx_t_1 = (__pyx_v_c1 < __pyx_v_c1);
} catch(...) {
__Pyx_CppExn2PyErr();
__PYX_ERR(0, 27, __pyx_L1_error)
}
__pyx_t_1 = (__pyx_v_c1 < __pyx_v_c1);
```
i.e. it does the comparison twice, and doesn't check for exceptions on the second one.
> Fixed a bug with C++ comparison operators

- Cython/TestUtils.py
- runtests.py
I hope that this solves #3369.  Speaking from experience (of maintaining widgets fetching data from command-line programs), quoting shell is a huge pain, that's why I'm favoring imputing commands via lists.
If any change is too excessive, feel free to tell me to undo it.
> Let tests run when Python executable path contains whitespace

- Cython/Includes/libcpp/utility.pxd
- tests/run/cpp_move.pyx
This PR adds a wrapper for std::move as discussed in #2169.
If-guard is used to avoid causing any issues in case `libcpp.utility` is cimported without C++11 (e.g. for using `std::pair`). Namespace `cython_std` is used for implementation details. 
Closes #2169.
> Add std::move wrapper to utility library

- Cython/Compiler/Code.py
- Cython/Utility/ObjectHandling.c
@subsitute: tempita tag ensures that they are loaded in tempita utility code class
-----------------------------
Should be no user-visible changes. This is really just to help me re-use some existing functions in https://github.com/cython/cython/pull/3346. Based on https://github.com/cython/cython/blob/8e35f7e282f0ec7e5dab48d7c0d31595f2b2c237/Cython/Utility/ObjectHandling.c#L282 this is something that's been worked round before, so maybe it'll be useful elsewhere.
> Allow tempita includes to be more readily @required

- Cython/Compiler/Code.py
The initialization now appears in a few large blocks rather than many
```
individual string line
```
-----------------------
On the fairly simple `compute_prange` example (arbitrary example, chosen just because that's what I was looking at at the time) it saves about 900 lines of preprocessor statements (about 3% of the total file length).
See #2542
> Cleanup of string initialization code for limited API

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- tests/run/pure_fused.pxd
- tests/run/pure_fused.py
Issues were:
1. DefNode.has_fused_arguments was set too early (before
locals/annotations) were evalutated, so function was not treated
as fused.
2. When re-evaluating the specializations of the fused function
it was treated as a redefinition because the locals/annotation was
reapplied over the specialized type.
> Fused arguments specified by annotation or locals

- Cython/Utility/CythonFunction.c
- tests/run/fused_def.pyx
Default arguments are now copied when the bound fused function is created rather than being left as a NULL pointer.
Fixes https://github.com/cython/cython/issues/3370 and enables https://github.com/cython/cython/pull/3366 to proceed using a local default argument to store the dict.
> Fixed crash with default arguments and bound fused functions

- Cython/Utility/CythonFunction.c
- tests/run/fused_def.pyx
Issue https://github.com/cython/cython/issues/3384
This happened where Cython was using a shared API because the
CyFunction type imported from the shared api wasn't the same as
used to initialize the fused function tp_base
> Fixed issue where fused functions didn't register as cyfunctions

- Cython/Compiler/Code.py
Strings weren't static for the limited API so had to be set at
module init rather than compile time
Re: https://github.com/cython/cython/issues/2542
> Fixed initialization of cachedcfunction

- docs/src/userguide/source_files_and_compilation.rst
`annotation_typing` is currently indented in a way which I don't think is intentional.
> fix indentation on annotation_typing docs

- Cython/Includes/cpython/number.pxd
PyNumber_MatrixMultiply() and PyNumber_InPlaceMatrixMultiply() were
missing from number.pxd.
(https://docs.python.org/3.8/c-api/number.html).
> Add missing declarations to number.pxd

- .travis.yml
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/Optimize.c
- runtests.py
- tests/pypy2_bugs.txt
- tests/pypy_bugs.txt
- tests/pypy_crash_bugs.txt
- tests/pypy_implementation_detail_bugs.txt
- tests/run/callargs.pyx
- tests/run/cpp_stl_conversion.pyx
- tests/run/importfrom.pyx
- tests/run/kwargproblems.pyx
- tests/run/list_pop.pyx
- tests/run/modop.pyx
- tests/run/pep448_test_extcall.pyx
- tests/run/powop.pyx
- tests/run/pure.pyx
- tests/run/py_hash_t.pyx
- tests/run/with_gil.pyx
Reasoning being that this make it easier to catch pypy
regressions as they happen.
* Fixed some very simple pypy failures (largely to do with
different exception strings)
* Splits pypy_bugs.txt into four files
- one for bugs that cause hard crashes (which we don't want to
run in Travis at all);
- one for bugs that are probably unfixable because they're just
due to implementation details (e.g. when destructors are
called).
- one file for pypy2-only bugs
- all other bugs remain in pypy_bugs.txt
(The categorization has been done fairly quickly, so some bugs
may be in the wrong place)
* Made sure (hopefully) all bugs are now categorized, so a basic
runtests.py with pypy should hopefully pass
* Changed pypy to be required in Travis
* Added an extra (optional) test that runs through …
> Enable pypy as a required Travis test

- Cython/Includes/cpython/slice.pxd
PySlice_Unpack() and PySlice_AdjustIndices() were missing from
slice.pxd.
(https://docs.python.org/3.8/c-api/slice.html).
> Add missing declarations to slice.pxd

- setup.py
I was trying to sort out what the minimum version of cython that works on py38 is, thought I would check the trove clasifiers and discovered no version of cython reports supporting py38, hence the PR ;)
> BLD: update the trove classifier to include python 3.8

- Cython/Build/Dependencies.py
As far as I can tell, `cythonize(quiet=True)` also suppresses non-error and non-warning messages on `stdout`, like `f"Compiling {filepath} because it changed."`, `f"[{n}/{t}] Cythonizing {filepath}"`, etc.
It's a minor distinction in a single flag, but I ran into it when trying to write a `doctest` for `Shadow.inline()`.
> Slight adjustment to documentation of "quiet" parameter for `cythonize()`.

- docs/examples/quickstart/build/setup.py
- docs/examples/tutorial/cython_tutorial/setup.py
- docs/examples/tutorial/external/setup.py
- docs/examples/userguide/parallelism/setup.py
- docs/examples/userguide/sharing_declarations/setup.py
- docs/examples/userguide/wrapping_CPlusPlus/setup.py
- docs/src/quickstart/build.rst
- docs/src/tutorial/clibraries.rst
- docs/src/tutorial/cython_tutorial.rst
- docs/src/tutorial/external.rst
- docs/src/userguide/debugging.rst
- docs/src/userguide/numpy_pythran.rst
- docs/src/userguide/numpy_tutorial.rst
- docs/src/userguide/source_files_and_compilation.rst
- docs/src/userguide/wrapping_CPlusPlus.rst
While the directives in the source files are still called `distutils`,
[Python upstream
documentation](https://docs.python.org/3/library/distutils.html) does not
recommend using distutils anymore, and rather points at setuptools, so
avoid confusing new users by providing confusing legacy usage examples.
Also, this corrects one example in which Extension is imported too late,
and would cause annoying errors when running `setup.py`.
> In the documentation, update references to point at `setuptools`.

- Cython/Compiler/CythonScope.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/PyrexTypes.py
- tests/memoryview/cythonarray.pyx
so that they can be inherited from.
Closes https://github.com/cython/cython/issues/3396
> Marks view.* extension types as imported

- Cython/Compiler/Nodes.py
This ensures that the CPU's branch predictor will take the most likely branch when the function is run for the first time (in that situation, the branch predictor has no prior information about which branch is more likely).
> Mark missing argument errors as unlikely

- Cython/Shadow.py
- tests/run/pure_py.py
The following code:
```python
import cython
@cython.cclass
class Foo:
a: cython.double
b: cython.double
c: cython.double
def __init__(self, a: cython.double, b: cython.double ,c: cython.double):
self.a = a
self.b = b
self.c = c
def bar():
l = []
l.append(Foo(10, 20, 30))
v = cython.declare(Foo, l[0])
r = v.a + v.b
print( r )
v2 = cython.cast(Foo, l[0]) #Faster - No __Pyx_TypeTest() call
r = v2.b + v2.c
print( r )
bar()
```
works fine when compiled and throws an exception when interpreted: `TypeError: __init__() missing 2 required positional arguments: 'b' and 'c'`
It could be fixed if we change implementations as shown in the patch. However, I don't think I understand the reason behind the current implementation to change it that way.
Should the issue be fixed and if not what's the reason …
> __init__() call from cython.declare and cython.cast in Shadow.py

- Cython/Shadow.py
- tests/run/pure_py.py
Fixes `x = cython.declare(cython.int[20], list(range(20)))` which was broken in GH-3244
> Fixed initialization of the array with the list which was broken in GH-3244

- docs/src/userguide/source_files_and_compilation.rst
This removes the `setup_requires` reference that AIUI is deprecated, in
favour of the `pyproject.toml` file which is what is supposedly needed nowadays.
> Use PEP 518 indication for Cython build-time dependency.

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/FusedNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- tests/run/pure_fused.pxd
- tests/run/pure_fused.py
These were previously getting missed. Added code to specialize them
and tests to prove it.
Fixes https://github.com/cython/cython/issues/3142
Also fixes https://github.com/cython/cython/issues/3460 - (seems related enough to go in the same PR)
> Specialize fused function local variables specified with pure-python

- Cython/Debugger/libpython.py
Without this patch, cy exec 3+4 outputs:
> Python Exception <class 'gdb.error'> 'free' has unknown return type; cast the call to its declared return type: 
> Error occurred in Python: 'free' has unknown return type; cast the call to its declared return type
The problem was that cygdb ran gdb.parse_and_eval("free(ptr)") . I changed that to gdb.parse_and_eval("(void) free(ptr)") . This seems to work, but it would be nice if someone who actually knows what he is doing could check if this is correct.
> Fixed a bug that broke cy exec

- Cython/Utility/AsyncGen.c
- tests/run/test_asyncgen.py
* allow closing async generators that are already closed
https://bugs.python.org/issue39606
* Prevent double awaiting of async iterator
https://bugs.python.org/issue39386
* Fix ag_running; prohibit running athrow/asend/aclose in parallel
https://bugs.python.org/issue30773
* Fix asynchronous generators to handle GeneratorExit in athrow()
https://bugs.python.org/issue33786
* Ignore GeneratorExit in async_gen_athrow_throw
https://bugs.python.org/issue35409
* make async_generator_athrow object tolerant to throwing exceptions
https://bugs.python.org/issue38013
> Bring async generator implementation en par with current CPython 3.9 alpha.

- Cython/Compiler/FusedNode.py
- tests/compile/fused_wraparound.pyx
It seemed difficult to reliably change the directives
applied to the __pyx_fused_cpdef dispatch function,
so instead wrote code that should be generally valid
Fixes https://github.com/cython/cython/issues/3492 (and then indirectly https://github.com/pandas-dev/pandas/issues/33372)
> Fused functions safe with wraparound+boundscheck off

- Makefile
Use `manylinx2010` images to build `manylinux1` and `manylinux2010` at the same time.
> Partial #3354 - build manylinux2010

- CHANGES.rst
The current wording implies that users can expect it to work, which isn't really the current state.
It seems better not to claim too much until it's a bit more advanced.
> Caveat limited API in the changelog

- Cython/Compiler/ExprNodes.py
In the old version any assignment to a name (most significantly any functions or attributes of classes) was added to the module dictionary rather than wherever target was intended. This version largely reverts to the original assignment code (which looked to be limited-api-safe anyway).
The only extra thing it has to do is get the module dictionary since this isn't a global variable in limited-api mode.
I've not added any tests since this should be adequate covered by the main test-suite when it's enabled for the limited API (I really hope...)
---------------------
I'm not intending to try to fix much limited API stuff, but this was very low-hanging fruit.
> Fixed all assignments being added to the module in the limited API

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/FusedNode.py
- tests/run/fused_def.pyx
If the 5th argument of the regular functions was optional it'd
overwrite the _fused_sigindex default of the dispatcher, causing
type errors at runtime
closes https://github.com/cython/cython/issues/3511
> Prevent fused dispatcher optional arguments being overwritten

- Cython/Compiler/ExprNodes.py
Follows up https://github.com/cython/cython/pull/3517
1. Actually fixes https://github.com/cython/cython/issues/3430 by handling non-Python types correctly.
2. Fixes another uninitialized temp error that was appearing in the test generators_py
I'm struggling to see how to add tests for these unfortunately. I'm not sure if `werror` catches C compilation warnings, but the Cython code seems to create enough low-level warnings that it isn't usable anyway.
> Cleanup more generator temps

- Cython/CodeWriter.py
- Cython/Compiler/AutoDocTransforms.py
- Cython/Tests/TestCodeWriter.py
This allows it to support all kinds of expressions without duplicating code between the different writers.
See https://github.com/cython/cython/issues/3513#issuecomment-613849055
> Make CodeWriter inherit from ExpressionWriter

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ParseTreeTransforms.py
- tests/run/fused_cpp.pyx
- tests/run/fused_types.pyx
Gets the specialized type if possible from
NameNode.analyse_as_type
This does introduce a potential new bug:
```
cimport cython
from cython cimport floating
just_float = cython.fused_type(float)
cdef OK1(just_float x):
return just_float in floating
cdef fail1(just_float x, floating y):
return just_float in floating
cdef fail2(floating x):
return floating in floating
def show():
"""
>>> show()
True
True
True
True
"""
print(OK1(1.0))
print(fail1(1.0, 2.0))
print(fail1[float, double](1.0, 2.0))
print(fail2[float](1.0))
```
fail1 and fail2 work before this patch but fail with it. It isn't
clear to me if this should actually be considered a bug. It
works in both versions with `cython.floating`, which possibly
suggests analyse_as_type in AttributeNode should also be changed
Closes #3203
> Make C++ typeid accept specializations of fused types

- docs/src/userguide/external_C_code.rst
* Updated URL for the "embedding Python" link in external_C_code.rst
in the userguide.
* The freenet.org.nz domain has clearly expired at some point and now
the original link goes spam links, but there are copies in the
Wayback Machine.
* The updated (fixed) URL uses the most recent archive for the
original page (author: June, 2004; web archive: Feb, 2012).
> docs: external C code

- Cython/Compiler/ModuleNode.py
- tests/compile/ctuple_unused_T3543.pyx
generate_type_definitions maintained a list of ctuples for which code
was already generated, but the logic did not match the logic used in
generate_type_header_code, which does not generate code if the entry is
marked as unused.
If the first ctuple of a certain type was marked unused, but later
instances were not, this could result in no code being generated for
the ctuple at all. Resolve by verifying whether the ctuple entry is used
before adding it to the list.
> FIX: Ignore unused ctuples (GH-3543)

- Cython/Utility/ExtensionTypes.c
- runtests.py
- tests/pypy_bugs.txt
- tests/run/reimport_failure.srctree
Work around error that "`__reduce_cython__` cannot be found" when re-importing an extension module that was already initialised before.
Closes #3545.
> Work around error "__reduce_cython__ cannot be found"

- Cython/Compiler/Symtab.py
- docs/src/userguide/migrating_to_cy30.rst
- tests/run/methodmangling_T5.py
- tests/run/methodmangling_cdef.pyx
- tests/run/methodmangling_unknown_names.py
Allow C functions/variables with names starting with "__" to be found
from within classes, even though their names would normally be
inaccessible due to the Python "class private names" mechanism.
https://github.com/cython/cython/issues/3544
Where globals are looked up by name (e.g. with error_on_unknown_names =
False) make sure to lookup the mangled name
> Relax class private names for c types

- Cython/Compiler/Code.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Utility/ModuleSetupCode.c
Avoid acquiring the GIL at the end of nogil functions unless it's really necessary for the cleanup. Previously, the GIL qas unconditionally acquired whenever the function contained a with-gil block.
Closes #3554.
> Avoid acquiring the GIL at the end of nogil functions

- Cython/Distutils/old_build_ext.py
Noticed some prereleases so I thought this simple change could make it to the Cython3 release cycle.
Fixes #2209.
> Maintain a separate copy of distutils' build_ext options

- Cython/Utility/Buffer.c
- tests/buffers/buffmt.pyx
- tests/memoryview/numpy_memoryview.pyx
This is an attempt to address #1407. In particular the case where there is a struct with array members, followed by a single element of the same type, such as:
```cython
ctypedef struct SameTypeAfterArraysStruct:
double a[16]
double b[16]
double c
```
A new test is included for this also.  I _think_ this addresses the issue with no side-effects (based on a before and after comparison of the test suite results).  This is also my first PR to Cython and attempt to look into the code base, so my apologies if I have misused some terminology.
> Memoryviews of arrays of structs fix

- tests/run/numpy_attributes.pyx
Strangely, this test passes. It seems the argument name in a cdef getter is not important, since the name in [`ndarray.size`](https://github.com/cython/cython/blob/3.0a1/Cython/Includes/numpy/__init__.pxd#L265) is `ndarray`, not `self`.
> add tests for ndarray

- CHANGES.rst
- Cython/Utility/ModuleSetupCode.c
Reimplement __Pyx_PyDict_GetItemStrWithError() as a hacky version in Py2 to get the semantics right of returning a borrowed reference with non-KeyError exceptions left in place.
Closes https://github.com/cython/cython/issues/3578
Supersedes https://github.com/cython/cython/pull/3592.
> Reimplement __Pyx_PyDict_GetItemStrWithError() in Py2 to fix a refleak

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Optimize.py
- tests/run/fstring.pyx
Float objects as arguments do not support '{x:d}' formatting.
Closes https://github.com/cython/cython/issues/3092
> Fix optimised string formatting for '%d'

- Cython/Compiler/ModuleNode.py
For 3.5+ (where inittab should be used instead). Generates a warning for GCC, Clang
and MSVC.
I'm relatively confident of the MSVC version but haven't actually been able to test it so please don't merge without looking at the windows tests!
-------------------------
Related to https://github.com/cython/cython/issues/3510
This is an attempt to reduce the number of bug reports of "I'm embedding a module and it crashed" due to calling the init function. It obviously adds a little bit of not very readable boilerplate code, but I can't see a better way of doing it and I think the warning is worthwhile.
> Generate a compiler warning on PyInit_ModuleName

- Cython/Compiler/PyrexTypes.py
- tests/compile/ctuple_no_cast.pyx
- tests/windows_bugs.txt
Fixes #3038. 
Structs are not allowed to be casted according to the C standard, and MSVC gives the compile error `C2440` accordingly. This is already being accounted for structs directly, but not for ctuples.
I ran into this because python accessible `def` functions generate a wrapper and call the actual function with a argument list in which ctuples were casted, which resulted in a compiler error.
Can be tested with this code:
```
def test((int, int) t):
print(t)
```
(I hope the test case is correctly written)
> Fixed illegal casting of struct via ctuple

- Cython/Compiler/ParseTreeTransforms.py
- tests/run/parallel.pyx
This is @Celelibi's suggestion for https://github.com/cython/cython/issues/3594. It looks like the right idea - I just want to see which tests it fails for and why....
> Run ParallelRangeTransform on function arguments

- Cython/Includes/numpy/__init__.pxd
- tests/run/numpy_test.pyx
xref https://stackoverflow.com/questions/28184211/calling-pyarray-searchsorted-from-cython-3-or-4-arguments/28184301
> BUG: PyArray_SearchSorted signature

- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Pipeline.py
- tests/memoryview/memoryview_no_binding_T3613.pyx
When utility code is merged into the main module it gets wrapped in a CompilerDirectivesNode
Fixes https://github.com/cython/cython/issues/3613.
---------------------------
Based on the discussion in #3613 it looks like it may be worth turning off binding and the auto pickling (and https://github.com/cython/cython/commit/17af8d69966e3143038059cc00b35c06ad71a97d seems to be the start of an approach to do that). I haven't made any changes to that in this PR so the memoryview utility code will compile with the default directives I believe (but it will do so consistently now)
> Ensure utility code keeps the directives that it was compiled with

- tests/buffers/buffmt.pyx
An attempt to address #3620.
I'm not sure about the recommended way to make the tests conditional on the platform, however, hopefully this is ok. I'm very happy to readdress the the issue using a different method though if that is preferred.
Please note that I also do not have access to a 32bit OS to test this on (I attempted to use an i386 Alpine linux docker image but was unable to get things running).
I'll also add further discussion to #3620...
> Use platform dependent test for unpacked_struct_with_arrays

- Cython/Includes/numpy/__init__.pxd
copy paste of the `__init__.pxd` edits in https://github.com/numpy/numpy/pull/16266
> ENH: port numpy #16266

- CHANGES.rst
- Cython/Compiler/Nodes.py
- Cython/Compiler/Options.py
- Cython/Utility/FunctionArguments.c
- Cython/Utility/TestCythonScope.pyx
- docs/src/userguide/source_files_and_compilation.rst
- tests/buffers/bufaccess.pyx
- tests/compile/fused_redeclare_T3111.pyx
- tests/memoryview/memoryview.pyx
- tests/memoryview/memslice.pyx
- tests/run/always_allow_keywords_T295.pyx
- tests/run/cyfunction_METH_O_GH1728.pyx
- tests/run/exceptionrefcount.pyx
- tests/run/refcount_in_meth.pyx
- tests/run/unicode_identifiers.pyx
Avoid METH_O functions by default, since they do not match normal Python semantics.
Closes #3090.
> Change default of "always_allow_keywords" directive to True

- Cython/Compiler/FlowControl.py
- tests/errors/w_uninitialized.pyx
- tests/errors/w_uninitialized_cpp.pyx
I am not sure whether I put the tests in the right place. `typeid` should probably only be used in C++ mode.
Ideally, `type()` should also be supported, but since it's a python callable, it can be aliased in many ways that are not analayzable.
Closes #3575
> Initialization isn't required in sizeof or typeid

- Cython/Compiler/ModuleNode.py
- Cython/Utility/Builtins.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/Optimize.c
- tests/run/verbatiminclude.pyx
Py_SIZE() must not be used as an l-value anymore in Python 3.9:
Py_SET_SIZE() must be used instead:
* https://bugs.python.org/issue39573
* https://docs.python.org/dev/c-api/structures.html#c.Py_SET_SIZE
> Use Py_SET_SIZE() on Python 3.9.0a4 and newer

- Cython/Build/Dependencies.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/ParseTreeTransforms.py
Fixes https://github.com/cython/cython/issues/3647
At least one (in ModuleNode) is a real bug. The others are just
getting the code compatible with Cython again`
> Small changes to get `--cython-compile-all` working again

- Cython/Utility/CythonFunction.c
- tests/run/classmethod.pyx
...instead of deciding for itself that the type is invalid
Fixes https://github.com/cython/cython/issues/3658
> classmethod should fallback to always calling PyClassMethod_New

- Cython/Compiler/ParseTreeTransforms.py
From https://github.com/cython/cython/issues/3625#issuecomment-631931675
When you use Python type annotations, it would be weird if you lost Python exception propagation semantics along the way, just by compiling the code. So the default behaviour is "except? -1" here for C integer types.
Arguably, this would also be a better default for the decorator case.
> Check for exceptions also when @returns() is used, not only for "->" return type annotations

- Cython/Utility/CythonFunction.c
Rebased 1bb26b964060392ecb08c3b6c8ca4626e5c1eec7 for cython 0.29.x, and made conditional to Python 3.  This
does not solve the original staticmethod problem in Python 2 but it does
resolve classmethod problems in Python 3.9.  Therefore, it unbreaks
other packages on Python 3.9, improves overall state for Python 3
and does not introduce regressions in Python 2.
> Always bind Cython functions in py3

- Cython/Includes/cpython/unicode.pxd
In https://github.com/python/cpython/pull/20878 and https://github.com/python/cpython/pull/20941 some of the old unicode APIs began to produce compiler warnings to suggest usage of APIs added in py33 instead.
While some of the unicode API added in 3.3 is already in this file, not all of it is.  I have not gone through to see what else is missing.
I found this because pandas converts warnings to errors and they import `PyUnicode_GET_SIZE` in one of their pyx files.  Given that this has been backported to py39 I think this patch should be backported as far as possible in cython as well.
> MNT: expose PyUnicode_GET_LENGTH

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/PyrexTypes.py
- Cython/Utility/Buffer.c
- Cython/Utility/Builtins.c
- Cython/Utility/CConvert.pyx
- Cython/Utility/Coroutine.c
- Cython/Utility/ExtensionTypes.c
- Cython/Utility/FunctionArguments.c
- Cython/Utility/ImportExport.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
- Cython/Utility/Optimize.c
- Cython/Utility/TypeConversion.c
This adds an abstraction for accessing a types name and using it as part of `PyErr_Format`. We cannot just access `tp_name` since the `PyTypeObject` is an opaque type when compiling with the limited API enabled.
- Adds a `__Pyx_PyType_GetName()` function / macro that either uses `__Pyx_PyObject_GetAttrStr(tp, PYIDENT("__name__"))` when compiling for the limited API returning a unicode `PyObject*` or directly accesses the `tp_name` field of the type.
- Adds `__Pyx_TypeName` typedef.
- Adds `__Pyx_FMT_TYPENAME` containing the necessary string format specifier to format either the `PyObject *` or the `const char *` as necessary.
- Adds `__Pyx_DECREF_TypeName()` macro that decrements the `PyObject *` in the limited API case or does nothing otherwise.
- Introduce …
> Avoid using tp_name when CYTHON_COMPILING_IN_LIMITED

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ModuleNode.py
- Cython/Utility/Builtins.c
`PyModule_GetDict` is part of the limited API so we can keep a reference
to the module dict around regardless of limited mode being enabled or
not. This simplifies the code.
> Keep reference to module dict around in limited mode

- Cython/Compiler/FlowControl.py
- tests/compile/tryfinally.pyx
Fixes #3712 (hopefully) by reverting a small part of bbef4d7
Should be applied to 0.29.x and 3.0 branches
> Flow control and names in finally blocks

- Cython/Compiler/Code.py
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/FusedNode.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- tests/run/cpp_classes.pyx
Backports 92147baf11071352ffbfa475d0d21e091753e628.
* Fix a temp leak in the type init code.
* Fix temp leaks in fused types initialisation code.
* Correctly release the buffer index temps allocated for index calculations.
* Make tests fails hard if a temp variable is not released at the end of a generated function.
* Fix temp leak in switch statement code.
* Make end-to-end tests fail on refnanny output.
* Fix result temp leak in PyTypeTestNode.
* Fix result temp leak in external type/function import code and enable the refnanny check for them.
* Fix temp leak when try-return-finally is used in generators.
* Make it explicit when an allocated temp is not meant to be reused.
* Fix temp leak when assigning to the real/imag attributes of complex numbers.
* Fix temp leak when assigning to a …
> Validate and fix temp releasing (GH-3708)

- Cython/CodeWriter.py
- Cython/Tests/TestCodeWriter.py
> Fixes CodeWriter for `cdef` functions aka. CFuncDefNode.

- Cython/Utility/StringTools.c
Update __Pyx_PyUnicode_Substring().
Closes https://github.com/cython/cython/pull/3677
> Avoid calling PyUnicode_FromUnicode() in Py3

- docs/src/tutorial/pure.rst
Mainly by moving it to a separate section to make it easier
to find, however also added a small amount of extra information
about some of the obvious limitations
> Improved documentation for annotation typing

- Cython/Utility/TypeConversion.c
> Fix #2749 - Cython 0.29 broke support for C++ enum classes.

- Cython/Includes/cpython/buffer.pxd
Ensure that Cython exposes `PyBUF_MAX_NDIM` from Python as part of `cpython.buffer` to allow access to developers.
> Define extern `PyBUF_MAX_NDIM`

- Cython/Compiler/Nodes.py
- Cython/Compiler/Parsing.py
- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
- Cython/Utility/CpdefEnums.pyx
- tests/run/cpdef_enums.pxd
- tests/run/cpdef_enums.pyx
- tests/run/cpdef_scoped_enums.pyx
Fixes #3805.
This adds support for "class" level docs when a enum is declared with `cpdef` and the docs should show up under `__doc__` in python. It also supports writing docs for `cdef enum` (and enum from `cpp` I believe) in the same style, but the docs won't be stored anywhere in that case.
The only issue currently is that the enum code is generated from `CpdefEnums.pyx`. What this means is that we manually handle dumping the docstring to the generated code. However, I'm not sure how to handle quote mixing. I.e. I just put triple-quotes around the text, but this would break if the original text e.g. was quoted with triple-single-quotes and has a triple-quote in the text itself. There's probably some standard way of escaping such generic text, but I'm not sure what it is.
Also, I wasn't …
> Add doc support for cpdef enum

- Cython/Compiler/Errors.py
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/FusedNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/PyrexTypes.py
- tests/errors/fused_types.pyx
Fixes https://github.com/cython/cython/issues/3820 (and probably some other bugs too)
Originally part of https://github.com/cython/cython/pull/3845.
-----------
It's pretty hard to test if a fused type specializes expect by doing it. For example, the specialization may go through a chain of const and pointer types. The I've changed the exception that this produces to make it more identifiable (rather than a generic Python KeyError). I've applied this to `cdef fused_type var`, `var: fused_type = something` and `sizeof(fused_type)` as well as a fused return type. All of these previously caused compiler crashes.
> Fixed assorted crashes with fused types

- Cython/Compiler/PyrexTypes.py
- tests/memoryview/memoryview.pyx
- tests/run/cfunc_convert.pyx
Fixes https://github.com/cython/cython/issues/3843
Final smaller part of https://github.com/cython/cython/pull/3845
--------
The most notable change here is that I made the cfunc wrappers use the name escaping mechanism that was already in `PyrexTypes.type_identifier`. This seemed more satisfactory than just replacing unknown characters with `_` (as was the status quo), and it's a tested mechanism used elsewhere in the code.
> Allow creation of wrappers for cdef functions with memoryviews

- Cython/Compiler/ModuleNode.py
`xml.etree.ElementTree.Element.getiterator()` was deprecated in Python [2.7](https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator) & [3.2](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator) and removed in Python [3.9](https://docs.python.org/3.9/whatsnew/3.9.html#removed).
This is currently crashing in the recently released Python 3.9 so I think it also needs to be backported to the 0.29.x releases.
> Replaced Element.getiterator() with Element.iter().

- Cython/Compiler/ModuleNode.py
`xml.etree.ElementTree.Element.getiterator()` was deprecated in Python [2.7](https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator) & [3.2](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator) and removed in Python [3.9](https://docs.python.org/3.9/whatsnew/3.9.html#removed).
This fixes the same issue as #3864, but targets the `0.29.x` branch which still supports Python 2.6.
> Preferred Element.iter() to Element.getiterator().

- Cython/Plex/Actions.pxd
- Cython/Plex/Actions.py
https://github.com/cython/cython/pull/3846 suggests that the code is broken since it won't be able to access the private attributes of the untyped "other". It looks to be unused since this doesn't cause any errors
--------
This is based on the warnings from https://github.com/cython/cython/pull/3846 that look like legitimate errors. The rest are mostly `cpdef` functions not being accessed as efficiently as possible which is less of a concern.
> Removed `same_as` from Plex.Actions.Action

- Cython/Utility/CppSupport.cpp
Relates to https://github.com/cython/cython/issues/3789
Right now I'm interested in if this gives any appveyor test failures. I think (but not 100% sure) that these versions should support `std::move`
> Try detecting _MSC_VER for __PYX_STD_MOVE_IF_SUPPORTED

- Cython/Compiler/Nodes.py
- tests/run/fused_types.pyx
Fixes https://github.com/cython/cython/issues/3881
I think this approach is more satisfactory than the old way it used to "work", where "fused_to_specific" was permanently added to the module scope containing the fused type (in this case the Cython scope), was applied in "Scope.lookup_type", but continued to have an effect on the scope forever.
Probably should be backported to 0.29 since it's fixing a regression there too.
> Fix memoryview casts involving fused types

- Cython/Compiler/Parsing.py
- tests/compile/cpp_templates_nested.pyx
Fixes #1355 
As noted in https://github.com/cython/cython/issues/3885, declarations such as the following currently fail:
```
cdef vector[vector[const int]] x
```
When the parser sees `cdef vector[...]`, it calls `looking_at_expr` [here](https://github.com/cython/cython/issues/3885) to figure out if `...` is an expression. Currently, that returns `True`. The approach taken here is to ensure it returns `False` so that `...` is parsed correctly as a _type_. I hope this the right way to go about it.
> [RFC] Fix const in nested template arg

- .travis.yml
- runtests.py
- tests/build/common_include_dir.srctree
It looks like it was the "common_include_dir" test that was timing out on OS X Python 3. This is fixed by setting nthreads to 0 (although it remains to be seen if the method I've picked to do it works)
> Fix "common_include_dir" test on OS X on Travis

- Cython/Compiler/FusedNode.py
- Cython/Compiler/MemoryView.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/PyrexTypes.py
- Cython/Utility/MemoryView.pyx
- Cython/Utility/MemoryView_C.c
- tests/memoryview/memoryview.pyx
Fixes https://github.com/cython/cython/issues/3827
Two commits (before review): the first fixes the crash, the second renames `__PYX_XDEC_MEMVIEW` to `__PYX_XCLEAR_MEMVIEW` to hopefully make it more obvious what effect it actually has.
> Fix memoryview self-assignment crash

- docs/src/userguide/external_C_code.rst
This is the point where I got stuck when creating bindings for a C-library. Luckily I got help in the comments: https://github.com/cython/cython/issues/3388#issuecomment-683672261. Later I found that there was some (minimal) documentation on `&`. I added a small sub-chapter to 'Interfacing with External C Code' to help noivce users who want to access external C-libraries that use functions with pointers. I linked to the cython documentation on differences with C pointer syntax.
Background information. I have been creating [bindings](https://github.com/rhpvorderman/python-isal) for the [isa-l](https://github.com/intel/isa-l.git) library. This required me to look at `zlibmodule.c` (from cpython) quite a lot. Both isa-l as `zlibmodule.c` contain a lot of pointers and pointer manipulation, so …
> Add small pointer guide in 'Interfacing with External C Code' chapter

- Cython/Utils.py
- tests/build/cythonize_pep420_namespace.srctree
In my understanding the mechanism for cimporting namespace packages that was implemented in #2946 differs from the way the standard CPython PathFinder would find the file to load.
Consider the following structure:
```
a/b/__init__.py
a/b/c/d.py
```
CPython3 allows importing `a.b.c.d`. In my understanding it implicitly creates a namespace package `a.b.c`.
Cython doesn't consider a.b.c a namespace package because `a.b` is a regular package as `a/b/__init__.py` exists.
This patch adds a test exposing the problem as well as an implementation of the following solution: if a directory contains a __init__p{y,xd} file, let's treat all its subdirectories as regular packages as well. This would be closer to what CPython's PathFinder does.
> Support namespace packages inside regular packages

- Cython/Utility/Coroutine.c
The C-API function applied in previous commit (https://github.com/cython/cython/commit/b37607f46b165e81f7af2b4eec2ae7f76f7717df) is now also obsolete.
This patch works for cython 0.29 and cpython after (https://github.com/python/cpython/commit/1e996c3a3b51e9c6f1f4cea8a6dbcf3bcb865060#diff-d2c90d06d281ca8dd7ac8b90109fc26755f7319dd209b5f9416efdecfa56e289).
issue #3876
> [0.29] Fix usage of undefined C-API "_PyGen_Send" in Py3.10 with "PyIter_Send".

- Cython/Includes/cpython/fileobject.pxd
- tests/run/cython_includes.pyx
(https://docs.python.org/3.9/c-api/file.html).
PyObject_AsFileDescriptor() is already present in object.pxd.
> Add fileobject.pxd

- Cython/Utility/Coroutine.c
- Cython/Utility/ObjectHandling.c
- Cython/Utility/arrayarray.h
Replace direct access to PyObject members with functions like
Py_TYPE() and __Pyx_SET_SIZE().
> Use Py_TYPE() and __Pyx_SET_SIZE() functions

- Cython/Includes/cpython/pycapsule.pxd
Eliminate C compiler warnings by making the constness of the
char* pointers in the declarations in pycapsule.pxd match
the actual types of the PyCapsule_* functions.
> MAINT: Add const qualifiers to char* types in pycapsule.pxd.

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/Nodes.py
- tests/compile/complex_annotations.pyx
- tests/compile/complex_decorators.pyx
Generating utility-code for complex types is special-cased, but
it wasn't when they were generated in annotations.
Fixes https://github.com/cython/cython/issues/3949
> Fix missing utility code for complex annotations

- Cython/Compiler/Optimize.py
- Cython/Utility/Optimize.c
- Cython/Utility/TypeConversion.c
This ensures that `float("1_2_3")` conversions (with underscored numbers) are handled correctly
whether or not the argument type is known.
Fixes https://github.com/cython/cython/issues/3958 (and thus the
currently broken builtin_float test)
--------------
I suspect a similar inconsistency may apply with integer conversions too - that isn't looked at here.
> Always use "new" string->float conversions

- Cython/Compiler/ParseTreeTransforms.py
- tests/errors/declareafteruse_T158.pyx
In 0.11.1 is was marked as an warning that would become an error.
3.0 is probably either the time to make it an error.
----------
Alternatively, I can leave it as warnings and change these to a test for warnings. I just doing think it make sense to leave it as "future_errors" permenantly.
> Changed "declared after use" warning to error

- Cython/Includes/cpython/long.pxd
These functions are available since Python 2.7.
Close #3980
> Expose "long and overflow" cpython functions

- Cython/Compiler/Nodes.py
- tests/errors/cpdef_vars.pyx
Allowing these gives people the false impression that they
do something meaningful. "Fixes" https://github.com/cython/cython/issues/3959
0.29.x version of https://github.com/cython/cython/pull/3963/files, with a warning instead of an error.
> Warning message on cpdef variables (0.29.x)

- tests/errors/fused_types.pyx
It was broken in #3976 (because it added another error message)
> Fixed fused_types error test

- Cython/Compiler/ExprNodes.py
- tests/run/cimport.srctree
> Don't break when probing type of cimported module

- runtests.py
It uses features that are unavailable thus always fails
Test was introduced in https://github.com/cython/cython/pull/3767
> Disable time_pxd test in Python 3.4

- tests/run/test_exceptions.pyx
The test.support (which sould not be used outside Python!) has been
splitted into sub-modules. Adapt test_exceptions for these changes.
> Port test_exceptions to Python 3.10

- Cython/Utility/ImportExport.c
PyPy does not support `PyImport_GetModule` yet: https://foss.heptapod.net/pypy/pypy/-/issues/3385
> PyImport_GetModule unsupported in PyPy

- Cython/Compiler/Code.py
- Cython/Utility/ObjectHandling.c
- Cython/Utility/TypeConversion.c
XCode warns about dead code, when a if statement always evaluates to false. This warning can be silenced using an extra '()'
> Fix compiler warning on xcode

- tests/run/generators_py35.py
I.e. works on Python 3.10+
Backported from 3dc2b9dfc23638fbef2558d619709b5235d5df08
Part fix for #3919
> Annotation tests work with non-evaluated annotations

- Cython/Utility/ModuleSetupCode.c
Even though the Python documentation states, that PyUnicode_KIND will return an int,
it actually returns a value of the underlying type of the PyUnicode_Kind enum.
This could be e.g. an unsigned int which can cause warnings about signed/unsigned comparisions.
> always return int from __Pyx_PyUnicode_KIND

- Cython/Compiler/Nodes.py
- tests/run/cpp_nested_classes.pyx
That fixes the following code:
```
ctypedef unordered_map[string, vector[string]] string_to_strings
cdef string_to_strings.iterator it
```
See for details: https://github.com/cython/cython/issues/2233
> Allow using nested types of typedefs

- .travis.yml
Mostly with the hope that the tests pass. Ideally we should
support the most recent version.
~I picked 0.9.5 because that's the last version to support Python 2, and that still appears to work~
Trying ~0.9.8~ 0.9.7.
> Temporarily pin Pythran version

- Cython/Utility/Builtins.c
- tests/run/set.pyx
part of #3919.
Wants backporting to 0.29.x
> Don't test for frozenset singleton on Python 3.10

- tests/run/test_asyncgen.py
The loop parameter of asyncio.sleep(), deprecated in Python 3.8, has
been removed in Python 3.10. asyncio.sleep() gets implicitly the loop
in Python 3.10 and it is safe to do the same on Python 3.6:
https://docs.python.org/dev/whatsnew/3.10.html#changes-in-the-python-api
> Port test_asyncgen to Python 3.10

- Cython/Utility/CythonFunction.c
- tests/run/function_self.py
The `__self__` argument should be present only for bound functions.
Fixes #4036
Currently it isn't easily possible to get this working absolutely
correctly for fused functions. I raise an attribute error but
`hasattr` still returns True
Additionally, Python 2 methods always have a `__self__` attribute
but set it to None. I follow Python 3 behaviour and don't have
the attribute
> Fixed CyFunction __self__ attribute

- Cython/Compiler/Nodes.py
- Cython/Utility/ObjectHandling.c
- tests/run/test_genericclass.py
Fixes https://github.com/cython/cython/issues/3537
Both the C code and the tests are largely copied from CPython
so hopefully should be pretty reliable.
This doesn't backport perfectly so I've hard to disable a few
tests of Python 2 (and may have to on earlier Python 3 versions too).
I think that's OK.
I haven't applied this at all to cdef classes. Maybe it could be
applied to the second+subsequent bases but I don't think it's
needed for the initial implementation.
> Implement PEP560 inheritance (__mro_entries__)

- setup.cfg
Closes #3854 
See
- https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
- https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#metadata
When building wheels, ensure `wheel>=0.32.0` (2018-09-29) is used.
> Instruct setuptools and wheel to include the license files

- Cython/Compiler/ModuleNode.py
For something I use Cython for, we do not use `setup.py` or anything like that, but add the output of Cython (i.e., the .c files) to our CMakeLists.txt.
However, for the rest of the code in our project, we already have `PY_SSIZE_T_CLEAN` set as a compile-time define (e.g., with `add_definitions(-DPY_SSIZE_T_CLEAN)`. This causes us an issue when we're compiling the output of Cython, as we get a warning (which becomes an error with `-Werror`) related to `PY_SSIZE_T_CLEAN`.
This PR changes Cython such that `PY_SSIZE_T_CLEAN` is only defined in the Cython-generated code, if it is not already defined.
Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>
> Only #define PY_SSIZE_T_CLEAN if it is not already #defined

- tests/run/powop.pyx
Fix optimised_pow2_inplace() doctest on Python 3.10: the error
message change.
Python 3.9 error message:
unsupported operand type(s) for ** or pow(): 'int' and 'str'
Python 3.10 error message:
unsupported operand type(s) for **=: 'int' and 'str'
> Fix optimised_pow2_inplace() on Python 3.10

- .gitignore
- runtests.py
Creating global CDEFS for holding compiler definitions. Then pass it to the distutils.
Also add .vscode folder to .gitignore
Fixes https://github.com/cython/cython/issues/4096
> Bug 4096 (Using CFLAGS for compiler defines)

- Cython/Compiler/Optimize.py
- Cython/Compiler/TreePath.py
- Cython/Compiler/Visitor.py
- tests/run/cstringmul.pyx
This just finishes off https://github.com/cython/cython/pull/3952 by adding a test-case.
It's surprisingly hard to create a test-case for this. I had to allow bytes-to-string comparisons in the TreePath code (allowing bytes constants might be another possibility I think). I've confirmed that it fails on the current master and passes with the patch.
> String constant folding (with test)

- Cython/Compiler/Annotate.py
Hi,
Just a quick fix for a common omission: the HTML report generated during compilation styles the line background colour, but does not do so for the text on top of it.  I guess most people have their browser set to black text on white background so don't notice, but mine is white on black—the report ends up somewhat difficult to read with white text on a white/yellow background!
Hopefully this PR is all that's needed? Let me know if there are any problems.
> Explicit black text colour for line readability in reports

- Cython/Compiler/Nodes.py
- Cython/Utility/ExtensionTypes.c
- tests/run/cdef_multiple_inheritance_cimport.srctree
This implements the fix of always using `__Pyx_PyType_Ready`. Another alternative would be to introduce syntax, like `cdef class Sub(Base, ...)` to indicate just those classes that need this special treatment.
As PyGC_Head is no longer visible, we can't use the trick of placing it before the type, so I made gc enabling/disabling a bit cheaper.
> Allow inheriting from cimported multiply inherited class.

- Cython/Compiler/PyrexTypes.py
(no test in this PR because it's only really an issue when
doing things like PrintTree)
> Fixed CReferenceBaseType.__repr__

- docs/examples/userguide/external_C_code/platform_adaptation.pyx
For reasons I don't full understand, including "windows.h" seems to break everything. There's an alternative sleep function in stdlib.h so I've used that instead since it makes the point just as well
> Fix platform_adaptation on windows

- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
- Cython/Utility/Optimize.c
- Cython/Utility/StringTools.c
Also prepare for Py3.12 where "PyUnicode_WCHAR_KIND" will be removed.
See https://www.python.org/dev/peps/pep-0623/
Closes https://github.com/cython/cython/issues/3925
> Make "__Pyx_UnicodeContainsUCS4()" work for WCHAR unicode strings with Py3.9+.

- Cython/Build/IpythonMagic.py
- Cython/Build/Tests/TestIpythonMagic.py
Fixes #3751 as discussed [here](https://github.com/cython/cython/issues/3751#issuecomment-702725848)
Some compilers (MSVC) and linkers write errors to stdout (and not stderr), so we need to catch both and if an error caught, redirect both to sys.stderr.
After fix, for this code:
```
%%cython
cdef extern from *:
"""
xxxx a;
"""
int a;
def doit():
return a
```
Shows error:
```
.../_cython_magic_0c7dc5ea1c624caa7d5b6b78d977eedea31eb934.c:622:5: error: unknown type name ‘xxxx’
xxxx a;
```
on Linux and
```
_cython_magic_18af9232b2d51cf1c8df01fd5af261c66fd7b162.c
...\_cython_magic_18af9232b2d51cf1c8df01fd5af261c66fd7b162.c(610): error C2061: syntax error: identifier 'a'
...\_cython_magic_18af9232b2d51cf1c8df01fd5af261c66fd7b162.c(610): error C2059: syntax error: ';' …
```
> Capturing and redirecting stdout/stderr for %%cython-magic

- Cython/Compiler/ExprNodes.py
- tests/memoryview/memoryview_inline_pxd.srctree
Fixes #1415
The utilitycode was generated at too late a stage, after the
utilitycode from the pxd was merged into the pyx scope.
> Include utilitycode for inline memoryview functions

- Cython/Build/Dependencies.py
- Cython/Compiler/ModuleNode.py
The fix in https://bugs.python.org/issue39432 isn't quite right (`"_name".encode("punycode") != "name".encode("punycode")`) and thus the unicode_imports test is failing on Windows 3.8+. I don't think Python is accepting patches to distutils any more but I'm going to submit one of setuptools in the near future.
For now just apply the hack to all versions >3.5
Link to distutils PR https://github.com/pypa/distutils/pull/38
This creates a dummy function with the alternative name so that the export doesn't fail.
> Fix windows linking error for unicode modules with a dummy function

- Cython/Compiler/ExprNodes.py
- tests/run/cyfunction_defaults.pyx
- tests/run/py34_signature.pyx
Fixes https://github.com/cython/cython/issues/4061.
Code is adjusted per discussion in issue to always add value to `default_args` or `default_kwargs`.
> Preserve default arguments values on methods for introspection

- Cython/Utility/ModuleSetupCode.c
There is a small typo in Cython/Utility/ModuleSetupCode.c.
Should read `equivalent` rather than `equalivalent`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, equalivalent -> equivalent

- Cython/Utility/Builtins.c
- Cython/Utility/Coroutine.c
- Cython/Utility/CythonFunction.c
- Cython/Utility/ObjectHandling.c
Don't access directly PyObject.ob_type and PyObject.ob_refcnt
members.
> Use Py_TYPE() and Py_REFCNT() macros

- runtests.py
Running ` python runtests.py -vv --debug cpdef_enums` on Windows with Python 3.7 I get the following error.
```
======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c/cy2) and running cpdef_enums
----------------------------------------------------------------------
File "runtests.py", line 1306, in run
ext_so_path = self.runCompileTest()
File "runtests.py", line 975, in runCompileTest
self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
File "runtests.py", line 1240, in compile
so_path = self.run_distutils(test_directory, module, workdir, incdir)
File "runtests.py", line 1112, in run_distutils
self.copy_files(test_directory, workdir, related_files)
File …
```
> Don't use symbolic links on Windows, it requires admin account.

- Cython/Compiler/Optimize.py
- Cython/Compiler/Visitor.py
- tests/run/builtin_types_class.py
Fixes https://github.com/cython/cython/issues/3954.
The problem seems to be that __Pyx_CallUnboundCMethod0 optimizes
the call incorrectly. This patch avoids it getting sent to
that mechanism.
> Fixed __class__() lookup on builtin types

- Cython/Compiler/ExprNodes.py
- Cython/Compiler/PyrexTypes.py
- tests/run/cpp_static_method_overload.pyx
Closes #1851
Not sure if the approach I'm taking here is the best, but I tracked the issue down to overloads not being properly accounted for in `AttributeNode.analyse_as_type_attribute`.
> [RFC] Enable overloaded extern static methods (GH #1851)

- Cython/Utility/TypeConversion.c
- tests/run/builtin_float.py
See issue #4143 
The implementation of __Pyx__PyNumber_Float() wasn't checking whether errors occurred on the calls to __Pyx_PyUnicode_AsDouble(), __Pyx_PyBites_AsDouble(), and __Pyx_PyByteArray_AsDouble(). Errors from those functions are now properly propagated to the caller.
I didn't understand the `@cython.test_assert_path_exists` decorators on some of the tests in that file. Please let me know if this new test needs such a decorator.
> Fixes #4143: Can't catch ValueError from float() calls

- .github/workflows/ci.yml
- Tools/ci-run.sh
Github Action: https://github.com/Endle/cython/actions/runs/837909611
It could generate an artifact for code coverage https://github.com/Endle/cython/actions/runs/837909611
However, some tests are failing when enabling coverage
```
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-39-x86_64-linux-gnu.so", line ?, in line_trace.run_trace
Failed example:
run_trace(py_add, 1, 2)
Exception raised:
File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/doctest.py", line 1336, in __run
exec(compile(example.source, filename, "single",
File "<doctest line_trace.run_trace[2]>", line 1, in <module>
run_trace(py_add, 1, 2)
File "tests/run/line_trace.pyx", line 230, in line_trace.run_trace (line_trace.c:6817)
try:
File …
```
> Add Code Coverage

- Cython/Utility/ObjectHandling.c
This is caused e.g. by:
```
__pyx_t_8 = __Pyx_PyObject_FastCall(__pyx_t_7, __pyx_callargs+1-__pyx_t_9, 1+__pyx_t_9);
```
from
```
code.putln("%s = __Pyx_PyObject_FastCall(%s, __pyx_callargs+1-%s, %d+%s);" % (
self.result(),
function,
arg_offset_cname,
len(args),
arg_offset_cname))
```
As an alternative the explicit conversion could be placed in each `__Pyx_PyObject_FastCall` call.
> fix implicit sign conversion warning

- Cython/Utility/AsyncGen.c
- Cython/Utility/Buffer.c
- Cython/Utility/Coroutine.c
- Cython/Utility/CythonFunction.c
- Cython/Utility/Exceptions.c
- Cython/Utility/ImportExport.c
- Cython/Utility/MemoryView_C.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
- Cython/Utility/Optimize.c
- Cython/Utility/StringTools.c
This implements the changes from #4149 that do not involve the code generation, so the review of those changes gets simpler.
> silence unused warnings in universal way

- Cython/Compiler/Nodes.py
- runtests.py
- tests/run/pep557_dataclasses.py
- tests/run/pep563_annotations.py
This patch fixes a problem with using dataclasses in Cython. Using Cython master, the following code:
```py3
import dataclasses
@dataclasses.dataclass
class Foo:
bar: int
print(Foo(1))
```
Fails with:
```pytb
File "<stdin>", line 1, in <module>
File "x.py", line 11, in init x
print(Foo(1))
TypeError: __init__() takes 1 positional argument but 2 were given
```
This is because decorated classes do not have an `__annotations__` attribute. The root cause of this problem is that annotations are looked for after wrapping the class with the decorator(s), and since `SimpleCallNode` does not forward the class' annotations, none are found. This patch fixes the problem by checking for annotations before wrapping the class.
> Fix annotations for decorated classes

- Cython/Compiler/Nodes.py
The condition wasn't triggering so code wasn't being tested
(#4163). This is applies to:
```
def f(vector[double] x):
pass
```
which should now generate:
```
__pyx_v_a = __pyx_convert_vector_from_py_double(values[0]); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 5, __pyx_L3_error)
...
__pyx_r = __pyx_pf_4cnvt_f(__pyx_self, __PYX_STD_MOVE_IF_SUPPORTED(__pyx_v_a));
```
I haven't included any specific tests because I think it should be
covered by the existing test-suite (now that it works) and it's only
a performance improvement - it doesn't allow any new behaviour.
> Fix move-if-supported for function wrappers

- Cython/Compiler/ExprNodes.py
- runtests.py
- tests/compile/cpp_temp_assignment.pyx
When compiling pyarrow with cython 3.0 we get an error about the copy
constructor of an object has been deleted on the generated context switch code.
This PR fixes it.
I'd like to add a unit test, but would need some input on which folder
or file under tests is a good place for it.
> Use std::move in c++ during yield context switch.

- .github/code-of-conduct.md
- .github/report-handling-manual.md
A code of conduct is a good thing for an open source project to have. It is a welcoming signal to many people, especially from underrepresented groups. Also, while it will hopefully never need to be used, it is good to have in place before an incident happens rather than having to then figure out what to do.
NumFOCUS, of which Cython is an affiliated project, recommends all its projects to have a CoC. And requires a CoC for new projects joining NumFOCUS (Cython joined before that was the case).
This CoC is taken over from the [SciPy CoC](http://scipy.github.io/devdocs/dev/conduct/code_of_conduct.html) with no changes other than replacing the project name and removing the parts regarding a Steering Council (which Cython doesn't have as a formal body - in one place it was replaced by …
> Add a Code of Conduct, and a reporting manual for it

- Cython/Includes/libcpp/utility.pxd
@scoder this works around the broken __cplusplus macro in msvc (https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/)
The same issue was fixed for the `__PYX_STD_MOVE_IF_SUPPORTED` macro here: https://github.com/cython/cython/pull/3792
> fix move on msvc

- Cython/Includes/libcpp/memory.pxd
- tests/run/cpp_smart_ptr.pyx
As discussed in [this StackOverflow answer](https://stackoverflow.com/a/67631211/5085211), having the `operator=` around enables us to assign `shared_ptr[Derived]` to `shared_ptr[Base]`.
Now admittedly, as the question will suggest, I'm new to C++ Cython and in particular I would be unable to see what pitfalls this might have, but it does work as intended in my particular use case.
> [ENH] Add operator= to shared_ptr for assignments to base classes

- Cython/Compiler/FlowControl.py
- Cython/Compiler/TypeInference.py
- tests/run/for_in_string.pyx
This broke C++ map iteration code, which needs a better fix.
See https://github.com/cython/cython/issues/4171
Reverts https://github.com/cython/cython/pull/4077
> Revert "optimize enumerate with start argument"

- docs/src/userguide/special_methods.rst
Continuation of #3626, closes #2090
I couldn't figure out how to make the intersphinx label work. According to https://webknjaz.github.io/intersphinx-untangled/docs.python.org/, which I found via sphinx-doc/sphinx#6659, 
```
:py:function:`functools.total_ordering` 
```
should have worked but it didn't. :shrug:
> DOC: add documentation for total_ordering

- Cython/Compiler/ParseTreeTransforms.py
- tests/run/cpp_classes_def.pyx
The problem was they were being skipped with SkipDeclarations.
Fixes https://github.com/cython/cython/issues/4212
> Fixed optimizations in defined cppclass

- Cython/Utility/CythonFunction.c
MSVC appears not like like `#if/#else` with an macro call. Hopefully fixes https://github.com/cython/cython/issues/4202
> Fix compile error preventing building in MSVC

- Cython/Utility/Builtins.c
In commit 1027db04fb7c5b, the qualification for PyPy was removed from this `#ifdef`. That will break pypy users for v7.3.3 and earlier (pypy v7.3.4 was released 2021-04-08). This PR replaces that commit with a more nuanced version.
xref #4234
> tweak 1027db04 for older versions of PyPy

- docs/src/userguide/glossary.rst
- docs/src/userguide/wrapping_CPlusPlus.rst
It looks like putting the title between `.. glossary::` and the
entries messed it up
> Glossary was broken

- tests/run/cpp_nonstdint.h
This was causing a (correct) warning
> delete -> delete[] in cpp_nonstdint test

- Cython/Compiler/ExprNodes.py
- tests/run/pep526_variable_annotations.py
- tests/run/pyclass_annotations_pep526.py
> Don't let Py-class annotations set a type

- docs/src/userguide/language_basics.rst
This PR updates error message in documentation to latest format. Code snippet based on documentation generates following error:
```
$ cython -2a test.pyx
...
$ cython -2a test.pyx
...
cdef char *s
pystring1 = 'a'
pystring2 = 'b'
s = pystring1 + pystring2
^
test.pyx:5:14: Storing unsafe C derivative of temporary Python reference
```
> Update error message in documentation

- Cython/Compiler/ParseTreeTransforms.py
- tests/run/annotation_typing.pyx
Fixes #4243 (and probably a bunch more annotation bugs)
AnnotationNode doesn't have any child_attrs/subexprs because
it mostly doesn't want to be analyzed (it's just transformed to
an evaluable string). However this means that InterpretCompilerDirectives
wasn't visiting its children to set is_cython_module and so the
typing was failing. I've special-cased InterpretCompilerDirectives
to visit AnnotationNode fully.
> Set is_cython_module on annotations correctly

- Cython/Debugger/Tests/TestLibCython.py
more #4249 problems, this time with run_distutils. Make it a bit more verbose so it is clear how the differently-named arguments map to each other.
> fix call to run_distutils

- Cython/Compiler/Code.py
- Cython/Compiler/ExprNodes.py
- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Symtab.py
- tests/run/cpp_optional_temps.pyx
- tests/run/cpp_optional_temps_unused.pyx
1) Entry utility_code wasn't being imported unless the entry
was visibly used. The utility code is needed for the definition
even if unused. I think
this is what utility_code_definition is for, but I'm not completely
sure. I also had to add some calls to ensure it's used.
Not confident that this is solved the right way
2) CppOptionalTempCoercions weren't being moved correctly. Tested by
printing from the destructor.
3) cdef-class attributes weren't being created or destroyed correctly.
Tested by printing from the destructor
> Fix a few bugs in cpp_locals

- Cython/Shadow.py
The directives are called `optimize` rather than `optimization` (unless I'm missing something?)
> Shadow.optimization -> Shadow.optimize

- Cython/Includes/libcpp/string.pxd
- tests/run/cpp_stl_string.pyx
`libcpp.string.npos` maps to `std::npos`, which is wrong and does not compile.
This PR fixes the bug as discussed in #4268 and also adds a few missing `std:::string` members.
I haven't run the test cases myself yet, so CI may fail. If that's the case, I'll fix them later.
> Fix std::string::npos and add missing std::string members

- docs/examples/tutorial/external/keyword_args_call.py
- docs/examples/tutorial/external/keyword_args_call.pyx
In header of each documentation is said:
> To make good use of the latter, including C data types, etc., you need the special cython module, which you can import with
> import cython
> in the Python module that you want to compile.
I have find out that this is not consistent with example in Calling C functions tutorial where we are using symbols imported directly.
> Use explicitely cython module in examples

- docs/examples/quickstart/cythonize/integrate_cy.pyx
- docs/examples/userguide/extension_types/shrubbery.py
- docs/examples/userguide/extension_types/shrubbery.pyx
- docs/examples/userguide/language_basics/casting_python.pxd
- docs/examples/userguide/language_basics/casting_python.py
- docs/examples/userguide/language_basics/open_file.py
- docs/examples/userguide/language_basics/optional_subclassing.py
- docs/examples/userguide/language_basics/optional_subclassing.pyx
- docs/examples/userguide/language_basics/override.py
- docs/examples/userguide/language_basics/override.pyx
- docs/examples/userguide/language_basics/parameter_refcount.py
- docs/examples/userguide/language_basics/parameter_refcount.pyx
- docs/examples/userguide/language_basics/struct_union_enum.py
- docs/src/userguide/language_basics.rst
This PR is introducing pure python mode in language basics documentation. It is partial fix of https://github.com/cython/cython/issues/4187
> Introduce pure python mode in language basics documentation

- docs/src/userguide/language_basics.rst
In the header of documentation it is mentioned that user should import cython in order to execute examples. But in examples function `cast()` is called directly. This PR is changing that to `cython.cast()` in order to conform the header text.
> Docs: Use cython.cast() instead of cast() in examples of language basics documentation

- tests/errors/w_uninitialized_cpp.pyx
- tests/run/cpp_operators.pyx
- tests/run/fused_cpp.pyx
Closes #4266.
It looks like I'd inadvertently fixed the remaining bugs in #4266, but I hadn't realized it. This PR just re-enables the tests for them
> Add more cpp_locals tests

- Cython/Compiler/Code.py
- Cython/Utility/ModuleSetupCode.c
Adds utility code sections designed to be able to toggle warnings for the duration of the utility code.
Hopefully supersedes #4165
@maxbachmann Opinions? Does this achieve what you want? (I need to reboot to get to MSVC so it isn't quick for me to test)
> Suppress warnings about constant expressions on MSVC

- Cython/Compiler/ParseTreeTransforms.py
- tests/errors/cdef_func_decorators.pyx
These were lost when cdef properties (for extern types) were
introduced.
"Fixes" #4322 (based on my interpretation of the problem as an
error-reporting issue)
> Restore error on cdef function arbitrary decorator

- Cython/Compiler/ExprNodes.py
- tests/run/tuple_constants.pyx
I'm hoping to speed up the complication of some of the larger
Cython internal modules (but it's worthwhile even if that fails
I think!). ExprNodes.py was creating hundreds
of tuples containing ("self", "env") for example, because it
wasn't able to match and deduplicate them.
> Fix deduplication of tuples constaining IdentifierStringNode

- docs/src/quickstart/install.rst
See https://github.com/cython/cython/pull/4142#issuecomment-831464115
I don't think MinGW has worked since around Python 3.4 (but I'm
not completely confident in that) while I know that MSVC does
work. Therefore we should recommend that.
> Update docs to recommend using MSVC on Windows

- Cython/Compiler/ExprNodes.py
- tests/errors/cpp_bool.pyx
Fixes #4348
~Note that patch is against 0.29.x and will need merging against master too.~ I've changed it to be patched against master (just so that the tests get run). I think it should be backported though
> Fix C++ bool coercion where no operator bool exists

- docs/src/userguide/language_basics.rst
- tests/errors/cpp_bool.pyx
One that I added in a recent commit (sorry!) and one pointed out here https://github.com/cython/cython/commit/0574dbceef7b8ee16a9cc94091c3629dfa23133d#r54025763
> Fix a couple of trivial typos

- Cython/Includes/cpython/contextvars.pxd
ff16389c0da5acc2be1 introduced convenient functions get_value() and get_value_no_default().
Unfortunately, the variable `value` in these functions was not set before usage with PyContextVar_Get().
This triggered some warnings:
```
...
"""Return a new reference to the value of the context variable,
or the default value of the context variable,
or None if no such value or default was found.
"""
cdef PyObject *value
PyContextVar_Get(var, NULL, &value)
^
Cython/Includes/cpython/contextvars.pxd:118:33: local variable 'value' might be referenced before assignment …
```
> Fix maybe uninitialized `value` in get_value and get_value_no_default.

- Cython/Utility/CythonFunction.c
- tests/run/fused_bound_functions.py
Fused methods use `__get__` to bind them to a class instance. However, there's no need to do the full binding process when just looking up a class attribute.
The main consequence is that for:
```
class C:
def f(self, FusedType x):
pass
```
`C.f is C.f` now returns True. This saves a bit of computation and also makes them pickleable by name (provided they're not in a closure or anything like that...)
> Avoid unnecessary binding of fused functions

- Cython/Utility/Coroutine.c
This is explicitly tested for: https://github.com/cython/cython/blob/aea4e6b84b38223c540266f8c57093ee2039f284/tests/run/test_coroutines_pep492.pyx#L2400
It turns out some earlier versions of Python assume that
C-API classes without a dict or slot are pickleable by the class
name. Currently it's isn't pickleable because it the class name lookup
is failing but this change makes it more robust.
Taken out of #4376
> Make __Pyx_CoroutineAwaitType non-pickleable

- Cython/Compiler/Code.py
- Cython/Compiler/ModuleNode.py
- Cython/Includes/numpy/__init__.pxd
- tests/run/numpy_import_array_error.srctree
This can happen (rarely) with exceptions very early in the
module init process.
Fixes #4377
I also cleaned up a few inline functions to have return statements.
~I'm struggling to see how to add a test for this (so I've
omitted it) but happy to take any suggestions~ Test is included now
> Avoid AddTraceback if stringtab isn't set up

- Cython/Utility/ModuleSetupCode.c
`compile time` would also be acceptable according to https://en.wikipedia.org/wiki/Compile_time
> Fix typo discovered by codespell

- runtests.py
The string comparison was reporting '11' < '4' (so OpenMP
tests were being skipped on GCC 11)
> Change gcc version to a numeric comparison

- Cython/Compiler/Nodes.py
- Cython/Compiler/ParseTreeTransforms.py
- Cython/Compiler/Visitor.py
- tests/run/decorators.pyx
A few children of function nodes need to be consistently evaluated
outside the function scope. This PR attempts to do so and thus
fixed #4367.
(I have a suspicion that this change will have some knock-on
consequences in a few places though, so may need further revision)
> Try to handle function outer_attrs more consistently

- Cython/Utility/NumpyImportArray.c
- tests/run/numpy_import_array_error.srctree
Stop using NPY_NDARRAYOBJECT_H since:
a) in principle it's private
b) Numpy has renamed it
and use a public symbol instead.
I think the existing tests are adequate - we just aren't yet testing
against a new enough version of Numpy to have caught it yet
Closes https://github.com/cython/cython/issues/4396 and https://github.com/cython/cython/issues/4394
> Improve "import_array" guard

- Cython/Includes/cpython/longintrepr.pxd
- Cython/Utility/ModuleSetupCode.c
- tests/compile/pylong.pyx
https://github.com/python/cpython/pull/28968 / 8e5de40f90476249e9a2e5ef135143b5c6a0b512 which is part of implementing https://bugs.python.org/issue35134 moved the header "longintrepr.h" into a sub-folder.  The notes on this change suggested to include "Python.h" instead.
> FIX: change c includes to account for upstream changes

- docs/examples/tutorial/numpy/convolve2.pyx
Arguably it's unnecessary if the auto-call works correctly, but
if we're still advising users to do it themselves then it probably
should be in the docs.
> Add "import_array()" to the Numpy tutorial

- Cython/Utility/ImportExport.c
Fixes the following warning in mpi4py:
```
In file included from src/MPI.c:4:
src/mpi4py.MPI.c: In function ‘__Pyx_MergeVtables’:
src/mpi4py.MPI.c:206412:50: warning: conversion to ‘long unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
206412 |     base_vtables = (void**) malloc(sizeof(void*) * (base_depth + 1));
|                                                  ^
```
> Fix GCC -Wsign-conversion warning

- Cython/Includes/libcpp/numeric.pxd
- tests/run/cpp_stl_numeric_ops_cpp17.pyx
Adds most of the C++17 STL functions of the [numeric library](https://en.cppreference.com/w/cpp/header/numeric) to `libcpp.numeric`, i.e.
- `reduce`
- `transform_reduce`
- `inclusive_scan`
- `exclusive_scan`
- `transform_inclusive_scan`
- `transform_exclusive_scan`
Unfortunately, I'm not really aware of an appropriate way to handle the ambiguous overloads in Cython only, so I excluded some of them, see also [my question at the mailing list](https://groups.google.com/g/cython-users/c/hMfR9LmOjGg).
> Add most of the C++17 numeric functions to libcpp.numeric

- .github/workflows/wheel-manylinux.yml
- setup.py
I've been looking at PyPI (e.g. [0.29.24](https://pypi.org/project/Cython/0.29.24/#files) or [3.0.0a9](https://pypi.org/project/Cython/3.0.0a9/#files)), and am puzzled why I don't see any binary wheels for Python 3.10. It seems the classifier is missing.
And if Python 3.10 is supported (I can't immediately tell if it is), please backport to the `0.29.x` branch.
> Add Python 3.10 classifier

- Cython/Includes/cpython/contextvars.pxd
PyContextVar_Get  was added to PyPy 7.3.6 (https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/doc/release-v7.3.6.rst)
> use PyContextVar_Get backport until PyPy 7.3.6

- runtests.py
**The problem**
In Python it usually dangerous to use mutable arguments like dicts or lists as default arguments in method, as is better explained [here](https://docs.python-guide.org/writing/gotchas/)
**the solution**
This PR applies a simple refactoring to remove a case where a method was created using default a mutable argument
> removed a default mutable argument pitfall

- Cython/Compiler/Scanning.py
- tests/run/coverage_cmd.srctree
Having a code object with `co_filename` set to just "stringsource", causes coverage.py to think that "stringsource" is a relative path to an actual file. The convention is to wrap such fake paths with angle brackets, which coverage.py correctly recognizes.
You will recognize this as the error:
```
No source for code: '.../stringsource'.
Aborting report output, consider using -i.
```
When running `coverage html` for example
> Avoid coverage.py balking on "stringsource"

- Cython/Utility/Coroutine.c
Hopefully fixes https://github.com/cython/cython/issues/4416 by using accessor function instead of struct member (which is now the wrong type)
> Fix co-routine frames on Python 3.11 alpha

- Cython/Includes/libcpp/algorithm.pxd
- tests/macos_cpp_bugs.txt
- tests/run/cpp_stl_algo_comparison_ops.pyx
- tests/run/cpp_stl_algo_minmax_ops.pyx
- tests/run/cpp_stl_algo_permutation_ops.pyx
Adds most of the missing minimum/maximum operations, comparison operations and permutation operations of the algorithm library (<= C++17):
- `minmax`, `minmax_element` (C++11), `clamp` (C++17) and one missing overload of `min/max_element`.
- `equal`, `lexicographical_compare`
- `is_permutation`, `next_permutation`, `prev_permutation`
> Add missing min/max, comparison and permutation operations of C++ algorithm library

- docs/src/userguide/memoryviews.rst
With some delay, this is an attempt to improve the documentation regarding initialization
checks for typed memory-views under a performance perspective.
This was originally discussed in the users group with @da-woods:
https://groups.google.com/g/cython-users/c/rU0_mt3Vgn0
I am looking forward to comments regarding this yet minimalist section.
> DOC Add a Performance section for Typed Memoryviews

- Cython/Utility/Coroutine.c
- Cython/Utility/ModuleSetupCode.c
- Cython/Utility/ObjectHandling.c
This is a cherry pick of https://github.com/cython/cython/commit/9d1ffd5dcdcc0f2f719f86a9a30ce08a67641f10 and https://github.com/cython/cython/commit/3f56484704742c1af33c9737642125c55b0634d5 for Cython 0.29.x. It is not a hugely clean cherry-pick because `__Pyx_PyCode_New` has a different number of arguments in the two versions.
It also disables `CYTHON_FAST_PYCALL` on Python 3.11 (which I imagine is a performance regression). This is because the frame object no longer has a `f_localsplus` field to use. On Cython 3 this is fine - we use `CYTHON_VECTORCALL` instead, however that doesn't exist on 0.29.x. Therefore this is the least intrusive change available I think.
I've tested it to the extent of building Cython with these changes with Python versions 2.7, 3.7, 3.8, 3.9, 3.10, and 3.11 …
> Get 0.29.x working on Python 3.11

- Cython/Includes/libcpp/algorithm.pxd
- tests/macos_cpp_bugs.txt
- tests/run/cpp_stl_algo_sorted_ranges_other_ops.pyx
- tests/run/cpp_stl_algo_sorted_ranges_set_ops.pyx
This adds the last missing overloads of the C++ algorithm library (ignoring the overloads with an execution policy). 
The tests are disabled on macOS, see https://github.com/cython/cython/pull/4448#issuecomment-964405071 .
> Add merge and set operations of the C++ algorithm library

- Cython/Compiler/ModuleNode.py
- Cython/Compiler/Nodes.py
- Cython/Compiler/Symtab.py
- Cython/Compiler/TypeSlots.py
- Cython/Compiler/Visitor.py
- docs/src/userguide/migrating_to_cy30.rst
- tests/run/binop_reverse_methods_GH2056.pyx
The type for the self argument for binops depends on the compile directives. Therefore it needs a set of type slots that depends on the compiler directives.
I've therefore got rid of the big static list of typeslots in TypeSlots.py in favour of a class that defines them all (and
can be initialized with suitable compiler directives as needed). This involves moving a static dictionary and list out of the
global scope too, so that they too can be part of the class. The passing of the dictionary and list to all the constructors
is a bit awkward
Fixes #4434
> Make self argument for binops typed

- Cython/Utility/ModuleSetupCode.c
Since it seems this code path will go away in CPython3.11, I don't really want to implement it only to remove it. Would it be reasonable to fall back to the older code path on PyPy?
> PYPY: pypy does not implement PyCode_NewWithPosOnlyArgs

- Cython/Utility/ExtensionTypes.c
If I understand correctly, the Cython-specific reimplementation
of trashcan isn't needed of Python 3.8+ (because the patch it
was based on was merged into Python). Therefore on these versions
it can be disabled and the Python macros used instead.
This is specifically needed for Python 3.11 since it removes
hides functions that are used in the Cython reimplementation.
However, I've gone back further.
(Admittedly I don't understand the exact special-case this was for
too well, but I'm hoping this is tested...)
> Disable Cython reimplementation of trashcan

- Cython/Utility/ModuleSetupCode.c
For the limited API, I'm not sure why USE_UNICODE_WRITER was ever
the default - PyObject_Format is part of the limited api so
should clearly be preferred.
Python 3.11 hid _PyLong_FormatAdvancedWriter and
_PyFloat_FormatAdvancedWriter. I've disabled USE_UNICODE_WRITER
for the moment but I suspect we want to find replacements in
the longer term.
> Disable USE_UNICODE_WRITER for limited api and Py3.11

- Cython/Compiler/Nodes.py
- tests/memoryview/memoryview.pyx
Fixes #4296
If there was an error in preparing the function arguments after a
memoryview had already been created then the memoryview was not
cleaned up correctly.
(This leaves it in the slightly odd position where memoryviews
are cleaned up in the wrapper function on failure, but in the
main function on success. I kind of think it'd be better to clean
them up in the wrapper function in both cases, but I'm reluctant
to mess with a system that largely works)
I doubt this can be backported cleanly to 0.29.x so may have to
stay at a 3.0 bug-fix for now
> Clean up memoryview reference counting on error

- Cython/Utility/Exceptions.c
With reference to https://github.com/cython/cython/issues/4365#issuecomment-977023011
in Python 3 PyCode_NewEmpty does everything we need to set exception traceback code objects.
The downside is for the "cline" case, where it creates an extra unicode object, gets the `char*` from that, and then `PyCode_NewEmpty` will use that to create another unicode object (in principle this could probably mostly be avoided using `snprintf` or similar, but it doesn't seem worth it given that all these code objects are cached). For all other cases it should end up largely the same.
It's mainly an improvement on the Py3.11 case (where the `PyCode_New` replacement is likely fairly slow). For simplicity I've done it on all Python 3 versions, but it could also be done for Python 3.11 only.
> Exceptions.c PyCode_New -> PyCode_NewEmpty

- Cython/Utility/Coroutine.c
- tests/pypy_bugs.txt
- tests/pypy_crash_bugs.txt
As stated in `pypy_bugs.txt`, "very little coroutine-related works" but at least do not segfault. The call to `__Pyx_Coroutine_del` manipulates `ob_refcnt` to resurrect the object, which might fail on PyPy, so disable it. I need to find a way around this, the code should be executed elsewhere, which might fix some of the coroutine breakage on PyPy. 
When digging into the code, it seems much of this was taken at some point from CPython (PR #73) in 2011 and then expanded on. Does CPython still use this paradigm or is there a point where the coroutine is finished and can be cleaned up before the destructor?
> PYPY: do not call __Pyx_Coroutine_del (tp_finalize) - it reconstructs dead objects

- tests/pypy_bugs.txt
- tests/pypy_crash_bugs.txt
- tests/run/pycontextvar.pyx
Now that they've implemented the PyContextVar C API it segfaults
instead of just failing. Therefore, move it to the "crash bugs"
list so that it doesn't get run.
> Disable pycontextvar test on PyPy

- Cython/Compiler/ModuleNode.py
Follow up to https://github.com/cython/cython/pull/4453.
That PR creates a temp that's only used in the limited API
(and therefore causes warnings on all other paths)
> Remove warning from unused temp in module init

- Cython/Compiler/TypeSlots.py
- Cython/Utility/AsyncGen.c
- Cython/Utility/Coroutine.c
- Cython/Utility/CythonFunction.c
To silence a compiler warning since it was added in Python 3.11a2.
For 0.29.x branch only
> Add tp_inline_values_offset to slot_table (0.29.x)

- Cython/Utility/ExtensionTypes.c
We run into the #4200 error again with Pyston because some projects are using the v0.29 but only v0.30 contains the fix.
It would be very helpful for use if this fix is included in the next 0.29 release
> pyston support: backport memory corruption fix #4200 to v0.29 branch

- Cython/Compiler/TypeSlots.py
- Cython/Utility/AsyncGen.c
- Cython/Utility/Coroutine.c
- Cython/Utility/CythonFunction.c
To remove a compiler warning since this slot was added in
3.11a2.
I'll make a separate backport for 0.29.x (since the branches have diverged a little here)
> Add tp_inline_values_offset to slot_table

- .github/workflows/ci.yml
As suggested in https://github.com/cython/cython/pull/4471#issuecomment-979489947
I don't think that we're getting any benefit from running the pypy
known bugs test as part of the CI (and it's causing minor problems)
Feel free to reject this if you disagree though.
> Remove pypy bugs tests

- Cython/Compiler/PyrexTypes.py
- Cython/Compiler/Symtab.py
- tests/errors/cpp_object_template.pyx
Specifically this disallows memoryviews (closing #3085)
but it extends to any future type that Cython has to generate
manual reference counting code for.
> Ban templating C++ classes with reference counted types

- runtests.py
It requires Py_DecodeLocale which appears in 3.5. This is causing
it to fail on Windows. It's somehow passing on Linux for reasons
that I don't understand (but it really shouldn't be)
> Disabled embed test from the docs on Py3.4

- docs/conf.py
- docs/examples/userguide/memoryviews/custom_dtype.pyx
- docs/src/userguide/memoryviews.rst
Closes #2760 
I have added a section in the memory view doc that indicates how to use memory views on numpy array that have a custom dtype.
I really think this is something that should be in the docs somewhere. I needed this and the only source was one of the scipy paper from 2008.
> [DOC] Add doc for memory views with custom numpy dtype

- docs/examples/tutorial/profiling_tutorial/calc_pi.py
- docs/examples/tutorial/profiling_tutorial/calc_pi_2.py
- docs/examples/tutorial/profiling_tutorial/calc_pi_3.py
- docs/examples/tutorial/profiling_tutorial/calc_pi_3.pyx
- docs/examples/tutorial/profiling_tutorial/calc_pi_4.py
- docs/examples/tutorial/profiling_tutorial/calc_pi_4.pyx
- docs/examples/tutorial/profiling_tutorial/often_called.py
- docs/examples/tutorial/profiling_tutorial/profile.py
- docs/examples/tutorial/profiling_tutorial/profile_2.py
- docs/src/tutorial/profiling_tutorial.rst
This PR is introducing pure python mode in Profiling tutorial. It is partial fix of #4187
> Docs: Migrate profiling tutorial to pure python

- Cython/Utility/CythonFunction.c
- tests/run/cyfunction_defaults.pyx
Cython can't make use of these new defaults so it seems sensible
to alert the user (even if we're choosing to allow the assignment
for compatibility reasons).
I know the warning mechanism is somewhat heavy. I think this is
OK because it's unlikely that users will be repeatedly assigning
to these attributes in a time-critical loop.
Doesn't fix #2650, but hopefully alerts users to it.
> Warn when cyfunction.__[kw]defaults__ is changed

- Cython/Compiler/Nodes.py
- tests/errors/pure_errors.py
- tests/run/pure_py3.py
This PR fixes issues in pure python mode when Python object is
annotated as returned value - e.g.:
```python
@cython.cfunc
def foo(s) -> str:
```
It raises following exception: `Exception clause not allowed for function returning Python object`.
This exception is raised because Pure python mode defaults `exception_check` to `True`:
https://github.com/cython/cython/blob/09cbf492dfcf1ad022e79660d6aec0be3f444244/Cython/Compiler/ParseTreeTransforms.py#L2508-L2510
I have tried to fix the issue in this place by checking of returned type but I have found it challenging because
during this stage of compilation we don't have annotation parsed. Hence, I decided to ignore the error and just reset
the `exception_check` value because:
Cython language is ignoring `exception_check` when python object is …
> Don't error when exception_check is set to True when return type is PyObject.
