cython/cython

Cython/Compiler/Symtab.py, tests/compile/cpp_class_redefinition.pyx
Condition is no longer valid since commit fa3db3679bbb3385eb2746483a91ddbbf31b82f0
=> Fix condition in declare_cpp_class

CHANGES.rst, Cython/Includes/numpy/math.pxd
Quick bugfix, hopefully still in time for 0.22 (?)
=> fix erroneous prototypes for npy_logaddexp*

docs/src/userguide/buffer.rst
Caught a strange typo and added some comments.
=> Fixes for buffer protocol docs

tests/run/numpy_math.pyx
Ping @scoder: this is the test from #365 as a separate PR.
=> test: assert that isinf returns -1 for negative infinity

Cython/Build/Dependencies.py, tests/compile/distutils_libraries_T845.srctree
Fix for `http://trac.cython.org/ticket/845`
=> When merging a transitive_list, copy the list

docs/src/tutorial/memory_allocation.rst, docs/src/tutorial/numpy.rst
I'll skip the CI since this does not touch code and no sphinx build is defined for Travis.
[skip ci]
=> Fix two small sphinx errors in the tutorials

docs/src/reference/compilation.rst
=> Fix links to CEP 516

Cython/Includes/libc/math.pxd
Also reorder a few imports to alphabetical order.
=> Add signbit to math.pxd.

CHANGES.rst, Cython/Compiler/Main.py, docs/src/userguide/sharing_declarations.rst, tests/compile/find_pxd.srctree
See https://groups.google.com/forum/#!topic/cython-users/PZTK8sZdxrY
=> Do not search sys.path for .pxd file if no explicit "cimport" is given

docs/src/userguide/buffer.rst
* shape calculation was off
* flag macros live in cpython, not cython
=> fix two mistakes in buffer protocol docs

Cython/Includes/libcpp/memory.pxd
Proposed for consideration with the aim of adding support for smart pointers.
=> Add <memory> header to libcpp

Cython/Includes/libcpp/memory.pxd
This patch is  against 0.23.x branch.
=> unique_ptr & shared_ptr: Added missing bool operator!()

Cython/Includes/libc/setjmp.pxd, Cython/Includes/posix/select.pxd, Cython/Includes/posix/signal.pxd
Various fixes and additions to include files.
=> Additions to includes

CHANGES.rst, Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/Pipeline.py, Cython/Compiler/UtilityCode.py, Cython/Utility/CpdefEnums.pyx, docs/src/reference/language_basics.rst, tests/run/cpdef_enums.pyx
For example
cpdef enum Eggs
SOFT
HARD
SCRAMBLED
produces three constants with int values that print as strings,
and a type Eggs with attributes Eggs.SOFT, etc. and list(Eggs)
giving the set of all enum values.  Instantiating Eggs with a
numeric or string value will return the appropriate constant.
=> More complete cpdef enums.

.mailmap
Not perfect yet, but it covers all committers with 10 or more commits.  I
didn't go looking below that threshold.
This should at least make it easier to get a more accurate count of developer activity via `git shortlog -sne`.  
Before this PR:
```
(master)denali[cython]> git shortlog -sne | head -20
3369	Stefan Behnel <stefan_ml@behnel.de>
2742	Stefan Behnel <scoder@users.berlios.de>
1366	Robert Bradshaw <robertwb@math.washington.edu>
724	Robert Bradshaw <robertwb@gmail.com>
518	Mark Florisson <markflorisson88@gmail.com>
514	Dag Sverre Seljebotn <dagss@student.matnat.uio.no>
339	Vitja Makarov <vitja.makarov@gmail.com>
292	Lisandro Dalcin <dalcinl@gmail.com>
151	scoder <stefan_ml@behnel.de>
50	Kurt Smith <kwsmith1@wisc.edu>
44	Craig Citro <craigcitro@gmail.com>
41	Lars Buitinck …
```
=> Add initial .mailmap file.

Cython/Utility/ObjectHandling.c
=> Fix a memory leak in ObjectHandling.c

Cython/Shadow.py
Add many missing decorators for compiler directives to Shadow.
=> Add missing decorators.

Cython/Compiler/Main.py
Also fix timestamps option  when writing output file to a specified location.
=> Fix timestamps option to work when generating a C++ output file.

docs/src/userguide/parallelism.rst
Add setup.py openMP instructions for Microsoft Visual C++ compiler
=> + setup.py instructions for Visual C++ compiler

Cython/Compiler/Buffer.py, tests/bugs.txt, tests/compile/cpp_structs.pyx
Description on UG: https://groups.google.com/d/topic/cython-users/LdakQ_xyDIM/discussion
=> Fix mangling for C++ namespaced types

docs/src/userguide/wrapping_CPlusPlus.rst
Fix documentation code example.
=> Fix errors in example code sections in documentation.

docs/src/reference/extension_types.rst, docs/src/tutorial/cdef_classes.rst, docs/src/userguide/extension_types.rst
=> Update docs wrt property syntax deprecation

Cython/Includes/cpython/object.pxd
A few more pieces of `PyTypeObject`...
=> Add tp_dict and tp_descr_* declarations

docs/src/reference/special_methods_table.rst, docs/src/tutorial/strings.rst, docs/src/userguide/buffer.rst, docs/src/userguide/pyrex_differences.rst, docs/src/userguide/special_methods.rst
Sphinx can automatically generate links to PEPs.
=> Use automatic PEP links in doc

docs/src/reference/language_basics.rst
=> Improve documentation for cpdef methods

Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/Profile.c
Hi All,
The changes in this PR originally from try to run extensions which needs Cython(NumPY, SciPy, lxml） in [Pyston](https://github.com/dropbox/pyston).
During the process of try to support more extensions in Pyston. There may have more Pyston changes in Cython.
Thoughts?
=> Initial Cython patch for Pyston.

Cython/Compiler/Symtab.py, tests/run/cdef_cpdef_GH543.srctree
See https://github.com/cython/cython/issues/543
=> Fix overriding of cdef by cpdef method in .pxd file

docs/src/userguide/debugging.rst
As a guy who hacked around for the last day getting cygdb to work, I think some additions and updates to the cygdb documentation would be enormously helpful for people trying to use it.
=> Added more detailed documentation for using cygdb

Cython/Compiler/ExprNodes.py
This commit fixes a few issues.  One is the following test case:
```
import numpy
cimport numpy
def testfunc():
a = numpy.arange(12).reshape([3,4])
cdef numpy.int_t[:,:] a_view = a
cdef numpy.int_t[:,:] b = a_view[1:2,:].T
testfunc()
print "If you see this message, you made it through successfully!"
```
The following commands compile and test this on my Scientific Linux 7 system:
```
cython testmemoryview.pyx
gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I/usr/include/python2.6 -o testmemoryview.so testmemoryview.c
echo 'import testmemoryview' | python
```
The error output for Cython 0.24:
```
Fatal Python error: Acquisition count is 0 (line 2110)
Aborted
```
With the patch it exits successfully.  The diff in the generated C-code is simply:
```
--- …
```
=> Fix refcounts for transposed memoryview slices.

Cython/Compiler/PyrexTypes.py, tests/run/cpp_stl_vector.pyx
I'm not sure whether this is the best way to fix the issue. Have a look
=> Fix for #1469

Cython/Compiler/ExprNodes.py, tests/compile/nogil_array.pyx
=> Allow slicing of C arrays without GIL

CHANGES.rst, Cython/Compiler/ModuleNode.py, Cython/Compiler/Naming.py, Cython/Utility/Exceptions.c, tests/run/tracebacks.pyx
Also changes the default to False.
=> Make C lines in exception tracebacks a runtime setting.

Cython/Compiler/ExprNodes.py, tests/run/complex_numbers_T305.pyx
=> Fix complex comparison

Cython/Build/Tests/TestIpythonMagic.py
[unittest.skip](https://docs.python.org/2/library/unittest.html#unittest.skip) requires a `reason` argument. Without this, it doesn't correctly skip tests on Windows.  The decorator needed adjustment to account for adding the argument. For reproducing, note that this test is only run if `ipython` and `mock` are installed.
=> skip_win32 doesn't properly skip tests

Cython/Compiler/Optimize.py, Cython/Utility/MemoryView_C.c, tests/memoryview/memoryviewattrs.pyx, tests/memoryview/memslice.pyx
=> Implement len(memoryview) and allow its usage in nogil sections.

Cython/CodeWriter.py, Cython/Compiler/AutoDocTransforms.py, tests/run/embedsignatures.pyx
This is for sure not enough, but at least it can handle "simple" annotations like non-compound compile-time constants and name nodes.
=> Update embedsignature directive to emit function annotations

Cython/Build/IpythonMagic.py, Cython/Build/Tests/TestIpythonMagic.py
=> Add --verbose option for cython magic

Cython/Coverage.py, tests/run/coverage_api.srctree, tests/run/coverage_cmd.srctree
this commit fixes #1898
use filepath with the correct upper and lowercases
=> Update Coverage.py 

docs/index.rst, docs/src/changes.rst
Since the changelog contains a lot of information that the documentation doesn't (e.g., async comprehension support, type hinting, etc.), it would make sense to include it. Updating the documentation would of course be the best solution and is the next step, but this seems like a good start.
=> Include changelog in Sphinx documentation

Cython/Utility/CythonFunction.c
See https://github.com/cython/cython/issues/1997
=> Put #include <structmember.h> later in the C code

docs/src/reference/extension_types.rst, docs/src/reference/language_basics.rst, docs/src/userguide/numpy_pythran.rst
Fixed a few typos and one broken link.
=> Docs Update

docs/src/reference/compilation.rst
=> Add warnings to compiler directive docs

Cython/Compiler/Buffer.py, Cython/Compiler/Code.py, Cython/Compiler/CythonScope.py, Cython/Compiler/FusedNode.py, Cython/Compiler/Main.py, Cython/Compiler/Nodes.py, Cython/Compiler/Symtab.py, Cython/Compiler/TypeInference.py, Cython/Debugger/libcython.py, docs/src/userguide/memoryviews.rst, pyximport/pyximport.py, tests/errors/e_directives.pyx
=> Misc typos

docs/src/quickstart/cythonize.rst
Here are some precisions added in the docs. I did with the best of my cython knowledge.
=> Updated cythonize.

docs/examples/tutorial/fib1/fib.pyx, docs/src/tutorial/cython_tutorial.rst
Let's make the documentation great again! 
I make a few changes at a time for easy review and organization, but if you want me to put more changes into each PR, just tell me.
=> Made the print python 3 style. pep8 and link to memoryviews.

Cython/Debugger/libcython.py, Cython/Utility/MemoryView.pyx, Demos/benchmarks/bpnn3.py, docs/src/quickstart/cythonize.rst, tests/run/__getattribute_subclasses__.pyx
=> Misc. typos

docs/src/userguide/numpy_tutorial.rst
It's temporary.
I think a better solution for this tutorial would be to rewrite everything with memoryview. I believe it's easier for people who have no previous experience with Cython. 
What are your thoughts on this?
=> Added a note for Cython for numpy users.

docs/conf.py, docs/src/quickstart/build.rst, docs/src/tutorial/cython_tutorial.rst, docs/src/tutorial/profiling_tutorial.rst, docs/src/userguide/source_files_and_compilation.rst, pyximport/pyximport.py
I added the API for `pyximport.install()`. And also some links.
=> Added argument list for pyximport.

Cython/Utility/TypeConversion.c, tests/run/cpp_bool_template_return.pyx, tests/run/cpp_templates_helper.h
=> Bug fix for boolean return using statement with internal commas.

Cython/Compiler/Main.py, Cython/Utils.py
so far only the inline cache looked at that environment variable.
=> CYTHON_CACHE_DIR should also set the compiler cache

Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, Cython/Includes/cpython/longintrepr.pxd, tests/run/longintrepr.pyx
As discussed with @robertwb yesterday.
=> Allow access to long/int internals

README.rst
Added the link to the `CONTRIBUTING.rst`, I also made the licence section lowercase to be consistent with the rest of the readme.
=> Improved the readme.

docs/README
There was an error in the readme.
=> Fixed wrong info in the readme.

docs/src/userguide/language_basics.rst
I chose to put it first as I believe it is a good introduction to the cython language.
=> Transfered declaring data types.

docs/src/userguide/language_basics.rst
Copy pasting from the language basics of the reference guide
=> transfered checked type casts

docs/src/userguide/language_basics.rst
Copy pasted this section, I fixed the syntax error issue for the examples and added some clarifications.
=> Transfer optional arguments

docs/src/userguide/language_basics.rst
Some copy pasting. I also added an example for python object pointers.
=> Transfered type casting

docs/src/userguide/extension_types.rst
I renamed **Attributes** into **Static attributes** and added a section called **Dynamic attributes**.
=> Transfer of the dynamic attributes into the userguide.

docs/src/reference/extension_types.rst, docs/src/userguide/extension_types.rst, docs/src/userguide/special_methods.rst
I have checked that all the sections were transferred with all the corresponding information.
The PR should not be merged until #2277 is merged into master.
=> Replaced the text in reference/extension_types.rst by links to the corresponding sections in the userguide.

docs/src/userguide/special_methods.rst
While working on this page, I noticed that this note wasn't rendered in the html. I fixed it.
=> Fixed the formatting of a note in special_methods.rst.

docs/src/quickstart/cythonize.rst, docs/src/reference/compilation.rst, docs/src/tutorial/cython_tutorial.rst
There might be other possible arguments. I didn't look much. I'm going to do another  PR later with the arguments covered in ``**options``.
=> Added a documentation for the Cythonize function and its arguments.

docs/src/tutorial/clibraries.rst
I took the PR #1921 from @MarvinTeichmann and changed a few things here and there according to the review.
There was a comment about link time optimisation. I looked it up, but I don't think I'm knowledgeable enough on this topic to add anything meaningful to the tutorial. I will let someone more familiar with the matter take care of it.
=> Fixing c library tutorial

docs/src/userguide/wrapping_CPlusPlus.rst
Just a small modification so that users see that for i in range(...) isn't the only way to iterate over a vector.
=> Added an example of iteration for x in vector.

Cython/Includes/cpython/ceval.pxd
Add PyEval_InitThreads and PyEval_ThreadsInitialized.
Resolves #2205.
=> Add decrlarations from ceval.h

docs/examples/quickstart/cythonize/cdef_keyword.pyx, docs/examples/quickstart/cythonize/integrate.py, docs/examples/quickstart/cythonize/integrate_cy.pyx, docs/src/quickstart/cythonize.rst
Moved the code snippets from the .rst file to the examples directory.
Those code snippets are now tested with the mode "compile".
=> Adding tests for the code snippets in docs/src/quickstart/cythonize.rst

docs/examples/tutorial/cdef_classes/math_function.py, docs/src/tutorial/cdef_classes.rst
By putting this piece of code in the `/examples` directory, it will be automatically tested at every build.
=> Added tests for cdef_classes.rst.

docs/examples/tutorial/cdef_classes/math_function_2.pyx, docs/src/tutorial/cdef_classes.rst
This PR is independent from #2329. I think that splitting those changes into several small PR makes it easier to review.
=> Added tests for cdef_classes.rst. Part 2.

docs/examples/tutorial/pure/A.pxd, docs/examples/tutorial/pure/A.py, docs/src/tutorial/pure.rst
Put a A.py and A.pxd from "pure python mode" in the examples directory for testing. There wasn't any bugs.
=> Adding tests for "pure python mode" part 1

docs/examples/tutorial/pure/pep_526.py, docs/src/tutorial/pure.rst
Put the pep 526 example in the examples directory for testing.
=> Adding tests for "pure python mode" part 7

docs/examples/tutorial/array/safe_usage.pyx, docs/src/tutorial/array.rst
Put the first code snippet from "working with python arrays" in the examples directory to enable the tests.
=> Added test of a piece of code in "working with python arrays".

docs/examples/tutorial/profiling_tutorial/calc_pi.py, docs/examples/tutorial/profiling_tutorial/profile.py, docs/src/tutorial/profiling_tutorial.rst
=> Added tests to "profiling tutorial" part 1.

docs/examples/tutorial/cdef_classes/integrate.pyx, docs/examples/tutorial/cdef_classes/sin_of_square.pxd, docs/examples/tutorial/cdef_classes/sin_of_square.pyx, docs/src/tutorial/cdef_classes.rst
Should we mention the `.pxd` file in the docs? It's not mentioned.
=> Added tests for cdef_classes.rst. Part 3.

docs/examples/tutorial/numpy/convolve2.pyx, docs/src/tutorial/numpy.rst
I had to put a tag at the top of the example. I don't think it's going to be an issue for the readers.
=> Adding tests for "working with numpy" part 2

docs/examples/tutorial/profiling_tutorial/calc_pi_2.pyx, docs/src/tutorial/profiling_tutorial.rst
I replaced `xrange` by `range`.
=> Added tests to "profiling tutorial" part 2

docs/examples/tutorial/profiling_tutorial/calc_pi_3.pyx, docs/src/tutorial/profiling_tutorial.rst
Modified `xrange` in favor of `range`.
=> Added tests to "profiling tutorial" part 4

docs/examples/tutorial/memory_allocation/malloc.pyx, docs/src/tutorial/memory_allocation.rst
I'll soon be able to do all that with my eyes closed, haha.
=> Added tests for "memory allocation" Part 1

docs/examples/userguide/parallelism/simple_sum.pyx, docs/src/userguide/parallelism.rst
I indented the comment (is that comment still useful?) because it was causing a rendering problem. A few paragraphs and examples are not currently displayed on the website because of it.
Indenting this comment fixed that.
=> Added tests to "Using Parallelism" part 1

docs/examples/tutorial/pure/locals.py, docs/src/tutorial/pure.rst
There was an invalid cast, so I changed the types in the example.
=> Adding tests for "pure python mode" part 8

docs/examples/tutorial/string/auto_conversion_1.pyx, docs/examples/tutorial/string/auto_conversion_2.pyx, docs/examples/tutorial/string/auto_conversion_3.pyx, docs/src/tutorial/strings.rst
it was just copy pasting for this one.
=> Adding tests for "Unicode and passing strings" part 12

docs/examples/tutorial/string/for_bytes.pyx, docs/examples/tutorial/string/for_unicode.pyx, docs/examples/tutorial/string/if_char_in.pyx, docs/src/tutorial/strings.rst
I'm not familiar with string encoding and decoding. So there may be mistakes when I declare the bytes and the unicode.
=> Adding tests for "Unicode and passing strings" part 14

docs/examples/userguide/buffer/matrix_with_buffer.pyx, docs/src/userguide/buffer.rst
I just added the distutils directive at the start.
=> Added tests to "Implementing the buffer protocol" part 2

docs/examples/tutorial/clibraries/queue3.pyx, docs/src/tutorial/clibraries.rst
I believe this version is more pythonic.
=> Refactoring of the extend function in "using C libraries" to make it simpler.

docs/src/reference/compilation.rst, docs/src/tutorial/numpy.rst, docs/src/userguide/numpy_tutorial.rst, docs/src/userguide/wrapping_CPlusPlus.rst
It's not easy to make the documentation Windows friendly, but we can try little by little to make it better for those who use it.
=> Added mention of .pyd files for windows users.

docs/src/userguide/language_basics.rst
=> Added tests for "language basics" part 2

CHANGES.rst, docs/src/tutorial/strings.rst, docs/src/userguide/external_C_code.rst, docs/src/userguide/memoryviews.rst
I couldn't find the page for the examples with the newaxis function, so instead, I've put a small example.
=> Fixing some broken links.

Cython/Compiler/ModuleNode.py
=> Allow C line in traceback also during module init

docs/src/userguide/source_files_and_compilation.rst
=> Moving compilation from the reference guide to the userguide Part 3

Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/Pythran.py
This fixes the way Cython verifies that Pythran supports the function we are translating!
=> Pythran: verify that pythran supports called Numpy APIs

docs/src/userguide/source_files_and_compilation.rst
It was just copy pasting and pep8tifying some code snippets.
=> Moving compilation from the reference guide to the userguide Part 4

docs/src/userguide/source_files_and_compilation.rst
Those are the last sections! We'll finally be able to say goodbye to the reference guide!
=> Moving Integrating multiple modules and Distributing cython modules into the userguide.

docs/index.rst, docs/src/reference/compilation.rst, docs/src/userguide/numpy_tutorial.rst, docs/src/userguide/source_files_and_compilation.rst
I should have prepared a speech.
=> Removing the reference guide from the docs.

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py, Cython/Compiler/Symtab.py, tests/run/pure_py.py, tox.ini
We can make the maximum line length lower than that, but I think it's better to go there progressively, to avoid huge PRs.
=> Set the maximum line length to 150.

Cython/Includes/cpython/bytearray.pxd
For Issue #2540
All feedback welcome. This Issue looked simple enough for a first issue, but I might have missed something.
=> Add export of the bytearray cpython api

CHANGES.rst, Cython/Build/Inline.py, Cython/Compiler/Main.py, Cython/Compiler/Options.py, Cython/Compiler/Parsing.py, Cython/Compiler/Scanning.py, Cython/Compiler/TreeFragment.py, runtests.py, setup.py, tests/run/test_coroutines_pep492.pyx
=> Warn when no "language_level" is specified.

Cython/Compiler/Code.py, Cython/Compiler/ExprNodes.py
=> Deduplicate constant tuples and slices

Cython/Build/Tests/TestStripLiterals.py, Cython/Utility/MemoryView_C.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Optimize.c, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c
Borrowed from https://bugs.python.org/issue28397
=> Smarter bounds checks

Cython/Compiler/PyrexTypes.py, tests/run/embedsignatures.pyx
Fixes #2634
& adds Tests suggested  in https://github.com/cython/cython/pull/2642#issuecomment-429567965
=> Fix Memviewslice docstrings & Test

Cython/Compiler/PyrexTypes.py
=> Fix Memviewslice docstrings

Cython/Compiler/ExprNodes.py, docs/src/tutorial/caveats.rst, tests/run/constant_folding.py
FIxes: https://github.com/cython/cython/issues/2133
=> Fix: Exponentiation of integer constants

Cython/Compiler/Parsing.py, tests/errors/cfunc_directive_in_pyclass.pyx, tests/errors/e_autotestdict.pyx, tests/errors/pure_errors.py, tests/errors/tree_assert.pyx, tests/run/annotation_typing.pyx, tests/run/cyfunction.pyx
=> fix co_firstlineno for functions that have decorators

Cython/Compiler/ParseTreeTransforms.py, tests/errors/w_undeclared.pyx
=> Fix warn.undeclared #2685

Cython/Utility/MemoryView.pyx, tests/memoryview/memoryview.pyx
Fixes https://github.com/cython/cython/issues/2644
=> Correctly assign MemoryView values from read-only object

Cython/Build/Dependencies.py, Cython/Utils.py, tests/run/cimport.srctree
Fixes: https://github.com/cython/cython/issues/2638
Though still a test is missing.
=> Fix: absolute import handling

Cython/Compiler/Pythran.py, tests/run/numpy_pythran_unit.pyx
=> Fix pythran include path for numpy math functions

Cython/Compiler/Main.py
=> Add "generator_stop" to default future imports for language_level=3

Cython/Compiler/Main.py, tests/run/language_level.srctree
=> Correctly remove future_directives with # cython: language_level=2

Cython/Utility/ObjectHandling.c, tests/run/dict_getitem.pyx, tests/run/set_item.pyx
That is the order that Python uses.
Closes #1807.
=> Try Mapping protocol before Sequence protocol on getitem/setitem/delitem

Cython/Build/IpythonMagic.py, Cython/Compiler/Code.py, Cython/Compiler/FlowControl.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/Parsing.py, Cython/Compiler/Scanning.py, Cython/Compiler/TreeFragment.py, Cython/Plex/Actions.py, Cython/Plex/Scanners.py, Cython/Tempita/_tempita.py, Cython/Tests/TestCodeWriter.py, Cython/Utility/CpdefEnums.pyx, Cython/Utility/MemoryView.pyx, Cython/Utility/TestCythonScope.pyx, tests/build/inline_distutils.srctree, tests/run/array_cimport.srctree, tests/run/cimport.srctree, tests/run/cimport_from_sys_path.srctree, tests/run/initial_file_path.srctree, tests/run/public_fused_types.srctree, tests/run/relative_cimport.srctree
As planned for Cython [3.0](https://github.com/cython/cython/milestone/58).
See #2565.
=> Change the default language level to "3str"

Cython/Utility/MemoryView_C.c
=> Remove superfluous code

Cython/Compiler/Main.py, Cython/Utils.py
moved to Main, as discussed in #2831.
=> REF: make Utils dependency-free by moving search_include_directories

CHANGES.rst, docs/src/userguide/extension_types.rst
Add changelog and documentation for #2842
=> Document trashcan

Cython/Compiler/TypeSlots.py
Avoid generating empty tp_new() functions if we can copy the function pointer from the parent at init time.
See GH-1555.
=> Avoid generating empty tp_new() functions

Cython/Includes/cpython/descr.pxd, Cython/Includes/cpython/dict.pxd, Cython/Includes/cpython/module.pxd, Cython/Includes/cpython/object.pxd, Cython/Includes/cpython/pyport.pxd, Cython/Includes/cpython/type.pxd
Add a bunch of declarations which are used by SageMath.
=> Add various declarations for the CPython C API

Cython/Includes/cpython/pystate.pxd
=> Add PyGILState_Check to Includes/cpython/pystate.pxd

Cython/Compiler/ModuleNode.py
We must clean the weakreferences before calling the user's __dealloc__
because if the __dealloc__ releases the GIL, a weakref can be
dereferenced accessing the object in an inconsistent state or
resurrecting it.
Closes #2929
=> Clean weakrefs before calling user's dealloc

Cython/Includes/cpython/bytes.pxd, Cython/Includes/cpython/object.pxd
The comments were taken from the CPython docs.
Closes #2713.
=> Add PyBytes_FromObject() and PyObject_Bytes()

Cython/Utility/CythonFunction.c, tests/run/reduce_pickle.pyx
Closes #2972 
This was spotted thanks to cloudpipe/cloudpickle#259
=> FIX reduce method of unbound cython method

.coveragerc, setup.cfg
Minor cleanup.
Identical behaviour and helps to reduce the number of config files in the top lvl directory of the project ( there is already quite a-lot )
Thanks,
=> CLN: Move coverage.rc -> setup.cfg

Cython/Compiler/ParseTreeTransforms.py, tests/run/closure_in_derived_class_T2967.pyx
=> Mangle cname for closures in derived c class

Cython/Compiler/Code.py, Cython/Compiler/TypeSlots.py
Preparing for addition of `METH_FASTCALL`
=> Minor cleanup in handling METH_xxx flags

docs/examples/userguide/language_basics/parameter_refcount.pyx, docs/src/userguide/language_basics.rst
=> Describe refcount behaviour of object vs PyObject*

Cython/Compiler/Optimize.py, Cython/Utility/StringTools.c
=> Return Py_ssize_t instead of size_t for len(memoryview).

Cython/Includes/cpython/memoryview.pxd, tests/run/cython_includes.pyx
Closes #2541
Any feedback is welcome.
=> Include memoryview C-API

Cython/Compiler/Scanning.pxd, Cython/Compiler/Scanning.py, tests/run/fstring.pyx
Fix for issue
https://github.com/cython/cython/issues/2877
=> [RFC] Fix for await inside f-string

Cython/Coverage.py, tests/run/coverage_cmd_src_layout.srctree
* Fix coverage path search
* Add testcase
=> Fix coverage on trivial module (see #1985)

Cython/Utility/ObjectHandling.c
Factor out the logic for creating a `tuple` and `list` from a C array into new functions `__Pyx_PyTuple_FromArray` and `__Pyx_PyList_FromArray`. This is useful for #3021 for constructing an `*args` tuple in case that that `METH_FASTCALL` is used.
As additional proof that this is useful, CPython also has an internal function `_PyTuple_FromArray` with the same functionality.
=> Refactor SliceTupleAndList utility code

Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, tests/run/fastcall.pyx
=> Support vectorcall for Cython functions

docs/src/userguide/source_files_and_compilation.rst
Document the change in the default value
=> DOC: document default change

Cython/Includes/libcpp/algorithm.pxd, Cython/Includes/libcpp/iterator.pxd, Cython/Includes/libcpp/string.pxd, tests/run/cpp_stl_algo_nonmodifying_sequence_ops.pyx
=> Add most non-modifying sequence operations to libcpp.algorithm

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, tests/run/py3k_super.pyx
=> Fix temp variable handling for the super() class cell.

Cython/Compiler/Nodes.py, tests/run/generators.pyx
Fixes https://github.com/cython/cython/issues/3265
=> Fixed handling of kwds in generator closures

Cython/Utility/ExtensionTypes.c
Resolves #3238 (tagging @NielsLiisberg as an interested party) to allow modules to build on the IBM i platform (discovered via `uvloop`)
Thanks!
=> Change goto label to avoid compile conflict

Cython/Utility/Optimize.c, tests/run/pyintop.pyx
=> Bugfix bitwise and with negative operand

Cython/Compiler/ModuleNode.py, tests/compile/ctuple_cimport.pxd, tests/compile/ctuple_cimport_T1427.pyx
After some research into the various failure mechanisms, I think this is the right solution.
(Reopened PR https://github.com/cython/cython/pull/3255 to point to the proper source branch.)
=> FIX: Declare cimported ctuples (GH-1427)

Cython/Compiler/Visitor.py
Includes extra information for some additional types of Node
=> Improvements to PrintTree

Cython/Includes/cpython/pylifecycle.pxd
=> Fix the signature of _Py_PyAtExit()

Cython/Shadow.py, tests/run/cdivision_CEP_516.pyx
=> Fix the cdiv() and cmod() definitions in Shadow.py

Cython/Includes/cpython/object.pxd
Some declarations were missing from object.pxd.
=> Add missing declarations to object.pxd

docs/src/userguide/extension_types.rst
Original change https://github.com/cython/cython/pull/1927
=> Updated documentation of multiple inheritence rules

Cython/Includes/cpython/genobject.pxd, tests/run/cython_includes.pyx
(https://docs.python.org/3.8/c-api/gen.html).
=> Add genobject.pxd

Cython/Includes/libc/math.pxd
=> Add fpclassify() and FP_* constants to math.pxd

Cython/Includes/cpython/iterobject.pxd, tests/run/cython_includes.pyx
(https://docs.python.org/3.8/c-api/iterator.html).
=> Add iterobject.pxd

Cython/Includes/cpython/marshal.pxd, tests/run/cython_includes.pyx
(https://docs.python.org/3.8/c-api/marshal.html).
=> Add marshal.pxd

Cython/Compiler/Optimize.py, Cython/Utility/StringTools.c, tests/run/strfunction.pyx
Rough draft for #3279 using https://github.com/cython/cython/commit/5f7ebe56b90dcea733fc5c47b5a0e32de39d4419 as inspiration
I realize the Py2 compat is not correct; could use some guidance on how to best tackle if you have insight to offer
=> Optimize builtin str calls

Demos/pyprimes.py
I have edited the variable increments
before:
`n = n+1`
`k = k + 1`
`i = i + 1`
I changed it into 
`i += 1`
`n += 1`
`k += 1`
=> changed the variable increment

Cython/Compiler/ExprNodes.py, Cython/Compiler/FusedNode.py, Cython/Compiler/Nodes.py
=> Remove "unused function" C compiler warning about "__defaults__" getter of fused dispatch function.

docs/src/tutorial/pxd_files.rst
Closes #3424.
This is my first time using `reStructuredText`, and I'm not actually completely clear on what the rules and conventions are for `cimport`s either, so let me know or do a code change if I got something wrong.
=> Mention __init__.pxd in tutorial documentation.

Cython/Debugger/Cygdb.py
The whole cygdb construct is quite messy and a faulty installation is hard to debug because the error messages don't really hint at the problem.
This PR slightly improves the situation.
=> Better diagnostics for faulty installations.

Cython/Includes/libcpp/algorithm.pxd, Cython/Includes/libcpp/functional.pxd, tests/run/cpp_stl_algo_partitioning_ops.pyx, tests/run/cpp_stl_algo_sorting_ops.pyx, tests/run/libcpp_algo.pyx
=> Add partitioning and sorting operations to libcpp.algorithm

Cython/Compiler/ExprNodes.py
closes https://github.com/cython/cython/issues/3430
=> Release temps used for buffer indexing after use

Cython/Compiler/Nodes.py, Cython/Utility/ObjectHandling.c, tests/run/test_genericclass.py
To address https://github.com/cython/cython/issues/2753
TODO: Write tests
=> Update GetItem to support __class_getitem__ for type objects

Cython/Utility/StringTools.c, tests/run/unicode_slicing.pyx
=> Fix #3531: avoid integer overflow when computing unicode substring

Cython/Utility/StringTools.c, tests/run/bytesmethods.pyx, tests/run/charptr_decode.pyx
=> Avoid integer overflow when decoding bytes/charptr

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/Pipeline.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, Cython/Includes/numpy/__init__.pxd, tests/run/ext_attr_getter.srctree, tests/run/numpy_parallel.pyx
Rewrites #2640 and #3095 based on `inline` methods.
=> Rewrite the C property feature

Cython/Compiler/Main.py, Cython/Utils.py, tests/run/versioned_pxds.srctree
… like "lib.cython-30.pxd" for a Cython 3.0+ version.
See https://github.com/cython/cython/issues/3573
=> Support for versioned pxd files

Cython/Compiler/ExprNodes.py, tests/run/builtin_abs.pyx
=> Fix overflow handling for signed int abs

Cython/Compiler/Nodes.py, tests/run/fused_types.pyx
Fixes https://github.com/cython/cython/issues/3642
=> Fix a bug where fused_to_specific was applied too widely

Cython/Compiler/Options.py, tests/run/unicode_formatting.pyx
=> Change the default of c_api_binop_methods to False.

docs/src/userguide/sharing_declarations.rst
Part of https://github.com/cython/cython/issues/3583
=> Documentation for version-tagged pxd files

Cython/Utility/MemoryView_C.c, tests/memoryview/relaxed_strides.pyx
=> always consider 0-sized arrays as C- and F-contiguous

Cython/Includes/libcpp/unordered_map.pxd, tests/run/cpp_stl_cpp11.pyx, tests/run/cpp_unordered_map_helper.h
=> Additional unordered_map template defaults

Cython/Compiler/ExprNodes.py, tests/run/lvalue_refs.pyx
Fixes https://github.com/cython/cython/issues/3754
=> Fixed reference types being passed to getitemint

Cython/Utility/CppSupport.cpp
=> Use a generic shape accessor for pythranized array

Cython/Compiler/PyrexTypes.py, Cython/Compiler/Symtab.py, Cython/Utility/CppSupport.cpp, Cython/Utility/ModuleSetupCode.c
Attempt to fix the issue described here: https://github.com/cython/cython/pull/3640#issuecomment-656598139
=> Fix Python 3.4 + MSVC issue with elaborated type specifier for enum

Cython/Compiler/ModuleNode.py, tests/run/inlinepxd.pyx, tests/run/inlinepxd_support.pxd
Fixes https://github.com/cython/cython/issues/1071
Related to https://github.com/cython/cython/commit/4c02adc906a55cd5ac663b2bb62418cf1132092f
=> Avoid merged in code picking up directives from main module

Cython/Compiler/Parsing.py, tests/run/ctuple.pyx
=> Avoid parsing failure on cast to ctuple

Cython/Coverage.py, tests/run/coverage_cmd.srctree
=> Do not cover lines marked `# pragma: no cover`

Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, tests/compile/packed_structs.pyx
Specifically this allows public packed structs but may also allow
other public declarations that require small amounts of utility
code
=> Support utility code in headers

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, tests/run/cython3.pyx, tests/run/decorators_T593.pyx, tests/run/locals_T732.pyx, tests/run/metaclass.pyx, tests/run/pep526_variable_annotations.py, tests/run/pyclass_annotations_pep526.py, tests/run/test_grammar.py
This is an attempt to resolve #2552 and follows recommendations by @scoder.
Looking forward to your feedback!
=> Add support for PEP 526 `__annotations__` in class body.

docs/src/tutorial/cython_tutorial.rst, docs/src/tutorial/memory_allocation.rst, docs/src/tutorial/pure.rst, docs/src/userguide/extension_types.rst, docs/src/userguide/glossary.rst, docs/src/userguide/language_basics.rst, docs/src/userguide/parallelism.rst, docs/src/userguide/wrapping_CPlusPlus.rst
=> Some more glossary entries

Cython/Utility/MemoryView.pyx
=> Fix unused variable warnings resulting from disabling assertions

Cython/Includes/posix/fcntl.pxd
=> Add O_DIRECT to posix/fcntl.pxd

Cython/Includes/cpython/codecs.pxd, tests/run/cython_includes.pyx
(https://docs.python.org/3.9/c-api/codec.html).
=> Add codecs.pxd

Cython/Includes/cpython/cellobject.pxd, tests/run/cython_includes.pyx
(https://docs.python.org/3.9/c-api/cell.html).
=> Add cellobject.pxd

Cython/Includes/numpy/__init__.pxd
https://github.com/numpy/numpy/pull/17150/files
=> Port numpy#17150 __init__.pxd edits

Cython/Includes/cpython/datetime.pxd, tests/run/datetime_pxd.pyx
Open to suggestions for how to test these.
=> ENH: cproperties for datetime objects

CHANGES.rst
=> Fix an error in CHANGES.rst

docs/src/tutorial/appendix.rst
Change suggested by Stepan Kasal on Cython-devel list
=> Update link to what's new in appendix

Cython/Utility/Coroutine.c, Cython/Utility/arrayarray.h
Don't access directly PyObject.ob_refcnt and PyVarObject.ob_size.
=> Use __Pyx_SET_SIZE() and __Pyx_SET_REFCNT()

tests/errors/e_decorators.pyx
It wasn't actually testing anything
=> Fixed e_decorators test

Cython/Build/Inline.py
Backport code from the master branch:
* commit 4e785d425f27f079bf2f6bba1381217fac4f5da3
* commit a9fb77681e41810052df0b41b25abb12738bb8f3
=> Make load_dynamic() compatible with Python 3.10

Cython/Compiler/ExprNodes.py, Cython/Compiler/Parsing.py, tests/run/test_fstring.pyx
=> Self documenting f-strings

.github/workflows/ci.yml, Cython/Utility/Profile.c, Tools/ci-run.sh, setup.py
Allow comparing speed and completeness of plain Python vs. compiled Cython.
=> Add coverage test job with compiled Cython

Cython/Compiler/ExprNodes.py, Cython/Compiler/UtilNodes.py, tests/run/type_inference.pyx
=> Fix type inference on builtin max

docs/conf.py
xref #4209 
The old extension was removed in sphinx1.8
=> change extension for sphinx 1.8+

Cython/Compiler/Symtab.py, tests/run/cython3.pyx
It looks to me to backport cleanly - I wonder if it initially failed because it was actually two commits so it requires both of them to be backported?
Fixes #4214
=> Backport #2811 to fix qualified-name issues

tests/run/cpp_classes_def.pyx
https://github.com/cython/cython/pull/4213#discussion_r648005583
=> Changed test for GH4212

Cython/Compiler/ExprNodes.py, tests/run/seq_mul.py
Closes https://github.com/cython/cython/issues/3922
=> Optimise "[...] * N" where N is a non-literal C integer value.

docs/src/tutorial/numpy.rst
People often have unrealistic expectations about what this typing helps with, so I've added a small paragraph to try to make it clearer.
=> Docs: limitations of np.ndarray

Cython/Compiler/ModuleNode.py, Cython/Utility/ExtensionTypes.c, tests/run/binop_reverse_methods_GH2056.pyx
Fixes #4172 by avoiding an infinitely loop on when not implemented.
=> Fix recursion in binops

docs/examples/tutorial/clibraries/cqueue.pxd, docs/examples/tutorial/clibraries/queue.py, docs/examples/tutorial/clibraries/queue.pyx, docs/examples/tutorial/clibraries/queue2.py, docs/examples/tutorial/clibraries/queue2.pyx, docs/examples/tutorial/clibraries/queue3.py, docs/examples/tutorial/clibraries/queue3.pyx, docs/src/tutorial/clibraries.rst
This PR is introducing pure python mode in Using C libraries tutorial. It is partial fix of #4187
=> Docs: Introduce pure python mode in Using C libraries tutorial

Cython/Compiler/ModuleNode.py, tests/run/include_multiple_modules.srctree
=> Make __PYX_WARN_IF_INIT_CALLED name unique per-module

docs/examples/tutorial/memory_allocation/malloc.py, docs/examples/tutorial/memory_allocation/some_memory.py, docs/src/tutorial/memory_allocation.rst
Continuing to Pythonize Сython documentation!
This PR Pythonizes [this](https://cython.readthedocs.io/en/latest/src/tutorial/memory_allocation.html) documentation page.
Lots of process details and standardization are found here: #4187
=> Pythonise Memory Allocation (memory_allocation.rst)

Cython/Compiler/Buffer.py, Cython/TestUtils.py
This PR fixes bugs that will allow to add Windows tests to GitHub Actions workflow in PR #4324
=> Fix bugs with Windows

Cython/Includes/cpython/unicode.pxd
See https://docs.python.org/3.5/c-api/unicode.html#c.PyUnicode_CompareWithASCIIString
=> PyUnicode_CompareWithASCIIString fix signature

Tools/cython-mode.el
The function `(cython-current-defun)` of `cython-mode.el` had some issues:
* ran into an endless loop
* for `cdef`s and `cpdef`s it picked the function type rather than the function
name.
* did not properly handle nested functions
This attempts to fix those issues
=> [cython-mode.el] Attempt to fix #3218 and other bugs around it

setup.py
Similar to #4449 but only updating the metadata.
=> Add Python 3.10 classifier (0.29.x backport)

tests/run/uninitialized.py
Exception messages had changed a little
=> Fixed uninitialized test on 3.11

tests/pypy2_bugs.txt, tests/pypy_bugs.txt, tests/pypy_implementation_detail_bugs.txt, tests/run/matrix_multiplier.pyx, tests/run/test_genericclass.py, tests/run/test_genericclass_exttype.pyx, tests/run/unicodemethods.pyx
"Fixes" a few bugs that are just caused by very small implementation
details, recategorize some others (e.g. those that cimport array
are not expected to ever work)
=> Recategorize a few pypy bugs, fix some others

Cython/Compiler/Nodes.py, tests/compile/cpp_temp_assignment.pyx, tests/run/cpp_locals_parallel.pyx
=> Support cpp_locals and std::move on prange temps

Cython/Build/Dependencies.py, Cython/Distutils/build_ext.py, pyximport/pyxbuild.py, pyximport/pyximport.py, tests/pyximport/pyximport_pyimport_only.srctree, tests/pyximport/pyximport_pyxbld.srctree
This PR uses cythonize() in pyximport. Closes #2304.
=> Use cythonize in pyximport

Cython/Utility/ImportExport.c, Cython/Utility/ModuleSetupCode.c, tests/pypy2_bugs.txt, tests/run/partial_circular_import.srctree
=> Add partial circular import fix (and test) for #4390

Cython/Compiler/ExprNodes.py, tests/run/lvalue_refs.pyx
Fixes https://github.com/cython/cython/issues/1863
=> Remove ban on assignment to reference

CHANGES.rst, Cython/Compiler/ModuleNode.py, Cython/Compiler/Nodes.py, Cython/Utility/ExtensionTypes.c, Cython/Utility/ModuleSetupCode.c
I certainly missed a few candidates, but this is a start.
=> Use PyType_GetSlot() in more places to avoid direct slot access

docs/src/userguide/source_files_and_compilation.rst
=> Document cython.compile

Cython/Build/Cythonize.py, Cython/Build/Dependencies.py, tests/build/depfile.srctree, tests/build/depfile_numpy.srctree, tests/build/depfile_package.srctree
Backport of gh-4563 for 0.29.x
=> Backport gh-4563 : generate dependency files

docs/examples/tutorial/array/clone.py, docs/examples/tutorial/array/overhead.py, docs/examples/tutorial/array/overhead.pyx, docs/examples/tutorial/array/resize.py, docs/examples/tutorial/array/safe_usage.py, docs/examples/tutorial/array/unsafe_usage.py, docs/src/cimport-warning, docs/src/tutorial/array.rst
Continuing to Pythonize Сython documentation!
This PR Pythonises [this](https://cython.readthedocs.io/en/latest/src/tutorial/array.html) documentation page.
Lots of process details and standardization are found here: #4187
=> Pythonise "Working with Python arrays" (array.rst)

.github/ISSUE_TEMPLATE/config.yml
I don't know if this works, but it's worth a try...
=> Try to direct to cython-users before the issue template

Cython/Compiler/Nodes.py, tests/run/ext_type_none_arg.pyx
Fixes https://github.com/cython/cython/issues/4668
=> Allow None to be passed to args annotated as object

tests/build/cythonize_cython.srctree
Fixing failing unittests in #4629
=> Fix typo in tests/build/cythonize_cython.srctree

docs/src/userguide/source_files_and_compilation.rst
Just let me make a meager contribution to the project and make it a little bit better.
=> Correct the typo in the word "decorator"

Cython/Utility/ModuleSetupCode.c
See comment https://github.com/cython/cython/issues/2542#issuecomment-1121484721 for bug report
=> Fix version detection and warning with double-digit versions

Cython/Compiler/Nodes.py, tests/run/cfuncptr.pyx
Fixes https://github.com/cython/cython/issues/4770
=> Preserve except* in function pointer types

Cython/Utility/CythonFunction.c, tests/run/cyfunction.pyx
Fixes https://github.com/cython/cython/issues/4779
Draft PR for now because I've run out of time/energy to do tests so I'll come back to it.
Note - PR is against 0.29.x (but I think should apply cleanly to master too)
=> IndexError->TypeError when calling unbound CyFunctions

Cython/Compiler/PyrexTypes.py, tests/errors/cfuncptr.pyx, tests/run/cfuncptr.pyx
and widen function pointer compatibility options slightly.
Issue #4689 - it was mostly already working, but not quite
perfectly
=> Add tests for function pointer exception specification conversion

Cython/Shadow.py
=> BUG: fused types not subscriptable in Cython.Shadow

Cython/Compiler/ExprNodes.py, tests/run/pep448_extended_unpacking.pyx
Fixes #4861
PR is against 0.29.x branch
=> Fix tuple multiplication in MergedSequenceNode

tests/buffers/bufaccess.pyx, tests/memoryview/memslice.pyx
Follow up on https://github.com/cython/cython/pull/4859
by adding tests for memoryviews too
#4858
@seberg
=> Tests for NULL objects in memoryviews

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/FlowControl.pxd, Cython/Compiler/FlowControl.py, Cython/Compiler/Naming.py, Cython/Compiler/Nodes.py, Cython/Compiler/Symtab.py, tests/run/funcexc_iter_T228.pyx
Fixes https://github.com/cython/cython/issues/3447
=> Avoid raising StopIteration in __next__ 

Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/Visitor.py, tests/run/decorators.pyx
Fixes https://github.com/cython/cython/issues/4836
=> Avoid conflict between propery names and function variables

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, tests/run/append.pyx, tests/run/assigned_builtin_methods.pyx
fixes https://github.com/cython/cython/issues/4828
=> Fixed over-zealous optimization of __Pyx_PyObject_Append

.github/workflows/ci.yml
See https://github.com/cython/cython/issues/4913
=> Update macos version for github actions

Cython/Compiler/CmdLine.py, Cython/Compiler/Main.py, Cython/Compiler/Tests/TestCmdLine.py, tests/compile/module_name_arg.srctree
Naïve backport of #4548 to 0.29 as discussed in that PR. If something breaks, it's 100% my fault 😅
=> [0.29] Add --module-name argument to cython command

Cython/Utility/MemoryView.pyx, Cython/Utility/MemoryView_C.c, tests/memoryview/memslice.pyx
Closes https://github.com/cython/cython/issues/4927
=> Fix error where import * tried to overwrite a macro

Cython/Build/Cythonize.py
I suppose we can close #1711 by accepting this PR.
=> Added epilog to cythonize listing supported environment variables

Tools/ci-run.sh
https://github.com/cython/cython/commit/16811213c6e21459582e29eb33f4a4fb80322b86#r80516644
=> ci-run.sh: Fix formatting of the condition

Tools/ci-run.sh
=> ci-run.sh: run msvc build with multiple processes

Cython/Utility/CythonFunction.c
=> "Fix" an exception formatting issue on Py2

docs/examples/userguide/early_binding_for_speed/rectangle.py, docs/examples/userguide/early_binding_for_speed/rectangle_cdef.py, docs/examples/userguide/early_binding_for_speed/rectangle_cdef.pyx, docs/examples/userguide/early_binding_for_speed/rectangle_cpdef.py, docs/examples/userguide/early_binding_for_speed/rectangle_cpdef.pyx, docs/src/userguide/early_binding_for_speed.rst
=> Docs: Migrate early binding for speed userguide to pure python

docs/examples/userguide/buffer/matrix.py, docs/examples/userguide/buffer/matrix.pyx, docs/examples/userguide/buffer/matrix_with_buffer.py, docs/examples/userguide/buffer/matrix_with_buffer.pyx, docs/examples/userguide/buffer/view_count.py, docs/examples/userguide/buffer/view_count.pyx, docs/src/userguide/buffer.rst
=> Docs: Migrate buffer userguide to pure python

docs/src/tutorial/clibraries.rst, docs/src/userguide/language_basics.rst
=> Docs: Update documentation after introduction of noexcept

.github/workflows/ci.yml
=> Update CCache script version

Cython/Compiler/ExprNodes.py, Cython/Utility/ObjectHandling.c
=> Optimized implementation of bound c methods

Cython/Compiler/Nodes.py, tests/run/return.pyx
=> Allow returning const types.

.github/workflows/ci.yml, Cython/Utility/ObjectHandling.c, Tools/ci-run.sh
Just want to run this on the CI before committing it - it didn't quite merge cleanly
=> 0.29.x merge

Cython/Compiler/Main.py, Cython/Compiler/Options.py, Cython/Compiler/Parsing.py, Cython/Compiler/TreeFragment.py, docs/src/userguide/language_basics.rst, docs/src/userguide/migrating_to_cy30.rst, docs/src/userguide/source_files_and_compilation.rst, tests/run/legacy_implicit_noexcept.pyx, tests/run/legacy_implicit_noexcept_build.srctree
=> Add compiler directive to disable the default exception propagation

Cython/Compiler/ExprNodes.py, Cython/Compiler/Options.py
Goes with https://github.com/cython/cython/pull/5016
=> Add 'cpow' as a forward compatibility to 0.29.x

Cython/Utility/Complex.c
Essentially SoftComplexToPy required another bit of utility code that has now become tempita. I've just skipped using this utility code
=> Fix error from combination of two Complex.c changes

tests/run/numpy_parallel.pyx, tests/run/numpy_test.pyx
numpy.int was deprecated and has now been removed
=> numpy.int -> numpy.int_

tests/run/numpy_parallel.pyx, tests/run/numpy_test.pyx
=> [0.29.x] numpy.int -> numpy.int_

Cython/Shadow.py, tests/run/pure_py.py, tests/run/pure_py3.py
=> Add `annotation_typing` in shadow.py

Cython/Compiler/Code.py, Cython/Compiler/Dataclass.py, Cython/StringIOTree.pxd, Cython/StringIOTree.py
makes insertion points behave as they do elsewhere, adds the ability to track indentation (which I don't use here, but which I think will clear things up)
=> Use PyxCodeWriter in the dataclass TemplateCode

Cython/Compiler/Optimize.py, Cython/Utility/Builtins.c, tests/run/py_ucs4_type.pyx
Closes https://github.com/cython/cython/issues/5216
=> Make sure we parse int(Py_UCS4) as a digit and not a plain character value integer

docs/examples/tutorial/parallelization/manual_work.py, docs/examples/tutorial/parallelization/manual_work.pyx, docs/examples/tutorial/parallelization/median.py, docs/examples/tutorial/parallelization/median.pyx, docs/examples/tutorial/parallelization/norm.py, docs/examples/tutorial/parallelization/norm.pyx, docs/examples/tutorial/parallelization/normalize.py, docs/examples/tutorial/parallelization/normalize.pyx, docs/examples/tutorial/parallelization/parallel_sin.py, docs/examples/tutorial/parallelization/parallel_sin.pyx, docs/examples/tutorial/parallelization/setup.py, docs/src/quickstart/install.rst, docs/src/tutorial/index.rst, docs/src/tutorial/parallelization.rst
I've written a parallelization tutorial. It doesn't cover that much new ground from the main parallelization documents, but hopefully it present a separate example of each use case, and is a little less of "here are the parameters, good luck" than the main parallelization reference
Kind of closes https://github.com/cython/cython/issues/5125
=> [docs] Parallelization tutorial

Cython/Compiler/Code.py
Another thing uncovered by https://github.com/cython/cython/pull/5261
Not all `py_constants` are actually `py_constants` so they need to be checked before generating clean-up code.
In this case integer function argument defaults look to be being added to `py_constants`.
This possibly isn't the right place to fix it though, so I'm open to other suggestions
=> Fix cleanup of non-py-object constants on module close

Cython/Compiler/Builtin.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/PyrexTypes.py, Cython/Utility/Builtins.c, tests/run/builtin_memory_view.pyx
Fixes #5270 - error in capitalization
Fixes #5268 - with managers were being optimized into a non-working state
=> Fix a couple of memoryview issues

Cython/Compiler/ParseTreeTransforms.py, tests/errors/e_invalid_special_cython_modules.py
Tries to provide some helpful hints for #5288 where people may be trying to cimport directives/types as if they were a module.
=> Improve error message for 'cimport cython.floating'

Cython/Compiler/Nodes.py
Originally proposed in  https://github.com/cython/cython/issues/5347#issuecomment-1493260542
=> Clean up the for-loop iterator before entering the 'else' branch

Cython/Utility/Builtins.c, Cython/Utility/Optimize.c, Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c
See https://github.com/python/cpython/pull/102464
=> Implement support for the new PyLong struct layout in Py3.12a7

Cython/Utility/Buffer.c, Cython/Utility/CMath.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/Overflow.c, tests/pypy2_bugs.txt, tests/run/buffer_n_overflowcheck_T5356.pyx
=> Fix duplication of `IS_UNSIGNED_IMPL`

.readthedocs.yaml
=> Backport .readthedocs.yaml

docs/src/userguide/external_C_code.rst, docs/src/userguide/migrating_to_cy30.rst
Related to #5040
> **Note**: #5371 needs to be merged first.
=> Document `CYTHON_EXTERN_C` macro

Cython/Compiler/ExprNodes.py, Cython/Utility/TypeConversion.c, docs/examples/userguide/numpy_ufuncs/ufunc_ctuple.py, docs/src/userguide/language_basics.rst, tests/run/annotation_typing.pyx, tests/run/ctuple.pyx
Closes https://github.com/cython/cython/issues/5397
I admit that this is really 3 PRs in 1, but I hope it's not controversial and would be annoying to rip apart.
Best to merge this via rebase.
=> Improve handling of ctuples in annotations and assignments

Cython/Compiler/FusedNode.py, tests/memoryview/numpy_memoryview.pyx
=> Catch ValueError when calling memoryview()

Cython/Utility/ExtensionTypes.c
Closes https://github.com/cython/cython/issues/5418
=> Avoid generating dead code in the special binop method handling helpers

docs/src/userguide/numpy_tutorial.rst
Since it's a source of confusion https://groups.google.com/g/cython-users/c/MGxLwVIUaqU
=> Document different openmp command line argument on Windows

docs/src/userguide/faq.rst, docs/src/userguide/index.rst
Follow on to #5374 in order to
- Reformat the page and get rid of the warnings and errors, hopefully without changing the content
- Add a top heading
- Link the FAQ to the userguide index
=> fomatting and linking the FAQ

Cython/Compiler/ModuleNode.py, Cython/Utility/ModuleSetupCode.c
Supersedes #5474
Co-authored-by: Thomas A Caswell <tcaswell@gmail.com>
=> Use `PyObject_GC_IsFinalized` in Cython >= 3.9

Cython/Compiler/ExprNodes.py, Cython/Includes/libcpp/map.pxd, tests/run/cpp_iterators.pyx
And use the same hack from forward iteration.
=> Don't remove const for reverse iteration

Cython/Compiler/Options.py, tests/build/cython_language_level.srctree
=> Dont override language_level from directives when set to None

tests/run/cpdef_enums.pyx
=> Temporary fix for tests on Python <= 3.5

Cython/Compiler/Main.py
=> print --version to stdout [no ci]

docs/src/userguide/nogil.rst
Document new decorator implemented in #5491
=> Document @cython.with_gil

Cython/Compiler/Nodes.py, tests/run/cpdef_enums.pyx
And other "special" integer constants.
Fixes #5524
=> Support hex constants in enums

README.rst
Cython 3 has been released, it's not a future project any more!
=> Update comment in README about Cython 3

Cython/Compiler/Nodes.py, tests/compile/cppenum.pyx
=> Allow interdependency between cpdef enums

Cython/Compiler/PyrexTypes.py, tests/run/exceptionpropagation.pyx
=> Use NULL as default exception value for ptrs

Cython/Compiler/Main.py, Cython/Compiler/Nodes.py, Cython/Compiler/Symtab.py, Cython/Compiler/TreeFragment.py, Cython/Compiler/UtilityCode.py, tests/run/relative_import_leak.srctree
This is first draft of PR. Maybe it is worth of refactoring code of lookup modules to improve readability. Tests to be implemented.
Fixes #5511
=> Fix leaking of Relative cimport out of the package to the environment

Cython/Compiler/ExprNodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/PyrexTypes.py, Cython/Compiler/TypeInference.py, tests/run/cpp_iterators.pyx
Fixes #5558 and hopefully #5333
=> Avoid creating const members in closure structs

Cython/Build/Cythonize.py
=> Remove useless shebang

Cython/Utility/ModuleSetupCode.c
Since it's available as a standard feature from C++11
=> Define thread_local for C++

Cython/Utility/StringTools.c, Cython/Utility/TypeConversion.c, tests/run/isolated_limited_api_tests.srctree
=> Fix bytes/bytearray decode in limited API

Cython/Compiler/ExprNodes.py, tests/run/isolated_limited_api_tests.srctree
Closes https://github.com/cython/cython/issues/5641
=> Make for-loops work in the Limited C-API

Cython/Compiler/Main.py, tests/run/relative_cimport.srctree
=> Fix relative cimport when package contains only `__init__.py`

Cython/Includes/libcpp/functional.pxd, tests/run/cpp_stl_cpp11.pyx
Adds libcpp bindings for `std::reference_wrapper`
=> Add reference_wrapper

Cython/Compiler/ExprNodes.py, tests/run/if_else_expr.pyx
Fixes https://github.com/cython/cython/issues/5731
=> Fix issue with mixed-type "x if y else z" expressions

Cython/Compiler/Symtab.py, tests/run/inlinepxd.pyx, tests/run/inlinepxd_support.pxd
Fixes #5748
Unfortunately I haven't been able to produce an isolated test for this yet.
=> Fix regression with inline functions in pxd

Cython/Compiler/ExprNodes.py, runtests.py, tests/memoryview/memoryview.pyx
=> Fix and test memoryview indexing performance_hint

Cython/Build/BuildExecutable.py, Cython/Parser/ConcreteSyntaxTree.pyx
=> Use sysconfig module instead of distutils.sysconfig for python >= 3.9

Cython/Compiler/FusedNode.py, tests/run/cimport_from_pyx.srctree
=> Fix issue with cpdef functions and cimport_from_pyx

Cython/Compiler/Options.py, Cython/Shadow.py, Cython/Tests/TestShadow.py, tests/bugs.txt
Mainly to confirm that all directives that should appear there do actually appear there, and also to confirm the presence of a few types.
=> Add tests for some of the contents of Shadow.py

Cython/Utility/Complex.c
=> Check for MSVC when checking for complex support on C11

Cython/Compiler/Optimize.py, tests/run/pyintop.pyx
For now let's get optimisation of int variable on par with untype variable. Further optimisations can be done in separate PR.
Fixes #5783.
=> Optimize numerical operations with python integer variable

Cython/Compiler/Code.py, Cython/Utility/Buffer.c, Cython/Utility/Exceptions.c, Cython/Utility/MemoryView_C.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/Profile.c
It's now always true for all the platforms we care about.
Closes https://github.com/cython/cython/issues/5812
=> Remove checks for WITH_THREAD

Cython/Build/IpythonMagic.py
displaying the full HTML document inline can result in problems rendering and can produce invalid HTML documents after export via nbconvert, mystnb, etc. In particular, my jupyter-book-built pages with `%%cython --annotate` output end up applying `.cython` to the _document_ body because of the duplicated `<body>` tags, in particular causing the whole page to render with courier.
This is easier and cleaner with a full HTML parser, but I imagine you don't want that as a dependency just for this. My in-production workaround is [here](https://github.com/UiO-IN3110/UiO-IN3110.github.io/blob/da31b00527ba0e81b3ae4d96df73ea7eac66521b/lectures/mixed-programming/_cython_annotate_fix.py):
```python
from functools import partial
from bs4 import BeautifulSoup
def _clean_annotated_html(original_clean, …
```
=> cython magic: extract style, body, not full HTML document

Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Compiler/Nodes.py, Cython/Utility/Coroutine.c
A try to remove patch utility code which seems not needed anymore.
~This is experiment PR just to see the CI results.~
=> Remove patch utility code in Coroutine.c

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, Cython/Compiler/PyrexTypes.py, tests/errors/reversed_literal_pyobjs.pyx, tests/run/type_inference.pyx, tests/run/type_inference_ll2.pyx
See https://github.com/cython/cython/issues/4237
Closes https://github.com/cython/cython/issues/5743
=> Infer the result type of builtin numeric binary operations

docs/src/tutorial/numpy.rst
We've had a few questions asking about this so I think it makes sense to add a note to the documentation.
=> Note on pure-Python mode and Numpy arrays

tests/run/line_trace.pyx
This is something of a wild guess, to see if it fixes the tests on Windows 3.12.
If it works, will close #5833
=> Try disabling gc for line-trace tests

Cython/Compiler/Nodes.py, tests/errors/const_decl_errors.pyx
=> [3.0.x] Warn about discarting const qualifier (#5987)

Cython/Utility/Coroutine.c, tests/run/generators_pep479.pyx
=> Explicitly set exception cause in __Pyx_Generator_Replace_StopIteration

Cython/Compiler/PyrexTypes.py, tests/run/fused_cdef.pyx
=> Fix call of final fused cdef functions

Cython/Compiler/PyrexTypes.py, tests/run/fused_cdef.pyx
=> [3.0.X] Fix call of final fused cdef functions (#6005)

Cython/Compiler/Nodes.py, Cython/Compiler/ParseTreeTransforms.py, Cython/Compiler/Parsing.py, tests/errors/w_noexcept.pyx, tests/run/legacy_implicit_noexcept.pyx
=> [3.0.x] Warn when function returning python object is marked as noexcept (#5999)

pyximport/_pyximport2.py, pyximport/_pyximport3.py
Fixes #5980
Just checking that it works before merging. It looks like a separate PR will be needed for master.
=> Fix typo in assertion (3.0.x)

Cython/Utility/ModuleSetupCode.c
=> Fix PyImport_AddModuleRef on the limited API

Cython/Compiler/ModuleNode.py
It's still unused even if we don't set it, so take it out of the bit that sets it conditionally.
=> Fix (most) unused variable warnings about clineno

Cython/Compiler/ModuleNode.py, tests/run/exttype_gc.pyx
Fixes #5971 
This works to solve me.  But I'm not sure if there is some mechanism to figure this situation in the compiler 
class DoesntNeedGC(BuiltinThatNeedsGC): pass
class NeedsGC(DoesntNeedGC): pass
=> Don't miss a required PyObject_GC_Track() in dealloc

CHANGES.rst
Changlog for https://github.com/cython/cython/commit/ead1ac69413e13d57a23a5a336a6896850a5c172
=> Add fixing of warning in 3.0.9 to CHANGES.rst

docs/src/userguide/faq.rst
Follow up to 408afdc106d9a332a4152d7a12531955de2d104e
Just leaving this up briefly in case there's any comments. If not I'll merge it tomorrow.
=> Mention `binding` in the size faq

docs/src/userguide/faq.rst
=> Add note about docstring to 'How do I reduce the size of the binary modules' faq

Cython/Compiler/Optimize.py
... in module init function. More marginal size reductions.
=> Avoid unpacking method calls at class scope

Cython/Includes/libcpp/complex.pxd, docs/examples/userguide/wrapping_CPlusPlus/python_to_cpp.pyx, docs/src/userguide/troubleshooting.rst, docs/src/userguide/wrapping_CPlusPlus.rst, tests/run/complex_numbers_cpp.pyx
* removing overload operator+ that seems to create a compilation issue
* adding unary operators + and -
* fixing type (polar)
* adding unit tests
Let me know if there is a particular linting/formatting to perform.
=> C++ complex class fixes and tests

Cython/Compiler/ModuleNode.py, Cython/Utility/ImportExport.c
(No need to review - just testing that it works. Will merge if it passes)
=> Change a "char *" to "const char*" in import code

Cython/Compiler/ExprNodes.py, Cython/Compiler/ModuleNode.py, Cython/Compiler/Symtab.py, tests/bugs.txt, tests/run/inherited_final_method.pyx
May not be the perfect and definitive fix, but hopefully better than adding workarounds with `#pragma GCC ...`.
Fixes #2747.
=> Fix bad self casts when calling methods of final types

Cython/Build/Dependencies.py, docs/src/userguide/source_files_and_compilation.rst
=> [docs] Document Cython cache

Cython/Build/Cache.py, Cython/Build/Dependencies.py, Cython/Compiler/Main.py
=> Refactor of Cache.py

Cython/Compiler/ExprNodes.py, Cython/Utility/CppConvert.pyx, Cython/Utility/CythonFunction.c, Cython/Utility/ImportExport.c, Cython/Utility/MemoryView_C.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/TypeConversion.c
This PR adds some additional support for using Python's limited API in more parts of Cython.
=> Add some more limited API support

Cython/Utility/Optimize.c, tests/run/isolated_limited_api_tests.srctree
=> Make limited API object==float work

Cython/Compiler/Nodes.py, runtests.py, tests/pypy2_bugs.txt, tests/run/legacy_implicit_noexcept_build.srctree
=> [3.0] Do not set exception_check if already set during analyzing pxd file

docs/src/userguide/language_basics.rst
Created based on discussion: https://github.com/cython/cython/issues/5245#issuecomment-2083523496
=> [Docs] Document examples of arrays of pointers and pointer to array

docs/examples/userguide/extension_types/dataclass.pyx
https://github.com/cython/cython/issues/4800
=> Improve `@dataclass` example

Cython/Build/Dependencies.py, docs/src/userguide/source_files_and_compilation.rst
=> Copy py_limited_api attribute of setuptools extension

docs/examples/tutorial/string/for_bytes.py, docs/examples/tutorial/string/for_char.py, docs/examples/tutorial/string/for_unicode.py, docs/examples/tutorial/string/if_char_in.py, docs/src/tutorial/strings.rst
Related to #4389, part of #4187.
=> Docs: Migrate several sections of "Unicode and passing strings" tutorial to pure python

Cython/Compiler/ExprNodes.py, Cython/Compiler/Optimize.py, tests/run/inop.pyx, tests/run/tuple.pyx
Closes https://github.com/cython/cython/issues/6288
=> Discard in-tests against empty sequences if they have no side effects.

docs/src/userguide/freethreading.rst, docs/src/userguide/index.rst, docs/src/userguide/nogil.rst
Just a fairly basic summary of the current status and some known problems.
=> Freethreading documentation

Cython/Compiler/TypeInference.py
instead use the mechanism designed for this.
(Mostly just checking that it work.... I think it should be right, but maybe I've missed something)
=> Avoid reassigning child_attrs

Cython/Compiler/ModuleNode.py, Cython/Compiler/Nodes.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/ObjectHandling.c
It's unused and no longer does anything
=> Remove GenericGetAttr utility code

Cython/Compiler/Code.py, Cython/Utility/Builtins.c, Cython/Utility/CythonFunction.c, Cython/Utility/Dataclasses.c, Cython/Utility/Exceptions.c, Cython/Utility/ExtensionTypes.c, Cython/Utility/FunctionArguments.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/StringTools.c, tests/build/common_include_dir.srctree, tests/windows_bugs.txt
Suggested here: https://github.com/cython/cython/pull/5323#issuecomment-2303922556
=> Add utility code macro "EMPTY(bytes|tuple|...)"

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/Tests/TestCode.py, Cython/Utility/TypeConversion.c
This isn't a big improvement since most of the time is spent in parsing/processing rather than generating the Cython utility code. It seemed more like a fun project to rewrite the textwrap based implementation in a more efficient way.
Downside is that it adds quite a bit of code. But at least it's tested. :)
=> Faster chunk indentation in PyxCodeWriter

Cython/Utility/Builtins.c
=> Fix CYTHON_LIMITED_API -> __PYX_LIMITED_VERSION_HEX 

pyximport/_pyximport3.py, tests/pyximport/pyximport_pythonpath.srctree
=> [3.0.x] pyximport: Search also pythonpath when searching for .pyx/.py file

docs/src/tutorial/pure.rst
=> Document `Union[tp, None]`

Cython/Compiler/ExprNodes.py, tests/errors/e_typing_errors.pyx, tests/memoryview/memoryview_annotation_typing.py, tests/run/annotation_typing.pyx, tests/run/ext_type_none_arg.pyx, tests/run/pep526_variable_annotations.py, tests/run/pure_ctuple.py, tests/run/pyintop.pyx
=> Implement optional annotation type `tp | None`

runcodestyle.py
Mostly because I find it hard to select those out of the runtests script.  I considered a separate command-line option but that seemed like a bigger change.
=> Add a separate script that just runs code style tests

Cython/Utils.py, tests/build/depfile_numpy.srctree
Close #6291.
This has been tested to work as expected on numpy, scipy and scikit-learn.
Suggestions more than welcome on how to add a test for this!
=> Use relative path for depfile

Cython/Compiler/ExprNodes.py, tests/run/extra_walrus.py
Fixes https://github.com/cython/cython/issues/6434
=> Fix ref counting of assignment expression memviews

Cython/Compiler/Pythran.py, Tools/ci-run.sh, tests/run/ufunc.pyx
Gets Pythran tests running again. I'm not sure this is the most efficient way of doing it (there may be some unnecessary copies), but it's about the limit of my understanding.
=> Fix Pythran

Cython/Compiler/FusedNode.py
I'm fairly sure we're not supporting PyPy2 any more.
=> Remove old PyPy2 workaround

Cython/Utility/FunctionArguments.c, Cython/Utility/Optimize.c, tests/limited_api_bugs.txt, tests/memoryview_tests.txt, tests/run/builtin_basestring.pyx
Almost no code changes; just disabling non-working tests.
=> Enable Limited API run tests (a-d)

Cython/Compiler/ExprNodes.py, Cython/Compiler/Nodes.py, tests/run/closure_inlining.pyx
=> Fix inlined calls of functions with closures with binding=False

Cython/Includes/libc/threads.pxd, Cython/Includes/libc/time.pxd, Cython/Includes/libcpp/mutex.pxd, Cython/Includes/libcpp/shared_mutex.pxd, runtests.py, tests/run/cpp_mutex.pyx, tests/run/libc_threads.pyx
(Given it's only libraries I'll leave it a few days for review comments and merge it if none appear, and if the tests pass - I don't think it needs hugely detailed review)
=> Add libc and libcpp mutex libraries

Cython/Compiler/ExprNodes.py, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c
Arguably it's fairly pathalogical code that'd ever be affected by this, but we're making other list code thread safe so no reason not to do this.
=> Thread safety for list slice

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/Nodes.py
=> Remove "in_try_finally" from funcstate

Cython/Utility/Coroutine.c, tests/run/async_def.pyx
=> Fix GetSet function definition for coroutine ci_running

Cython/Debugger/libcython.py
for backwards compatibility with GDB 12 to resolve [this comment](https://github.com/cython/cython/pull/5958#discussion_r1958890525)
=> remove static_link from GDB API dependencies

Cython/Utility/CythonFunction.c
Two improvements for https://github.com/cython/cython/pull/6582
=> Improve critical sections in CyFunction

Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c
Tries to resolve parts of the performance regression of Cython 3.1 compared to 3.0 found in https://github.com/cython/cython/issues/6710
=> Optimise async implementation

Cython/Compiler/Code.py, Cython/Compiler/Nodes.py, Cython/Utility/CythonFunction.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/ObjectHandling.c, Cython/Utility/TypeConversion.c
Includes cherry-pick of #6636.
=> Fix C compiler warnings

Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c
Hopefully should be fastter because it avoids exception-handling.
See https://github.com/cython/cython/issues/6710
=> Avoid raising StopIteration from iternext

Cython/Utility/Coroutine.c
I'm fairly sure this is the intent.
=> Use optimized GetAwaitableIter function

.github/workflows/ci.yml, Demos/benchmarks/run_benchmarks.py
It might be useful information, maybe. We've certainly spent a bit of time trying to reduce it at times...
=> Have the benchmark runner report compiled file sizes

docs/src/userguide/source_files_and_compilation.rst
(No need for review - will merge when I've checked the docs look right)
=> Fix formatting of a link in the docs

CHANGES.rst
The directive doesn't take True as an argument.
=> Small correction to changelog

Cython/Compiler/ExprNodes.py, tests/run/cpp_struct_refs.pyx
=> Avoid making DictNodes with reference types

Cython/Compiler/ExprNodes.py, tests/run/type_inference.pyx
=> Better fix for type of variable named after type

Cython/Compiler/Builtin.py, Cython/Utility/ImportExport.c, Cython/Utility/ObjectHandling.c
=> Limited api fixups

Cython/Compiler/ExprNodes.py, tests/run/cpdef_enums.pyx
Closes https://github.com/cython/cython/issues/4571#issuecomment-2876089164
=> Allow access to special attributes on cpdef enums.

Cython/Utility/Coroutine.c, tests/run/asyncio_leaks.srctree
Fixes https://github.com/cython/cython/issues/6878
Fixes https://github.com/cython/cython/issues/6850
=> Fix a reference leak of async return values on delegation

Cython/Compiler/Code.pxd, Cython/Compiler/Code.py, Cython/Compiler/ModuleNode.py, Cython/Compiler/Naming.py, Cython/Utility/AsyncGen.c, Cython/Utility/Coroutine.c, Cython/Utility/CythonFunction.c
By moving them into utility code rather than having a list of shared types in "Naming"
=> Refactor declaration, initialization and cleanup of shared types

runtests.py
It appears to have been used on Python 2 only
=> Remove fork from runtests.py

Cython/Compiler/Optimize.py, tests/run/isinstance.pyx
We previously only did this for tuples of types.
See https://github.com/cython/cython/issues/6420
=> Optimise type checks from PEP-604 union types (joined by bitwise or)

Cython/Compiler/Optimize.py, tests/memoryview/memoryview.pyx
Fixes #7005
The LetNodes were generated in the wrong order
=> Fix iteration over memoryview temporaries

Cython/Utility/Buffer.c, Cython/Utility/ModuleSetupCode.c, Cython/Utility/Optimize.c, Cython/Utility/Overflow.c, Cython/Utility/TypeConversion.c
It's always defined so there's no need to conditionally generate code for it.
=> Remove uses of HAVE_LONG_LONG

Cython/Compiler/ExprNodes.py
=> Fix empty container test

Cython/Utility/ImportExport.c
Since we only need the first half of the string
there's no point in splitting, creating a list
and then picking only some of the list.
Follow up to #7035
=> Optimize split in import code

Cython/Compiler/Code.py, Cython/Compiler/Errors.py, Cython/Compiler/Nodes.py, Cython/Compiler/Scanning.py
Normalise the input to simplify the output.
Supersedes https://github.com/cython/cython/pull/7060
=> Discard all line endings from source lines for error reporting and C source comments
